### ISSUE TITLE
Reminder support?

### ISSUE THREAD

**Issue by melissachang** [leggett/simplify#10]
I don't know if you've tried any of the workarounds for Reminders in gmail. I've been experimenting with them. I think with a little help from this extension, Reminders could look good.

**Hide Snoozed text**

![Screen Shot 2019-04-05 at 8 16 01 AM](https://user-images.githubusercontent.com/10929390/55638055-31d2c000-577b-11e9-8af0-0b6a73bc39ee.png)

I just want reminders in one place like Inbox. I don't need bright bold orange letters telling me how long something's been snoozed. The extension could change "Snoozed 14 hours ago" to the normal date/time.

**Email to self**

This looks pretty good, no changes needed. Changing "me" to "Reminder" could be nice, for consistency with the changes below.

![Screen Shot 2019-04-04 at 9 52 13 PM](https://user-images.githubusercontent.com/10929390/55604309-f0fb8c80-5723-11e9-83cd-dd980024f49e.png)

**Calender event**

One workaround is to make a reminders calendar and create calendar events with email notifications.

FYI I use this when creating a reminder from mobile that is either:
1. Scheduled in the future. I use the New event widget. With one tap, I'm in a UI where I can type reminder name *and* set date/time. (The email-to-self hack is a pain on mobile; it's many steps before you can set date/time.)
1. Repeating reminders. This isn't possible with email-to-self hack; emails can't be snoozed repeatedly.

The problem is, there's a lot of noise. This is what a reminder "Test" looks like:

![Screen Shot 2019-04-04 at 9 58 44 PM](https://user-images.githubusercontent.com/10929390/55604480-da096a00-5724-11e9-9a52-b13ca96d06d4.png)

All I want is the word "Test"!

This extension could do something like "If this is a Google Calender email with reminder in the subject, replace "Google Calendar" with "Reminder" and remove noise from snippet."

**Draft**

If I want an editable reminder, I create a draft email and put it in my inbox.

![Screen Shot 2019-04-04 at 10 04 29 PM](https://user-images.githubusercontent.com/10929390/55604641-ab3fc380-5725-11e9-861e-cbf1b9a5f5c2.png)

The extension would detect "If a draft is in inbox, change red "Draft" to gray "Reminder".

**t keyboard shortcut**

This is the crème de la crème change. Extension maps "t" to: Create draft, move to inbox. Voilà, you now have editable reminders. The extension would have to call gmail API, but to me it's worth it.

If you're ok with any of these, I'm happy to try to write a PR.

**Comment by leggett** [comment]
**Hide snoozed text**
I agree the snoozed text is pretty loud. I'm still thinking about what exactly I want to do because I do think it is helpful to know why it has returned to the inbox (Inbox did this too though it wasn't as loud).

**Email to self**
Changing "me" to "Reminder" would only work in english. More troubling, you would only want to do that on emails sent from you _to_ you. And I can't tell to whom the message is addressed in the inbox.

**Calendar event notification**
This is easier to do across for english only without accidentally messing up other languages (as I'm not manually adding words, I'm only removing them). But again, I suspect this would not be expected for events that you didn't create as a reminder for just yourself. So I'm not sure it is a wise change. 

**Draft in inbox = reminder**
This _might_ work as I wouldn't do it on drafts that were attached on other threads. But it would be a lot of work to actually create these no? You would have to draft an email, go to your drafts, select the email, and move it to your inbox. If you could do all that from the compose mole (even via the "Add label" under the overflow button in the composer), I'd be more inclined to make that change. But you can't... or can you...

**t keyboard shortcut**
I've looked at App Scripts... my understanding is I can't bundle that with the extension and the user have to add that separately. Is that right?

**Comment by leggett** [comment]
Thanks for all your ideas and such a detailed description of each one.

**Comment by melissachang** [comment]
**Calendar event notification**

We could require some relatively unique string in event/calendar name, like SimRem.
 
**Draft in inbox = reminder**

Yes, there is no easy way to do this. I suppose this is a power user feature for people who are feeling nostalgic for the ability to edit reminders.
 
But with the **t keyboard shortcut** change, this could be really nice.

**t keyboard shortcut**
 
You don’t need App Scripts; you can call Gmail API from the Chrome extension. You would use the [Javascript client libraries](https://developers.google.com/gmail/api/quickstart/js). Here’s a [Medium post](https://medium.com/streak-developer-blog/how-to-use-the-gmail-api-in-a-chrome-extension-a272b2405b57) that shows how to call Gmail API from Chrome extension.

<br/>

Thank **you** for Inbox. Now I understand where its design ethos came from. Part of why I’m sad about the shutdown is, I can no longer refer to it (eg snoozed text). To me, it’s the reference for perfect email design.

**Comment by leggett** [comment]
I thought about this some more and have decided it isn't something I want to pursue as I won't be able to mirror the experience in the Gmail mobile app. Thanks again for brainstorming with me.

**Comment by leggett** [comment]
It has been a while since I've really dug in and thought about how I could possibly restore Inbox's experience with regards to Reminders. With some of the new capabilities I've made for Simplify v2, I might be able to create something with scheduled sends.

**Comment by melissachang** [comment]
FYI here's what I ended up doing.

https://github.com/melissachang/reminders-in-gmail

**Comment by leggett** [comment]
Almost 3 years later and I'm adding my first attempt at supporting reminders. It is a humble start with more to come.

With [Simplify v3.0.60](https://beta.simpl.fyi) installed, press `t` to start a new reminder.

<img width="586" alt="image" src="https://github.com/leggett/simplify/assets/8763662/6abd706b-8256-498d-86dc-0bf546672e64">

Once saved to the inbox: 

<img width="912" alt="image" src="https://github.com/leggett/simplify/assets/8763662/887cd760-55bc-4905-930f-b59a11ce9127">

Plenty more to do here including internationalization and support for adding reminders to conversations with seeing what the reminder is in list view (I've got plans for how to support that). For now, going to close this request. v3 should launch to everyone by end of this year and maybe even end of this month.

**Comment by leggett** [comment]
I might also add an option to dress up specific Google Calendar alerts as Reminders.

**Comment by freste** [comment]
> Almost 3 years later and I'm adding my first attempt at supporting reminders. It is a humble start with more to come.
> 
> With [Simplify v3.0.60](https://beta.simpl.fyi) installed, press `t` to start a new reminder.

I just saw this feature (by accident!), but in 3.0.73 after "Save", by clicking button or Control-Enter (on a Chromebook), I just get an error dialog with "Error Please specify at least one recipient." 

Aha, just noticed they do appear in Drafts; but it looks like "From" is not set to the special "+reminders" that it looks like it's looking for.

**Comment by leggett** [comment]
Yeah, I **just** ran into that myself. I think I broke something in the last update. Hope to get it fixed soon.
