### ISSUE TITLE
Expand and center search

### ISSUE THREAD

**Issue by adamglazier** [leggett/simplify#100]
I wish that search was expanded and centered at the top rather than a small icon on the right (see ui mock attached)
![centered search mock](https://user-images.githubusercontent.com/17174020/56837653-cee7bc80-6840-11e9-8237-4680ab6a6fd4.png)

**Comment by leggett** [comment]
1) This is clearly a better design if you don't use the buttons you hid (many do), you move or hide search when select an item (could work), and you don't mind moving or hiding search when you open a thread (sounds bad). 

2) But even if you did those things, centering search is near impossible if you want to keep the app and action bars merged into one bar (has to do with where those elements are in the DOM).

3) Search being open or closed is sticky (it won't close unless you close it, even after a refresh).
