### ISSUE TITLE
Better support for large displays

### ISSUE THREAD

**Issue by wildcardjoker** [leggett/simplify#101]
I've just installed this extension, and I love the fact that it removes all the clutter.

However, I would like to request that the amount of whitespace around the list of email is reduced. At present, I find that most of the display on my 1920x1080 screen is wasted.

I've played with the CSS a little, and I've found that if I modify the `left-margin` property of the `nH` class and the width of the next `<div>` tag (which has the attribute `role="main"`), this decreases the margins to a much more palatable setting.

I have attached screenshots of the default and modified windows. In the modified screenshot, I have adjusted the width of the `'main' <div>` tag to 1700px.

This was only a very quick modification, however I manually modified the CSS to match my screen sizes. I don't know how difficult it will be to modify the CSS to allow for different screen dimensions etc.

I appreciate all of your hard work on this extension. Thank you so much for making this available!
![simplify-default](https://user-images.githubusercontent.com/8613803/56842855-b1603480-68cc-11e9-8931-053cd0afbd24.png)
![simplify-modified](https://user-images.githubusercontent.com/8613803/56842869-b4f3bb80-68cc-11e9-99d7-d62cf4f77280.png)

**Comment by leggett** [comment]
I'm not going to do this for the default view. Reading is much worse for long line lengths. It isn't that big of a deal in the inbox but the inbox and conversation view are tied together.

I use a larger max-width on the preview pane though. Up to 1680px. Or you can make a local override with your own extension.

**Comment by EranBoudjnah** [comment]
I'm a new user of this extension, and this is the only annoyance for me with it. Would be nice to be able to configure this behaviour, and potentially some of the other tweaks?

**Comment by leggett** [comment]
I don't want to add or support settings. It makes support more difficult (as there are the many permutations of Gmail times the many permutations of Simplify). I'd rather find a better solution for people maximizing their window on large monitors.

**Comment by EranBoudjnah** [comment]
Fair enough, keeping it simple makes sense. I do have a pending PR with a fix, but there was a comment there addressed to you so didn't want to action before you had a look :)

**Comment by leggett** [comment]
I'm going to make this issue the place I track the ideas and feedback around better use of screen real-estate on large monitors.

**Comment by leggett** [comment]
One idea is to make the nav wider on large displays... might be useful if people have a lot of nesting or long label names.

**Comment by EranBoudjnah** [comment]
Can you explain your assumption that "The optimal line length for reading is only 50-70 characters."?
I'm only expressing my personal view here, but when I scan through emails, I don't read every line to its fullest, but not being able to read everything when there's clearly real estate for it is frustrating - especially when about a third my screen is just white...

**Comment by leggett** [comment]
Sure...

First, some context. The inbox and the conversation have the same parent div where the max-width is set so they are linked. I could try and change the max-width really quick with a mutation observer but I don't think that will be a great experience nor do I think it is worth it.

Yes, in the inbox, you likely only are scanning the left 500-800px which has the star, senders, label, subject, and start of the snippet. If you're only reading the left side, then you don't really need the rest and it pushes the timestamp, attachment icon, and hover actions further from the thing you use to identify the message (the stuff on the left). So stretching the inbox is bad in my opinion but not the end of the world.

But in the conversation, where I assume you are reading the whole message, it is horrible. Here is a good explainer why: https://baymard.com/blog/line-length-readability

**Comment by EranBoudjnah** [comment]
First of all, thank you for the detailed reply!

As to the attachment icon - you make a good point. It may have been a poor choice to place it on the right (although I see why it was done, if the icons on the left are meant to help identify messages and attachments aren't considered a part of that identification). Having the timestamp on the right seems less of an issue, probably, like you said.

I thought the character limit idea would come from those principles you linked to, which is kind of why I asked.

I totally agree it will be horrible to allow full width for the message. However, when it comes to the inbox, I think there's a difference between reading blocks of text, in which finding the next line has meaning, to reading a single line as is the case in a list of items (like the inbox). Here, you don't have the overhead of needing to find the next line to continue reading. 

Also, keep in mind we have the hovering effect to help us single out a specific line.

It's your extension, so essentially your call, just raising some considerations. Decoupling the inbox and the conversation might be worth it - they are significantly different.

**Comment by leggett** [comment]
Good to understand the push back is just on the inbox and not the conversation view.

**Comment by leggett** [comment]
#90 also improved how things work on large displays. It didn't quite work for me but I liked the approach and will likely build off of it.

**Comment by leggett** [comment]
@EranBoudjnah So can you say more about the benefit of stretching the inbox across a wide display? Are you reading entire messages in the snippets in the inbox? Do you just like the feeling that the space is being used? Or is it so the actions line up with the messages?

**Comment by leggett** [comment]
Playing with some stuff:
<img width="1437" alt="Screen Shot 2019-04-28 at 11 29 21 PM" src="https://user-images.githubusercontent.com/8763662/56879501-ddcf9a00-6a0d-11e9-9e67-1e4fd6061427.png">

<img width="1437" alt="Screen Shot 2019-04-28 at 11 36 00 PM" src="https://user-images.githubusercontent.com/8763662/56879621-6ea67580-6a0e-11e9-90f6-93df8e65861d.png">

<img width="1436" alt="Screen Shot 2019-04-28 at 11 31 10 PM" src="https://user-images.githubusercontent.com/8763662/56879503-e1632100-6a0d-11e9-9f47-90ab2247c523.png">

Lining up the actions with the content is better. One of the reasons I didn't do this initially is the text button labels take up so much room, it doesn't really work. And it is variable across languages. I might be able to detect the width of the buttons and set a css variable so I do it even for text buttons at really high resolutions. 

The other change I'm playing with here (moving search to the left) has other problems. 

1. You can't really leave it open all the time. 
2. You'd have to at least hide it when you opened a conversation or if you selected any items in the inbox. 
3. I don't like that the button that it minimizes to is so far from where the search box lives. 

So I'll probably get this working with search staying on the right for now and push out a change later this week.

**Comment by EranBoudjnah** [comment]
Great to see that you're continuously improving this!

As to your question - the way I view my inbox is this: I skim through the emails. If any catches my interest or is the one I'm currently after, I might get lucky and be able to find everything I need without having to open that message at all. This is why the wider the view is - the better.

And OMG, the lined-up actions look so much better!

**Comment by AndrewKennedyRx** [comment]
I'd agree, I prefer having the action buttons lined up with the content, then I don't have to go hunting for them in what looks like a header bar (thus my brain automatically filters it out because I'm looking at content, not header), and the select-all check box is lined up with the individual check boxes on the messages. 
The search bar makes sense on the right, it has room to expand, but is out of the way of the primary use; which I would argue is processing mail as it comes in, I use it much less than Google seems to think I should based on their original location. Also, having used Firefox for a long time before switching to Chrome, they had a separate search bar on the right side of the browser window, so right side search feels familiar to me.
Widening the nav might be a good use of the extra space on wide monitors, but I don't have a large folder tree to navigate (maybe I should...) so the current width works for me.
Overall, other than a couple tweaks like lining up the action buttons, I really like the extension. I think it just takes a bit of getting used to all the extra free space. But, on the plus side, it lets me see my background images more.

**Comment by lukasvermeer** [comment]
> Reading is much worse for long line lengths.

+1 on this! I for one would definitely not want the UI to scale to a 5K screen. I would probably sprain my neck.

**Comment by TheSpyder** [comment]
When I installed the extension the tight width on my 2560x1440 monitor was quite jarring. It wasn't until I saw this thread that I turned on the preview pane and showed the folder list on the left. I now find it to be quite acceptable at the full screen width.

Perhaps surfacing the `wider max-width with preview turned on` change a bit stronger in the about / installation pages would help with some of these concerns 🤔

**Comment by leggett** [comment]
Yes, that with aligning the actions and pagination controls on the left/right on the content. 

I considered this initially but it was more work and I deemed it not worth it initially. Never maximizing my window on large monitors and mostly using keyboard shortcuts, the current design seemed acceptable.

But the push back has been more vocal than I expected.

**Comment by TheSpyder** [comment]
The use cases are definitely interesting.

If I'm reading a lot of mail I will un-maximise my window (well, maybe not anymore 🤣), but I use JIRA a lot and that really only works well maximised. If I'm switching back to gmail for a quick update I'll just leave it at the size it is.

**Comment by ZackBoe** [comment]
For the inbox alone, the current width is rather unusable for me. I'm at 1440p using multiple inboxes, which can result in some incredibly short subject lines. In the second screenshot I've bumped the width up to 2000px with a userstyle.

![wzD](https://user-images.githubusercontent.com/904055/57197229-db4fd180-6f32-11e9-8cab-2c71bd9b710c.png)
![Yji](https://user-images.githubusercontent.com/904055/57197228-db4fd180-6f32-11e9-9989-c2a97f87faf2.png)

**Comment by leggett** [comment]
I just pushed a bunch of changes on this. Still work to do. I'd love some feedback / suggestions on this if you think there is a better way to do this.

- The biggest change is when your window is wider than 1641px, I line up the actions with the content. This was even harder than I expected (see the list of resolutions, views, and states in style.css line 244). There might still be bugs (there are so many different states to check). It isn't working yet for Preview pane or Multiple inboxes. And I'm not sure I'm approaching it the right way even. Would love some feedback / ideas on my approach. 
- I allowed the max-width on preview pane to go up to 2000px (Ideal ratio would be 55% width for message list and 45% for message -- but I don't force a ratio)
- I think I've figured out how to allow side-by-side Multiple inboxes stretch wide but keep the messages maxed out at 1100px. It is based on a className I suspect changes a lot which means this could break any time Gmail changes it. Time will tell.

**Comment by leggett** [comment]
Ok, I think I have pinning the actions to the content working at lower resolutions now. I still haven't tested it on preview pane or multiple inboxes though and I want to do that before I release the improvements. 

I'm also being more aggressive/thorough about hiding pagination and even settings at lower resolutions when both search and add-ons are open.

**Comment by leggett** [comment]
Tested on preview pane and multiple inboxes. Since I allow a wider max-width, I'm not going to move the actions for now. Eventually, I could try and detect (and observe changes to) the width of the left pane in the vertical preview pane and move the actions over the content. But it will often bump into the pagination and search box so I'm leaving it alone.  

To do vertical split pane right, I'll need to move a lot of things around (search to the left, actions to the right, select all... somewhere else). And that's a bigger task than this. I'll make a new task to track it.

**Comment by jnunderwood** [comment]
I have an Ultra-Wide monitor with 3840x1600 UW-QHD+ resolution. I realize that my setup is uncommon, but there is just so much white space on the left side of the message list and on the right side of the preview pane. I would love it if the preview pane could be wider, at least. Any suggestions?

**Comment by leggett** [comment]
@jnunderwood Sorry for the slow reply. Was at my sister's wedding and then some travels with the family.

Am I hearing you right -- you want your messages to be 2000-3000px wide? They will be super hard to read at that line length and you'll still have a lot of white space... everything will just be left aligned instead of centered. Maybe send a screenshot of your spam folder or something to give me a better idea of what you're looking at?

**Comment by jnunderwood** [comment]
@leggett I would like the message to be wider as well as the message list. Perhaps even the sidebars too. Here is a screenshot (please excuse the excessive political spam):

![image](https://user-images.githubusercontent.com/5722763/64022505-6bc6a900-cb04-11e9-8a18-8ef246b04143.png)

Thanks!

**Comment by leggett** [comment]
Can't look into this right now -- but that is broken. Vertical Preview Pane should be allowed to stretch to 2000px wide. 

This is what that setup looks like for me on a big monitor:
<img width="2539" alt="Screen Shot 2019-08-30 at 2 21 01 PM" src="https://user-images.githubusercontent.com/8763662/64051869-764b6780-cb31-11e9-8226-516dfcc04b9b.png">

It might be an issue on my end or maybe something unique to you and your setup. One thing to check: do you have Multiple Inboxes enabled under Gmail Settings > Advanced? It isn't compatible with Preview Pane and I've seen some people have both enabled but no sections defined for Multiple Inboxes so they don't know they have them both enabled.

**Comment by jnunderwood** [comment]
I had Multiple Inboxes enabled but didn't realize it. **\*sigh\*** Things appear normal now.
Thank you very much for your assistance.
