### ISSUE TITLE
Detect use of high-contrast theme and don't dim elements

### ISSUE THREAD

**Issue by thundernixon** [leggett/simplify#105]
I love this extension! It's really excellent, and it makes the reading/writing experience in Gmail so much better.

One thing that distracts me, however, is that I can barely read the inactive tabs – and I know that others with less-perfect eyesight will struggle a lot more.

Here's a comparison of current Gmail default vs the Simplify Gmail tab bar:

![image](https://user-images.githubusercontent.com/7355414/56850049-fbe0b180-68ca-11e9-84a1-b42f37e63738.png)

I recognize that the light gray helps to signify that these tabs are inactive, _but_ the current tab is already shown clearly with red text, so the light gray text doesn't really signify anything that isn't already clear.

Using https://github.com/ThePacielloGroup/CCAe, I checked the contrast ratios of these elements. Gmail's passed (most of) these tests, even for inactive elements, but Simplify Gmail failed all of them.

## Simplify Gmail

![image](https://user-images.githubusercontent.com/7355414/56850115-e455f880-68cb-11e9-9a4f-6443341061f0.png)

## Original Gmail

![image](https://user-images.githubusercontent.com/7355414/56850117-eddf6080-68cb-11e9-95e7-cbf03619a5e9.png)

**Comment by leggett** [comment]
Thanks for all the detail. I'm familiar with minimum contrast ratios for accessibility. Anything I dim, I un-dim when you hover on it. Not perfect for low vision users, but maybe good enough.

I've actually had a couple low-vision users email me to praise how much easier it is to use Gmail with Simplify because there is less on the screen and more space around what is left. 

Obviously this doesn't mean it couldn't be even better. I think what would be reasonable is to detect use of the high-contrast theme and not dim anything if that theme is in use.

**Comment by thundernixon** [comment]
Awesome! Yeah, it's certainly more readable overall, now, so I'm glad you've gotten such good feedback around it.

It's a great idea to support the high-contrast theme.

However, I also think it would still be worth upping the contrast on the default theme for two reasons:

1. It's not very user-friendly to require people to hover elements to make them easily readable. Defaults should meet basic accessibility standards, and themes can go beyond that.

2. This is a popular implementation of something "simple," so therefore it is probably helping to set trends around what people think of as "simple" design. If your example uses low-contrast text to make the design "simple," others will follow your lead, and it may have an overall negative impact on other web design. Real simplicity should come from focus and layout, rather than fading out things that still matter enough to be included in the view.

That's just my two cents, though. Obviously, it's your project, and you can do what you like with input. 

Thanks for making and sharing this!

**Comment by leggett** [comment]
Nearly 2 years later and I'm finally adding detection of high contrast theme and trying to ensure I don't decrease contrast. It will be part of v2.3.0 which is going to have a lot of upgrades. Thanks again for the original report.
