### ISSUE TITLE
Hide the "Offline" indicator.

### ISSUE THREAD

**Issue by steren** [leggett/simplify#108]
Once offline mode is enabled, I do not see the need of constantly displaying the "Ready for offline" indicator at the top.

**Comment by leggett** [comment]
I don't use offline so I wasn't sure if this was *ever* useful. You're saying it is never useful?

**Comment by steren** [comment]
Once offline mode is enabled *in the setting*, the indicator appears and stays the same all of the time.

I think it's safe to assume that once Offline has been enabled in setting, that the app will have offline mode.
I actually think Gmail should do offline by default, like Inbox did and like modern web apps.
