### ISSUE TITLE
Create an official privacy policy

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#110]
First draft -- any recommended edits?

> We do not transmit, collect, or store any data. Period. No ads, no trackers, no analytics. Nothing. Not even cookies. We do store a few parameters about your setup (light or dark theme, do you use preview pane, etc) as local variables on your computer to make the experience better. But that's it. And what you do on your computer stays on your computer.

**Comment by rajeevedmonds** [comment]
The first line can be rewritten as:

"We do not transmit, collect, or store (_local or remote_) any **PII** data."

Just a suggestion.

**Comment by leggett** [comment]
I was trying to be even more broad -- we don't collect or transmit any data of any kind... not just PII.

**Comment by rajeevedmonds** [comment]
Makes sense.

**Comment by lukasvermeer** [comment]
Perhaps add a bit about how Simplify works, to explain why no data needs to be transmitted in the first place? Something like:

> Simplify is simply some styling sugar applied on top of the existing Gmail interface. It does not send or receive data of any kind.

**Comment by leggett** [comment]
Kept it short and sweet. 

> Simplify is simply some re-styling applied on top of the existing Gmail interface. Simplify does not send or receive data of any kind nor does it use any cookies. Not even for analytics.
