### ISSUE TITLE
Compose button missing on Chromebook in fullscreen mode

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#111]
Someone wrote to show that the compose button is missing on Chromebooks if you let the app open in a new tab but it shows if you instead set it to open in a new window (full screen).

I asked for further clarification and they responded, "There's an app draw or shelf on Chromebook. So if I long press the icon, I can change it to either opening it direct in the browser or opening as a frameless full screen window. In the frameless window, the button now appears."

I don't have a Chromebook so I need some help seeing if this is an issue and then troubleshooting it if it is. Can anyone repro this?

![inbox_compose_missing](https://user-images.githubusercontent.com/8763662/56869660-f7de8d80-69b7-11e9-910b-d7d2038d00e8.png)

**Comment by wesort** [comment]
I'm NOT seeing this issue. Tested in tabs, windows and with or without fullscreen activated.

I'm on a Chrombook Pixel LS (2015) 
```
Google Chrome	74.0.3729.90 (Official Build) beta (64-bit)
Revision	cfe563e7c6f4aff361234564204481496ed48722-refs/branch-heads/3729@{#842}
Platform	11895.74.0 (Official Build) beta-channel samus
Firmware Version	Google_Samus.6300.276.0
```

**Comment by leggett** [comment]
No one can reproduce the issue. I'm going to close for now.
