### ISSUE TITLE
horizontal scrollbar

### ISSUE THREAD

**Issue by Netphilou31** [leggett/simplify#114]
Hi,
I use the vertical splitting between messages list and message display. When activating the extension, the horizontal scrollbar does not show for wide messages.
Best regards,
Phil.

**Comment by leggett** [comment]
Thanks Phil. Found the source of the problem and will try to fix soon.

```
/* Give view full height */
/* BUG: we should only apply this to vertical split pane */
html.simpl.splitView .apg .age {
	/* Normally... */
	/* height: calc(100vh - 64px); */
	
	/* In default inbox, there are tabs */
	height: calc(100vh - 119px);
}
```
