### ISSUE TITLE
Pagination controls are misplaced when using 2 or more inboxes

### ISSUE THREAD

**Issue by vgladiyenko** [leggett/simplify#115]
If I enable additional inboxes in Settings -> Multiple inboxes, pagination arrows, email counter and settings icon are misplaced. On the first screenshot I've marked the place where these controls are placed in the default Gmail layout.

![firefox_kpLRdaieFd](https://user-images.githubusercontent.com/5185770/56883370-29fef680-6a6f-11e9-8928-627f53c47ed3.jpg)

**Comment by leggett** [comment]
I can't seem to repro this. I've seen this happen (and I've got a fix ready) for when you have both Multiple Inboxes and Preview Pane enabled (even if it is set to No Split). But it doesn't look like you have Preview Pane enabled. You are using Multiple Inboxes, right?

**Comment by vgladiyenko** [comment]
Exactly, Multiple inboxes are enabled, Preview pane - disabled. Below is the exact configuration.

![firefox_K3RMOcCJTn](https://user-images.githubusercontent.com/5185770/56914846-d49e0600-6abd-11e9-85e8-ed2ab0828c26.jpg)
![firefox_L2CdoBlILE](https://user-images.githubusercontent.com/5185770/56914852-d8318d00-6abd-11e9-9e24-3ba90aa82095.jpg)

**Comment by leggett** [comment]
Ok, I was just able to reproduce this. Sort of. Something went wrong and it detected use of Preview Pane (even though it isn't enabled). So I must be detecting use of preview pane in a bad way. 

I'm not getting the multiple action bars though with v1.2.9. You might check for updates and see if that fixes itself. I'll fix the detection of the modes. Thanks for your help.

**Comment by leggett** [comment]
Putting out a fix for this finally.
