### ISSUE TITLE
Header UI elements overlap auto-reply notification

### ISSUE THREAD

**Issue by vgladiyenko** [leggett/simplify#116]
Menu, settings and checkbox overlap the auto-reply notification.

![ykhdnyVAm8](https://user-images.githubusercontent.com/5185770/56883386-35522200-6a6f-11e9-9d12-a6a8181e78ef.jpg)

**Comment by leggett** [comment]
Known issue. Being tracked on #51

**Comment by leggett** [comment]
This is fixed in v1.2.9.
