### ISSUE TITLE
Why is the inbox width limited to 960px?

### ISSUE THREAD

**Issue by chx** [leggett/simplify#118]
https://github.com/leggett/simplify/blob/master/gmail/style.css#L390

```
html.simpl .AO .aeF > .nH {
	margin: 40px auto 0 auto;
	max-width: 960px; 
}
```
this ends up wasting quite a bit on a full screen browser window on the common 1920 wide screen. Especially with the preview pane it'd be useful if it extended full width. Thanks!

<img width="901" alt="2019-04-29 03_20_28-StrokesPlus" src="https://user-images.githubusercontent.com/193045/56890378-2303c400-6a2e-11e9-8cb4-958adbf28295.png">

**Comment by leggett** [comment]
1. You need to reload to detect the use of preview pane -- the action bar should not be where it is.
2. If you are using the preview pane, I allow the interface to stretch to 1680px.
3. I explain why the max-width here: https://github.com/leggett/simplify/issues/101#issuecomment-487423874
4. I'm tracking ways in which I can improve Simplify on larger displays on that same issue (#101)
