### ISSUE TITLE
Shorten labels with long Text

### ISSUE THREAD

**Issue by stritti** [leggett/simplify#119]
There are Google-generated labels (in German e.g. `Benachrichtigungen`) which are very long and they shorten the subject often to be not readable:

![image](https://user-images.githubusercontent.com/184547/56898160-9fc78a00-6a90-11e9-82ba-d29151d6059f.png)

Would be cool if the length could be set to `max-length` and then there is added just `...` (like it is done with subject.

**Comment by leggett** [comment]
That sucks as you didn't get to choose that label. But shortening the labels could hide important parts of people's intentionally long labels.

You could just set the label to not show in the message list (if it is not useful).

<img width="412" alt="Screen Shot 2019-04-29 at 7 32 57 AM" src="https://user-images.githubusercontent.com/8763662/56903460-2eb4b200-6a51-11e9-885e-f2e1918407b4.png">

**Comment by stritti** [comment]
Wow, great! I haven't seen this feature. That solves already my issue. Thank you very much!
