### ISSUE TITLE
Drag & drop of attachments not working

### ISSUE THREAD

**Issue by slhck** [leggett/simplify#12]
I am using 1.0.6 with Chrome Version 73.0.3683.103 (Official Build) (64-bit) under macOS 10.14.4.

I cannot drag and drop files to the compose window:

![attach](https://user-images.githubusercontent.com/582444/55619499-18407100-5799-11e9-9909-25cc3ab89d8d.gif)

The title of the compose window changes accordingly, but when releasing the mouse, the file is not attached.

**Comment by leggett** [comment]
Thanks for the gif -- super helpful. I think I know what is causing that.

**Comment by leggett** [comment]
Fixed this in 1.0.7. Will push to Chrome web store shortly.

**Comment by slhck** [comment]
I can confirm it's working. Thanks for your support!
