### ISSUE TITLE
Make sure localStorage variables are unique for multiple accounts

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#121]
I'm not doing anything to distinguish which account a localStorage variable is tied to. So if you sign in with multiple accounts in the same chrome profile and they use different setups, it is always going to have to re-detect everything and it will make the load feel janky.

**Comment by leggett** [comment]
I started to work on this. The username isn't available anywhere as far as I can tell. I'm probably going to have to use the "/u/0" in the URL which I think mostly maps to the same account over time. Maybe unless you sign out and back in.

**Comment by russelldc** [comment]
@leggett The current user's email address is stored by Gmail in window.GLOBALS[10]

**Comment by russelldc** [comment]
Oh, I see now you got something working in one of your recent commits: https://github.com/leggett/simplify/commit/8579162be817a4ae3a73299e49e8c27be70d5010#diff-695016f5c91c8995d61bc180a2a5fd75R55 :

```javascript
document.querySelector('.gb_db').innerText;
```

Is there a specific reason you do a loop with 20 retries -- is the window/document ready eventListener not working out properly?

**Comment by leggett** [comment]
I am firing on DOMContentLoaded but I've seen things still not be ready when that fires. So I started just looping. I should go back through and test to see if any of them don't really need loops. And I should simulate it on a slow connection to see if that makes a difference. 

And the 20 retries is a maximum number of tries. I didn't want it looping forever. Most of them have a max of 10... it could probably be even fewer.

**Comment by leggett** [comment]
As for getting the username, my function doesn't work either as I need the username as soon as the page starts loading (so I load the right saved states). So while /u/# changes if you sign out of all accounts and back in, I think it is my best bet. 

Note that I re-detect everything eventually... the saved states is just about not having the custom styles load piecemeal while Gmail is loading causing things to shift around a bunch until loading is complete.

**Comment by leggett** [comment]
I'm deleting this from the source code so it doesn't even look like I'm trying to collect PII. Saving here in case it is ever useful (I doubt it will be as it doesn't work until the dom is fully loaded).

```
var usernameLoop = 0;
function getUsername() {
	var username = document.querySelector('.gb_db');
	if (username) {
		if (simplifyDebug) console.log( 'Username = ' + username.innerText );
		//initLocalVar();
	} else {
		usernameLoop++;
		if (simplifyDebug) console.log('Username loop #' + usernameLoop);
		
		if (usernameLoop < 21) {
			setTimeout(getUsername, 100);
		}
	}
}
```
