### ISSUE TITLE
change the main menu keyboard shortcut (toggle)

### ISSUE THREAD

**Issue by abcdefghijklmnopqrstuvwxyzabc** [leggett/simplify#122]
Gmail's keyboard shortcuts are listed via "?". Obviously there is no keyboard shortcut for the main menu, which is now nicely hidden by Simplify. Is it possible to have a designated keyboard shortcut to toggle open/close the main menu? Thanks for your fantastic extension, it makes me happy.

**Comment by leggett** [comment]
As Gmail has a TON of keyboard shortcuts AND you can customize them, I fear that any keyboard shortcut I choose will likely conflict with other shortcuts. But I'll consider it at some point...

**Comment by mwvd** [comment]
I went to fork and add this in, and seems to already be in here, aha.

`ctrl + m` toggles the menu.

From [script.js](https://github.com/leggett/simplify/blob/fbbfc45f0d64d06b16f99a92324de7cd3865a45d/gmail/script.js) (lines 35-40):
```
        // If Ctrl+M was pressed, toggle menu open/closed
	if (event.ctrlKey && event.key == "m") {
		document.querySelector('.aeN').classList.toggle('bhZ');
		toggleMenu();
		// TODO: if opening, focus the first element
	}
```

**Comment by leggett** [comment]
It does... I just haven't publisized it b/c I'm not sure `ctrl + m` is the best shortcut. I wanted to think about what modifier I should use for each platform and what other shortcuts I want to add.

**Comment by leggett** [comment]
And yes, I added it after the OP posted the original request.

**Comment by mwvd** [comment]
Hmm - I forked and changed to `cmd|ctrl + \` on my fork bc I've gotten used to Notion, but don't think that's ideal (I found v clumsy in Notion at first). 

`shift + \`\ seems intuitive to me also, but suppose this just a personal preference.

Imagine eventually people will ask for the ability to customize shortcuts after you publicize, now that you have two, but at that point is a full blown feature, aha. Although, that seems clumsy as well for just one shortcut.

**Comment by jonsmithers** [comment]
It seems to me that there is now a ctrl-shift-m shortcut to toggle the main menu. Just wanted to say that this conflicts with the Google Chrome shortcut I use to switch browser profiles.

https://github.com/leggett/simplify/blob/efd10350809ef62a2db9010addae3e10c81e8109/gmail/script.js#L68

**Comment by leggett** [comment]
Yeah... someone else brought that up. I was trying to use a key-combo that I could use for all Simplify shortcuts (thus adding the shift). But adding a key meant I conflict. And I don't want to use <key>Command</key + <key>\</key> because that conflicts with 1Password. Basically, it is impossible to pick something that won't conflict for some people. 

I need to (a) pick a different shortcut and (b) add settings to let people edit the shortcut.

**Comment by leggett** [comment]
I tried one more time to see if I could get `cmd/ctrl + \` to work but I can't prevent the system shortcut from firing and opening 1Password. 

Going to go with 
- `cmd/ctrl + m` for show/hide the menu bar and 
- `cmd/ctrl + s` for toggling on/off Simplify.
