### ISSUE TITLE
Show left sidebar icons when menu collapsed

### ISSUE THREAD

**Issue by wesort** [leggett/simplify#123]
I would very much like to still see the sidebar icons when the menu is collapsed. 

Perhaps as option for those who like the current minimalism. Personally, I'm finding this is one of the only things I'm missing as I do tend swap between (standard Gmail) labels quite a bit. 

Here's what it looks like in standard Gmail with just the icons
![Gmail label icons](https://user-images.githubusercontent.com/3920126/56922344-e2ed2180-6abf-11e9-925c-b74891fa5032.png)

**Comment by leggett** [comment]
I don't have (and I don't want to have) any settings for Simplify. It makes supporting the extension a lot harder (as I have to support and test all the various combinations of settings) and really, it is just a dodge on making hard decisions.

As for this one, I'm very much opposed to this version of the minified nav. I totally understand your use-case (it is perfectly valid) but the little icons and all the little unread badges are just awful. :(
