### ISSUE TITLE
Revive the "Done" button for categories

### ISSUE THREAD

**Issue by lukewilde** [leggett/simplify#124]
I really miss the "Done" button from Inbox, which in one click would mark all unread messages in a given category as read. Currently, I think the easiest way to do this is: 

1. Select Category
2. Select all 
3. Mark as read
4. Deselect all

P.s, Absolutely love this extension, thanks for all your hard work!

**Comment by leggett** [comment]
It actually just archived items, it didn't mark them as read. I think there is an issue somewhere to track this.

**Comment by lukewilde** [comment]
Ah yes, just found it: https://github.com/leggett/simplify/issues/39

Sorry for the duplication.
