### ISSUE TITLE
Doesn't quite jive with Boomerang

### ISSUE THREAD

**Issue by msj00** [leggett/simplify#126]
Love this plugin, first of all.

But I noticed immediately that it clashes with Boomerang (which I also love) in one critical way. Because Boomerang has its own button immediately to the left of the user image, the "search" button has now moved to the same location as the "settings" button. For whatever reason, the settings button is 'on top' of the search button, so you cannot actually click the search button now.

Image attached so you can see what I mean.

Is there a way to account for Boomerang users?

![Screen Shot 2019-04-30 at 11 05 20](https://user-images.githubusercontent.com/50146409/56971958-2be0bc80-6b38-11e9-8ed2-2609ef325ead.png)

**Comment by particlepants** [comment]
Noticed the same issue myself, and glad to see someone already filed the feedback so +1 on this issue.

In the meantime I use the "/" hotkey to access search as the click takes you to settings.

**Comment by leggett** [comment]
Known issue and being tracked in #83
