### ISSUE TITLE
Feature Request - New Message Button Replacement

### ISSUE THREAD

**Issue by volomike** [leggett/simplify#127]
Can you implement a new message button replacement? The rainbow plus for me simply confuses me and is one of the most aggravating things about Gmail, yet your plugin doesn't resolve this. Right above the column headers of my message, give me a blue button that says "New Message", and then get rid of the rainbow plus.

**Comment by lukasvermeer** [comment]
I also found it aggravating and found a simple solution: [hide the new message button entirely](https://github.com/lukasvermeer/simplify/blob/master/gmail/lukas.css#L4).

I always use the keyboard shortcuts ('c' for compose) rather than the on-screen button anyway. Useless clutter.

**Comment by leggett** [comment]
The rainbow button is a clever way for Google to slip in some branding without hitting you over the head with it or taking up extra room. It is in all the Google apps and it doesn't bother me much. So I'm inclined to leave it.
