### ISSUE TITLE
"Options" option greyed out

### ISSUE THREAD

**Issue by wolf99** [leggett/simplify#128]
Per title. 
Installed today, basic GMail reorganising worked as expected but cannot select "Options" from the extension icon's right-click menu. 
I assume this is where I can set things like dark mode, etc? Either way, I can't access it now.
Have tried restarting browser, checked for updates, etc

Extension version 1.2.9
Chrome Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by leggett** [comment]
There are no options. Dark mode is just Gmail's dark theme.
