### ISSUE TITLE
Feature request: let us send you some money

### ISSUE THREAD

**Issue by lukasvermeer** [leggett/simplify#129]
Simplify is simply awesome! I want to show my appreciation by buying you a coffee or a beer or whatever. Could you add a donation button somewhere on [simpl.fyi](simpl.fyi)? 

![TAKE MY MONEY](https://media.giphy.com/media/3oKIPa2TdahY8LAAxy/giphy.gif)

**Comment by leggett** [comment]
Thanks @lukasvermeer and others.

I believe in paying for software... but I also believe in doing things for others out of generosity or just to improve the lives of others. As soon as I start asking for donations, it makes it about money for me AND I likely wouldn't get that much money. Double suck.

Simplify has been more successful than I expected to be honest. I have ideas about turning it into a legit business where I do this for more sites/apps and then charge an annual subscription fee (for maintenance and adding more sites/apps each year). And I have some crazy ideas around the price going down as there are more users (as it shouldn't really cost a lot more to support 500k users over 250k users). 

But for now, it is free for all. Just being a fan, spreading the word, being patient when things break, and helping me make it better for everyone else is all I ask for right now.

**Comment by mgalgs** [comment]
Any "progress" on this :smile: 

I don't know how many man days I've lost since Google Inbox got the axe (probably man *months* at this point).  If I lose Simplify as well I might just have to hang up my hat and check out of email altogether.  Maybe retire and go into the Forest Service or something.

I'd like to stay in software at least a little while longer so investing in Simplify seems like the logical next step to keep myself in business.

> As soon as I start asking for donations, it makes it about money for me AND I likely wouldn't get that much money. Double suck.

I definitely hear that.  Maybe going through Patreon or [GitHub Sponsors](https://github.com/sponsors) would alleviate some of that feeling of accountability since they're completely opt-in, best-effort?

**Comment by leggett** [comment]
Thanks for asking. My thinking has evolved on this. I think this is likely to go one of three ways:

1. I don't accept any money and it likely dies at some point (bad)
2. I do accept money and keep it alive but don't improve it (not horrible, but not great)
3. I do accept money and it not only lives on, but gets better (great, if you agree it is actually better)

I don't want to fall into the trap of adding features to Simplify Gmail until that becomes a hot bloated mess (that's how Gmail itself got into this mess). That said, I do have a short list of big ideas that I think most people would really like. 

Where I think it will get really interesting is building a service around simplifying other sites. So, say you pay $5 / year to simplify Gmail or $10 / year to simplify Gmail plus 5 other sites. 

Pricing, what other sites, and timing on this are all up in the air. I think a lot of people over-charge for these kinds of things too... or what if the price got cheaper as I got more users (b/c at the end of the day, I'm just trying to cover my time). 

So stay tuned. I don't want Simplify to die. I realize now that it can't stay free for that to happen. I hope to figure all this out in 2020. And just knowing that is keeping me going.

**Comment by cy2k** [comment]
My gmail, even with Simplify, seems to have gotten painfully slow these days... to the point where I've started using a desktop client again for the first time in many years.  When I do have to get into "real" gmail for certain actions, it's only bearable with Simplify.  So I'm glad to hear that you're thinking about how to make it sustainable!  Keep up the great work.  The idea of doing it with other sites as well is a REALLY interesting one.
