### ISSUE TITLE
Feature: collapsible label list

### ISSUE THREAD

**Issue by ljm22** [leggett/simplify#13]
One nice simplification would be a css collapse of the labels. Happy to attempt this if you are looking for contributions... won't get to it for a few weeks though. Would want it to be a persistent state, though.

In the image here, the labels list (blue) would offer a collapse like the categories (red)

![image](https://user-images.githubusercontent.com/5173413/55626075-69a12e00-57a2-11e9-9390-8e35b39dc639.png)

**Comment by ljm22** [comment]
Oh. https://www.lifewire.com/how-to-hide-and-show-labels-in-gmail-1171914

**Comment by leggett** [comment]
Haha, I actually designed that as part of an overhaul of labels back in 2007 or 2008. That is the best way to do it. :)
