### ISSUE TITLE
Search can't be focused on click

### ISSUE THREAD

**Issue by allisonacs** [leggett/simplify#131]
![image](https://user-images.githubusercontent.com/1230973/57008393-ae9f6100-6ba4-11e9-8adf-c23966b1a560.png)

You can see in this image that the search field is auto expanded but not focused. I can not it, except by using the `/` keyboard command. If invoke focus via the keyboard command and then `esc` out, goes back to looking like the screenshot. 

I've checked to make sure I don't have any other browser extensions or Gmail add-ons that might be messing with this. I previously had Boomerang, but it is currently disabled.

**Comment by tobiasrenkin** [comment]
Same issue here.

**Comment by stepacu** [comment]
Likewise.

**Comment by rodolfo-romero** [comment]
Same thing is happening to me, however, this is not happening in G-Suite Business, only in my personal account.

**Comment by craigerskine** [comment]
> Same thing is happening to me, however, this is not happening in G-Suite Business, only in my personal account.

Strange, my G-Suite and normal account are also affected by this issue.

**Comment by leggett** [comment]
Looking into it right now. Not sure if I broke something with my last update or if Gmail changed out from under me.

**Comment by leggett** [comment]
Some classnames changed out from under me. Updating now.

**Comment by leggett** [comment]
I've fixed the problem and submitted it as v1.2.10 to Chrome and Firefox.

**Comment by spelleg** [comment]
I'm experiencing a similar issue. The search button overlaps with settings. Click defaults to settings and am unable to click search. 
![Screen Shot 2019-05-13 at 10 29 23 AM](https://user-images.githubusercontent.com/50586713/57629631-18871580-756a-11e9-9278-70732e612651.png)

**Comment by leggett** [comment]
@spelleg This likely caused by use of an additional 3rd party extension that pushes search over.

**Comment by leggett** [comment]
See issue #83
