### ISSUE TITLE
Actions and settings overlap search bar

### ISSUE THREAD

**Issue by realtomkwok** [leggett/simplify#132]
![Screen Shot 2019-05-01 at 2 59 51 PM](https://user-images.githubusercontent.com/3367751/57008562-a0dcf080-6c23-11e9-99fa-e864af3436c4.png)

Browser: Chrome 74.0 on macOS
As you can see, all the actions and settings overlap the search bar, which also disables the search bar. I've tried to turn off some extensions like Stylus, but it still doesn't work.

**Comment by rodolfo-romero** [comment]
This is related to #131 
I noticed though that this is only happening in my personal Gmail account. My G-Suite account works fine.

**Comment by leggett** [comment]
I've fixed the problem and submitted it as v1.2.10 to Chrome and Firefox. It should be live by 8:30a PST.
