### ISSUE TITLE
"This tab is empty" has no padding

### ISSUE THREAD

**Issue by paullessing** [leggett/simplify#134]
When using the preview pane, if the list view on the left is less than 550px, the text looks off because it has no padding (see screenshot).

![image](https://user-images.githubusercontent.com/6681183/57010378-2779d980-6bf4-11e9-8cae-74ef76f21acb.png)

**Comment by leggett** [comment]
I might have already fixed this in Simplify v1 but it is definitely fixed in Simplify v2 (not yet launched).
