### ISSUE TITLE
Search Section Not Clickable

### ISSUE THREAD

**Issue by lpommers** [leggett/simplify#135]
### Version
Chrome: Version 74.0.3729.131 (Official Build) beta (64-bit)

<img width="1440" alt="Screen Shot 2019-05-01 at 10 53 02 AM" src="https://user-images.githubusercontent.com/5764316/57023293-97419180-6bff-11e9-94ad-24673519e9e4.png">

This is anecdotal, but this doesn't happen on my other Google Chrome Profile which does not use the Inbox Tabs.

**Comment by leggett** [comment]
Gmail changed their code which broke Simplify. I've submitted a fix in v1.2.10. 

You can [force an update](https://kixie.zendesk.com/hc/en-us/articles/235601588-How-to-Force-an-Update-of-Your-Chrome-Extensions) in Chrome.
