### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by KenWuqianghao** [leggett/simplify#138]
Icons on the top not showing when select or clicked into a mail.

**Comment by leggett** [comment]
One other person said they were seeing this and I haven't been able to reproduce the issue. Can you restart your browser and make sure you are using v1.2.10 of Simplify?

If you're still seeing the issue, can you share more about your setup so I can try and repro?

- Browser
- OS
- Inbox type
- Advanced settings being used (e.g. Preview pane, Multiple Inboxes, etc)
- Place you were in when you opened message (e.g. inbox, label, search, sent, etc)
- Are you running any other extensions that change Gmail?
- Does making the window smaller make a difference?
- Are you using text button labels or icons?

**Comment by KenWuqianghao** [comment]
I'm using Chrome and I'm very sure it is up to date. I didn't change any advanced settings. I have boomerang and mail track installed. Making the window smaller didn't help. Here are the images.
![Screen Shot 2019-05-02 at 19 02 09](https://user-images.githubusercontent.com/20444505/57093124-5cc61a80-6d0d-11e9-8d08-13a0c9494249.jpg)
![Screen Shot 2019-05-02 at 19 02 48](https://user-images.githubusercontent.com/20444505/57093126-5d5eb100-6d0d-11e9-9c4a-fde03ce0c2a2.jpg)
As you can see, the top where the icons are supposed to be displayed isn't there.

**Comment by leggett** [comment]
Sorry, I wasn't saying make sure Chrome is up to date – I was saying make sure Simplify is up to date. Instructions on how to see the version number and force an update if you aren't running v1.2.10: https://kixie.zendesk.com/hc/en-us/articles/235601588-How-to-Force-an-Update-of-Your-Chrome-Extensions

But I don't expect that to solve the problem. Simplify is not compatible with other extensions right now. I hope to see what I can do about this at some point, but it isn't high on my list. You can track it here: #83

**Comment by KenWuqianghao** [comment]
Sorry, I wasn't talking about the extensions. I was talking about the default icons, like "back to inbox", "archive", "report spam" and "delete". As you can see in the image, those weren't displaying when I selected a mail or opened one.

**Comment by leggett** [comment]
Right, I understand that. I'm saying that it might be caused by the other extensions you have installed and/or you not having the latest version of Simplify loaded up.

**Comment by leggett** [comment]
If you disabled Boomerang and Mailtrack, made sure you had the latest version of Simplify, restarted your browser... if you did all those things, I suspect the problem would go away. 

If instead you were still seeing the issue, then it is a problem with the current version of Simplify and I am not seeing it because I don't have your exact setup (which is why I asked for the other information about how you have your Gmail setup).

**Comment by KenWuqianghao** [comment]
Thanks you so much! After restarting the browser and updating the extension it started working!
