### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by Anole** [leggett/simplify#139]
Using latest FF: While there is a nice, quick delete button in the preview list, there is no delete button I've found while reading an actual email without going into the  ... vertical ellipsis? Minor irritation, but would be nice to have a quick, obvious way to delete messages from inside.

Thank you!

**Comment by leggett** [comment]
You should be able to see the delete button (and all other actions). 

Can you make sure you have the latest version of Simplify (v1.2.10) and restart your browser to see if that fixes it?

**Comment by Anole** [comment]
Ahhh. I was expecting it to be with the 'print' and 'new window' icons in the message. I found them in the upper left of the window. My bad. But you might take (people like me) into consideration in future, perhaps... ;)

Thanks for your reply!
