### ISSUE TITLE
Settings cog icon missing in default multiple inboxes

### ISSUE THREAD

**Issue by ZNemesis** [leggett/simplify#145]
Steps to reproduce:

Within Settings -> Inbox -> Inbox type change to Default
Untick all categories.
Advanced -> Multiple Inboxes -> Enable
Set up at least one Multiple Inbox

![image](https://user-images.githubusercontent.com/9064604/57201640-16a7da00-6fdf-11e9-909d-0a0b08d6f3c8.png)

Workaround: open any other view

**Comment by leggett** [comment]
The settings cog is on the main section of your multiple inboxes. It looks like you have your sections to appear above the main inbox sections pushing that cog to the bottom section. Re-open the issue if it isn't there.
