### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by craigerskine** [leggett/simplify#147]
It'd be nice to have a changelog to see what's new when you push new updates.

**Comment by leggett** [comment]
Agree. I assume that is typically done with a .md file in the root directory?

**Comment by craigerskine** [comment]
I usually include a update section on my main readme.md file. Though you could create a separate .md if you want... doesn't really matter.

**Comment by rhulse** [comment]
@leggett now that Simplify is under very active development, it'd be good to have this. Perhaps linked from the version number to changelog.md. :-)

**Comment by leggett** [comment]
I just started one today actually: https://changelog.simpl.fyi -- It doesn't go that far back yet.
