### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by jeff-hykin** [leggett/simplify#148]
I'd love to help out, and it seems a lot of people would like to as well. You've got a really awesome repo here, it seems simple and easy to improve. It'd be great to know if you have any preferences on how things are done (conventions for the code). It'd also be helpful to know how to test a forked version of the repo.

I've packed chrome extensions before, and I do web dev but I'm not sure the best way to test the code in this repo before creating a PR.

**Comment by leggett** [comment]
Yeah... I should write something so others understand how I'd like people to help.
