### ISSUE TITLE
Compose button overlaps right scrollbar w/ right side chat on firefox

### ISSUE THREAD

**Issue by The-Bob** [leggett/simplify#149]
![composeoverlap](https://user-images.githubusercontent.com/31973884/57268277-06701900-7038-11e9-887a-7877883a2e35.PNG)

Could be fixed by setting the scrollbar style to thin using `scrollbar-width: thin;`  (Firefox only)

**Comment by leggett** [comment]
The problem is with Right Side Chat... there shouldn't be that extra padding between the chat roster and the scrollbar (pushing the scrollbar to the left).

**Comment by leggett** [comment]
Got a fix for this in v1.3.4
