### ISSUE TITLE
Display Addon Menu

### ISSUE THREAD

**Issue by Pome-ro** [leggett/simplify#15]
Love this redesign! However, I do often use the Add-On menu with calendar and keep, right now it's hidden (not even just collapsed) making it inaccessible.

**Comment by leggett** [comment]
You can sort of use it with the hidden Command+J (or Win+J on Windows) that toggles the extension. Hit that, open the pane, and then re-enable the extension. 

Proper support is on the list along with preview pane view and dark themes. Check back in a week.

**Comment by colbyfayock** [comment]
idea: not sure how much effort or the feasibility but maybe you can utilize Tasks to recreate the reminder experience. thanks for your efforts here 🙏

**Comment by leggett** [comment]
Definitely not easily done and may only be possible via the Gmail API. Will look into it once things settle down with proper support for all the basic and advanced features.

**Comment by leggett** [comment]
Sneak peak at how I plan to support opening the add-ons pane: secondary FAB that expands to show the different add-ons. 

<img width="1200" alt="Screen Shot 2019-04-06 at 11 25 14 PM" src="https://user-images.githubusercontent.com/8763662/55679639-d06a3880-58c3-11e9-8441-4dbbd3143d3e.png">
<img width="1198" alt="Screen Shot 2019-04-06 at 11 29 07 PM" src="https://user-images.githubusercontent.com/8763662/55679640-d7914680-58c3-11e9-8891-c5c479f708ed.png">

**Comment by colbyfayock** [comment]
looks great 😍would the FAB hide after it expands? thinking about how i would change between Tasks and Keep, for instance, once it's open

**Comment by leggett** [comment]
It would collapse back into a single FAB. So you would just hover over that and click on a different app icon (similar to how Inbox's compose button always expanded to show top contacts). For those that switch between apps a lot, it will be mildly annoying as you will have to hover on the FAB to switch. But for everyone else, it will be nice to not have to stare at the icons all the time.

**Comment by leggett** [comment]
Done. Shipping momentarily in v1.1.0

**Comment by zanona** [comment]
The only problem I am facing right now is that for custom or 3rd party add-ons sometimes their icons show up but sometimes they don't?

With Simplify extension on:
<img src=https://user-images.githubusercontent.com/32017/58463718-a8b18700-8134-11e9-9c61-13bae160923a.png height=300>

With Simply extension off, notice the last icon:
<img src=https://user-images.githubusercontent.com/32017/58463743-b535df80-8134-11e9-8970-05af4f5be24e.png height=300>


And this was me using the extension a few minutes after (3rd party add-on now showing again)
<img src=https://user-images.githubusercontent.com/32017/58463849-e6aeab00-8134-11e9-85b1-c3b0bcea3a38.png height=300>

The only way I can work around it at the moment is by disabling the extension, reaching to the add-on menu and then switch it back on.

**Comment by leggett** [comment]
What add-on is that? Is it one you added via Gmail or a 3rd party browser extension that adds an icon to the tray?

**Comment by zanona** [comment]
That is an add-on I have developed and it's being used under development,
meaning it's not publicly available but associated with my Gmail account.

Il Mar 28 Mag 2019, 16:19 Michael Leggett <notifications@github.com> ha
scritto:

**Comment by ebozonne** [comment]
If I understood well the issue I have very similar issue with the very useful extension contact+ (https://app.contactsplus.com/)
It works first, but after 1 or 2 clicks the right sidebar addon icons disapear and impossible to switch back to another 3rd party addon (still the addon sidebar is displayed).

Any idea?
Thanks!
