### ISSUE TITLE
Please display the search bar

### ISSUE THREAD

**Issue by janrosa** [leggett/simplify#151]
Please display the search bar (or make it configurable so we can turn on/off the search bar permanently). It would be quite handy, it's the only thing I'm missing after installing Simplify as I live in my inbox due to the nature of my job and not having a search bar is like not having the right hand.

Thank you.

**Comment by leggett** [comment]
If you click on the search button to open it, and you don't close it, it will stay open. 

Right now, clearing the search will close it... I hope to make that smarter where it can distinguish between users that have it open and users who have it closed and do the right thing.
