### ISSUE TITLE
[Feature Request] Search Bar Location

### ISSUE THREAD

**Issue by the543Nteam** [leggett/simplify#152]
Not sure if it is just me, but I would prefer if the search bar was on the left side and move the buttons to the right of it.

**Comment by leggett** [comment]
- The actions are used far more than search across users.
- This is weird/bad for the back button and the select all button. 
- Separating those buttons from the other actions (so that back stays on the left and the actions move to the right) is not easy... maybe not possible at all.

**Comment by leggett** [comment]
Sorry for the curtness of my reply. I appreciate you taking the time to send your request. I've even considered other ways to do this (see screenshots in #101). But it isn't going to happen.

**Comment by the543Nteam** [comment]
I really like this one:

https://user-images.githubusercontent.com/8763662/56879621-6ea67580-6a0e-11e9-90f6-93df8e65861d.png

Shucks.  Anyway, thanks for your awesome work.

**Comment by leggett** [comment]
I don't like that the select checkbox isn't aligned with the content but that isn't the biggest problem. It gets really messy when you open an item... the actions run into the pagination controls. Do I auto-minimize search and re-expand it when you leave the item? It just doesn't feel good to have things that seem unrelated to the action (open an email) changing other things on the screen (show/hide search).
