### ISSUE TITLE
Search Option Disappeared

### ISSUE THREAD

**Issue by GutoA** [leggett/simplify#154]
The search emails function has disappeared today, has anyone else got this issue? I use Simplify on 4 different accounts, and on 3 of them the search emails icon has gone today. Is this a known issue?

**Comment by leggett** [comment]
Hmm, not a known issue. Make sure you are running the latest version (v1.3.2) and reload Gmail. If still a problem, can you send a screenshot? 

It could be another chrome extension or it could be an issue with local variables to save state being overwritten by multiple accounts (see issue #121 ).

**Comment by brenoot** [comment]
I'm having this issue too. I disabled all my extensions and the search button still not appearing.

**Comment by GutoA** [comment]
![Screenshot 2019-05-08 at 19 03 02](https://user-images.githubusercontent.com/50411451/57397191-0866e300-71c4-11e9-8bba-fa3d282d4c6b.png)

Here's a screenshot. It was there for the first week and a half with Simplify, only noticed it missing today.

**Comment by leggett** [comment]
**What is that pencil icon with the down arrow to the left of the settings gear?** I've never seen that and it could be effecting one of the more generic selectors I implemented to deal with Gmail's continual change of certain css classnames.

**Comment by GutoA** [comment]
No idea, it's on all my accounts - I think it's a Chromebook setting related to input language. Anyway, when you switch it off the pencil disappears and the search bar doesn't come back (see screenshot)

![Screenshot 2019-05-08 at 19 29 12](https://user-images.githubusercontent.com/50411451/57398769-b3c56700-71c7-11e9-86f9-11bb80935c27.png)

When I turn keyboard shortcuts on and use / the search bar appears and I can use it. The search bar stays around until I clear my search, it then disappears again.

**Comment by ecdejong** [comment]
I'm having this exact same problem. Disabling all my other Chrome plugins doesn't bring the search icon back.  '/' to toggle the search bar works.

**Comment by brenoot** [comment]
after using the search:
![Captura de Tela 2019-05-08 às 16 19 47](https://user-images.githubusercontent.com/34926864/57402212-2b39cd00-71ad-11e9-845e-f9c83b620195.png)

**Comment by leggett** [comment]
Actually, I've got a guess about what is happening here. Pushing an update in v1.3.3 now. You can hit [ / ] if you have keyboard shortcuts turned on to get to search while it pushes out. Please let me know if that fixes it.

**Comment by obra** [comment]
Just noticed this issue in 1.3.2. FWIW, hitting / does -not- get me to a search box, even with shortcuts enabled. (The shortcut worked fine before the box disappeared.)

(Also, thanks so much for creating Simplify and maintaining it. It makes my life better)

**Comment by obra** [comment]
Ok. That's weird. GMail just force-reloaded. v1.3.2 now shows the search icon again. And / works fine again.

**Comment by leggett** [comment]
Ghosts in the machine...

**Comment by brenoot** [comment]
I'm using Simplify Gmail v1.3.3 and still missing the search box

**Comment by leggett** [comment]
Ack! I was really hoping the change would fix it. Did it fix it for anyone? @brenoot does your screen look like the above screenshots? If not, can you share a screenshot of your screen?

I wonder if Gmail is rolling out a change slowly and we have different css. I think I'm going to move to detecting certain classnames and inject the styles...

**Comment by brenoot** [comment]
![Captura de Tela 2019-05-09 às 11 53 43](https://user-images.githubusercontent.com/34926864/57464095-7bb73600-7252-11e9-9119-f3ba2c776387.png)
Hmm... I guess it looks the same

**Comment by leggett** [comment]
Ah ha!! Found the problem for sure this time. Submitting a fix in v1.3.4 and created #161 to address the systemic problem here.
