### ISSUE TITLE
Apply max-width to horizontal preview pane

### ISSUE THREAD

**Issue by pkedrosky** [leggett/simplify#155]
I like that Simplify creates a narrower messages list, so it's a bit weird that periodically when I load Gmail with the extension -- like today -- the messages list is the entire width of the screen. Reloading doesn't help, nor does restarting Chrome browser. I'm currently in 1.32, on latest Chrome build, but this happened in prior versions as well.

**Comment by leggett** [comment]
Hmm... that's no good. Are you using multiple inboxes or preview pane? Are you signed into and accessing multiple accounts?

**Comment by pkedrosky** [comment]
I have tried with and without preview pane, with no difference. I am signed into multiple accounts, but only use one. No other mail-related extensions.

**Comment by pkedrosky** [comment]
By way of update:
- Have tried signing out of all accounts, and then back into only one. No change.
- Have tried uninstalling extension and reinstalling. No change. 
- Have tried disabling all extensions except this one. No change.

Baffling.

**Comment by leggett** [comment]
Can you send me a screenshot of your whole screen? You can go to your spam folder or something.

**Comment by pkedrosky** [comment]
Sure, here you go:
![2019-05-08_17-34-22](https://user-images.githubusercontent.com/3206644/57417012-95f00600-71b7-11e9-8b77-90010e94f008.png)

**Comment by leggett** [comment]
It appears that you don't have v1.3.3 (which should fix the issues with the search box in the top right) and Preview Pane is still on (white it is set to no split). If you disable Preview Pane under Gmail Settings > Advanced > Preview pane, and update to v1.3.3, does it fix those two things?

**Comment by pkedrosky** [comment]
Actually, I already had 1.3.3. But ... disabling Preview Pane in settings seems to have fixed things. Is there a problem with Preview Pane?

**Comment by leggett** [comment]
It seems so... I'll look into it now that I understand the setup.

**Comment by pkedrosky** [comment]
Okay. Chrome version is 75.0.3770.18 (Official Build) beta (64-bit), if that helps.

**Comment by leggett** [comment]
@pkedrosky looking at your screenshot again, I realized you have preview pane enabled and it set to horizontal split. Not applying a max-width in this case is intentional but perhaps not desired. So no bug here. Still, room for improvement and that is what I'm about to check in as part of v1.3.5.
