### ISSUE TITLE
Overlap of right (search) panel and left (email) panel

### ISSUE THREAD

**Issue by snahri** [leggett/simplify#156]
![2019-05-08 (2)](https://user-images.githubusercontent.com/50418354/57392639-2f96c380-7176-11e9-8521-ac5802a369d0.png)

you can see the menu button (left panel) overlaps with the navigation buttons (right panel). The overlap worsens when I use an extension like "Todoist for Gmail". 

My screen is 1366x768. Browser is Chrome. 

Thank you developers for the good work.

**Comment by leggett** [comment]
This is due to moving the actions to line up with the content. I should probably stop doing that sooner or hide pagination sooner when search is expanded. You can click on the search icon to collapse search for now.

**Comment by leggett** [comment]
I'm going to make search a bit smaller in the next version to accommodate for moving the actions to line up with the content and make sure this doesn't happen.
