### ISSUE TITLE
Label disappeared from left navigation list

### ISSUE THREAD

**Issue by mgdudas** [leggett/simplify#157]
Been using it since I saw it on HN a few weeks back. No issues whatsoever until today.

I used it on my gmail account that I use for work, and just 1 label suddenly disappeared. It's a parent label for another label, and the child label shows up under a different label for some reason.

I tried going in to manage the labels, and set it to hide the label, force refresh, go back in, show the label, force refresh, and it's still missing. 

Only way to make the label show up again is to disable the extension.

Using Chrome 74.0.3729.131 (Official Build) (64-bit) on Ubuntu 19.04

Thanks!

**Comment by leggett** [comment]
That sounds super weird. I don't do *anything* with labels (hiding them, rearranging them, etc). Not in the nav or on messages. I only show/hide the left nav entirely when you click the menu button.

You can try making sure you have the most recent version of Simplify (v1.3.2) but again, I'm not sure how my extension could be doing that. 

I did put in some more generic selectors for hiding things in the action bar but I don't see how that would effect labels. If you have the most recent version... maybe you could share a screenshot of your labels with the extension on/off?

**Comment by leggett** [comment]
I removed the generic selectors in v1.3.3. I'm going to close this issue. But feel free to re-open it if it is still an issue.

You might also look to see if the labels are just hiding under the "More" option in the nav.

**Comment by mgdudas** [comment]
Hi,

I can confirm I am using 1.3.3. This issue didn't come up until yesterday, so I'm not sure what the problem is.

This is a screenshot of the label list with the extension disabled. https://imgur.com/a/4wxYtSg

In this one, the 'Support' label and its sub-label 'Hackrepair' are where they should be.

Here's a screenshot with the plugin enabled and 'Support' is missing. https://imgur.com/a/M3ZldLb

You'll note there is an 'Observium' label, and the 'Hackrepair' sub-label has now been moved to be underneath 'Observium' though it is still 'Support/Hackrepair' within gmail. -- I can also confirm that 'Support' does not disappear into the 'More' option. I wish it did....

Thanks for your help!

**Comment by leggett** [comment]
Oooooh. Ick. Yeah, that's on me. Will fix today.

The classnames keep changing which has certain buttons re-appear. So I started hiding the support button via:
`html.simpl div[data-tooltip="Support"]`

I'll change that to be more specific to things with that tooltip in the app bar:
`html.simpl #gb div[data-tooltip="Support"]`

**Comment by mgdudas** [comment]
Haha, that will do it. Figures I have a label named the same as a button. 

Thanks again!
