### ISSUE TITLE
Search Icon Overlap = Not Clickable

### ISSUE THREAD

**Issue by magius72** [leggett/simplify#158]
I cannot click the search icon to search email messages from my inbox. I think the issue is that my Wisestamp plugin icon that still appears in the upper right is moving it to the left, overlapping with the settings (gear) icon.

![image](https://user-images.githubusercontent.com/50438531/57431964-67356680-726f-11e9-896e-0b6c905b79e8.png)

Using latest version (just installed yesterday) on latest Chrome. 1920x1200 resolution, Windows 10.

**Comment by lydenyardley** [comment]
My issue is very similar. The search field overlaps the settings icon when an email is open. See below

![Screenshot 2019-05-09 at 11 24 17](https://user-images.githubusercontent.com/2838799/57446676-29bfe180-724d-11e9-9dbb-3b6868de670a.png)

Running Simplify v1.3.3

**Comment by leggett** [comment]
This is happening for different reasons for each of you. 

@magius72 you have another extension that adds an icon to the left of your profile photo and pushes search to the side. I'm not compatible with other extensions. Fixing that isn't high on my list, but it is on my list: #83 

@lydenyardley Somehow the inputs menu button is messing things up. If you don't use that, you can disable it and it should fix your problem. It also appears that the new change to move the actions to line up with the content is maybe part of the problem. I'll enable that button and see if I can figure out what is going on.

**Comment by leggett** [comment]
@lydenyardley I'm going to make the search input a little less wide in v1.3.4 to prevent this when the actions are lined up with the content.

**Comment by magius72** [comment]
Hi @leggett,

Thanks for the reply. Yes, as I mentioned, I thought it was probably the Wisestamp icon (that's what you are referring to when you mention the icon to the left of my profile photo).

Bummer that I can't use search if I also have another GMail plugin installed. Will await the fix then!

**Comment by leggett** [comment]
@magius72 sorry, I missed that you suggested that was the problem somehow. That is it. I also noticed you originally sent a different screenshot where all the timestamps on your emails are orange. That is only supposed to be the case when the item is snoozed. Are you still seeing that? Are all those emails snoozed (I doubt it).

**Comment by magius72** [comment]
@leggett no worries there -- that's just because I have a GMail add-on that makes it appear that way. :)

**Comment by leggett** [comment]
Phew!

**Comment by dany-eudes** [comment]
In my case, this happens because I have another extension (the green Mailtrack icon). Maybe it's occurs because  Google Input Tools icon also.

My workarround about this: I switch to Preview Pane view when I need to use Search box.

![GMail_Simplify](https://user-images.githubusercontent.com/82278/57460196-0bf17d00-724b-11e9-9d1c-27ff8eb53cb7.PNG)

**Comment by leggett** [comment]
You can also toggle Simplify on/off with Command+J on Mac (not sure what the shortcut is on Windows... I thought it was Windows+J)

**Comment by lydenyardley** [comment]
@leggett I think you've fixed my issue! Options screen still says I'm running 1.3.3, but it looks perfect! Thank you!!
