### ISSUE TITLE
Always show the Google apps icon for large resolutions.

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#160]
The (new?) behaviour of briefly displaying the Google Apps icon when hovering over the account avatar is quite hard to discover.

I would suggest at least an option of always displaying the Google Apps icon. Useful for larger displays and for those who use this action frequently.

**Comment by leggett** [comment]
Agree it is hard to discover. Having a setting isn't much better and I don't want to have any settings if I can help it. Open to other suggestions.

**Comment by leggett** [comment]
I thought about this some more and other than having it always visible somewhere, I don't think there is a better place for it. I improved the interaction to show/hide immediately and stay visible. I'll push that out with some other updates in v1.3.5

**Comment by nhojb** [comment]
Thanks for the update. My only suggestion would have been to show the apps
icon when the window width exceeds some limit.

I appreciate the desire to avoid settings of possible.

John

**Comment by leggett** [comment]
That's reasonable.

**Comment by jahirfiquitiva** [comment]
For me, hovering doesn't even work (it does some times, though, but not always), so it would be great if it could be shown always

**Comment by leggett** [comment]
This is revamped and much better in v2 which I'm trying to get out asap. Stay tuned.

**Comment by jahirfiquitiva** [comment]
thank you so much! waiting eagerly for it 🤞 😀 😅

**Comment by leggett** [comment]
I fixed this in Simplify v2.
