### ISSUE TITLE
Detect current Gmail classnames

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#161]
**Disclaimer: if anyone has a better idea of how to deal with this, please speak up!**

Gmail minifies their code to make the code smaller and Gmail faster (a common practice). This results in classnames changing and Simplify breaking or doing unintended things. 

I expected this would happen to some degree but wasn't sure how many classnames would change or how often they would change. In the first few weeks of Simplify, they didn't change at all. Then in the last week, they changed 3 times. 

Some classnames appear to have some meaning and I expect them to be more stable. The action bar is .G-atb (Google Action Bar?). Other classnames are clearly going to change (.gb_be with the next element having .gb_ce). I've tried to not use these unstable classnames where ever I can but I still have to use them sometimes. 

My plan to fix this is to detect and cache the unstable classnames from stable children. I can reliably get to the Search input and then walk up the tree to find the parent element I need to restyle. I'll do that with javascript and then inject the styles I need to onload. And I'll store these classnames in localStorage variables so I don't have to wait for Gmail to load to detect them and apply the styles. 

If the classnames have changed, the worst case is Simplify will be broken for a few seconds during loading (using the cached classnames) and then will self-correct when it detects the new classnames.

Doing this for any classnames that might change will be a sizable chunk of work. And it will make maintaining the code a bit harder as the styles will live in js functions that inject them instead of in style.css.

**Comment by leggett** [comment]
I might be able to do this more cleanly by using [Less](http://lesscss.org) at runtime.

**Comment by aboodman** [comment]
Seems reasonable to me.

**Comment by aboodman** [comment]
There was a "Gmail Greasemonkey API" specifically for this at one point. It's not clear if it still exists though.

**Comment by leggett** [comment]
I'm only detecting a handful of classnames. And I found other ways to select other elements. I'll have to monitor things and see what other classnames change and need to be added to addStyles(). But the core infrastructure to do this is now in Simplify, so closing this issue.
