### ISSUE TITLE
Detect other themes

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#165]
Right now, I detect and categorize a theme as light (inbox rows are dark text on light bg) or dark (inbox rows are white text on dark bg). 

But not all light themes are the same. Some have the nav and other elements as dark text on a light bg and some have it as light text on a dark bg.

In the later case, the search button is often dark when it should be light when minimized. And dimming different things (pagination & settings) makes them hard to use. 

I should detect this variant and correct these things.

**Comment by jahirfiquitiva** [comment]
Can you please also add an option to set a color for the fabs? I use this white Android theme and the buttons are almost invisible for me, given that their position also change with this extension 🙏 

<img width="152" alt="Captura de Pantalla 2019-05-20 a la(s) 19 22 45" src="https://user-images.githubusercontent.com/10360816/58059941-af3c6f00-7b34-11e9-88fb-78cde9d34576.png">

**Comment by leggett** [comment]
I'm now detecting what I'm calling "Medium Themes" -- themes with light inbox rows (and therefore dark icons in the inbox) and dark backgrounds (and therefore, white icons in the app & action bars).

**Comment by leggett** [comment]
@jahirfiquitiva I'm trying really hard to avoid having any options as it makes maintaining the extension a lot harder. Plus, the whole idea is an opinionated redesign of Gmail. I'm not trying to enable users to customize Gmail a ton beyond all the options for customizing Gmail already offers.

**Comment by jeff-hykin** [comment]
As an opinionated redesign, I'm actually surprised you support any themes! I think just picking 1 or 2 officially supported themes would be sufficient. Most of the people who loved Inbox loved its simplicity not its customizability.

Maybe in the future you could support a developer setting on the extension that allows additional CSS. Then if people want to tweak something they can do it without having to repack the entire extension. It would also make contributing a lot easier.

**Comment by leggett** [comment]
Yeah, I'm considering a sort of userstyles approach for the long term plans where people can post different tweaks that build on the base changes. We'll see.
