### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by squidfunk** [leggett/simplify#167]
Starting of today, the layout seems to be broken, most probably related to changes Google made to the HTML or CSS:

<img width="1551" alt="Bildschirmfoto 2019-05-16 um 09 56 53" src="https://user-images.githubusercontent.com/932156/57836584-4f0a9d80-77c1-11e9-95d0-e0df9793cad0.png">

It was working perfectly before and I did not install any new extensions.

**Comment by pseudonymcp** [comment]
Noticed the same today, also area to click for Inbox doen't match exactly and search is missing.
![shot-0002](https://user-images.githubusercontent.com/1522647/57837068-49618780-77c2-11e9-85a6-7e7b38b2b8c2.png)

**Comment by ghazlewood** [comment]
Looks like #168 and #169 are duplicates of this problem!

**Comment by orzechowskid** [comment]
and #170 ...

**Comment by kachar** [comment]
and #173

**Comment by leggett** [comment]
I've got a fix... sending to Chrome store and Firefox store now

**Comment by dany-eudes** [comment]
For me I see that toolbar is overlapping the first  item of the email list.  To click on the first item I need to move the mouse pointer to very close to  the bottom line of the first item or I will just click on some toolbar command like Select, Refresh and so on.

![simplify_overlapping](https://user-images.githubusercontent.com/82278/58669202-ba9c5100-8311-11e9-8fc2-41d2f0de940f.png)

**Comment by leggett** [comment]
Do you have the Mail Track extension? It is causing this for a few others.

**Comment by dany-eudes** [comment]
Thank you for your reply! Yes,  I have the Mail Track extension.
