### ISSUE TITLE
Suggestion: Remove "No new emails!"

### ISSUE THREAD

**Issue by ralvs** [leggett/simplify#171]
I don't see a real necessity of show "No new emails!".

Removing it would be even cleaner!

<img width="1176" alt="Screen Shot 2019-05-16 at 08 58 21" src="https://user-images.githubusercontent.com/5287233/57854795-7a8c8880-77bf-11e9-9d54-6b8ac8b10d2e.png">

**Comment by leggett** [comment]
Thanks -- tracking doing something different for when you've reached inbox zero here: #70
