### ISSUE TITLE
Not enough margin for top bar

### ISSUE THREAD

**Issue by kachar** [leggett/simplify#173]
Since the Gmail updates of today we've lost:

* Search capability
* Layout positioning

![image](https://user-images.githubusercontent.com/893608/57856042-d291b200-77f4-11e9-83e6-67414420d2db.png)

![image](https://user-images.githubusercontent.com/893608/57856066-e63d1880-77f4-11e9-969e-58c9656fd2d0.png)

**Comment by ecdejong** [comment]
My full layout is broken:
![Schermafbeelding 2019-05-16 om 15 14 16](https://user-images.githubusercontent.com/50423233/57856425-5182ec80-77ed-11e9-93ed-9b8af22c4234.png)

**Comment by MrJibus** [comment]
Same here :/
