### ISSUE TITLE
Compose "+" is Missing in 1.3.7

### ISSUE THREAD

**Issue by jdsimcoe** [leggett/simplify#175]
I updated to `1.3.7` today and noticed that the Compose "+" is missing:

![image](https://user-images.githubusercontent.com/275617/57874946-8f204f00-77c6-11e9-90de-cbd1643153f4.png)

**Comment by jdsimcoe** [comment]
FWIW in `chrome://flags` I had lazy image/frame loading enabled. Disabling it brought back the "+". I'll mark this closed for now but once native lazyLoading becomes more ubiquitous this might be worth referencing down the road.

**Comment by leggett** [comment]
This sounds like it was a problem with Gmail then. Was it missing with Simplify disabled?

**Comment by jdsimcoe** [comment]
Yes, it is a Gmail/Chrome problem. I was able to confirm that it also happens when Simplify is disabled:

![image](https://user-images.githubusercontent.com/275617/57890562-e1746680-77ec-11e9-864e-52ce530dac26.png)

**Comment by vchong** [comment]
I have the same problem : (. Disabling lazy image/frame loading didn't help. Disabling Simplify brought back the "+".

Simplify Gmail 1.5.8
Google Chrome is up to date
Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by leggett** [comment]
I'm not able to reproduce this. Did it just start happening? Do you have other extensions running? Or did you just turn off lazy image/frame loading? If so, did you restart Chrome after doing so?

**Comment by vchong** [comment]
Oops, so sorry for the noise! :( Was looking for the "+" compose button at the top left corner of the window, but found it at the bottom right instead. A draft email sub-window was also partially blocking it. Thanks and sorry again!
