### ISSUE TITLE
Icons overlapping text as you scroll

### ISSUE THREAD

**Issue by staringispolite** [leggett/simplify#176]
Looks like the menu bar has a transparent background (Looks like only in gSuite?) which leads to overlaps like this

![image](https://user-images.githubusercontent.com/151620/57877014-9c8c0800-77cb-11e9-881f-cb3c5518725c.png)

**Comment by koolza** [comment]
Got this issue also today. I use the Firefox extension. And it's a gmail account not a gSuite account.
The menu seems very thin also.

**Comment by staringispolite** [comment]
Oh, I just hard-refreshed Gmail and I'm getting it there too now. Could've sworn refreshing Gmail wasn't repro'ing before, but for whatever reason, it is now. This is from MacOS / Chrome:

![image](https://user-images.githubusercontent.com/151620/57878727-854f1980-77cf-11e9-865e-dacb561049c2.png)

**Comment by leggett** [comment]
Do you have the latest version of Simplify? I pushed out version 1.3.7 earlier today

**Comment by albertavery** [comment]
Confirmed that 1.3.7 fixes it, had to manually check for updates for the add-on, as I was still on 1.3.5 apparently. (Firefox)

**Comment by staringispolite** [comment]
Ah, Chrome hadn't auto-updated it yet, I was on 1.3.5.

After updating, I can't repro it in gMail or gSuite 👍🏼
