### ISSUE TITLE
new Calendar and Task side tool in GMAIL now showing up when SIMPLIFY extension is ON.  Bug?

### ISSUE THREAD

**Issue by rhgaspar** [leggett/simplify#177]

**Comment by leggett** [comment]
Can you share a screenshot?

**Comment by rhgaspar** [comment]
Best,

Richard
cell/office 214-704-4896


On Thu, May 16, 2019 at 9:02 PM Michael Leggett <notifications@github.com>
wrote:
Can you share a screenshot?

**Comment by leggett** [comment]
Sorry, the screenshot didn't come through. If you want to just email it to me, send it to hi.simplify@gmail.com.

**Comment by leggett** [comment]
Got a screenshot ... it was an issue with other extensions

**Comment by leggett** [comment]
Actually, not sure if this is what you were originally reporting (maybe you meant they are NOT showing instead of NOW showing), but I see now that the add-ons tray is broken. Fixing now.

**Comment by leggett** [comment]
It doesn't seem to happen often, but I'm seeing a mis-detection of the number of add-ons in the tray every once in a while. Refreshing Gmail usually solves it but I'm adding a minimum count of 3 so it will always show at least the default 3 add ons. Submitting this as part of v1.3.8.

**Comment by rhgaspar** [comment]
I'll let you know on my end. Thank you sir!

Regards,

Richard
214-704-4896 Cell/Text

**Comment by leggett** [comment]
I still think you're going to have a number of other problems with all those other extensions installed until I do something to play better with them. See #83 for details on that.

**Comment by rhgaspar** [comment]
I'm happy to work with you on troubleshooting if you would like. But it
won't be this weekend

Regards,

Richard
214-704-4896 Cell/Text

**Comment by leggett** [comment]
Thanks for the report. I'm looking into it right now. Tracking here: #244
