### ISSUE TITLE
Control inline images

### ISSUE THREAD

**Issue by n-kort** [leggett/simplify#179]
Hello. Firstly, thanks for this great extension! This is more of a feature request than a bug, but for some reason inline images in Gmail don't have a `max-width`, which means that the message thread and compose box can get blown off the right of the screen: 
![artboard](https://user-images.githubusercontent.com/1377218/57952595-fdabfc80-78ed-11e9-8fa8-9fa5bf32cc9b.jpg)

How do you feel about adding something like `img { max-width: 100% }` (or more specific) to the injected styles so I don't have to use an extra extension just for that 🙂

![artboard2](https://user-images.githubusercontent.com/1377218/57952616-069cce00-78ee-11e9-8d1e-638e408b44c8.jpg)

**Comment by leggett** [comment]
Yes! Love it. I'd want to scope it to the messages only just so there are no unintended consequences.

I'll add it in v1.3.8.
