### ISSUE TITLE
Revamp z-index ranking, esp around compose

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#18]
I need to redo the whole z-index system. I'm messing with things way too much and it has all kinds of unintended consequences. Here is another one. 

Link dialog is under compose mole:
<img width="438" alt="Screen Shot 2019-04-05 at 10 10 17 AM" src="https://user-images.githubusercontent.com/8763662/55644565-28e9ea80-578b-11e9-8bf0-e0a799e059a9.png">

**Comment by Martziano** [comment]
Any plans on creating a kick-ass email client like Inbox was going to be? because I am looking for that team.

**Comment by leggett** [comment]
Hi Martziano, sadly no, I don't have any plans to do that. I might write more about what I think should be built but I'm dedicated to spending my time working directly on climate change for the foreseeable future.
