### ISSUE TITLE
Inbox no padding from top

### ISSUE THREAD

**Issue by wylliamjiang** [leggett/simplify#180]
Not sure exactly why this issue might be coming up as I've had no problems with the extension up until now. Recently whenever I have the extension enabled it removes any and all padding from the inbox view.

![Screen Shot 2019-05-17 at 3 35 17 PM](https://user-images.githubusercontent.com/21237705/57959602-780e5980-78b9-11e9-89c1-bc69843e44f4.jpg)

**Comment by leggett** [comment]
You don't have the latest version of Simplify -- you need to update to at least v1.3.6.

**Comment by leggett** [comment]
Also, you might need to restart Chrome to have the update apply.

**Comment by wylliamjiang** [comment]
Yep, sorry about that.
