### ISSUE TITLE
Bad layout when "Out of storage" warning is shown

### ISSUE THREAD

**Issue by andrejkmet7** [leggett/simplify#182]
"Out of storage" warning is overlapping with buttons:

![image](https://user-images.githubusercontent.com/46405539/58006607-bdfd3480-7ae8-11e9-9f4d-4f9947481790.png)

Plugin version: 1.3.8
Chrome version 74.0.3729.157 (Official Build) (64-bit)

**Comment by leggett** [comment]
Bummer. I fixed this once but the classnames must have changed. Would you be willing to help me fix it?

I need a screenshot of the inspector with that element in focus. Right click on the warning and choose "inspect element". It will be a little hard with the bars overlapping... try right clicking at the very top of the screen. You'll know you selected the right one by the highlight when the inspector is open.

**Comment by leggett** [comment]
It should look like this:
https://github.com/leggett/simplify/issues/51#issuecomment-492345965

You can do it from your spam folder or something so no private information is shared.

**Comment by andrejkmet7** [comment]
I am unable to reproduce this right now, because I have updated my credit card info and the warning is gone... But I have just reverted the changes so I will see the warning again in one month, so I will inspect it then.

**Comment by leggett** [comment]
Request for help: just need a screenshot of the DOM around this element so I can figure out how to best target it.

**Comment by saadzee** [comment]
Simplify Beta Gmail 1.5.3:

Another warning similar issue: 
![G Suite Subs](https://user-images.githubusercontent.com/40451764/58835594-3e548700-860b-11e9-9807-67b73c189232.png)

Hope this helps.

**Comment by saadzee** [comment]
Sorry, this is the one with Simplify Beta Gmail 1.5.3:

![Screen-Shot-2019-06-03-at-2 26 44-PM](https://user-images.githubusercontent.com/40451764/58836026-67294c00-860c-11e9-840e-d0f114f976ea.png)

The previous post was with the live version Simplify Gmail Beta
1.5.0

**Comment by leggett** [comment]
Everything happens to you @saadzee! :(

Glad to see the corp logo is correctly hidden now. Can you right click on that banner and click "Inspect" and send me a screenshot of the inspector? Be sure to not right click on the action bar that is overlapping the red bar -- right click near the very top or maybe to the side.

**Comment by saadzee** [comment]
Haha =)

Here you go:

![Screen Shot 2019-06-03 at 3 22 17 PM](https://user-images.githubusercontent.com/40451764/58838501-b3c45580-8613-11e9-95d4-ec595f1c8bdd.png)

**Comment by leggett** [comment]
Ok, fix going in for v1.5.4. It is possible even these classnames aren't very stable and I should detect them... but I'm going to cross my fingers that they don't change.

**Comment by leggett** [comment]
P.S. The fix should put the banner in the bottom left corner and make it white text on a dark gray background with light-blue links (similar to the confirmations except you can't dismiss this one).

**Comment by leggett** [comment]
I'm closing this... feel free to re-open if you still see the issue post updating to v1.5.4+

**Comment by andrejkmet7** [comment]
@leggett: the one month expiration has kicked in today and its nok, here is the screenshot of 1.5.8:
![image](https://user-images.githubusercontent.com/46405539/60251525-f69ee380-98c8-11e9-9dfe-7018b753bbab.png)

I am unable to reopen this issue.
Thank you for your effort.
