### ISSUE TITLE
Send email and add-ins buttons

### ISSUE THREAD

**Issue by fiscalis** [leggett/simplify#183]
The create new email button and right panel access button locations used by Simplify Gmail conflict with important functions used by the Gmail Salesforce extension. Could you give us a couple of options as to where these items should be located?

![Simplify](https://user-images.githubusercontent.com/50847842/58052248-25c37780-7b09-11e9-9e2b-9eef27eb6522.JPG)

**Comment by leggett** [comment]
Simplify isn't compatible with other 3rd party extensions. I'm tracking the most popular ones to see if I can remedy this for a few extensions on issue #83. I'll add Salesforce to the list.
