### ISSUE TITLE
Option to enable click-to-show addons

### ISSUE THREAD

**Issue by jahirfiquitiva** [leggett/simplify#184]
Currently, addons are immediately shown after the small fab is hovered, but I always make the mistake of clicking it because that's the common/expected/ideal behavior for me

Can you please add this as an option one can turn on/off?

Thanks in advance.

**Comment by leggett** [comment]
Thanks for the suggestion. I'm going to pass on this one though. I don't want Simplify to have options. And I think this would add complexity to the widget that I don't want to add.
