### ISSUE TITLE
Back button in settings does nothing

### ISSUE THREAD

**Issue by jahirfiquitiva** [leggett/simplify#185]
![Grabación de pantalla 2019-05-20 a la(s) 20 32 42](https://user-images.githubusercontent.com/10360816/58062157-eb74cd00-7b3e-11e9-8810-5351643c7e08.gif)

**Comment by leggett** [comment]
Strange! I'll look into it right away. Thanks for the report.

**Comment by leggett** [comment]
Found the issue. Will get a fix out shortly.

**Comment by leggett** [comment]
Fixed in v1.4.0.
