### ISSUE TITLE
Taskbar panel causes search box to overlap settings icon

### ISSUE THREAD

**Issue by tony19** [leggett/simplify#186]
This issue is similar to #97 but *not* caused by third-party extensions...

When the side panel (for Tasks/Calendar/Keep) is opened, the search box is moved over, causing it to overlap the settings icon:

![Simplify Toolbar Layout Bug](https://user-images.githubusercontent.com/26580/58214090-1fc0c880-7cba-11e9-9c64-734a271d657a.gif)

 * Simplify 1.4.0
 * Chrome 74.0.3729.157
 * macOS Mojave 10.14.4

**Comment by leggett** [comment]
Thanks for the gif! Super helpful.

It looks like I'm not handling this combination (preview pane + add-ons shown) correctly. I'll look into it.

**Comment by leggett** [comment]
I've got a fix for it. Will include it in the next release (v1.4.1).

**Comment by AndreyYolkin** [comment]
This is not completely fixed.
When I was on main page, icons in app bar looked nice, but when I moved to the message, setting icon began to overlap the search panel. After refreshing page this problem disappeared.

- Chrome 75
- Simplify 1.5.8
- Windows 10.1803
- Screen resolution 1366px x 768px

![issue](https://user-images.githubusercontent.com/11289484/59979664-2dd47280-95f3-11e9-84f3-6ecbd30923c7.png)

**Comment by leggett** [comment]
Thanks for the report @AndreyYolkin -- it might be that you just had an old version of Simplify and hadn't refreshed Gmail in a while (or Chrome wasn't applying it for some reason). 

If you don't think that was the case, can you give me steps to reproduce this? I wasn't able to reproduce it. I tried setting my window to 1366px wide, changing my interface language, opening the nav and search, and then clicking on a message. I also played around with the add-ons pane. If you can reproduce it, happy to troubleshoot.
