### ISSUE TITLE
Not enough padding after options/more menu in email view

### ISSUE THREAD

**Issue by lydenyardley** [leggett/simplify#188]
Hi @leggett, Recently I've noticed there's not enough padding after options/more menu in email view... only when your extension is active. Also, the email content is not centre-aligned within email pane.

NOTE: I'm running 1.4.0, and in GitHub I see you've published 1.4.4, so not sure if this is now resolved? In any case, I can't get it to update, even by going into Chrome extensions > Developer mode on > Update.

I'll include screenshots here:

![Screenshot 2019-05-29 at 08 35 34](https://user-images.githubusercontent.com/2838799/58538592-5bddb700-81ed-11e9-8050-6fdbce852e00.png)
![Screenshot 2019-05-29 at 08 35 17](https://user-images.githubusercontent.com/2838799/58538593-5c764d80-81ed-11e9-9301-11fffa230d08.png)

**Comment by leggett** [comment]
Thanks -- I've actually got a fix for this and I thought I had pushed it out but I now see I haven't (it is in the code I've been working on for a couple weeks with support for some of the top 3rd party extensions). I'll leave this issue open until I get that pushed out as an update.

**Comment by leggett** [comment]
I've decided I'm going to push the fix (and some other much bigger changes) in the next couple days.

**Comment by lydenyardley** [comment]
Nice one! Thanks @leggett !
