### ISSUE TITLE
Layout issue - right alignment of middle messages

### ISSUE THREAD

**Issue by lydenyardley** [leggett/simplify#189]
Notice the star on the right-side. When there is more than one 'collapsed' message in the thread, the alignment is off. When I click to open that same second message, the alignment reverts to normal!

**Mis-aligned on right edge (collapsed):**
![Screenshot 2019-06-03 at 20 24 28](https://user-images.githubusercontent.com/2838799/58828641-cce1fc00-863d-11e9-84b9-8e882e326425.png)

**Correct aligned on right edge (expanded):**
![Screenshot 2019-06-03 at 20 24 49](https://user-images.githubusercontent.com/2838799/58828640-cc496580-863d-11e9-8f29-8f031526dbb2.png)

Let me know if that's unclear at all.

**Comment by leggett** [comment]
I think I fixed this in v1.5.3 that just came out today. It might not be fixed when the collapsed message has an attachment (though, even that case appears to be working for me). 

Can you see if that is the version you are running and refresh Gmail to see if it solves the problem?

**Comment by lydenyardley** [comment]
Yup - nailed it!!! Good man!
