### ISSUE TITLE
Actionbar is not moved to the top app bar when Multiple Inboxes is enabled

### ISSUE THREAD

**Issue by sryo** [leggett/simplify#19]

**Comment by leggett** [comment]
I can't get Multiple Inboxes to work at all. Can you share a screenshot?

**Comment by leggett** [comment]
Re-open when you send a screenshot.

**Comment by sryo** [comment]
![Screen Shot 2019-04-07 at 23 29 13](https://user-images.githubusercontent.com/46853/55695098-6f0e9c00-598d-11e9-9d70-e9833ee81755.png)

**Comment by leggett** [comment]
Oh my, very broken. I'll see if I can enable multiple inboxes on a different account (it still isn't working on my primary account).

**Comment by leggett** [comment]
Took me a while to figure out that I had to use the default inbox and deselect all but the primary tab to use multiple inboxes. Now that I've got that figured out, I can figure out how to support this setting.

**Comment by leggett** [comment]
This is fixed now in v1.1.7.
