### ISSUE TITLE
Use WebExtension Toolbox

### ISSUE THREAD

**Issue by balcsida** [leggett/simplify#194]
Hi @leggett,

I just recently stumbled upon your extension and it is super useful. Thank you for creating it!

I'm one of the maintainer/developer of a set of multi-platform extension dev tools called [WebExtension Toolbox](https://github.com/webextension-toolbox).
With this Issue, I would like to open the discussion with you and the community to possibly adapt this tool and other techniques to make the extension development easier and faster for multiple browsers.

I would like to be perfectly honest: I know this tool is not perfect, but currently, it works pretty good in our internal projects @liferay. I also think WebExtension Toolbox should go beyond internal projects and non-disclosed public projects - so it can pressure me to allocate more time to it.

Kind regards,
@balcsida

**Comment by leggett** [comment]
I think I'm good. The same zip and manifest file currently works for Firefox, Chrome, and Chromium-based browsers (new Edge, Brave, etc). 

Safari is the only pest currently because of the new requirements that an extension be party of an app.
