### ISSUE TITLE
Search bar overlapping settings again

### ISSUE THREAD

**Issue by pkedrosky** [leggett/simplify#195]
Think this is similar to a prior bug that was fixed, but search and settings are overlapping again. \
![2019-06-19_14-14-17](https://user-images.githubusercontent.com/3206644/59800909-9e4e5d00-929c-11e9-8e8a-699a19741fcd.png)

**Comment by leggett** [comment]
The help button being visible is the problem. I dynamically detect the help button to hide it every time Gmail loads so it shouldn't be visible. Can you reload Gmail or maybe even restart Chrome to make sure the problem doesn't automatically correct itself?

**Comment by pkedrosky** [comment]
Ah, restarting Chrome did the trick, but refreshing hadn't. Interesting.

**Comment by leggett** [comment]
It's super annoying... I don't know why Chrome does it. Sometimes the whole extension stops working until you restart Chrome. :/
