### ISSUE TITLE
Max width of inbox items

### ISSUE THREAD

**Issue by bgold0** [leggett/simplify#2]
First off this is genius. I commend you on make such a clean an elegant version of Gmail. I'll be using this everyday. Thanks so much for making this public.

Do you think there is any way for the end user to accomplish some slight css change to change the max width of the inbox items?  `html.simpl .AO .aeF > .nH`

I know we're talking about pure taste at this point.

**Comment by leggett** [comment]
Thanks! Glad you like it.

Making the max-width wider makes it harder to read content (as line lengths get pretty long). When I add support for preview pane, it will likely be a full-width UI but still apply a max-width to the message body. 

And I don't want to add any options for these extensions. What you could do is write your own mini chrome extension (you can use this one as a basis) that sets a different width and load that locally to override mine. Make sure you apply a "!important".

**Comment by leggett** [comment]
Changed my mind (ish). I'm going to play with setting it to be wider (perhaps 1100px) if the screen is above a certain resolution.

**Comment by leggett** [comment]
Ok. I bumped the default up to 960px from 900px and then if your screen is > 1450px wide, I bump again to 1100px. Not going any wider for readability concerns.

**Comment by bgold0** [comment]
Awesome man, I use this everyday and love it! Thanks for your dedication to an awesome email experience

**Comment by chirag04** [comment]
I just landed here to report that 960px felt a little too less. overall it looks like I have a lot of white space now.
