### ISSUE TITLE
Compose button misaligned

### ISSUE THREAD

**Issue by eavanvalkenburg** [leggett/simplify#202]
Hi, I love this extension, but as of late the compose button is shown overlaying the Inbox button: 
![image](https://user-images.githubusercontent.com/13749212/60887214-14b6fd00-a254-11e9-83b7-b48b8c4ab888.png)

I'm using Edge Chromium Version 77.0.197.1 (Official build) dev (64-bit). When I disable, enable the extension it is in the right place again (bottom right).

**Comment by leggett** [comment]
Thanks for the report! 

Super weird... so it is in the right place now after you disabled and re-enabled the extension? I can't seem to reproduce this but it might be that Gmail is about to change the classnames around the compose button and I just haven't gotten that version of Gmail yet.

Do you happen to have any other 3rd party extensions installed that change Gmail?

**Comment by eavanvalkenburg** [comment]
no, just yours, anyone I can try?

**Comment by leggett** [comment]
But the issue is fixed now, right?

**Comment by eavanvalkenburg** [comment]
no, sorry, when you disable, re-enable, it briefly shows the button in the right place, but then after a refresh or restart of browser it is again in the spot in the pic.

**Comment by leggett** [comment]
Got it. So either it is unique to your setup or you are the canary in the coal mine.

If you're comfortable with the inspector, can you inspect the element and send a screenshot of the DOM around the compose button?

It might be Edge somehow, but I doubt it as that is just a wrapper around Chromium.

**Comment by eavanvalkenburg** [comment]
So, I had a look, and I think it is related to the fact that the compose button is part of the left panel, while the three-dot button isn't, here is the dom:
![image](https://user-images.githubusercontent.com/13749212/60954459-49cc5980-a2ff-11e9-9775-a0b1073dc5c9.png)

**Comment by christian-steinmeyer** [comment]
I had the same problem. I'm using the Chromium based Edge browser and when looking for the build version, I saw that I had a pending update (three dot menu > help and feedback > about Microsoft Edge). After finishing this update through restarting the browser, the problem was resolved for me. Note, that before the fix, I experienced the following behavior: After activation of the extension and loading gmail, the button was in the correct place but change position to the top left on hover.

**Comment by eavanvalkenburg** [comment]
Indeed seems to have resolved with Version 77.0.211.2 (Official build) dev (64-bit)

**Comment by leggett** [comment]
Glad to hear it is resolved. Thanks for the report. It looks like the classnames are the same as before (what I was worried about).

I also just got Simplify v1.5.9 approved (it had an unusual 2+ week review period) and updated v1.6.0 immediately after. It improves the search experience and a few other things... let me know if anything looks out of sorts.
