### ISSUE TITLE
Email count colour is difficult to read

### ISSUE THREAD

**Issue by lydenyardley** [leggett/simplify#203]
Hi @leggett,

In the below screenshot, where it reads '1-8 of 8'... the text is low contrast due to the 70%  white being applied:
![Screenshot 2019-07-11 at 08 59 27](https://user-images.githubusercontent.com/2838799/61033064-945edc00-a3ba-11e9-9a8c-2c4a3f8de396.png)

And even more difficult to read in other areas of the image:
![Screenshot 2019-07-11 at 09 03 46](https://user-images.githubusercontent.com/2838799/61033190-d4be5a00-a3ba-11e9-8247-4ef220a291d1.png)

Here's the offending CSS:
`.Dj {
    color: rgba(255,255,255,0.70);
}`

Here's my setup:
- Priority inbox, with multiple sections (not multiple inbox)
- Background photo theme
- It's the same whether I select 'light' or 'dark' text background
- Simplify v1.6.0

**Comment by leggett** [comment]
Thanks for the well documented report. Sorry for such a slow reply. 

Simplify isn't setting the text color -- you would have the same issue with Simplify turned off as your background image is a mix of dark colors and light colors. 

The light/dark text background setting only changes the emails themselves, not the section headers (unfortunately). 

And if I tried to fix it and set the text to be dark, the "Unread" would be harder to read as it is on a darker part of the image. Not sure there is much I can do with this one.

**Comment by lydenyardley** [comment]
Hi @leggett Thanks for the response.

My suggestion is simply to make the section headers non-transparent: `.Dj { color: rgba(255,255,255,1); }`

That would help no end, and work better on any background (light or dark). Here's how that looks on the lightest part of my background (compare with my original screenshot above):

![Screenshot 2019-09-02 at 09 38 29](https://user-images.githubusercontent.com/2838799/64101331-8cda0480-cd65-11e9-98e1-1ba88843e22f.png)

To me, this is a no-brainer tweak... what do you think?

**Comment by leggett** [comment]
You're right. I do dim the pagination controls. I like it that way as I rarely look at or use that number but it is useful to some so I didn't just hide it. But for those that use it often or in certain themes, the dimming makes things bad. So I'll drop the dimming for now. Update coming in the next day or so.

**Comment by lydenyardley** [comment]
Thanks @leggett, 

I appreciate it!
