### ISSUE TITLE
Disable/remove Command J override

### ISSUE THREAD

**Issue by arv** [leggett/simplify#204]
Command J is interfering with some web apps that I use on a daily basis.

It is confusing that even when I only allow simplify on `*://mail.google.com/*` it still steals all `Command-J` key presses. Maybe that is a Chrome bug?

Can we disable this shortcut or remove it entirely?

**Comment by leggett** [comment]
Ack. I was worried this implementation would do that and I agree it is very annoying. You can see the history here: https://github.com/leggett/simplify/pull/193

The good news is you can change or even disable the shortcut by going to chrome://extensions/shortcuts

If this does indeed steal the shortcut for all tabs, I'm probably going to go back to how I had it before and figure out how to let people change the shortcuts on the Simply Options page (this will be the first preference I add).

**Comment by arv** [comment]
Thanks. That works for me

**Comment by leggett** [comment]
I want to leave this open for now as I don't think this screen is easy to find. Maybe it is as simple as linking to it from the Simplify Options page.

**Comment by JaapRood** [comment]
Just to have it logged: I went through a bit of a search when Cmd+J didn't work in some other apps, only landing here after about an hour 😅. I can't say I expected a well respected extension to override a shortcut like this, but perhaps I was just unlucky that quite a few other web-apps I use daily make use of it. Perhaps it's an idea to ship with this disabled by default, letting the power-users who want this kind of control opt-in to it?

**Comment by Leopere** [comment]
What if it shipped on by default since the users looking for this would be looking for Inbox.Google.Com behavior typically as it was the reason I found it.  Ya could potentially mention it the first time it's used and offer to toggle it off.

**Comment by leggett** [comment]
Ok, I've reverted to the way I used to do this which removes the ability to change the keyboard shortcut via chrome://extensions/shortcuts. I'd like to notify users about this change and give them the ability to edit the shortcuts on Simplify's option page before I push it out.
