### ISSUE TITLE
search cursor position with keyboard shortcuts is broken

### ISSUE THREAD

**Issue by captn3m0** [leggett/simplify#205]
This is post the July 9th update (https://github.com/leggett/simplify/commit/efd10350809ef62a2db9010addae3e10c81e8109). Steps:

1. <kbd>g</kbd> + <kbd>l</kbd>
2. Type a label quickly

If you start typing fast enough, the cursor moves to the first character while you are typing, resulting in a invalid search. (`|` is the cursor in the below)

- `label:|`
- `label:s|`
- `|label:s`
- `s|label:s`
- `ent|label:s`

Here's a gif:

![GIF](https://user-images.githubusercontent.com/584253/61297185-4eaa7500-a7f9-11e9-80c0-53e1423b542f.gif)

**Comment by leggett** [comment]
Nice find -- I try to put the cursor at the end of the search query when you tap to focus. It appears I am doing that milliseconds before the "label:" gets filled in. I suspect if I put a short delay on moving the cursor, it will solve it. I'll look into it.

**Comment by leggett** [comment]
Finally fixed this one. Thanks again for the report.
