### ISSUE TITLE
Its still very hard getting simplified hotkey behavior from Inbox.Google.com with suggestions from #200

### ISSUE THREAD

**Issue by Leopere** [leggett/simplify#208]
Ideally, it would be nice if we could just completely have the frustrating default Gmail behavior replaced and cleaned up by Simplify it feels as though Gmail is relatively hostile to the end-user inbox.google.com let me power through my entire email flow from the main view with one hand in under 5 minutes daily.  I was addicted to that blue sky screen at the end of my list of things.  It should not be this frustrating to power through my email in 2019.

**Comment by leggett** [comment]
I think #78 will get Gmail closer if I can figure out how to safely do it.
