### ISSUE TITLE
Customize rich text fonts

### ISSUE THREAD

**Issue by adityabhaskar** [leggett/simplify#209]
Setup:
MacOS 10.14.6
Chrome 75, 
Simplify 1.6.0

Simplify seems to standardise font sizes when composing, even though Gmail treats them as different. I realised when I saw an email I'd sent on the phone, and some of the text was slightly different size from the rest.

I tested on the laptop using the WhatFont extension, and turns out there's a 1px difference in the version displayed by Simplify (screenshots attached).

What I thought was a uniformly formatted email was a jumble of slightly different font sizes. Not very apparent on the laptop, but quite jarring on mobile.

Update: this may be related to #73 .

---

Simplify disabled:
<img width="1021" alt="Screenshot_2019-08-01_at_20_34_31" src="https://user-images.githubusercontent.com/2292388/62323171-94746800-b49e-11e9-8389-85de1cddf3e2.png">

Simplify enabled:
<img width="1052" alt="Screenshot_2019-08-01_at_20_34_57" src="https://user-images.githubusercontent.com/2292388/62323173-94746800-b49e-11e9-9e45-acf8d5398d5a.png">

**Comment by leggett** [comment]
I do bump up the font as visible in the composer but I don't believe this changes the font size of what is sent. Did you paste in some text or change the font size some in the composer? It might be I'm masking the difference... I'll do some testing to see if I can reproduce the problem. If you can give any more info or forward me an example to hi@simpl.fyi that might help.

**Comment by adityabhaskar** [comment]
The font change was my fault. I pasted some text, realised the wrong font, so deleted it and typed it in instead. The font size from the pasted text must have persisted.

The problem was that _Simplify masked the change_, so it wasn't apparent—while composing, or viewing—that there were two different font sizes in the email.

I'd be glad to provide more info, if there's anything specific you need.

Thanks for the extension!

**Comment by leggett** [comment]
That's enough info for me to understand what is going on (you did a great job figuring it out). But I'm not sure I can easily fix it unless I just stopped bumping up the font to 14px (which I really really like). 

FWIW, I almost always paste text without formatting (Edit > Paste and match style). I do it so much that I changed the keyboard shortcut globally to Command-Shift-V.

<img width="668" alt="Screen Shot 2019-08-30 at 1 42 39 AM" src="https://user-images.githubusercontent.com/8763662/64006603-8595cb00-cac7-11e9-9948-46be6112500e.png">

Feel free to re-open this if you have any suggestions about how I could handle this.

**Comment by leggett** [comment]
I changed my mind... I'm going to figure out how to not mask the difference or remove the font-size increase (or at least make it a setting... uhg... settings)

**Comment by leggett** [comment]
Can I change what font-size:small|medium|large|etc do to more safely change things?

**Comment by adityabhaskar** [comment]
Thanks for reopening this!

**Comment by adityabhaskar** [comment]
Hi @leggett, there's a related issue. When text is pasted into the editor, it shows as the regular default text colour. But after I press send, the sent email shows the pasted text in a different colour from the typed-in text. The typed-in text is black, as expected, while the pasted text is a dull shade of red.
I am guessing this is related to the editor font/color standardisation that impacts the font-size as well.

I can provide details replication steps and screenshots if needed.

Cheers!

**Comment by leggett** [comment]
Not a Simplify bug -- that's just how Gmail works (toggle off Simplify and you should see the same thing this time). Let me know if that's not the case.

Text is colored dark purple when it is quoted text. So if you paste text into the editor that appeared earlier in the thread, it will get colored purple for you on send. This isn't how others see it unless they too are using Gmail (it isn't styled in the email that is sent itself, Gmail adds the styling) and have the same emails in the thread history (if they were added in the middle of the thread and someone removed the quoted text, they won't have the original messages).

**Comment by leggett** [comment]
Ok, I'm removing all styles from fonts in compose and in the messages themselves (have this working in v1.7.8+). I'll take another shot at it in Simplify v2.

**Comment by andyszy** [comment]
Thanks for fixing this! I had actually disabled Simplify because I ended up sending out embarrassing emails that looked like crap, with mixed font sizes, and I wasn't quite sure what was going on but I had a feeling it had something to do with Simplify. Now I can safely reenable it.
