### ISSUE TITLE
LinkedIn invitation photos distorted

### ISSUE THREAD

**Issue by maseup** [leggett/simplify#210]
When Simplify is enabled, the photos inside LinkedIn connection invites are distorted. See in the screenshot here, the circle photo turns into an oval. 
https://www.evernote.com/l/Aawa31a6GLlH1rbQURG5usuvkEkivXysUpA

Additionally, the LInkedIn logo in the top right of the email is hidden. 

Chrome on MacOS
Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by leggett** [comment]
Thanks for the report. I'm seeing this too now (LinkedIn must have changed their HTML for these emails). I address this oddity when the height is set inline with an HTML attribute but I guess more is needed for width when the containing element is less wide. Should get fixed in v1.6.1
