### ISSUE TITLE
Opening conversations "In new window" results in extra padding

### ISSUE THREAD

**Issue by kevinlin1** [leggett/simplify#213]
When the option to open a conversation "In new window" (popout icon in the screenshot below) is used, the resulting new window contains some extra padding on the right resulting in an email body that isn't centered in the window. The padding is visible in the screenshot as well: notice how the card for the conversation doesn't extend to the width of the window.

I often encounter this because I use GMail's desktop notifications which open incoming emails in a new window.

![Screenshot 2019-08-21 at 9 07 56 AM](https://user-images.githubusercontent.com/1915715/63448858-bb65f000-c3f3-11e9-96c1-a61a1c92b02f.png)

This is caused by the following line of code.

https://github.com/leggett/simplify/blob/6b677e94331b6dc060000755d439d82e9ffb33c4/gmail/style.css#L629

The fix for this could be somewhat complicated because users can change the size of the window arbitrarily. Ideally, the conversation should be centered in the window with equal margins on both the right and the left, without the drop shadow effect from GMail's stylesheets.

**Comment by leggett** [comment]
Good catch. I should be able to detect that the window is a pop-out somehow and negate that extra padding. I'll look into it. Thanks for the report!

**Comment by leggett** [comment]
Finally got around to fixing this and added a bunch of improvements for popups too.
