### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by fiscalis** [leggett/simplify#214]
For some reason, it seems Simplify does not load the first time I start Gsuite/Gmail. Most always it works the second time around. It's worked fine for months and now this. When I open Chrome, I have it set to automatically load two tabs, one for Gmail and another for Salesforce. All I do to get Simplify working is click on the offending tab's refresh/reload link at the top left of page just to the right of the back and forward page arrow links.

THANKS!

**Comment by leggett** [comment]
I've seen Chrome have issues loading Simplify but they have never been reproducible after a restart of the browser or OS. 

- Have you restarted your browser lately? 
- If not, after you do, does the problem persist? 
- Do you have other extensions that modify Gmail?

**Comment by fiscalis** [comment]
Thanks for getting back to me so quickly.

How exactly should I "restart" my browser?

**Comment by leggett** [comment]
Quit Chrome and let all the windows/tabs close. Then open it up again. Restarting your computer should also do the trick.

**Comment by fiscalis** [comment]
Oh Yes, this happens frequently.

I cannot say for sure yet, but yesterday I did clear the cache including
history, images, cookies, and hosted app data. I had cleared the hosted app
data in quite a while, so perhaps including this step will help.

Bill

**Comment by leggett** [comment]
I can't repro this so closing for now. If you can provide steps to reproduce the issue, please re-open.
