### ISSUE TITLE
Support Gmail's new search tools when launched

### ISSUE THREAD

**Issue by Julian88Tex** [leggett/simplify#216]
### Issues
There appears to be a relatively new gmail feature named with the html label "search refinement" that provides suggested additional search parameters. When this feature is enabled and these parameters display, it pushes the select & refresh buttons on top of messages.

### Steps
1. Enable Search Refinement
2. Search for anything

### Results
-  If preview pane ("advanced" [formerly labs] setting) is disabled, buttons are pushed down to a somewhat odd location and search parameters formatting is oddly close to search:
[example](https://www.dropbox.com/s/cgqzy7mbxoxab57/Screenshot%202019-09-03%2014.47.36.png?dl=0)
- If preview pane is enabled, formatting is even odder with button appearing on top of messages and 
[example](https://www.dropbox.com/s/9oyf0a0brxdvbf2/Screenshot%202019-09-03%2014.43.22.png?dl=0)

### Note
- Confirmed that odd formatting doesn't occur when "Simplify Gmail" is disabled with or without preview pane enabled:
[example 1](https://www.dropbox.com/s/oyttzsixjj7nyj8/Screenshot%202019-09-03%2014.49.27.png?dl=0)
[example 2](https://www.dropbox.com/s/azh1fd8g9mnfgog/Screenshot%202019-09-03%2014.48.22.png?dl=0)
- "Search Refinement" is the css label name but I couldn't find any documentation on this feature so far. It may be a pilot and/or beta that is currently only available on business (Gsuite) accounts.

**Comment by leggett** [comment]
Yes, unfortunately, you have access to an early feature that I can't access or work with. :(

I emailed some of the people on the Gmail team about this (you're the second to have issue with this) and never heard back from them. I can try again but it seems that maybe I'm cut off.

**Comment by Julian88Tex** [comment]
@leggett Ah makes sense I figured as much. Appreciate you trying! Yes, I guess this is the downside of a delayed rollout... ideally though developers would have a way to get guaranteed early access.

**Comment by leggett** [comment]
These showed up on my son's account! I'll figure out how to support them soon.

**Comment by Julian88Tex** [comment]
@leggett Great thanks! :-)

**Comment by leggett** [comment]
A first attempt at supporting this went out with v1.7.1. For those that have it, let me know what you think please.

**Comment by Julian88Tex** [comment]
Looking really good to me thanks!

[Proof](https://www.dropbox.com/s/fqr4bl4f4p20a70/Screenshot%202019-11-23%2013.35.58.png?dl=0)

**Comment by leggett** [comment]
Thanks for checking but that looks broken to me still... it should be below the action bar and only visible when you are scrolled to the top. If you're using Chrome, v1.7.1 hasn't been approved yet.

**Comment by Julian88Tex** [comment]
@leggett Oh my bad you're right, I forgot about this second situation and didn't notice that buttons are still getting pushed down in addition to other issues.

**Comment by Julian88Tex** [comment]
@leggett hey noticed this one is closed but still seems to be happening... okay if we reopen?

**Comment by Julian88Tex** [comment]
I see thanks!
