### ISSUE TITLE
Leave the button of google app always visible

### ISSUE THREAD

**Issue by matteobz** [leggett/simplify#218]
Hi,
On my personal account, the google app button appears when I hover the button of my account (where there is my profile picture). But on my pro account, the button doesn't appear. To fix the problem, the app button could be visible at all times ?
Thanks

**Comment by leggett** [comment]
It should work for all account types (it works on my GSuite account). You can re-open this if you're still not seeing it on one of your accounts and are willing to help me troubleshoot. 

I've got a separate issue to try and show it all the time for large displays you can track here: #160
