### ISSUE TITLE
Idea: use tabs to simulate bundles somehow

### ISSUE THREAD

**Issue by dhleong** [leggett/simplify#22]
Hello! First of all, thank you for helping to fill the Inbox-shaped hole in my heart—and, I guess, for building Inbox in the first place!

One of the best features of Inbox was Bundles, and while Google suggests that its tabs are an adequate replacement for them, I find them seriously wanting. The most delightful part of the Updates and Promos bundles I had set up was that they showed up once a day, I could review all the updates that came in, then archive everything at once and not get bothered until the next morning.

I propose the following:
1. Add a settings page to the extension, for options config
2. Add a setting for each tab, something like "Show once a day / once a week"; possibly allow choosing a time (*show time*)
3. Add a button on the right side of each tab to "archive all."
4. When that button is pressed, or when the tab becomes empty, record the *emptied timestamp* and hide the tab
5. When *emptied timestamp* occurred before the *show time* for the current day, and the time is now after the *show time*, show the tab

Future work could explore the following:
- If all tabs other than Primary are hidden, hide the tabs row
- Perhaps, remove the tabs treatment altogether and show the tab entries inline as slightly larger email rows (reminiscent of the way bundles were treated in Inbox). For simplicity, clicking on an inline bundled-tab could just restore the tab and use the original treatment
- Use the settings page to promote labels to Bundles; gather such-labeled emails together into a Bundle row per tab. Clicking on such a Bundled Label Row could simply restore the default treatment

I don't have a lot of experience with Chrome extensions and haven't looked into the nitty gritty of this one yet, so I'm not entirely sure what all is possible, but ever since I had to restart my computer and lost the cached copy of Inbox I've been looking for ways to recapture the magic. I'm not sure the best way to go about making these changes myself so I wanted to make a proposal first and get some feedback!

Cheers!

**Comment by leggett** [comment]
I'm going to give the Gmail team more time to ship bundles. I'm also hesitant to do something like this because it won't be the same on mobile. But if they don't do something in the next few months, I'll reconsider what I could do with Simplify.

**Comment by dhleong** [comment]
Thanks for your time! I'd heard some rumors about bundles coming to GMail but nothing ever came of it so I started thinking about alternatives. Fingers crossed!
