### ISSUE TITLE
No longer working with 9/18/2019

### ISSUE THREAD

**Issue by KamranAsif** [leggett/simplify#221]
Looks like the lastest gmail broke the styles

**Comment by leggett** [comment]
I do a lot of things to adapt as Gmail changes their code. Can you share more about what broke? If Simplify isn't working at all, you may need to refresh Gmail or even restart your browser. Please let me know if the problem persists.

**Comment by KamranAsif** [comment]
The main padding to the right/left no longer seem to be working. I've tried restarting as well as re-installing the extension.

![image](https://user-images.githubusercontent.com/2875524/65157958-8a330c80-d9ff-11e9-8f2f-278164fbfff3.png)

**Comment by leggett** [comment]
That looks like horizontal preview-pane is enabled... do you have preview pane enabled under Gmail's advanced settings?

**Comment by leggett** [comment]
If not, can you share a screenshot of your whole screen? Your spam folder or promotions tab is fine.

**Comment by KamranAsif** [comment]
Disabling the split view in advance panel fixed it. Thanks for the help :)

**Comment by leggett** [comment]
Yup, split view allows the interface to stretch the entire width of the screen. This makes more sense in vertical split.
