### ISSUE TITLE
Find new way to hide ads at top of promotion tab

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#222]
Some users are reporting that Gmail's code has changed such that the html/css around an ad is the same as it is around emails breaking Simplify's ability to hide the ads at the top of the Social and Promotions tabs. 

I can't do anything about it until I see the change in my own account but I'm keeping an eye out.

**Comment by leggett** [comment]
This still hasn't shown up for me. Closing it out for now. Will re-open if it ever does.

**Comment by danielanewman** [comment]
@leggett I am now seeing this—ads at the top of the Promotions tab. Let me know if I can provide any other info to help diagnose.
<img width="1680" alt="2020-07-08_14-47-42" src="https://user-images.githubusercontent.com/5234389/86958394-1991e380-c12a-11ea-820a-1506ba337332.png">

**Comment by leggett** [comment]
I see it on my end too. 

I've got a robust fix for this in Simplify v2 that isn't dependent on the hierarchy of objects. If Simplify 2 isn't released in the next month or so, I'll look into back-porting that fix to the current version.

**Comment by leggett** [comment]
Actually, there is another bug showing up that I'm going to fix today. I'll fix this at the same time.
