### ISSUE TITLE
Search button hidden by Settings

### ISSUE THREAD

**Issue by SQLMagpie** [leggett/simplify#225]
On my laptop - which is 1366x768 pixels - the Settings icon and covers the Search button and I can only get the Settings to activate. See screen shot for example
![simplify](https://user-images.githubusercontent.com/56051726/66005475-842f3800-e4a3-11e9-8d18-02dcc29d3e49.jpg)

**Comment by leggett** [comment]
The support button is visible (it shouldn't be) and is pushing the search button on top of the settings gear. I can't reproduce this issue... if you're still seeing it would you re-open the issue and I can try to work with you to figure out what is going on.

**Comment by vchong** [comment]
I have the same issue.
<img width="371" alt="Screen Shot 2019-11-28 at 2 31 17 AM" src="https://user-images.githubusercontent.com/7334750/69746266-3a9f5880-1187-11ea-8318-d743bae9111e.png">

**Comment by leggett** [comment]
The help button is showing for both of you and it should be hidden. I saw it briefly in FIrefox but then it went away when I refreshed Gmail. 

Can you refresh Gmail (maybe a hard refresh by holding down the shift button when you refresh) and see if it persists?

**Comment by SQLMagpie** [comment]
Michael

I've tried the shift and refresh and it doesn't have any effect. I did try
making the window smaller on screen to see if it would move the buttons and
I noticed something odd. When I have the "Google Account" highlighted the
Support button gets "corrupted" - as per the screenshot below. If I move
the pointer to the Support button i get a highlight box that says "Google
Apps".

I'm pretty sure it isn't my gmail account as this works properly on my
desktop pc. I also checked that I had the most recent version of Chrome.

I haven't tried this with Firefox but can do if that would help? There is
another app which misbehaves in Chrome - Workona - it has descriptions of
the buttons instead of the actual buttons appearing. I've included a
screenshot in case it helps? I can send you a screenshot of what it should
look like if you need a comparison.

Tim

**Comment by vchong** [comment]
Hard refresh fixed it for me. Thanks!

**Comment by SQLMagpie** [comment]
I was having some other issues with Workona - which turned out to be an
adblocking issue. Checked to see if it was still an issue after I stopped
the adblocker on the Workona control page and it was but noticed that
uBlock Origin has a logging function, I enabled and did a refresh from the
logger of the gmail pages and it's fixed it! Hope that helps?

Tim
