### ISSUE TITLE
Margins on 13" 2017 MacBook Pro look broken

### ISSUE THREAD

**Issue by dru212** [leggett/simplify#229]
Not sure if this started happening after the latest extension update to 1.6.1 or the update to MacOS Catalina last week...

The Gmail margins looks fine on my external monitors but on the MacBook Pro screen they seem very wide and overlap on the right side. I've been using this extension for many months and didn't notice this before.  I'm running the latest Chrome Version 77.0.3865.120 (Official Build) (64-bit).

![Inbox](https://user-images.githubusercontent.com/31677159/66872709-7bd30480-ef5b-11e9-8f25-9ad7f0e87575.png)

**Comment by leggett** [comment]
Yeaaah... I moved one of the break points to be just under 1440px wide instead of just over. You'll notice a difference if you move your window to be just a tad less wide. Maybe that was a mistake. I'll look at it and revert quickly if it was.

**Comment by leggett** [comment]
Was a mistake. Will correct as soon as I can. I had some other small updates in v1.6.2 which are pending review for some reason. As soon as that is unblocked (which took over a week last time) I will update it.
