### ISSUE TITLE
Proposal: clearer Archived indicator

### ISSUE THREAD

**Issue by dhleong** [leggett/simplify#23]
Inbox had a nice checkmark on the right side of emails to show they're already archived. The Gmail row seems to know, since if I mouse over it the archive button is disabled. Would it make sense to implement the Inbox treatment here?

**Comment by leggett** [comment]
I don't think so as anything that doesn't have a "Inbox" label on it is archived.

**Comment by dhleong** [comment]
Ah okay, thanks for the tip. I did not notice that label.
