### ISSUE TITLE
New Command M shortcut overrides Mac system shortcut for minimize window

### ISSUE THREAD

**Issue by gojira** [leggett/simplify#230]
I don't see an issue for this (open or closed).  The new keyboard shortcut undoes years of muscle memory to minimize windows in Mac.  I hope there is a fix on the way (it sounded from another issue that it is going to be moved to Cmd-Ctrl-M?).

**Comment by leggett** [comment]
Cmd+Ctrl+M conflicts with a different shortcut. I'm going to add a setting to disable the shortcut at the very least and hopefully some way to change the shortcut.

**Comment by gojira** [comment]
Thanks - looking forward to the change!

**Comment by lukemcfarlane** [comment]
I just started having this problem too, looking forward to being able to disable this shortcut!

**Comment by leggett** [comment]
Super super close. Here is what the screenshot of settings looks like right now:
<img width="639" alt="Screen Shot 2019-10-23 at 4 23 26 PM" src="https://user-images.githubusercontent.com/8763662/67441393-86237d00-f5b1-11e9-9fa8-6c7ce771da58.png">

**Comment by leggett** [comment]
All of those settings will be disabled by default -- you'll have to turn them on if you want them. At some point, I'll let you set the keyboard shortcut to something else.

**Comment by leggett** [comment]
Setting added in v1.6.4. 

I might want to figure out a way to let people know the setting was added and these shortcuts were disabled by default for those that use them. Maybe only if they press that shortcut... I'd like to figure that out before I push it so I don't upset people that _are_ using them. Shouldn't take more than a day or two to wrap it up and push an update to the Chrome and Firefox stores.

**Comment by lukemcfarlane** [comment]
Sounds great @leggett, thanks for being so responsive and addressing this quickly!

**Comment by briatte** [comment]
Thanks indeed, many of us are Cmd-M addicts!

**Comment by gojira** [comment]
Yes, thanks a lot for the quick turnaround!  I had to disable it for the time being :(.  Thanks for the great work on the extension!

**Comment by leggett** [comment]
FYI: I've pushed the updates to Firefox and Chrome. Firefox accepted the update and Chrome is reviewing them. The few times that has taken more than an hour, it has lasted anywhere from 1 day to 17 (which I was told was a fluke). Hopefully it won't take long.

**Comment by gojira** [comment]
Hooray!  1.7 is out!  Thank you for quick turnaround!

**Comment by forivall** [comment]
Interestingly, firefox uses ctrl+M to mute the tab, but i don't think gmail has any sound playing anyways 🤷‍♀

**Comment by bgv2** [comment]
Couldn't you do Option + M and Option + S?
