### ISSUE TITLE
Set default 'Gmail navigation menu' to 'closed' (or make the default setting configurable)

### ISSUE THREAD

**Issue by vishrutarya** [leggett/simplify#235]
**Problem:** Opening a new Gmail browser window defaults the 'Gmail navigation menu' to be in the 'open' state. Given I rarely use this menu, this requires an additional step of toggling this menu closed (via the new cmd + M keyboard shortcut) virtually every time I navigate to gmail.com

**Feature request:** 
1. Opening a new Gmail browser defaults to the navigation menu being closed; or
2. The default setting for the navigation menu is configurable in the simpl.fyi configuration settings.

**Comment by vishrutarya** [comment]
Oh interesting.

No, I don't often sign out of my account; in fact, I virtually never log out of my Google account on Chrome.

**Comment by leggett** [comment]
I'll email you some more info but I don't think this is a bug in Simplify.

**Comment by jesperdahlstrom** [comment]
I have this problem aswell. I would much appreciate any tips on how to solve this!

**Comment by leggett** [comment]
Can you give me steps to reproduce the error? I'm trying this and not able to reproduce it:

- Open Gmail
- Close the left-hand nav
- Open Gmail in a new tab
- Observe nav is still closed on load (working as expected)

Maybe you have another extension running that is causing problems?

**Comment by jesperdahlstrom** [comment]
Im doing as you described. I have also tried to disable all my other extensions without success. Please tell me if there is something else i can do to help.
