### ISSUE TITLE
Hidden menu not appearing on hover

### ISSUE THREAD

**Issue by PhilEv90** [leggett/simplify#236]
Hi, 

Windows 10
Chrome Version 78.0.3904.87 (Official Build) (64-bit)
Simplify v1.7.0

As per title, the hidden menu is not appearing when hovering on the hamburger menu. It must currently be toggled on and off to navigate between folders/labels.
I believe that it used to drop down and show the icons without titles. 
Not sure if it's a bug or a feature taken away? Would be great to have this back. 
Thanks. 
Phil

**Comment by leggett** [comment]
Wasn't removed. You hover over the profile photo to see the Google app menu button. Is that not working?

**Comment by leggett** [comment]
Or maybe you mean the hidden left nav menu? With Simplify off, Gmail minimizes the left menu to a column of icons which you can hover over to see the full nav menu. Simplify hides the nav menu entirely disabling this interaction.

**Comment by PhilEv90** [comment]
Thanks, I did mean the hidden left nav menu as per your second comment. 
Could I ask this to be considered as a new feature? Perhaps in options to opt-in.
As in, when minimized, a hover would show the icons below only, without labels (to keep this Simplify'd). 
Thanks
Phil

**Comment by leggett** [comment]
Yeah, I'll look into it. If it has a slight delay (so it doesn't misfire all the time), I could see this being useful.

**Comment by leggett** [comment]
I've added this (show the nav menu when you hover on the hamburger button) in Simplify v2 (not yet launched). It works great!
