### ISSUE TITLE
The ads are back :(

### ISSUE THREAD

**Issue by JayTeeHaitch** [leggett/simplify#237]
I've noticed in the last week or so that I've got ads in my Social and promotions tabs. It wouldn't bother me if they were in the sidebar or down the bottom or something, appearing as an email is just a pain and I like clearing out the tabs as each email is dealt with.

**Comment by leggett** [comment]
I see it in my account too -- will work on it this weekend.

**Comment by leggett** [comment]
I've got a fix for this but I want to test it for a while to make sure I'm only hiding ads. Stay tuned.

**Comment by leggett** [comment]
This is fixed in v1.7.1 which is live on Firefox and stuck in review on Chrome. Hopefully in your browser soon.
