### ISSUE TITLE
Link to Simplify settings in pop-up is broken on Firefox

### ISSUE THREAD

**Issue by nyc** [leggett/simplify#241]
Hi, thanks for the great extension.

I just installed this on Firefox, and I couldn't figure out a way to open the options/settings page without using "Ctrl+M" to bring up the little pop-up that asks if I was trying to use the keyboard shortcut (I was). However, once you bring up that pop-up, the button to go to the "Simplify Settings" is broken.

It looks like it might be because the options URL was commented out in this commit:
https://github.com/leggett/simplify/commit/40e4960f88d2a606e7a4b6fcb58a49a9baa22ae4?diff=split#diff-695016f5c91c8995d61bc180a2a5fd75L181

**Comment by leggett** [comment]
Great catch – thanks for the report. Will be fixed in the next release.
