### ISSUE TITLE
Keep pagination controls visible at lower resolutions now that search semi-minimizes when not in focus

### ISSUE THREAD

**Issue by vchong** [leggett/simplify#242]
When searching for emails, a 'results' page is displayed with the number of emails found at the top. After selecting one of these email, a user can go back and forth through the results list by clicking on '<' or '>'.
![Screen Shot 2019-12-03 at 12 14 35 AM](https://user-images.githubusercontent.com/7334750/69971023-9fc9c400-1562-11ea-9d40-efde9681971f.png)

These buttons are not displayed when Simplify is enabled.
<img width="796" alt="Screen Shot 2019-12-03 at 12 14 49 AM" src="https://user-images.githubusercontent.com/7334750/69971089-b8d27500-1562-11ea-9bcf-3f7892931824.png">

Is it possible to support this?

Thanks

**Comment by leggett** [comment]
It is supported but the pagination controls are hidden below certain resolutions. 
![pagination](https://user-images.githubusercontent.com/8763662/69983037-9e5cb500-14ea-11ea-8f10-8c4bbf2c2db3.gif)

It is possible with the changes to search (I shrink the search box when it isn't in focus now) it could stay visible for longer.

**Comment by vchong** [comment]
I see. I have a sidebar visible on the browser that reduces the resolution (width) of the main window low enough to hide the pagination controls. I can see the controls now if I disable the sidebar.

Thanks!
