### ISSUE TITLE
Remove background from tab when empty.

### ISSUE THREAD

**Issue by seattleowl** [leggett/simplify#243]
When I have a tab empty, there's a background to the empty message.
![Screen Shot 2019-12-11 at 4 02 50 PM](https://user-images.githubusercontent.com/32573897/70671109-c4433180-1c2f-11ea-8fba-62cbc2858f01.png)
 I would like it to be a least a bit transparent.

```...
* {
   opacity: 0.5;
}
```

**Comment by leggett** [comment]
Definitely want to do this and more when you have no email in your inbox. There is a separate issue meant to cover all the ideas: #239
