### ISSUE TITLE
Tasks button missing from pop up menu (Firefox)

### ISSUE THREAD

**Issue by maxwood** [leggett/simplify#244]
Using Firefox, version 71.0 but the tasks button has disappeared recently.

Thanks for all your efforts developing this. It's a fantastic addon!

![image](https://user-images.githubusercontent.com/2072219/71029614-ac741d80-2107-11ea-8d5e-de7839cfd56b.png)

**Comment by leggett** [comment]
Thanks for the report. Working on it now.

**Comment by leggett** [comment]
Found the issue and am improving my detection of add-ons to include buttons that are put in that area via extensions instead of adding an actual add-on (Gmelius is one example). Will push out now as v1.7.3. Should be in Firefox quickly and in Chrome in a week or so.

**Comment by megaroeny** [comment]
I'm seeing this in Chrome. I didn't add/remove any Add-ons. Just using the defaults.
![image](https://user-images.githubusercontent.com/1559447/71104827-6dd37700-218a-11ea-9a2f-8bf49c4f2a06.png)

Here's my browser and system info: https://whatsmybrowser.org/b/VQ9DR8G

**Comment by leggett** [comment]
Ok, here is the latest:

Something changed in Gmail and I'm not sure what... but I've made changes that appear to fix the problem when I test it locally. I checked in those changes last night for Chrome and Firefox (v1.7.3) but somehow it appears to have broken again today. I've made more changes and checked those in to Firefox (v1.7.4) and will have to wait for v1.7.3 to go live on Chrome* before I can submit another update. If you're on Firefox, please keep telling me if it isn't working on your end after you get v1.7.4. 

*Why do updates to a week on Chrome? Sometime in 2019, Chrome changed its review process and the time for updating the extension that requests permissions to a specific domain has jumped from an average of ~1 hour to 3-7 days. I've tried explaining how much that sucks for Chrome users... not sure what can be done: https://twitter.com/DotProto/status/1199142025787871232

**Comment by leggett** [comment]
Ok, v1.7.3 finally went live in the Chrome Store (9 days after submitting) and I have submitted v1.7.4 that fixes this problem. So hopefully in 3-10 days it will be live too.

**Comment by leggett** [comment]
v1.7.4 went live on Jan 6th and fully fixed this as far as I can tell. Please let me know if you still have any issues. Separately, I'm trying to figure out how I can get the updates to get approved faster so it doesn't take weeks to fix bugs.
