### ISSUE TITLE
Dark mode broken for read messages

### ISSUE THREAD

**Issue by rejhgadellaa** [leggett/simplify#245]
It seems like a recent(?) Gmail update breaks Simplify when Gmail is in dark mode. Read messages are light grey (see screenshot).

![example](https://user-images.githubusercontent.com/4703109/71287271-3f12f780-2368-11ea-8471-e9eacf1d735b.jpg)

**Comment by leggett** [comment]
You have to reload Gmail if you switch between a light and a dark theme. The theme is only detected on initial load. I've tried to detect when the theme changes but haven't got it working.
