### ISSUE TITLE
Can you offer a keyboard shortcut complete replacement with the old Inbox.Google hotkeys?

### ISSUE THREAD

**Issue by Leopere** [leggett/simplify#247]
It seems very frustrating that this proposes itself as an extension to re-enable the useful features of Inbox. Still, all it does currently is massively reduces the UI clutter on the Gmail interface, which is fine, but inbox was far better at boosting productivity.  Although ultimately, I desperately wish that this was an email client and not just a modifier for Gmail as I don't care much for Google at this point.

Pressing the `?` key reveals the old `leet haxor` hotkey reference guide, from the "good old days" of Gmail. However, realistically that's not what made Inbox excellent; what made Inbox excellent was the fact that it was brutally reductive to the point of almost eliminating some data for the sake of just getting to the point.  It seems that this is a thing of the past at this point, and it breaks my heart.

**Comment by leggett** [comment]
I hear you and am right there with you. Right now, this is just a fun side project I do in my spare time. If I were ever to quit my day job, charge people for this, maybe I could go take it further. But I would need full API access which if I was a user, I would be very reluctant to give. Same goes for a 3rd party email client. 

For what it's worth, there is an advanced feature for customizing the keyboard shortcuts: Gmail settings > Advanced > Custom keyboard shortcuts. I use that to modify a few myself.

**Comment by Leopere** [comment]
Would it not be possible to use inbox folders as a labeling tool?
Otherwise, if it were to become a web client perhaps a support database
stored wherever a web client would be could be used.  Finally, why not just
start an OpenCollective page to see if you can't just make a reasonable
support salary from open source supporters.  I for one would support
something like this if it were usable on any SMTP server interface and
public/self hostable.  The biggest thing I'd like to see is even an
improvement as a whole for email interface like GPG made trivially and
safely hosted on your own self-hosted apps on your own self-hosted email
infrastructure.  Ultimately I really would like to just quit Gmail it
should be easy enough to run my own email server with Docker and all of
that other magic these days.  Something like this would be incredible if
you bring the workflow magic of a super bad ass email UI that does away
with conventions and just focuses on workflow.
