### ISSUE TITLE
Date group header for 2 months ago is hardcoded to August

### ISSUE THREAD

**Issue by kherock** [leggett/simplify#248]
Hi,

Title is self-explanatory, and the line in question is here:

https://github.com/leggett/simplify/blob/4a4fb1f8b5871522873c7f9ebd591a29755f075e/gmail/style.css#L117

If it's too much of a hassle to get a current month to show, I'm perfectly content with just lumping those emails into the "Earlier" group.

**Comment by leggett** [comment]
Wow... well that's just dumb on my part! What was I thinking?? Thank you for the report. I'll do something about it soon.

**Comment by leggett** [comment]
Finally fixed this. Thanks again for the report.

**Comment by daMelody** [comment]
Has this fix been deployed?  Using the 'group by date' feature now, and the category for "two months ago" still says 'AUGUST'.

lines 782-803 in gmail/script.js correctly return "FEBRUARY" as month2, so I'm not sure what's going wrong.

Thanks

**Comment by leggett** [comment]
I have the fix but have several other fixes that weren't done yet. In retrospect, I should have been working off a branch instead off of master so I could deploy this fix by itself.

The good news is I'm getting close to finishing the other fixes and this should be in soon.
