### ISSUE TITLE
Full dark mode?

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#249]
I know its not really a simplify thing but it would be really neat to have an option to invert/dark modeify the preview pane/the part of the page where it shows the email, so we can enjoy full dark mode without slowing  down the loading of gmail too much
 (by using custom dark mode extentions)
http://prntscr.com/qmoseg

**Comment by roguesoulboss** [comment]
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh  dynamic theme does pretty well but slows the loading of the page a lot...

**Comment by leggett** [comment]
Requires giving access to every website you visit (unideal). 

Did you try this in Gmail with Simplify enabled? Did it work well across different rich text or html emails?

**Comment by roguesoulboss** [comment]
Yes, suprisingly. If you enable simplify and this extention, it looks really good across all emails, it only takes too long to load. If you could maybe trim down the  dark reader code a bit (it is opensource and has a github) so it doesent take too long to load, it would be ideal... I only want gmail in dark mode, not other pa ges really..

**Comment by roguesoulboss** [comment]
proof: normal mail: http://prntscr.com/qn517v
rich text/html email: http://prntscr.com/qn52aa is as good as it can get

i almost want to use the extentions combined but the load time with dark reader on is soo looong...

**Comment by leggett** [comment]
I started playing with this for v2 and got further than I expected. But it has some unintended consequences / difficulties to get really right. 

This email from FexEx is a good example:
<img width="860" alt="Screen Shot 2020-05-16 at 5 57 39 PM" src="https://user-images.githubusercontent.com/8763662/82134988-b67f7280-97b2-11ea-95de-6505451f3edf.png">

Using Gmail's dark mode on mobile, I see that the header is not inverted but the icons in the footer are (making the YouTube icon impossible to read.

**Comment by leggett** [comment]
Here is another example of Simplify dark mode on desktop vs original vs dark mode on mobile:

<img width="867" alt="Screen Shot 2020-05-16 at 8 36 43 PM" src="https://user-images.githubusercontent.com/8763662/82135241-4f16f200-97b5-11ea-9b36-cfb0ce1b7904.png">

<img width="906" alt="Screen Shot 2020-05-16 at 8 35 44 PM" src="https://user-images.githubusercontent.com/8763662/82135243-52aa7900-97b5-11ea-8a08-7d41f0387cce.png">

![Screenshot_20200516-203819~2](https://user-images.githubusercontent.com/8763662/82135269-aa48e480-97b5-11ea-8f28-d26d3c37544b.png)

**Comment by leggett** [comment]
I'm guessing getting from 90% to 99% is a sizable task but I'll keep digging into it. If anyone has any pointers, tips, or resources on this, please share.

Maybe I can get it to 99%. Or maybe can detect when there are complex elements and turn off full dark mode for just those emails. As it is, I think it will be at least good enough to include in v2 as a "use at your own risk" feature that you opt into.

**Comment by leggett** [comment]
A couple good write-ups:
https://habr.com/en/company/yandex/blog/450032/
https://medium.com/dev-channel/re-colorization-for-dark-mode-19e2e17b584b

**Comment by KraXen72** [comment]
i already posted this here but this extention does a pretty good job in general + is open source
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by leggett** [comment]
I've got dark theme support working in Simplify v2 now.
