### ISSUE TITLE
Add back pagination menu + fix dismissal

### ISSUE THREAD

**Issue by Sushubh** [leggett/simplify#252]
![Menu on page number does not load in Simplify mode](https://user-images.githubusercontent.com/310098/74490280-07e73f80-4eee-11ea-9ff9-a1974f3b6ec4.png)

I have checked on Firefox, Chrome and (new) Edge and I have to disable Simplify to access this menu.

**Comment by leggett** [comment]
Correct -- I've had it hidden for a while. It has funny issues with it not dismissing correctly so I just hid it. It seemed like the need to jump to the end of the results was minimal but it makes sense that someone finds it valuable. 

I can look into adding it back and figuring out the dismissal issues.

**Comment by leggett** [comment]
I've added this back in Simplify v2 (not yet launched). You have to hover over the next/previous button to see the count of messages in your inbox but the menu works.
