### ISSUE TITLE
Profile pics in the inbox list view

### ISSUE THREAD

**Issue by forivall** [leggett/simplify#254]
[Feature request]

Ideally, this would be the icons as shown in the hover card, but failing that, some color based on a hash with the first letter shown in the middle of the circle.
![Screen Shot 2020-02-18 at 3 58 51 PM](https://user-images.githubusercontent.com/760204/74788838-baf5c700-5267-11ea-89a6-4a6b52ef3d49.png)

I noticed that the email address and name itself is in the DOM:
![Screen Shot 2020-02-18 at 3 50 16 PM](https://user-images.githubusercontent.com/760204/74788821-add8d800-5267-11ea-9375-2df4b3444034.png)
, so it's do-able to at least get _something_, albeit, not as good as what was in Inbox. Ideally, they would appear where checkboxes are, and change to a checkbox on hover, (and when one is checked, they all become checkboxes) as they did in Inbox.

This would probably be a similar complexity to #56.

**Comment by leggett** [comment]
I've played with this a tiny bit and it is on a list of things to try and do. One thought I had was to build a local cache of profile picture urls in conversation view and slowly replace something generic with actual faces. So definitely possible...

**Comment by leggett** [comment]
Closing this as it is a dup of #41 

I looked into this some for Simplify v2 but it didn't make it because (a) it is hard to do well and (b) I was surprised how many people do not have a profile photo. It is still on my list as a someday maybe.
