### ISSUE TITLE
Multiple Inboxes no longer full-bleed

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#257]
Gmail refactored how multiple inboxes works and it broke Simplify.

![Screen Shot 2020-03-05 at 9 49 39 AM](https://user-images.githubusercontent.com/8763662/76010311-8b7dc600-5ec7-11ea-983b-697b8e9570fa.png)

**Comment by leggett** [comment]
Finally turning my attention to this and I've almost got it fixed. 

Gmail totally re-wrote how Multiple Inboxes is structured (I'd say a good thing) and I needed to update how I detect it is enabled, that it is side-by-side vs stacked vertically, and how I restyle it.

**Comment by ymolodtsov** [comment]
So that was a bug – I recently tried that template and thought it was expected behavior. Thank you!

**Comment by leggett** [comment]
Ok, I've got a fix for this (mostly). The one downside is if you have your multiple inboxes set to be side-by-side (as you do in the above screenshot), it will make all your list views (labels, searches, etc) extra wide. I have the beginning of infrastructure to address this but it is a bigger change and I don't want to delay making this better any further.
