### ISSUE TITLE
Preview Pane In Gmail causing issues with simplify?

### ISSUE THREAD

**Issue by cougar6x6** [leggett/simplify#258]
Good Day Michael.
We have chatted in the past re Simplify,but i completely forgot how we communicated? sorry.
I just wished to let you know that one gmail account (not my others) is conflicting with Gmail preview pane? I keep receiving a dialogue box,I took a screen snip and attach it here.I do not have split screen enabled and I have toggled on and off and unloaded simplify and reloaded but it as not helped and you can see the text at bottom as follows(am not sure if its clear on the screen snip)

> 0.16 GB (1%) of 15 GB used,Manage Terms · Privacy · Programme Policies Last account activity: 57 minutes ago

The snip is below..my email is **amewi6x6@gmail.com**

All the best Steve
<img width="960" alt="Annotation 2020-03-05 132731" src="https://user-images.githubusercontent.com/61845580/76013518-4930a500-5f18-11ea-9131-09bcce361ef7.png">

**Comment by leggett** [comment]
Thanks for the report and screenshot. 

This is an unfortunate state that I learned some are in (they actually want to have preview pane on in advanced settings and toggle it on/off). I won't have a fix for that until I rebuild support for Preview Pane on (in settings) and off (set to No Split) and kill this warning. 

That is being tracked in #253 so I'm closing this bug. Let me know if you think it isn't covered there or I'm missing something.

**Comment by cougar6x6** [comment]
Hi Michael
Really good to hear from you.Afraid i am not very tech savvy,but as long as it is own your to do list that's fine with me.funny thing is,the issue only appears with 1 x Gmail account, and I have several,which are continuing no issues what so ever.
Cheers Steve

**Comment by cougar6x6** [comment]
Oh Michael
I am so embarrassed,I was looking at my gmail settings went in to INBOX and saw that I had for some reason (never before) had ticked:-Reading pane: | Enable reading pane 
Of course I new instinctively what had occured and low and behold, Yep the Inbox is back to how it should be..and explains why only one account should have being affected.
Sorry

Rehards Steve
