### ISSUE TITLE
New search categories hide the first email

### ISSUE THREAD

**Issue by mjabdulm** [leggett/simplify#260]
Hi,

The new search categories in Gmail hides the first email in the search results.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/29857497/76588979-9d3a1b80-650e-11ea-824b-f3eb91f7404e.png">

Thanks,
Abdul

**Comment by leggett** [comment]
Thanks for the report -- this is being tracked in #255 and I've started working on a fix. Closing this ticket.
