### ISSUE TITLE
Email action buttons are out of alignment

### ISSUE THREAD

**Issue by bryansmithsf** [leggett/simplify#262]
Email action buttons are escaping the email view pane. See the attached screenshot. 

<img width="679" alt="Screen Shot 2020-03-27 at 4 30 33 PM" src="https://user-images.githubusercontent.com/17604285/77808529-ecbd3300-7048-11ea-8ca2-a65fcab5f34f.png">

**Comment by leggett** [comment]
There is no "Share this email" action in Gmail. What other add-on or extension are you using? I try to support some of the popular ones to some degree but I can't support them all.

**Comment by bryansmithsf** [comment]
This feature was added by Mixmax. It’s used by my company. Would it be possible to remove the text in the element with Simplify?

**Comment by leggett** [comment]
It is possible... I'll need to look into it. My free trial of MixMax expired so it might mean paying for the service to support it.

**Comment by bryansmithsf** [comment]
I have a basic paid account I can use to help.

**Comment by leggett** [comment]
Thanks, but I need to have it on my end. 

The solution isn't always straight forward and then I have to test any solution in a bunch of different setups (add-ons pane open/closed, nav open/closed, both nav and add-ons open, reading pane off/no split/vertical/horizontal, etc).

**Comment by leggett** [comment]
Ok, have a fix for this. Will go into the next version.
