### ISSUE TITLE
Scrollbar size

### ISSUE THREAD

**Issue by mjabdulm** [leggett/simplify#263]
Hi Mike,

Its an enhancement.

Is it possible to add an option to reduce the GMail's scrollbar size. 

I've a workaround through stylish add-on but I would prefer loading just one add-on.

Thanks,
Abdul

**Comment by leggett** [comment]
I played with this some and while I agree a narrower scrollbar looks nicer, it feels harder to use / click on. I'm going to go with function over form on this one.
