### ISSUE TITLE
"Disable Preview Pane?" dialog should be updated.

### ISSUE THREAD

**Issue by Leftium** [leggett/simplify#267]
The "Preview Pane" was renamed to "Reading Pane" and the setting was moved from "Advanced" to "Inbox" settings tab. So it was really hard to disable this setting! I thought my gmail account was stuck in a limbo state where the "Preview Pane" was enabled, but the option in the settings to remove it was gone!

This [announcement ](https://gsuiteupdates.googleblog.com/2020/02/multiple-inbox-updates.html) explains the change for G Suite, but the relevant parts also apply to vanilla gmail.

**Comment by leggett** [comment]
Thanks for the comment. Would definitely fix this except I'm about to get rid of this dialog as I add support for Reading Pane = "No split"
