### ISSUE TITLE
Hide reading pane when no messages are present.

### ISSUE THREAD

**Issue by seattleowl** [leggett/simplify#268]
Hey Michael! I use the reading pane as of today, and I wish the pane would go away when I have no messages in my inbox.

Thanks -OwL

**Comment by seattleowl** [comment]
Consept: (display: none on pane and seperator)
![Screen Shot 2020-04-22 at 4 15 24 PM](https://user-images.githubusercontent.com/32573897/80042748-99f26200-84b4-11ea-9a1d-371299aacc6c.png)

**Comment by leggett** [comment]
Definitely want to do this. Tracking on #239
