### ISSUE TITLE
Shift inbox / conversation to the left when compose / reply is popped out

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#270]
This was actually the intended design and it just never got built into Google Inbox or Gmail. 

Doing it for popped out replies is a no-brainer. Doing it to the inbox for compose is a maybe. 

Suggested by https://twitter.com/i/status/1253695264629698564

**Comment by cy2k** [comment]
That would be phenomenal, and given that most/all screens are widescreen now, it's a no-brainer given the available real estate.

**Comment by ymolodtsov** [comment]
That approach was validated by Superhuman. It works only for threads and it's incredible. If Simplify would add that to Gmail is would be wonderful.

**Comment by leggett** [comment]
This is now working in Simplify v2!
