### ISSUE TITLE
Fonts change size when Simplify Gmail enabled

### ISSUE THREAD

**Issue by jpotocki** [leggett/simplify#271]
I am getting a larger font on screen when Simplify Gmail is enabled, back to normal when disabled. Annoying. See 2 screenshots:

1. with Simplify Gmail enabled:
![Adnotacja 2020-04-27 111440](https://user-images.githubusercontent.com/4987508/80355640-a130bb80-8878-11ea-9ebc-af494de660a3.jpg)

2. and disabled (Ctrl+s):
![Adnotacja 2020-04-27 111533](https://user-images.githubusercontent.com/4987508/80355694-af7ed780-8878-11ea-926c-3508f1ee749c.jpg)

Is this a known issue /what can we do about it?

NB: Have "Preview pane" enabled (maybe this is the reason of font changes?), as see no option to disable it - where /how can I disable it (to check if this may cause font change /as said it breaks Simplify Gmail)? See screenshot:

![Adnotacja 2020-04-27 111246](https://user-images.githubusercontent.com/4987508/80355185-0df78600-8878-11ea-9ea3-e13fdbe0f9dd.jpg)

**Comment by leggett** [comment]
This is being tracked in #209 -- I have a fix for it that will go in the next release.
