### ISSUE TITLE
BUG: Toolbar shifts below when search for email in GSuite Gmail

### ISSUE THREAD

**Issue by JerryGoyal** [leggett/simplify#272]
Notice the toolbar location on a GSuite Gmail page with extension installed.

![image](https://user-images.githubusercontent.com/7106086/80400658-ba695480-88d8-11ea-9ef8-bc4901bc4e9c.png)

When I search some mail, that toolbar goes below and shows above the first email. See the highlighted ellipse.

![image](https://user-images.githubusercontent.com/7106086/80400405-5d6d9e80-88d8-11ea-8b52-afddcdad337a.png)

**Comment by leggett** [comment]
Thanks @JerryGoyal -- this is the same as #260. I have a fix for this that will go in the next version.
