### ISSUE TITLE
Update screenshots on README and on simpl.fyi

### ISSUE THREAD

**Issue by ahatzz11** [leggett/simplify#273]
Example:
![image](https://user-images.githubusercontent.com/6256032/80540888-c6542580-896f-11ea-8530-fcd83f8a808d.png)

Here is a site for this image: https://raw.githubusercontent.com/leggett/simplify/master/screens/09.png and this is what I get when clicking that:

![image](https://user-images.githubusercontent.com/6256032/80540914-d3711480-896f-11ea-8a6b-01788585717b.png)

**Comment by leggett** [comment]
Thanks! I'll look into it soon. I need to make new screenshots in general as Simplify has changed a fair bit since these early ones.

**Comment by leggett** [comment]
All the images load for me including https://raw.githubusercontent.com/leggett/simplify/master/screens/09.png

I'm going to repurpose this ticket to update the screenshots though.
