### ISSUE TITLE
Search chips still covers nav for side-by-side multiple inboxes

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#274]
![image](https://user-images.githubusercontent.com/21956756/81173641-af7d8680-8fa0-11ea-9545-6bf0339adbc8.png)
i just noticed this today so it's probably really new
this is how it looks without simplify:
![image](https://user-images.githubusercontent.com/21956756/81173717-d0de7280-8fa0-11ea-8360-e5d32b0ee156.png)
i would suggest moving it here:
![image](https://user-images.githubusercontent.com/21956756/81173784-e81d6000-8fa0-11ea-9416-e4afafb7795e.png)

**Comment by KraXen72** [comment]
```css
.G6 {
    margin-left: 215px;
}
```
this fixed it

**Comment by KraXen72** [comment]
by default this is solved in gmail like this - but i can't replicate it...
![image](https://user-images.githubusercontent.com/21956756/81192961-20ca3300-8fbb-11ea-8401-9ce4d0869a36.png)

**Comment by leggett** [comment]
Hmm, it shouldn't cover the nav. I thought I fixed that. Can you either send me a bigger screenshot (you can email it to hi@simpl.fyi) or tell me more about your setup? (Do you use reading pane? How big was your window? What kind of inbox setup do you use? etc)

Maybe I used an aria attribute which would break in non-english setups. I try to never do that but maybe I slipped.

**Comment by leggett** [comment]
As for the horizontal scroll bar (for when there are more chips than fit on the screen). That was the best I could do for now. As I recall, Gmail's solution (the right arrow) didn't work after I moved the bar. 

I'm working on Simplify v2 now and hope to see if I can do better after I move some things around.

**Comment by KraXen72** [comment]
Hi, i sent an email to hi@simpl.fyi with all the details.

**Comment by martenson** [comment]
I am having same situation. This is after you search for something and work with the results.
![Search_results_-_emulatorer_gmail_com_-_Gmail](https://user-images.githubusercontent.com/1814954/81555295-a1f14380-9388-11ea-96b6-87156ef336b4.png)

**Comment by leggett** [comment]
Found the issue -- will submit a fix today.

**Comment by leggett** [comment]
To confirm, I believe you both have large windows (larger than 1639px wide) and the nav is open. Let me know if that is not the case.

**Comment by leggett** [comment]
If you had a smaller window, please re-open this issue. Otherwise, this will be fixed in v1.7.12.

**Comment by leggett** [comment]
I found another case where this happens... Multiple Inboxes side-by-side breaks it too. I'll rename/reopen this but I think I won't fix this until v2 as the entire system of detecting and handing different inboxes will be dramatically improved then.

**Comment by martenson** [comment]
> To confirm, I believe you both have large windows (larger than 1639px wide) and the nav is open. Let me know if that is not the case.

correct, 1890 for me, it is much better now, thank you for the fix! 🥇 

![Search_results_-_emulatorer_gmail_com_-_Gmail](https://user-images.githubusercontent.com/1814954/81784531-4a281900-94fd-11ea-95ef-81245615acba.png)

**Comment by KraXen72** [comment]
in 1.7.12 it is fixed for me, so i guess ill close the issue. If you guys still have this problem reopen the issue.

**Comment by leggett** [comment]
Keeping open for Multiple Inboxes. Glad it is separate from the issue you are having.

**Comment by leggett** [comment]
I'm going to fix this in v2.
