### ISSUE TITLE
Hide Meet widget if Chat is disabled

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#275]
If the user has disabled Chat, you could make a case that they would like to hide the Meet widget too.

**Comment by leggett** [comment]
Or it _could_ be a Simplify Preference...

**Comment by ymolodtsov** [comment]
Not sure, I haven't used chat in years but find some use for Meet widget despite that.

**Comment by leggett** [comment]
There is now a Gmail setting to hide the Meet widget if you want.
