### ISSUE TITLE
Reader view/plain text for html emails

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#278]
I have preview pane on, set to about half of the space, and its really annoying, when i get an html email where half of the lines are off screen. 

normal emails can overflow pretty good:
![image](https://user-images.githubusercontent.com/21956756/82023930-4a581e00-968f-11ea-8e5f-179535d0fb4c.png)
  
my problem - html/rich text emails don't overflow which cuts them off: 
![image](https://user-images.githubusercontent.com/21956756/82023782-141a9e80-968f-11ea-89d3-eb054124b19e.png)  
 ## Solution:

Either force overflow to normal in all children of the mail, or have a toggle to view html/rich text emails in plain text/reader view/markdown.  
 
reader view example built in vivaldi browser:  
![image](https://user-images.githubusercontent.com/21956756/82023624-d74ea780-968e-11ea-8859-54099248a8a8.png)
https://help.vivaldi.com/article/reader-view/  
vivaldi reader view is good but it converts the whole ui which is not good.

**Comment by leggett** [comment]
Thanks for sharing this. 

- **A question**: can you still horizontally scroll at least?
- **A short term fix**: Gmail has a pop-out button ... but it is in the top right. If you can't scroll to the side, you can't get to it. You can also shift+click on the email and it should open it in a new window.
- **More thoughts**: I went way down the rabbit hole once on an email that refused to wrap. I don't remember the exact reasons, but as I recall, I found it was impossible to force it to wrap. If you send me the example email you have there to hi@simpl.fyi, I'll look at it and add it to my collection of emails I test.

**Comment by leggett** [comment]
I added a lot of things in Simplify v2 to try and force html emails to reflow. I can't always do it, but it should be better.
