### ISSUE TITLE
Toggle navigation menu open/closed also in Google Calendar?

### ISSUE THREAD

**Issue by jpotocki** [leggett/simplify#279]
Could you easily make Ctrl+M work also in Google Calendar?

Or do you know any other extension or shortcut that is doing it in GC?

PS: I love your extension, thank you for making it!

**Comment by leggett** [comment]
Thanks for the suggestion and glad to hear you enjoy Simplify so much. Currently the permissions are restricted to mail.google.com only preventing us from having access to or modifying any other website. 

I'm going to close this for now as it isn't actionable on the current Simplify Gmail extension but know that we're working on future plans to expand our product offering to other sites and apps. And if we do, we will certainly maintain the same shortcut for general actions across products.
