### ISSUE TITLE
Settings button overlaps the search button 

### ISSUE THREAD

**Issue by charmarkk** [leggett/simplify#280]
Perhaps inconsistently, but settings overlaps the search button, preventing me from pressing it. Plan to return later with full steps to recreate etc. In the meantime, here is a screenshot.

![image](https://user-images.githubusercontent.com/22264269/82937956-a7d55000-9f56-11ea-9671-a7e2d2ff1e64.png)

**Comment by leggett** [comment]
The help button is the cause -- the className on that element changes often. 

Simplify detects and remembers what the classname is each time you refresh Gmail. So a refresh should fix this about 5 seconds after it loads. Let me know if it doesn't.

**Comment by leggett** [comment]
Hmm... I take that back. I think maybe there is a live bug. Did refreshing fix the problem for you?

**Comment by charmarkk** [comment]
It does get fixed on a refresh, most of the time. Sometimes it takes a couple tries, but yes, it seems to be working now. Thanks for the quick reply!

**Comment by leggett** [comment]
I'm going to make this more robust in v2.
