### ISSUE TITLE
Bug: Layout Update?  Inbox view is now requiring me to scroll horizontally 

### ISSUE THREAD

**Issue by aakar** [leggett/simplify#282]
Looks like something changed with the container sizing?  Depending on the size of my window I'm required to scroll to the right-side to see the date/time when the email was sent.

![Sent_Mail_-_aakar_circleci_com_-_CircleCI_Mail](https://user-images.githubusercontent.com/337445/84037303-62f4e480-a96c-11ea-9ef3-f25834413ee5.png)

**Comment by leggett** [comment]
Thanks for the report @aakar. 

I'm not seeing this in the inbox but I am seeing it in label views when I have reading pane enabled and set to "No Split". I will get in a fix asap. 

Also, fwiw, I'm in the middle of building Simplify v2 which is a total re-write. It should make issues like this much less likely to happen.

**Comment by leggett** [comment]
Found and fixed the problem. Uploading to Firefox, Chrome, and Edge stores now.

**Comment by leggett** [comment]
Submitted.
