### ISSUE TITLE
search bar and pane settings overlap

### ISSUE THREAD

**Issue by derylseale** [leggett/simplify#285]
There seems to have been a recent change with GMail settings that now causes the collapsed search bar and the pane options to overlap. I notice, too, that the main settings gear icon has changed, so maybe it's related?

<img width="1217" alt="Screen Shot 2020-06-26 at 9 48 16 AM" src="https://user-images.githubusercontent.com/1426718/85864431-856f6600-b792-11ea-816e-0e2fd0570728.png">

**Comment by leggett** [comment]
Thanks for the report. I added support for Quick Settings and thought I had this fixed this... but I guess not. I've been spending all my time on Simplify v2 that I must not have tested this enough. Will check in a fix today.

**Comment by derylseale** [comment]
Happy to help, looking forward to v2.

**Comment by leggett** [comment]
Fix checked in and update submitted to the various browser stores

**Comment by derylseale** [comment]
I updated to 1.7.16 but I don't see any difference in the behavior.

<img width="281" alt="Screen Shot 2020-06-28 at 11 42 51 AM" src="https://user-images.githubusercontent.com/1426718/85952041-c3a48b00-b934-11ea-8895-429d776da2e2.png">
