### ISSUE TITLE
Easier way to close message?

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#29]
Inbox let you click outside the message to collapse it. Duplicating that in Gmail is somewhat problematic as (1) it isn't obvious what is outside the message in the default white theme and (2) it doesn't make complete sense as in Gmail where the message is a new view (in Inbox it was expanded in a stream).

Other suggestions have been clicking on the title of the message. This is problematic as it could misfire when you are just trying to select the subject text to copy it. 

I'll leave this here as a placeholder to think on some more.

**Comment by CyborgSemon** [comment]
This is exactly what I miss most about inbox. Having all of your emails easily accessible by just clicking outside the open one to close is was sooo helpful!
This would be pretty cool if you did manage to get it to work. It is slightly annoying having to drag the mouse all the way up to the top just to go back to the inbox.

**Comment by dhleong** [comment]
Couldn't you press ESC to close messages in Inbox? That's not a 100% solution, but it might be a nice addition if we can make it work without interfering with other UI. I know I've pressed ESC a few times out of muscle memory before remembering it doesn't work the same.

**Comment by jmarquis** [comment]
You can actually set up ESC to close the current message in Gmail without any extensions:

1. Go to Settings → Advanced and turn on "Custom keyboard shortcuts"
2. In Settings → Keyboard Shortcuts, remove ESC from anywhere it currently exists, and add it to "Back to threadlist"

I'd love to be able to click out of a message too, but the ESC keybinding is nice too.

**Comment by leggett** [comment]
Good point. I might be able to just support that so you don't have to use that Advanced Setting.

**Comment by asomervell** [comment]
@leggett could you just put a simple div with an onclick either side in the blank space? I would hazard a guess people are just clicking to the left or right of the message? Looks like class="no" is the target area but floating over the div class="nh" ??

**Comment by leggett** [comment]
There are a lot of div's with class=nh. I have it working as far as changing the cursor but right now, clicking anywhere on the message propagates to that parent div. I need to play with event.stopPropagation on the messages and make sure that doesn't break something. 

I'm much less confident I can add a div and keep it from overlapping the message content. Maybe I can elevate the z-index of the message over that inserted div. Happy if anyone wants to take a swing at it and submit a PR.

**Comment by leggett** [comment]
Here is my CSS:

```
/* Style to hint that clicking outside the message goes back to the inbox */
html.simpl .aeF:hover {
	cursor: w-resize;
}
html.simpl .aeF > div:hover {
	cursor: initial;
}
```

**Comment by leggett** [comment]
Still not sure about supporting clicking outside the message to close it... (still considering). 

BUT, I will soon add support for pressing escape to exit a message. This will also leave a search or settings and return to the inbox or the previous list.

**Comment by TheFlatworm** [comment]
I wanted to bump this request about clicking outside of an open message to return to the email list.  It seems that with v2, the bounding area to click out of to return to the message list is more defined, and this would be a welcomed feature.

**Comment by leggett** [comment]
Thanks for the bump... I still have this in mind and have done some experimentation in v2.  can't do it via a click on the background but I can add and size new elements that sit in the gutters around the thread.

I'm also considering making the buttons to go to the next/previous **unread** thread easier. So maybe a few click targets outside the thread. I

**Comment by leggett** [comment]
FYI: This doesn't actually work. Gmail's Custom keyboard shortcuts feature does **not** support keys like ESC.

> You can actually set up ESC to close the current message in Gmail without any extensions:
> 
> 1. Go to Settings → Advanced and turn on "Custom keyboard shortcuts"
> 2. In Settings → Keyboard Shortcuts, remove ESC from anywhere it currently exists, and add it to "Back to threadlist"
> 
> I'd love to be able to click out of a message too, but the ESC keybinding is nice too.

**Comment by leggett** [comment]
Update on this: I added support for the ESC key closing a message to SImplify Gmail v2. It also closes settings, a label, or a search (returns to the inbox) and even returns to the primary inbox tab if you use the tabbed inbox and are on a different tab.

I continue to consider a mouse interaction for this (click outside the conversation) but am now considering that as part of a bigger idea (keyboard shortcuts and buttons to jump to the next/previous unread message). I'm tracking that on #460
