### ISSUE TITLE
Gmail toolbar misaligned w/ reading pane

### ISSUE THREAD

**Issue by s2eves** [leggett/simplify#290]
The new settings/google apps button cluster (top right) leaves the toolbar misaligned, slightly left of reading pane.

**Comment by leggett** [comment]
Thanks for reporting. I'm holding off on fixing this because I'm trying to finish Simplify v2 (which is a total re-write and redesign) and replace v1 ASAP. If it gets in the way of using Gmail, please let me know. And if I can't get v2 out by the end of this month, I will fix this.

**Comment by s2eves** [comment]
Absolutely, no worries.. thank you so much for the extension and for your
commitment to making Gmail a great user experience. Clearly they can not do
it with their own small army.

Cheers,

Sean

**Comment by leggett** [comment]
Fixed in v1.7.17
