### ISSUE TITLE
Sort labels with unread messages first

### ISSUE THREAD

**Issue by Gomat** [leggett/simplify#291]
Gmail's paternalistic label list sort algorithm really needs to be done away with. It would be great if Simplify could do that for us. My primary sort preference would be to sort labels with unread messages and then by label name secondary.

**Comment by leggett** [comment]
Gmail let's you do this already, no? You can set it to only show the label if it has unread mail and otherwise keep it under More.

I guess for heavy label users, it might be better to keep it visible (not under More) but grouped with other labels with no new mail. That's what you're asking for, right?

**Comment by Gomat** [comment]
Wow! If there's such a setting, I wasn't able to discern that from the setting name. I have a lot of labels and at least half of those with unread mail are located in More. Please tell me the setting to use.

Thanks!!!!

  - Scott
    413 210-0032
________________________________

**Comment by leggett** [comment]
You can set any label to only show in the nav if it has unread email in it. 

**You can do that under the label menu on the label in the nav by selecting "Show if unread":**
<img width="414" alt="Screen Shot 2020-07-06 at 11 38 56 AM" src="https://user-images.githubusercontent.com/8763662/86627631-7b611a80-bf7d-11ea-9bb7-dcc55fa83f73.png">

**Or you can do that in Settings > Labels**
<img width="790" alt="Screen Shot 2020-07-06 at 11 39 39 AM" src="https://user-images.githubusercontent.com/8763662/86627693-959af880-bf7d-11ea-9d62-dd56ab3419af.png">

Does this address your need?

**Comment by leggett** [comment]
I'm going to close this but feel free to add more comments or thoughts.
