### ISSUE TITLE
                           Newer/Older buttons overlap with Search and Help (Win10, Edge) 

### ISSUE THREAD

**Issue by Gomat** [leggett/simplify#292]
Using Edge (83.0.478.58) on Windows 10. The Newer/Older (less-than/greater-than) buttons overlap with the search and help buttons.
![Capture](https://user-images.githubusercontent.com/1144504/86797286-7ebbdb00-c03d-11ea-89ac-0367f315c33b.JPG)

**Comment by leggett** [comment]
The help button should be hidden. Try doing a hard refresh (hold down shift while pressing the refresh button) and Simplify should detect Gmail's changed classnames and auto-fix itself.

**Comment by Gomat** [comment]
![Capture](https://user-images.githubusercontent.com/1144504/86804148-afebd980-c044-11ea-978c-c6682c64960c.JPG)

**Comment by Gomat** [comment]
[image: Capture.JPG]
  - Scott
    413 210-0032

**Comment by Gomat** [comment]
![Capture](https://user-images.githubusercontent.com/1144504/86935621-07547d00-c10b-11ea-8352-817862aac870.JPG)

**Comment by leggett** [comment]
The help button being visible is still the problem here. 

What version of Edge are you using? Is it the new one (with the wave logo) or the older one with the "e" logo?

**Comment by leggett** [comment]
Sorry, you said that at the outset -- Edge 83.0.478.58 -- that's the new version of Edge I believe. I'm really stumped as to why the help button (the question mark) isn't hidden for you. :/

It can take a few seconds for Simplify to detect Gmail's updated classnames, but it should detect them each time you load Gmail. A hard refresh didn't fix the problem (holding shift while pressing refresh)? Or it did and it came back?

**Comment by leggett** [comment]
I'm able to reproduce the problem now and will work on a fix ASAP.

**Comment by Gomat** [comment]
:-)

  - Scott
    413 210-0032
________________________________

**Comment by Gomat** [comment]
Hi Michael,
I cannot figure out how to get Edge to update the Simplify extension. Mine
remains at 1.7.16 while 1.7.17 is available in the store. Can you help with
that?
  - Scott
    413 210-0032

**Comment by leggett** [comment]
@Gomat I don't see a way to do it in Edge (at least not on Mac). 1.7.17 went live for Edge on July 12th (Microsoft is a bit slow approving updates). Maybe you just need to restart your browser?

**Comment by Gomat** [comment]
That worked fine. Thanks!
  - Scott
    413 210-0032
