### ISSUE TITLE
Search box is not wide enough (Edge Browser)

### ISSUE THREAD

**Issue by Gomat** [leggett/simplify#294]
The search box only shows a couple of characters.
![Capture](https://user-images.githubusercontent.com/1144504/87800103-ffd45880-c81b-11ea-8fc5-0507ba94b2fd.JPG)

**Comment by leggett** [comment]
This is because (a) your screen is not very wide, (b) I have to leave space for those that use text buttons instead of icon buttons and (c) the search field is not focused. If you click on the search box, it will expand.

Simplify v2 will address this through a change in the design for the search+app bar.

**Comment by Gomat** [comment]
My Screen is pretty wide. I do not think that's the problem. There';s a lot
of room to the left of the search box. Maybe it's just not expanding
correctly. Here it is with focus in the search box (not expanded).
[image: Capture.JPG]
  - Scott
    413 210-0032

**Comment by leggett** [comment]
Your screenshot didn't come through, but here is what I see on my screen when my browser is less than 1280px wide:

Search not focused:
<img width="1260" alt="Screen Shot 2020-07-17 at 9 39 25 AM" src="https://user-images.githubusercontent.com/8763662/87810287-98b1a680-c811-11ea-8fe4-b2ba404499b8.png">

Search focused:
<img width="1261" alt="Screen Shot 2020-07-17 at 9 39 43 AM" src="https://user-images.githubusercontent.com/8763662/87810301-9ea78780-c811-11ea-94eb-3bd9bb2d4d8d.png">

**I'm not trying to say that this is an awesome experience, just the intended one for now.** 

In Simplify v2 (not launched yet), I actually hide the search box in conversation view entirely:
<img width="1283" alt="Screen Shot 2020-07-17 at 9 44 07 AM" src="https://user-images.githubusercontent.com/8763662/87810603-15dd1b80-c812-11ea-87aa-c7a58a006563.png">

There is a way to get to it if you need to do a new search while still in a conversation which makes the search box big:
<img width="1282" alt="Screen Shot 2020-07-17 at 9 44 59 AM" src="https://user-images.githubusercontent.com/8763662/87810698-3d33e880-c812-11ea-83d3-214dc3dfdf50.png">

And search is nice and big when not in a conversation:
<img width="1283" alt="Screen Shot 2020-07-17 at 9 45 51 AM" src="https://user-images.githubusercontent.com/8763662/87810758-55a40300-c812-11ea-8c45-6dd78cbc0481.png">

**Comment by Gomat** [comment]
Thanks, Michael. The search box is not expanding when I select it.
[image: Capture.JPG]
  - Scott
    413 210-0032

**Comment by leggett** [comment]
What precisely are you clicking on to expand it? You need to click on the text in the search box (the "in" in your earlier screenshot).

**Comment by Gomat** [comment]
yes, you can see the cursor in there next to the "n".
  - Scott
    413 210-0032

**Comment by Gomat** [comment]
I'm running Edge Version 83.0.478.58 (Official build) (64-bit) on Windows
10.
  - Scott
    413 210-0032

**Comment by leggett** [comment]
Unfortunately, I can't see any of your screenshots here. Can you email me directly at hi@simpl.fyi?

**Comment by Gomat** [comment]
Hey! Now it's working! Not sure what I did but it's good now. I'll let you
know if I can replicate the issue.
  - Scott
    413 210-0032
