### ISSUE TITLE
Inconsistent location of of action buttons (archive, delete, snooze, etc)

### ISSUE THREAD

**Issue by geoken** [leggett/simplify#298]
One of the biggest issues I've had with Gmail since being forced off Inbox is how I'm always hunting for the location of the archive or delete button. In inbox, this was always on the right, no matter what context I was in I knew exactly where I had to look to find the controls to action the current email.

In Gmail, even though it's a simple formula (action buttons on the right in reading list, top left in individual messages), I still find myself instinctively looking and even moving my mouse to the right while in a message.

I think it would definitely be a cool addition to somehow get it so that the controls are always on the same side.

**Comment by leggett** [comment]
Doing this would be super hard to support... so I'm going to have to decline the request. 

Simplify v2 places the actions in a more consistent place but they are not where they were in Inbox nor are they the same place as Gmail's hover actions.
