### ISSUE TITLE
magnify

### ISSUE THREAD

**Issue by thegaryking** [leggett/simplify#299]
Some (particularly older) users tend to magnify the browser window beyond where you have accounted for.  Some of the buttons go off the screen or overlap with others (e.g., trying to click search doesn't do anything for some magnifications).  it would be great if you could fix this.

**Comment by leggett** [comment]
What % do you magnify to?

**Comment by thegaryking** [comment]
try 175% altho it is a moving target.   then in the top right corner (sometimes only after you search once) you get < 0 >, where 0 is the magnifying glass meaning 'search'.  but you can't click on it.

**Comment by leggett** [comment]
This looks a lot better in v2 (which I hope to launch in ~6 weeks). Screenshots below.

Testing what I have now, it seems to work pretty well but it will depend on how high a resolution screen you use and on your Gmail setup. Use a low screen resolution with the nav and an Add-on open, and it will probably not be great. But it shouldn't be any worse than Gmail itself any more. 

And I figured out how to customize it further if needed based on the zoom level.

Here are some screenshots at 175% on a 1440x900 screen with the nav hidden:

<img width="1440" alt="Screen Shot 2020-07-27 at 7 54 02 AM" src="https://user-images.githubusercontent.com/8763662/88557109-a835aa00-cfde-11ea-939a-82048012ba79.png">
<img width="1440" alt="Screen Shot 2020-07-27 at 7 54 15 AM" src="https://user-images.githubusercontent.com/8763662/88557115-aa980400-cfde-11ea-812a-b1701465d6e0.png">
<img width="1440" alt="Screen Shot 2020-07-27 at 7 56 02 AM" src="https://user-images.githubusercontent.com/8763662/88557123-ac61c780-cfde-11ea-9d3b-3fecf5480c5f.png">

**Comment by thegaryking** [comment]
(I have a hires screen).  your first screen shot doesn't seem to have a
search option.  the rest looks great.  and many thanks, i'll look forward
to the next version.

Gary
--
*Gary King* - Albert J. Weatherhead III University Professor - Director,
IQSS <http://iq.harvard.edu/> - Harvard University
GaryKing.org <http://garyking.org/> - King@Harvard.edu - @KingGary
<https://twitter.com/kinggary> - 617-500-7570 - Assistant
<king-assist@iq.harvard.edu>: 617-495-9271

**Comment by leggett** [comment]
I hide the search box in message view for focused reading BUT I do not disable it. If you use the keyboard shortcut `/` or click anywhere in the action bar between the last button and the pagination controls (I change the mouse cursor to better expose this), the actions are hidden and you get the search box. Clicking out of the search box reverts to showing the actions.

<img width="1440" alt="Screen Shot 2020-07-27 at 8 23 02 AM" src="https://user-images.githubusercontent.com/8763662/88560175-a79f1280-cfe2-11ea-9247-fbfacddcf3c2.png">

**Comment by thegaryking** [comment]
oh that sounds perfect.  many thanks,
Gary
--
*Gary King* - Albert J. Weatherhead III University Professor - Director,
IQSS <http://iq.harvard.edu/> - Harvard University
GaryKing.org <http://garyking.org/> - King@Harvard.edu - @KingGary
<https://twitter.com/kinggary> - 617-500-7570 - Assistant
<king-assist@iq.harvard.edu>: 617-495-9271
