### ISSUE TITLE
Hangouts contacts button appears when hovering mouse over new email button

### ISSUE THREAD

**Issue by stwrt** [leggett/simplify#30]
When I hover my mouse over the new email button, the hangouts contacts button appears in the lower left hand side of the window, but does not appear to be functional. It then goes away if I move my mouse off the new email button.

![image](https://user-images.githubusercontent.com/1958441/55695173-2abed400-596c-11e9-822b-23b2de3e695c.png)

**Comment by leggett** [comment]
My son saw this one but I wasn't able to repro it. Will look again, thanks.

**Comment by leggett** [comment]
Nice catch. Found it and will submit as part of v1.1.1 later today.
