### ISSUE TITLE
Compatibility with Gmail Tabs by cloudHQ

### ISSUE THREAD

**Issue by dheeraj-chakilam** [leggett/simplify#300]
Hello,

My Gmail workflow is finalizing to consist of the following chrome extensions: Inboxy, Gmail Tabs, and Simplify Gmail. It all works fine for the most part, except when I make a search.

I have two tabs on Gmail Tabs "Inbox" and "Starred". Something that should be this (with Simplify disabled)...
![image](https://user-images.githubusercontent.com/20345157/89061320-84ea6200-d332-11ea-9e42-b0448b2e7dbb.png)

...looks like this with Simplify enabled
![image](https://user-images.githubusercontent.com/20345157/89061361-916eba80-d332-11ea-8c15-f29032fed74a.png)

**Comment by leggett** [comment]
I believe I've fixed all the issues with Gmail Tabs in Simplify v2.
