### ISSUE TITLE
Inconsistent width in email ist when reading pane is enabled but set to No Split

### ISSUE THREAD

**Issue by Newportkiwi** [leggett/simplify#301]
The width of the emails displayed in my inbox (sometimes other folders, but mostly inbox) is inconsistent. 

Sometimes they are the normal width - happy days! Other times they are very narrow, usually breaking to two lines:

<img width="1679" alt="2020-08-10_16-01-09" src="https://user-images.githubusercontent.com/16562458/89798063-98ac7a00-db23-11ea-9676-898859edb36d.png">

I'm using a screen res of 1680 width, so that's not the problem. It happens with or without labels, with or without attachments, and any gmail screen density setting. In other words, I can't find a pattern.

Happens in Chrome and Firefox, on Mac.

Thanks!

**Comment by leggett** [comment]
It looks like Gmail thinks you are using reading pane with the vertical split. I'm not sure why though... 

If you don't use reading pane, you can disable it under https://mail.google.com/mail/#settings/inbox > Reading pane > Uncheck "Enable reading pane" and that should solve the problem. 

If you do use reading pane, reply here and we can trouble shoot further.

**Comment by Newportkiwi** [comment]
You sir, are a scholar and gentleman.

Disabling the reading pane in the settings worked a treat.

Thanks!

**Comment by leggett** [comment]
I finally figured this out! It happens when you only have messages with short subjects and snippets. I'm working on a fix.

**Comment by leggett** [comment]
This was fixed with Simplify v2
