### ISSUE TITLE
Improved "message clipped" experience

### ISSUE THREAD

**Issue by davegaeddert** [leggett/simplify#304]
Personally I would love it if Simplify helped with how Gmail cuts off long emails. There are certain emails that I get (like digests from Basecamp) that routinely get "clipped". I find it really annoying to get to the bottom of one of those long emails, realize it got clipped, click a link to open the full email in a new tab, and then have to scroll way down and try to find out where I was so that I can finish reading.

![image](https://user-images.githubusercontent.com/649496/91089923-e217c180-e619-11ea-81ae-14ed6f42404f.png)

Do you think this would fit in Simplify? Seems like there would be a couple "simple" ways to make this a better experience.

**Comment by leggett** [comment]
Unfortunately, I can't do anything as the rest of the message is not laded at all. :(
