### ISSUE TITLE
Feature request: really hidden labels

### ISSUE THREAD

**Issue by joaquinvanschoren** [leggett/simplify#305]
Gmail offers a setting to 'hide' a label, but it is not really gone: it just moves under the 'More' fold, and that quickly gathers a lot of labels, making it messy. Also, some labels I want to *really* hide but not really remove.

A simple solution could be a 'Hidden' label that is really hidden by Simplify, including its sublabels. Then, people could make labels like 'Hidden/label1' and 'Hidden/label2' and they would all be hidden. 

Just a thought, feel free to close if this doesn't seem right.

**Comment by leggett** [comment]
Yeah, I could probably do that. I don't think I'd fully hide it... I think I'd add a "Hidden" group under the More section that let you see all the labels you've hidden.

**Comment by joaquinvanschoren** [comment]
Sounds good, thanks!

**Comment by leggett** [comment]
Cleaning out old requests and bug reports... is the issue the labels being visible in the nav or that they are visible everywhere (e.g., in the Add Label and Move To menu)

**Comment by joaquinvanschoren** [comment]
It's just that they are visible in the nav. It's fine if they are in the Add Label and Move To menus. 

There is a lot of email that I automatically label, i.e. stuff that I will get to later but I don't want to be reminded of all the time. Still, these 'hidden' labels will show up in the More menu, in boldface if there are unread emails, which I find very distracting. 

If these could be hidden as subtly as possible that would be great. Not having the 'uncertain reward' of seeing boldface labels every time I open the More menu would make it a lot less addictive to check these folders. Thanks!

**Comment by leggett** [comment]
Why not just put them all under another label (e.g., "Hide" or "Zzz" so it is at the bottom) and just never expand that label? It won't unbold that label but it is pretty out-of-sight.

**Comment by joaquinvanschoren** [comment]
That's what I do now but it is still distracting, I have relatively few labels and especially on a large monitor it very much in sight :). I would love to have an option like 'Don't boldface labels in nav' similar to  'Hide unread count in nav'.

**Comment by leggett** [comment]
Cleaning out old requests for the impending v3 launch... 

- I think Gmail added support for what you wanted (a separate "More/Less") section under the user labels section. Now when you elect to Hide the label in the label's options, it is hidden just with the user labels until you want it.
- Separately, I've had some users ask for a way to hide all the User Labels (they either don't use them much or at all but still want to see the system labels). For that, I'm adding an option in the next release of Simplify v3 to hide user labels under the "More/Less" toggle in the system labels section. 

That will go out with v3.0.69 and [v3](https://beta.simpl.fyi) should be out to all users and all browsers by the end of the year.
