### ISSUE TITLE
Date headings break when Gmail is left open overnight

### ISSUE THREAD

**Issue by scottsb** [leggett/simplify#307]
If I leave Gmail open overnight and then come back to it the next day, Simplify doesn't seem to update correctly: it will capture emails that belong in "Yesterday" still under "Today." This does not seem to happen 100% of the time, but I have not found the pattern. If I can find one, I'll update this issue.

**Comment by leggett** [comment]
Thanks Scott -- I've got this fixed in v2 and am racing to get it out to address this and other issues.
