### ISSUE TITLE
Inbox Zero triggers if sections are collapsed and blocks re-expanding those sections

### ISSUE THREAD

**Issue by alecbz** [leggett/simplify#309]
If I click "Everything else":

<img width="1202" alt="Inbox_-_alec_level_com_-_Level_Mail" src="https://user-images.githubusercontent.com/92369/91737695-68ce2080-eb7d-11ea-8b37-1b8909ee8725.png">

I get to this blank page:

<img width="1666" alt="Inbox_-_alec_level_com_-_Level_Mail" src="https://user-images.githubusercontent.com/92369/91737751-7d121d80-eb7d-11ea-9cfc-aaacf99b9da8.png">

with no obvious way to get things back (had to disable simplify).

**Comment by leggett** [comment]
Great catch! 

**Question:** Do you have other sections expanded? Were they all empty or did they have email in them? 

**Work around for now:** Refreshing Gmail should re-expand the section.

**What is going on:** Simplify thinks you reached inbox zero. When you toggle a section closed, Gmail actually removes all the emails in that list from the code so it looks just like an empty inbox to Simplify. I would expect this to only happen if all your sections are empty or collapsed. 

**How it should work** I think this is still Inbox Zero BUT you should be able to re-expand the collapsed sections somehow. There also needs to be a message in the bottom left (which I bet there isn't in this case).

**Comment by alecbz** [comment]
> Question: Do you have other sections expanded? Were they all empty or did they have email in them?

<img width="1663" alt="Inbox_-_alec_level_com_-_Level_Mail" src="https://user-images.githubusercontent.com/92369/91739556-17736080-eb80-11ea-8f08-97184cbb6b81.png">


Yeah it was just "Everything else", no email in the other sections.

> Work around for now: Refreshing Gmail should re-expand the section.

Doesn't seem to work for me. Need to disable simplify, expand the section in vanilla gmail, and re-enable simplify.

> There also needs to be a message in the bottom left (which I bet there isn't in this case).

Yeah my second screenshot in the original post should be the whole screen, no message.

**Comment by leggett** [comment]
First off, it is a fantastic edge case you've caught. Testing software often includes doing weird things to try and break things. So this is great!

**Here is a new work around:**
Disable Simplify (Option+S on Mac, Alt+S on PC), re-expand the section, and re-enable Simplify.

**What is desired?**
Simplify is trying to reward you reaching Inbox Zero with a super minimal interface (and a background if you don't use a theme with a background image). IF there was a way to escape this mode (show the inbox or re-expand these sections) when this happened, would you still want the experience as it is today?

**Comment by alecbz** [comment]
> IF there was a way to escape this mode (show the inbox or re-expand these sections) when this happened, would you still want the experience as it is today?

Meaning, still getting the "reward" background?

I think I'd lean towards "no"? I didn't really get to Inbox zero, I just hid the emails. In my head getting to Inbox zero means "dealing with" each of the emails, and just toggling their visibility temporarily doesn't feel like "dealing with" them.

But I think that's kind of moot; as long as there's a way to get back without reloading/disabling the extension, the specific decision seems less important IMO.

**Comment by quickdraw-m** [comment]
> > Question: Do you have other sections expanded? Were they all empty or did they have email in them?
> 
> <img alt="Inbox_-_alec_level_com_-_Level_Mail" width="1663" src="https://user-images.githubusercontent.com/92369/91739556-17736080-eb80-11ea-8f08-97184cbb6b81.png">
> 
> Yeah it was just "Everything else", no email in the other sections.
> 
> > Work around for now: Refreshing Gmail should re-expand the section.
> 
> Doesn't seem to work for me. Need to disable simplify, expand the section in vanilla gmail, and re-enable simplify.
> 
> > There also needs to be a message in the bottom left (which I bet there isn't in this case).
> 
> Yeah my second screenshot in the original post should be the whole screen, no message.
> 
> edit: Admittedly I don't have much of a reason for collapsing this section, just something I did when clicking around.

I am experiencing the same issue with the same triggers, and refreshing GMail itself is similarly not restoring the missing email.

Also, I am on dark theme, and am receiving no indication that this is an "inbox zero" status; if I wasn't looking for this as a bug, I'd just be wondering where the heck my un-actioned email has gone.  In this regard, I cosign @alecbz ; to me, this isn't a proper "inbox zero" as I have not actioned the email.

**Comment by leggett** [comment]
Sorry -- I should have updated the original comment. Refreshing Gmail won't fix it (the sections stay collapsed which makes sense). 

**Updated work around:** Disable Simplify (Option+S on Mac, Alt+S on PC), re-expand the section, and re-enable Simplify. I will get this fixed in the next couple days.

**Comment by leggett** [comment]
On your second point (no indication that this is an inbox zero status), most inbox setups have this but I have failed to maintain that for the sectioned inbox (Priority Inbox and the like).

**Comment by leggett** [comment]
A fix for this is going out tomorrow in v2.1.9.
