### ISSUE TITLE
Consider adding back Google Apps menu

### ISSUE THREAD

**Issue by Kuree** [leggett/simplify#31]
Google apps (9 dots on top right next to your avatar) is missing. It's quite useful to jump to other google services such as Drive and Calendar through the popup portal. Is there any plan to add it back?

Thanks.

**Comment by leggett** [comment]
Sorry to say but I don't plan to add the app switcher back. I need as much space as I possible to merge the app and action bars into one bar. I've just spent some time supporting the add-ons so you can at least see your calendar, tasks, and keep in the right side bar.

**Comment by melvinthambi** [comment]
It would be great if you can show the 9 dots (Google apps) while clicking on the profile picture.

**Comment by leggett** [comment]
New idea on how to sort of support this. I still don't to add back the app switcher button. Space remains at a premium. 

But I can add a mutation observer on the account switcher (.gb_7b) being shown/hidden and then toggle the display:block/none for the app menu (.gb_A). I'd also need to move the app menu to right:310px so it doesn't cover the account switcher. 

The biggest downside is this isn't obvious in any way. :/

**Comment by tcdk** [comment]
How about placing it above the new (+) and the (...) in the lower right corner? Lot's of space there...(don't know how well it will expand up)

**Comment by leggett** [comment]
Ok... not sure if this will please everyone. It certainly isn't super discoverable but it is close to where it is without Simplify and I really don't want it shown by default. I welcome feedback and will re-open if I get a ton of pushback or people still asking for it.

![app_switcher](https://user-images.githubusercontent.com/8763662/57354489-6e9a2a00-7120-11e9-892a-b36fce714334.gif)

**Comment by melvinthambi** [comment]
thanks @leggett

**Comment by jackcasey** [comment]
I found the current behaviour pretty odd and thought it was a glitch. But now I understand it's intentional and that there is a deliberate delay on reverting to the search button I can deal with it.

Another option would be putting it in the popup in the `...` menu above calendar, keep & tasks?

**Comment by leggett** [comment]
The timing on when it shows and when it hides isn't quite right. The delay is to give you time to get your mouse to the app switcher. There is probably a better way to do it so it doesn't feel so rough. I'll try to play with it a little more to make it less janky.

I considered adding it as another mini-fab or somehow in the add-ons mini-fab. But I felt the muscle memory of the app switcher being in the top right in every other Google app was going to be too strong and it would be unwise to diverge from where it is.

I also considered not having an app switcher and just showing the app menu when you click on your profile pic... but that is even less obvious/discoverable.

**Comment by leggett** [comment]
Ok, I've much improved how it shows/hides and will check it in with the next update (v1.3.5) in the next day or two.

**Comment by garyzim** [comment]
On one of my computers, mousing over my Google Account picture in the gmail window shows an app switcher under the picture. Nice. But on other computers the Google Account tooltop pops up and I can't say if it's covering the app switcher or if the app switcher just isn't there.  I find the app switcher convenient to move around my G apps, but it's presence isn't really a deal killer for me.

**Comment by nichruoff** [comment]
It`s not working on business accounts, just on regular ones.

**Comment by leggett** [comment]
It works for me. Might be a conflicting chrome extension that modifies Gmail and messes up what I'm doing.

**Comment by nichruoff** [comment]
The only thing different is that I use Opera and a extension to install chrome apps.

> Descrição
> Install extensions from Chrome Web Store.
> Versão
> 2.5.7

For me the apps just work on regular gmail accounts. But thanks anyway.
