### ISSUE TITLE
Better handling of 4K resolutions

### ISSUE THREAD

**Issue by phaseburn** [leggett/simplify#310]
The message list doesn't expand to fill the whitespace available on 4K displays. It clips the subject lines unnecessarily, and the whitespace between the labels on the far left and the messages makes it look like there's an ocean of white dividing them.

![Simplify v2 4K](https://user-images.githubusercontent.com/102327/91737459-f7ce3f00-eb63-11ea-8df4-04bb32e862db.png)

Can I suggest expanding the email list to use more of this whitespace in some manner?

**Comment by leggett** [comment]
**What is going on:** This is an ongoing struggle... I can expand the list but it makes the list harder to read/use (as the lines get longer and the date and hover actions are pushed further from the subject/sender name). It also makes the transition from the list to the conversation more jarring as I absolutely don't want the conversation to stretch the entire width of the screen. So for the most part, this is working as intended. 

**Things to try:** For such a large monitor, would it be better to use the vertical split reading pane and see both the list and the message at the same time? Or you could turn on Right-side chat (if you use chat at all).

**How it probably needs to work** I suspect v2 will at least have to add a setting to let people override what I think is the right trade-off and have the list be wider on really large screens.

**Comment by phaseburn** [comment]
I understand the balance issues, and your explanation of the transitions being jarring does make sense. An option to override would probably be the best solution for me, but perhaps as a workaround, moving the labels to the immediate left of the conversation view would make sense? The mouse movement to cross the ocean of whitespace between them is pretty jarring, too, considering how I use labels as individual boxes/piles of things, and am constantly going from label to message list to label to message list.

To answer your questions, I'm not fond of the reading pane at all but I'll give it a try, and I don't use chat in gmail, either. Monitor is also not particularly large, it's just a 4K resolution display on a Pixelbook Go and interface scaling disabled.

**Comment by leggett** [comment]
I added options to increase the width of the list or the message in a recent update. It isn't my preference but I had several people explain use cases where a wider view makes email easier (like commonly getting emails with large tables in them).
