### ISSUE TITLE
Integration with Boomerang is broken

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#312]
From an email report: "Integration with Boomerang is pretty broken. I know you said you haven't actively made efforts to support add-ons like that yet, but I figured I'd let you know. The problems are most apparent when viewing a message. In that situation, an out-of-place, large Boomerang button appears in the header area of the site, and clicking anywhere in that header area then leads to unexpected behaviors that don't line up with what you're actually clicking. I've disabled Boomerang for now."

**Comment by jayarr100** [comment]
Adding more detail to this:

First, please disregard the bit about the out-of-place, large Boomerang button. That was apparently an unrelated UI change on Boomerang's behalf that just happened to come up for me today, coincidentally, so it struck me as seeming unusual. But it's not actually related or a result of anything connected to Simplify.

As for the unexpected behaviors, please see the attached screengrab for illustration. As you'll see, the icons don't line up with their appropriate actions. Some are completely unclickable. Some are mapped to incorrect functions. And clicking on one (as shown with what ultimately opens the search box, despite my clicking on the overflow menu icon) causes things to _really_ go haywire, with the Boomerang button replicating itself numerous times.

[simplify-boomerang.zip](https://github.com/leggett/simplify/files/5152943/simplify-boomerang.zip)

**Comment by leggett** [comment]
Wow... I heard you liked a little Boomerang in your Gmail... so I gave you ALL THE BOOMERANG! That's pretty bad though. I expected other extensions to not necessarily look good and maybe some jank. But didn't expect this kind of breakage. Thanks for the video.

**Comment by leggett** [comment]
I greatly improved integration with other extensions including Boomerang in v2.3.3. Let me know if any issues persist.
