### ISSUE TITLE
Hovering over chat > nav inverts chat

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#315]
After hovering over the Hangouts icon to reveal the chat section in the left-of-screen menu, mousing back up into the upper area of that menu causes the chat section to turn white.

**Comment by jbsaff** [comment]
+1 when using the Orcas Island theme. When I reverted to the default white theme, the issue no longer presented.

**Comment by quickdraw-m** [comment]
I think this is the same issue I'm seeing on dark theme, but am providing this screenshot to show.

I've obscured my contact names, but they were all the same illegible very-light-gray as my name/status there.
![Screenshot 2020-08-31 at 17 38 28 (1)](https://user-images.githubusercontent.com/70546828/91772007-fd527600-ebb1-11ea-9710-9f6c6c6ee450.png)

This was happening the moment I moused over the Hangouts icon/bubble, didn't require moving away.

Oddly, now that I have refreshed, this problem has ceased, and a related one is happening: some kind of fade-through of a white background, within the Hangouts window.  Again, contact names redacted.  In this one I am circling the issue in red.
![Screenshot 2020-08-31 at 17 47 43](https://user-images.githubusercontent.com/70546828/91772217-6e922900-ebb2-11ea-8312-42aa020cc5ac.jpg)

**Comment by leggett** [comment]
Thanks for the added screenshots. Will definitely chase these down and address them.

**Comment by leggett** [comment]
I've got a fix for this in v2.1.11. 

I'm still not sure this design for the chat roster is the right one in general... or at least there should be option to leave it visible in the nav. So will come back to chat in general in a future version.
