### ISSUE TITLE
Bug (minor): Toggling the Reading Pane with multiple messages selected clobbers the search input with buttons.

### ISSUE THREAD

**Issue by phaseburn** [leggett/simplify#316]
![image](https://user-images.githubusercontent.com/102327/91740880-c441e380-eb68-11ea-9c38-24c251eb7f93.png)

**Comment by leggett** [comment]
Nice catch!

**Comment by leggett** [comment]
It seems I fixed this at some point... unable to repro the bug. Let me know if you see other wise.

**Comment by phaseburn** [comment]
I'm still able to repro this bug.

![image](https://user-images.githubusercontent.com/102327/93258711-95746180-f753-11ea-8d64-77c23c0af5f8.png)

This seems to be 100% reliable when Chrome is opened to Gmail for the first time since launching, but far less so when Chrome has been on Gmail for a while. Situation + steps as follows:

Situation: Have the reading pane set to vertical split.
Step 1: Select multiple messages, I usually do 3.
Step 2: Disable the reading pane entirely from the option that expands from your profile pic.

Search is clobbered with icons.

It doesn't seem to repro 100% of the time if you have messages selected before enabling the pane or if the pane isn't setup in that orientation when gmail first loads.

**Comment by leggett** [comment]
Got it. I can repro it now... will fix.
