### ISSUE TITLE
Action an email without having to hit "x" first

### ISSUE THREAD

**Issue by steventhebrave** [leggett/simplify#32]
In Inbox, you could use J and K to navigate messages then E to archive and # to delete and so on. In gmail you must first hit X to select the message. It would be great if messages were automatically selected as you hit j and k.

Thanks for the great extension!

**Comment by leggett** [comment]
In Inbox, didn't that only work if the message was open? 

I started to write that this might be possible but the more I thought about it, the more I'm not sure there is a good way to do it.

To do this, I would have to auto-select whatever message has focus. But then how would you select multiple messages via keyboard shortcut? As soon as you hit J, the previous message would unselect. How would I know when you wanted to keep it selected? X would unselect (I can't change what a keyboard shortcut does). 

Furthermore, I think doing that is pretty dangerous with keyboard shortcuts that don't have a modifier key. You might think a text field has focus and start typing and have a bunch of actions happen in the background. That is still a risk today but it has to start with pressing an X.

Feel free to re-open if you can think of a safe way to do this.

**Comment by steventhebrave** [comment]
Thanks. Didn't know it if it would be easy or hard so I appreciate the reply!
