### ISSUE TITLE
Add ability to show expanded chat roster inline in nav (Gmail's default UI)

### ISSUE THREAD

**Issue by jbsaff** [leggett/simplify#322]
The Simply option to always show chat is not working for me. The chat remains hidden until I mouse over the icon in the bottom left corner.  Default theme, v2.

**Comment by leggett** [comment]
This setting makes the chat button always visible in the bottom left corner even when the nav is closed.

There isn't an option to keep the chat roster visible as the bottom half of the nav, yet. 

This is one of a few places where I went more extreme for the beta to see what people think.

**Comment by jbsaff** [comment]
My usage commonly has 2-3 chats ongoing throughout the day, which I don't always want to have open at all times. Having the list of chats visible on the left nav lets me see when a conversation has a new reply.

I'll give this a try for now and circle back on how it feels.

**Comment by jradar** [comment]
i'm really liking the peek-a-boo functionality of this!

**Comment by leggett** [comment]
I don't think having no way to keep the chat roster visible is a viable offering... but it is helpful to see how many people are frustrated by the current setup to better decide the best default.

**Comment by ibmkahm** [comment]
I'm not sure it this belongs in the same topic but:
when chat is disabled in Gmail settings the chat button should never be shown. Currently, it is shown, but when opening the chat window there is an empty white screen. This does not make sense

**Comment by leggett** [comment]
@ibmkahm agree this is a bug. But it is a separate one. Created an issue here: #333

**Comment by leggett** [comment]
I got rid of this option and stopped hiding the nav (and therefore chat) when you open a conversation. But I should add back the option (probably rename it) and provide an experience for heavy chat users that shows the roster inline in the nav (aka Gmail's default UI).

**Comment by leggett** [comment]
I added this back before the v2 launch
