### ISSUE TITLE
Profile hover icons need background

### ISSUE THREAD

**Issue by scottjenson** [leggett/simplify#323]
![image](https://user-images.githubusercontent.com/1055674/91758211-7935c980-eb84-11ea-9460-a5db37f70ecc.png)

**Comment by leggett** [comment]
Yikes! Your actions are super close to the profile button. Small screen? Or maybe you're using reading pane?

Either way, definitely agree that there should be a background (or I may hide the actions while the app menu is open so there isn't an overlap).

**Comment by leggett** [comment]
Fixed in v2.1.9

**Comment by scottjenson** [comment]
Wow, that was fast. Well done. Just FYI, this was in the message view in a fairly large window. It was more that there were LOTS of actions across the top for the message, not that it was a small window.

**Comment by leggett** [comment]
I assumed reading pane with text buttons. Maybe with the nav open. Are you saying you don't use vertical reading pane?

**Comment by scottjenson** [comment]
sorry for the confusion. No, it was just a simple reading pane on a not-full-screen-width window
