### ISSUE TITLE
Bug: 'Show search options' not working

### ISSUE THREAD

**Issue by dbenac** [leggett/simplify#324]
Inability to access advanced search bar functionality.

Google Drive link to screen capture: https://drive.google.com/file/d/1BnloJJbNfQ7fmfhFxyGj-zY4D82ZmIRh/view?usp=sharing

**Comment by leggett** [comment]
Good catch. You can access it from list view but there is definitely a bug here (in conversation view and when something is selected in list view).

**Comment by dougwaldron** [comment]
There is also bugginess while in list view with nothing selected. The search options button works if search is not selected, but if search is selected, the button does not work. Plus it causes the icons to switch to the gray versions.

![buggy-search-bar](https://user-images.githubusercontent.com/737326/91990560-e28e1780-ecff-11ea-9dcd-2e0fc73ec35e.gif)

**Comment by leggett** [comment]
Oh, there too! Got it. Thank you!

**Comment by leggett** [comment]
Fix for this coming in v2.1.12
