### ISSUE TITLE
v2 - space bar no longer scrolls long message

### ISSUE THREAD

**Issue by freste** [leggett/simplify#325]
In v2, in a long message, space and shift-space do not vertical scroll. (At least for me!)
Arrow keys, pgup/pgdown, etc all work as expected.

Space does work for scrolling in the list of conversations.

**Comment by leggett** [comment]
Oh man! Early on, I started to work on enhancing Space / Shift+Space to jump to (and focus) the next/previous message OR scroll if the current message is longer than the view window. I never finished it (still hope to) and must have left the event listener. Will get this fixed in the next release.

**Comment by baychang** [comment]
Probably responsible for Space not working in the third-party extension I use, Simple Gmail Notes. In SGN's note field (appears at the bottom of a conversation) Space key does nothing, so it's probably getting eaten by the same event listener.

**Comment by leggett** [comment]
Fixed in v2.1.9
