### ISSUE TITLE
Large whitespace above "Everything else" even though no other categories are displaying

### ISSUE THREAD

**Issue by quickdraw-m** [leggett/simplify#326]
Screenshot pretty much says it all.  I use Priority Inbox with 3 sections: Starred, Important Unread, and Everything Else.  This email is in the Everything Else sections, and I have no other emails in inbox (visible or otherwise).  There's a ton of whitespace above the section header, even though there shouldn't be anything there to be taking up that space even if hidden.

Also note, you can see a single pixel gray line atop the gray bubble encasing that one email, that extends a little further than it should to the left and right where the top corners of the bubble itself begin to turn downward.  No idea what's causing that either.
![simplifyscreenshot](https://user-images.githubusercontent.com/70546828/91780382-65f71e00-ebc5-11ea-8a80-7c631a613bc2.png)

**Comment by leggett** [comment]
You have your sections set to hide when they are empty. They are hidden but still take up space. Simplify should reclaim this space.

The one pixel sticking out is the bottom border on the section. The keyboard focus is highlighting the message in the same color making it look odd. I'll have to think about what to do about that.

**Comment by quickdraw-m** [comment]
Yup, that's correct, I have sections set to hide when empty.  I'm a ruthless minimalist.  I _think_ Simplify v1 handled it properly (and stock Gmail does; I can't use extensions at work :( ), so this behavior is definitely throwing me.

**Comment by leggett** [comment]
I don't remember doing anything special for it with Simplify v1 but it might be that Simplify v2 is making it worse somehow. I think I increase the space between the sections some and that space is probably just adding up. Either way, it is a bug and I will fix it.

**Comment by leggett** [comment]
A fix for this will go out tomorrow in v2.1.9
