### ISSUE TITLE
Janky menus with hidden or overlapping icons (please add any examples here)

### ISSUE THREAD

**Issue by JamesKumeroa** [leggett/simplify#327]
When viewing an image from a Chat, the Details and Open in New Window icons are overlapping with the text.

![image](https://user-images.githubusercontent.com/70552262/91782553-866cba00-ec51-11ea-8882-175bad2f45ed.png)

**Comment by leggett** [comment]
Yeah, I restyled the menus but it breaks some of the menus I haven't found. I should pull back my restyling to try and target only the menus I'm aware of so this doesn't happen. Thanks for flagging this one.

**Comment by derylseale** [comment]
All of the default add on menus are similarly broken: Calendar, Keep, and Tasks. This is most noticeable in smaller windows (1024x768 in my case). 

<img width="313" alt="Screen Shot 2020-09-01 at 8 41 20 AM" src="https://user-images.githubusercontent.com/1426718/91852662-2533ef00-ec2f-11ea-8a83-3037810331a3.png">
<img width="300" alt="Screen Shot 2020-09-01 at 8 41 30 AM" src="https://user-images.githubusercontent.com/1426718/91852663-25cc8580-ec2f-11ea-8eab-008af1618338.png">
<img width="304" alt="Screen Shot 2020-09-01 at 8 41 38 AM" src="https://user-images.githubusercontent.com/1426718/91852664-25cc8580-ec2f-11ea-8da3-367731bdf62a.png">

**Comment by leggett** [comment]
That's not the menu being janky... you've made your window so small that the Gmail action bar is overlapping with the Add-ons pane. I don't think there is anything I can do about that. I _might_ be able to get it to go behind the add-ons but Gmail is still unusable in this state (1024px wide window with add-ons open), even with Simplify disabled.

**Comment by leggett** [comment]
Another example in the composer menus:
<img width="716" alt="Screen Shot 2020-09-01 at 11 01 09 AM" src="https://user-images.githubusercontent.com/8763662/91881748-d722e980-ec36-11ea-97c6-646eabafaaf8.png">

**Comment by leggett** [comment]
Ok, I revamped how I do menus and it should fix all these and any others. Basically, I default to expecting menus to having icons in them and then remove the extra left padding in the few I know don't have any icons.
