### ISSUE TITLE
"Minimal compose" option backwards?

### ISSUE THREAD

**Issue by jayarr100** [leggett/simplify#329]
I might just be misunderstanding the intention here, but it seems to me like the "Minimal compose" option within the extension settings might be backwards.

To illustrate, here's how the compose window looks with the "Minimal compose" toggle in the _off_ (switch to the left and not lit up green) position:

![minimal-off](https://user-images.githubusercontent.com/40185140/91856081-ae492700-ec2b-11ea-892c-750070a4d9e4.jpg)

And here's how it looks with the toggle in the _on_ (switch to the right and lit up green) position:

![minimal-on](https://user-images.githubusercontent.com/40185140/91856114-b99c5280-ec2b-11ea-81ca-95592742da4c.jpg)

Doesn't it seem like that should be reversed — with the extra formatting elements hidden away when "Minimal compose" is _on_?

**Comment by leggett** [comment]
It is poor naming on my part... it is more minimal but it doesn't look like it is. The formatting bar is stripped down to what I think are the most valuable items and then put inline. So it is fewer things... but more icons visible. 

Bottom line, working as intended but I need to rename the setting.

**Comment by leggett** [comment]
I'm going to do a lot more on compose in the next update but for now, I changed this setting to be called, "Alt compose buttons"
