### ISSUE TITLE
Switch to more compact view below certain resolutions.

### ISSUE THREAD

**Issue by dhleong** [leggett/simplify#33]
There's a keyboard shortcut to focus the hangouts conversation list (`hm`) that appears to do nothing if the sidebar is hidden. Would it be reasonable to show the sidebar in this case?

I would also be interested in a way to "break out" the conversation list into its own little window thing, but I suspect that's out of scope for this project.

**Comment by leggett** [comment]
The `hm` keyboard shortcut works for me with the sidebar hidden. But it shows the Hangouts menu. Showing Hangouts (and unhiding the nav) would be a lot harder. I'd have to listen for those keys and make sure the focus wasn't in an input or contentEditable field which can be buggy to support (I've done it in other extensions in the past). So anything beyond what happens now is unlikely.

**Comment by leggett** [comment]
As for a breakout for the conversation list... you can pop out a conversation. If you want to pop-out the inbox, I think that works pretty nicely with Simplify as is. I'm not sure what else I could remove/hide. You can use the Preview Pane view which drops the margins around the inbox. Or I could set the margin to drop if the window is below a certain size assuming someone is using it in a side bar. That could be cool. I'll look into it.

**Comment by dhleong** [comment]
Sorry, I meant the `hc` shortcut, but I understand if you've tried this before and it was more hassle than it was worth.

Thanks for your time!

**Comment by leggett** [comment]
I now remove the padding around the inbox and conversation when the screen is smaller than 960px wide.
