### ISSUE TITLE
Chat button still shown even when disabled in Gmail settings

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#333]
When chat is disabled in Gmail settings the chat button should never be shown. Currently, the chat button is shown when the nav is opened, but when opening the chat window there is an empty white screen.

**Comment by leggett** [comment]
I believe this is because Meet is still enabled. If you disable both of them, I don't think it will appear. Even still, I'm sure the roster is way too tall when it is just Meet and it should definitely go away if both Meet and Chat are disabled.

I will investigate.

**Comment by ibmkahm** [comment]
> I believe this is because Meet is still enabled. If you disable both of them, I don't think it will appear. 
No... i also disabled Meet, but the button is still shown!

**Comment by leggett** [comment]
in v2.1.11, chat button will change into Meet button if Meet is still on. If both Meet and Hangouts are disabled, the button will disappear.
