### ISSUE TITLE
Background on red highlight text in compose

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#334]
One of the things I had in early versions of Simplify v1 was changing the font size in compose to match the To and Subject field. But there were issues (detailed #73, #209, #271) and I eventually just removed it. 

In Simplify v2, I dug deep into this issue and solved it. If the text turns and **stays red**, my solution broke. 

This is one of the first things I built for Simplify v2 and I've been testing it myself for months with very few occurrences (which I then fixed). So it should be solid but I'm counting on wider testing to be absolutely sure. 

To help debug this and make sure it is rock solid, I highlight text in red so I can see when the issue resurfaces. It is normal to see a flicker of red (working as intended, will be removed for public launch). But it should never stay red.

**Comment by andymand** [comment]
Staying red. :(

![screenshot-mail google com-2020 09 06-08_45_53](https://user-images.githubusercontent.com/51393001/92326105-a3bcd200-f01d-11ea-9537-365b2567534e.png)

Steps: I sent a message to someone last night.  Today, I went to Sent folder, clicked Reply, typed a little intro, pasted the URL into the new compose message body, typed some more text, and the red persists.

I tried switching to a different email and back, to see if the compose refreshed in some way, but same red highlight.

**Comment by leggett** [comment]
Thanks for the report and clear repro steps @andymand. I see it on my end -- somehow this workflow is resulting in a composer that I'm not observing for the style issue. An odd work around for this case is to start and then delete a separate new message (which scans for composers and catches the inline reply). I'll figure this out and patch it in the next update.

**Comment by andymand** [comment]
Just found another instance which might help you narrow things down:

I was (again) working from a saved draft and near the end of the message, decided that I wanted to put the closing on one line

![screenshot-mail google com-2020 09 07-18_17_06](https://user-images.githubusercontent.com/51393001/92418675-b37c0980-f136-11ea-9d29-6b4b10d89f12.png)

so I backspaced over the couple of hard returns and the dreaded red highlight returned:

![screenshot-mail google com-2020 09 07-18_17_24](https://user-images.githubusercontent.com/51393001/92418690-c68ed980-f136-11ea-915d-eff33889a0db.png)

When I (re)added the hard returns, the red highlight remained:

![screenshot-mail google com-2020 09 07-18_17_38](https://user-images.githubusercontent.com/51393001/92418708-d9a1a980-f136-11ea-92ec-3917f6a05aff.png)

and I couldn't get rid of them except via undo, which meant that I couldn't get them on the same line without the highlight.  Maybe I could have copied and pasted?  Anyway, hope that helps with the sleuthing!

**Comment by leggett** [comment]
Yes, backspacing at the start of a line or pasting in text from another message both cause the underlying issue. 

That the text stays red (e.g. the formatting meant just for you in your Gmail is applied to the message that will be sent) is what is broken because Simplify is not observing these composers.

Working from Drafts or opening a message in another label like Sent reproduce that bug. I'm working on a fix for these.

**Comment by leggett** [comment]
Ok, I've improved this a lot and hopefully it doesn't happen any more. Going to leave the issue open though because I want to triple check everything before launching out of beta.

**Comment by andymand** [comment]
thx, I'll circle back if I see it again

**Comment by leggett** [comment]
In fact, I think I made horizontal reading pane worse in this update :(

**Comment by andymand** [comment]
...and I agreed to play in this beta space, knowing that regression was a possibility, so it's all good. :)

**Comment by leggett** [comment]
I'm calling this 100% done at this point and changing the red highlights to only show if you have "Debug" enabled in Simplify Settings.
