### ISSUE TITLE
Feature Request: Automatically set light mode/dark mode by system setting

### ISSUE THREAD

**Issue by danielanewman** [leggett/simplify#336]
I use [NightOwl](https://nightowl.kramser.xyz/) to automatically set my Mac to light/dark mode based on sunrise/sunset (similar to the OOTB behavior of [Dark Mode on iOS](https://support.apple.com/en-us/HT210332#:~:text=You%20can%20also%20set%20Dark,a%20schedule%20for%20Dark%20Mode.)) As I've been using it, I've noticed more and more websites automatically following my system's light/dark setting, and would love for Gmail to do the same.

**Comment by leggett** [comment]
Thanks for this tip... would love to support this. 

But, I think Gmail would have to do this... I can't change your theme for you. I could try to fully invert the default theme but that was be a massive project to get all the various corners of Gmail. Building on Gmail's dark theme is far more sustainable.
