### ISSUE TITLE
Transition to an empty inbox tab is highly disorienting when using the vertical split

### ISSUE THREAD

**Issue by danielanewman** [leggett/simplify#337]
The sidebar/reading pane configuration should be maintained even when the tab has no messages in it. Popping the search to the center is really odd.
![2020-09-01_12-04-27 (2)](https://user-images.githubusercontent.com/5234389/91877395-ef513380-ec4b-11ea-96b2-dbfff29e4c3f.gif)

**Comment by danielanewman** [comment]
Another related issue @leggett — beyond the shifting of the search bar and oddness in adding/removing background color, when you're in an inbox tab with no messages, the load new messages button isn't available, either.
![2020-09-11_10-46-17](https://user-images.githubusercontent.com/5234389/92940717-7016e900-f41d-11ea-9805-add67577a718.png)

**Comment by leggett** [comment]
It is there (on hover left of the search box) but agree this isn't good and needs to change.

**Comment by danielanewman** [comment]
Oh! They're invisible until you hover on them...? I would have never known.

**Comment by danielanewman** [comment]
@leggett the reload messages button also isn't visible when you have a message selected with the reading pane open.

**Comment by leggett** [comment]
Correct -- that is actually how Gmail works with the reading pane (e.g. you will have the same issue with Simplify disabled). I have it on my list to try and make the refresh button always available in reading pane.

Two work arounds:

- Clicking on Inbox in the nav should also refresh your inbox
- You can use the `u` keyboard shortcut to go Up or Unselect the current message in reading pane so you can click on the refresh button

**Comment by leggett** [comment]
And as for the buttons being invisible... they are only invisible in Inbox Zero. It is a hot mess in reading pane (as I revert to the styles for non-reading pane right now which is why the search box moves). 

It makes more sense in the non-reading pane view because they don't move... they just fade out. But even there it probably is too aggressive as it is natural to want to refresh when you don't have any mail.

**Comment by danielanewman** [comment]
Thanks. Relatedly... as a user of the reading pane, I'd prefer if message selection was automatic—so when I land on an inbox tab, the message at the top was auto-selected. Realize that once again, this is fighting the nature of how Gmail's reading pane works, but figured I'd mention it.

**Comment by leggett** [comment]
@danielanewman I'm pretty hesitant to do that as it would also mark the first message read (after a short delay). You can just hit enter to open the first message after it loads (if you have keyboard shortcuts turned on).

**Comment by leggett** [comment]
Fix coming in v2.1.11
