### ISSUE TITLE
Hitting the left arrow while using keyboard controls pops focus into the menu even if the menu is hidden

### ISSUE THREAD

**Issue by danielanewman** [leggett/simplify#338]
![2020-09-01_12-11-37 (2)](https://user-images.githubusercontent.com/5234389/91878486-5de2c100-ec4d-11ea-8056-1a86269e91e2.gif)

**Comment by leggett** [comment]
Hmm... I'm not sure if I can prevent this. The compose button is technically in the nav so I can't actually hide the nav... instead I set it to be width:0. I'll look at it some more and see if I can address this.

**Comment by leggett** [comment]
Didn't find a good way to prevent this.
