### ISSUE TITLE
Content preview and attachments not showing in new window

### ISSUE THREAD

**Issue by Medicfoos** [leggett/simplify#339]
When I opened up my email account, the preview for the content of the email and attachments are not there. I opened my gmail account in a new tab and it was fixed. 

![image](https://user-images.githubusercontent.com/70595736/91881061-eca40d80-ec4e-11ea-91b1-009d37fde339.png)

**Comment by leggett** [comment]
Thanks. This is an odd bug I thought I fixed where the reading pane thinks it is wider than it is and doesn't wrap the content to multiple lines. If it happens again, any details on what happened would be appreciated. It might be I need to do an extra check on initial install.

**Comment by leggett** [comment]
Got a fix for this coming in v2.1.11
