### ISSUE TITLE
Nav should have a white background in Inbox Zero state

### ISSUE THREAD

**Issue by ymolodtsov** [leggett/simplify#340]
When you open the nav permanently in the inbox zero state the items don't look too good on the background. Even on the current default image that is close to white. I imagine it'd look worse on other, less specifically selected images.

<img width="418" alt="Screen Shot 2020-09-01 at 20 53 58" src="https://user-images.githubusercontent.com/2446078/91888798-8db5b700-ec95-11ea-90de-3874762f86ff.png">

The solution, in my opinion, would be to always have the nav on the white background if the user decided to toggle it at all.

**Comment by leggett** [comment]
Thanks for the feedback. I'm not going to put the nav on a white background... BUT there will be options on what the zero-inbox image is (including no image).
