### ISSUE TITLE
dark mode + inbox zero does this thing idk

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#341]
![image](https://user-images.githubusercontent.com/21956756/91891885-0ca8f080-ec92-11ea-9f7a-6939f5fe8f08.png)

**Comment by KraXen72** [comment]
v2

**Comment by leggett** [comment]
Good catch... I must have forgotten to correct the inbox zero treatment for tabs + reading pane + dark theme + inbox zero.

**Comment by leggett** [comment]
Fixed coming in v2.1.11
