### ISSUE TITLE
disable darkmode text inverting does not work

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#342]
the disable option acts like invert all emails
![image](https://user-images.githubusercontent.com/21956756/91892084-55f94000-ec92-11ea-9444-3b6c37207954.png)
![image](https://user-images.githubusercontent.com/21956756/91892175-7de8a380-ec92-11ea-8699-29bdb946de25.png)

**Comment by KraXen72** [comment]
sorry i don't know how to add v2 label

**Comment by leggett** [comment]
Found the bug. A fix will go out in the next update.

**Comment by leggett** [comment]
Workin in all views except reading pane it appears. There are some lingering issues with the setting not updating in reading pane... need a little more digging.

**Comment by leggett** [comment]
This appears to be working reliably now. Not sure if I fixed it in a previous version or in v2.1.12.
