### ISSUE TITLE
[v2] [suggestion] move this here for better imersion

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#344]
![image](https://user-images.githubusercontent.com/21956756/91893925-2ac42000-ec95-11ea-92d0-323d4b48a939.png)

**Comment by leggett** [comment]
Tabs need to stay there... the search box shouldn't have moved.

**Comment by leggett** [comment]
(There is a separate bug somewhere tracking the search box not moving in inbox zero for vert reading pane)
