### ISSUE TITLE
Date groupings out of order in v2

### ISSUE THREAD

**Issue by LWGO** [leggett/simplify#345]
Not sure if this is intended, but the Date groupings seem out of order for me (Today > July > Yesterday > Last Month):
![image](https://user-images.githubusercontent.com/5504616/91883913-fec78100-ec39-11ea-92fa-ba77da4ba524.png)

Also, one of the "July" emails had a reply as recently as today, so I would expect it bucketed in Today instead.

**Comment by leggett** [comment]
Are any of them snoozed emails?

**Comment by LWGO** [comment]
Yes, the bottom two "July" emails were snoozed. 

The top one was snoozed for a later date, but most recent reply brought it back to my inbox this morning.

**Comment by leggett** [comment]
Have a fix for this that will go in the next update. Needed to process the list backwards.
