### ISSUE TITLE
emoji button no longer visible when composing/replying to e-mail (v2)

### ISSUE THREAD

**Issue by TransBat** [leggett/simplify#346]
The emoji button no longer appears down at the bottom of the formatting options in an e-mail.  In v1 and standard Gmail, the emoji icon sat along the bottom row of icons adjacent to the formatting options toggle, the insert attachment, insert link, insert image option.

Gmail:
![image](https://user-images.githubusercontent.com/70607246/91906098-9eeecb80-ec75-11ea-9af0-a68abc3265b7.png)

Simplify v1:
![image](https://user-images.githubusercontent.com/70607246/91906174-c0e84e00-ec75-11ea-96a7-75f687154051.png)

This is certainly NOT a pressing/extension breaking issue, just something I noticed was missing in the compose options.  My apologies if this was already reported and I missed it.

**Comment by Kw-git** [comment]
Along the same lines, it appears there just might be TWO "Insert Photo" icons.
![Simplify V2 beta 2020-10-07 17_55_54-Inbox (2,758) - dockwpk@gmail com - Gmail](https://user-images.githubusercontent.com/32313784/95394325-3c1ece80-08ca-11eb-9b1d-4eb47281fca2.png)

**Comment by leggett** [comment]
Yeah... Gmail puts that second one back in the menu automatically. I can't figure out why or how to prevent it. ¯\_(ツ)_/¯ 

I'll address this and other things around compose in the next update.

**Comment by CarlosRebolledo** [comment]
I had not realized that the Emoji did not appear. That accounts for how little and nothing that I use it.

Is it worth having emoji?

I think so, although it would be better to have keyboard shortcuts for simple answers and short answers, something we do with TextExpander

**Comment by leggett** [comment]
Big changes to compose settings in the works with a new default setup that makes sure any hidden actions are in the overflow menu (not the case right now for emojis).
![Settings](https://user-images.githubusercontent.com/8763662/96029466-96121d80-0e0f-11eb-81b5-15af24e0acc2.png)

**Comment by Kw-git** [comment]
Thank you very much, Michael - that looks terrific - I'm looking forward trying this! :-)

**Comment by CarlosRebolledo** [comment]
Looks great !!! Applause and the bottle of wine (Chilean by the way) is
waiting for the launch to toast your great work.


*Carlos Rebolledo Aguirre*
*Abogado*

Inversiones en Línea Limitada


*F: *+56712212721 | *M: *+56983419924 | *E:* carebolledo@inverline.cl
*A: *1 Norte 880, oficinas 7 y 8, Talca

**Comment by leggett** [comment]
Full revamp of compose settings is set to launch shortly. Settings isn't quite as fancy looking as the above mock (yet) but is functional. And all the compose actions I hide, I make it easier to get to them.

![gmail_compose](https://user-images.githubusercontent.com/8763662/99757654-b84d2a00-2aa4-11eb-8202-71010567dff8.gif)
