### ISSUE TITLE
UI Bug: Message count overlaps open addon sidebar

### ISSUE THREAD

**Issue by stevebertan** [leggett/simplify#347]
![Screen Shot 2020-09-01 at 2 28 24 PM](https://user-images.githubusercontent.com/12550061/91908243-19145580-ec60-11ea-9a9f-b17870207d0d.png)

**Comment by leggett** [comment]
Safe to assume your window is very narrow here? And you're not using reading pane, right?

**Comment by stevebertan** [comment]
The window is sufficiently wide but I did notice it only happens when the reading pane is split "Right of inbox." Not an issue when "Below Inbox" is set. 

Here is a larger image:

![Screen Shot 2020-09-01 at 3 49 07 PM](https://user-images.githubusercontent.com/12550061/91913887-9d200a80-ec6b-11ea-8879-8bfb53c23bc7.png)

**Comment by leggett** [comment]
Super helpful. It is the reading pane that is narrow. I'll figure out something.

**Comment by leggett** [comment]
Fix coming in v2.1.12
