### ISSUE TITLE
Alt+M keyboard shortcut not work in Compose Reply

### ISSUE THREAD

**Issue by Periphas** [leggett/simplify#348]
Keyboard shortcut to "Toggle Gmail navigation menu open/closed" does not work when replying to an email in Compose using the Coversation view.

**Comment by leggett** [comment]
Sadly, I don't think I can do anything about this one. The composer eats all keyboard shortcuts preventing Simplify from knowing about them. Perhaps there is a work around I haven't figured out yet... I'll look.

**Comment by leggett** [comment]
Nope. Composer eats all keypresses. I can't detect / listen for them.
