### ISSUE TITLE
Shifting of reading pane when navigating from message view back to Inbox

### ISSUE THREAD

**Issue by group7access** [leggett/simplify#349]
Conditions:
- Windows 10.
- Latest stable Chrome browser.
- 23.5" monitor at 1920 x 1080 resolution.
- Side menu pinned open.

Steps to reproduce:

- Open an email.
- Click the back < arrow to go back to inbox.

The shifting of the message list is very distracting.

Here it is in action:
![message-back-to-inbox-jumpy](https://user-images.githubusercontent.com/70614907/91921700-5d681b80-ec89-11ea-9790-ab93c7ba211b.gif)

**Comment by leggett** [comment]
This is intentional (meant for a more focused reading experience) but the shift is pretty jarring. I expect to remove it (letting the nav always stay open)... I might leave it as a setting.

**Comment by group7access** [comment]
I definitely get the reasoning for--and prefer--the hiding of the side menu. It's definitely the jarring that is... jarring. Perhaps the menu could still be present, but covered by a blank object that matches my background colour (if I was using a solid background...).
Keep up the awesome work, my friend!

**Comment by leggett** [comment]
This was addressed in v2.1.10 where I stoped hiding the nav but instead dim it and hide the unread counts. It reverts when you hover over the nav in message view or return to the list view.
