### ISSUE TITLE
Show search options button is fickle in v2

### ISSUE THREAD

**Issue by dougwaldron** [leggett/simplify#351]
When I have a message open and then open the search bar, the "show search options" button behaves differently depending on how I click on it.

* If I tap on my touchpad, it opens the search options panel, but the search bar goes away.
* If I click on the touchpad, the search bar disappears and then reappears. (No search option panel.)
* If I click real fast (faster than a casual click), the search bar just goes away.

![image](https://user-images.githubusercontent.com/737326/91926525-6ebf2100-eca5-11ea-8d9b-6b14af9186e0.png)

**Comment by dougwaldron** [comment]
Here's a screen recording of the three different clicks:

![Screen-Recording-2020-09-01-at-1](https://user-images.githubusercontent.com/737326/91927080-ad091000-eca6-11ea-8511-264c3b9dfe17.gif)

**Comment by leggett** [comment]
Thanks Doug. This is the same as #324 but your extra screen grabs help. It only happens when search is hidden (in the conversation or in the list when a message is selected). Hope to fix this soon.
