### ISSUE TITLE
'Esc' should deselect threads in the inbox

### ISSUE THREAD

**Issue by ymolodtsov** [leggett/simplify#352]
Simplify v2 did a lot of great tweaks to put the user in the flow but I believe there's one last missing step. As you go back and back by clicking 'Esc' I suggest it should eventually deselect all threads. It looks very reasonable and logical to me, and similar to the behavior found in a lot of native apps.

This is also exacerbated by the terrible default keyboard shortcut for deselection that Gmail has (press * then n), at least it could be changed, but how many people do that?

**Comment by leggett** [comment]
Interesting! I like it.

**Comment by leggett** [comment]
Finally adding this in v2.3.8
