### ISSUE TITLE
Folder menu has no transition in Edge

### ISSUE THREAD

**Issue by jstride** [leggett/simplify#353]
The left-hand folder menu instantly shows/hides when mousing over the 3 horizontal bars and is jarring compared to the transition when mousing over the profile pic to show help/settings/cal/keep/etc.

**Comment by leggett** [comment]
This is intentional (for technical reasons) and like this in all browsers but I'm going to see if I can do something about it.

**Comment by leggett** [comment]
Finally looked into this. Bad things happen if I try and animate the transition. So it will remain an instant transition.
