### ISSUE TITLE
Inconsistent message/buttons shift when opening new message pop-up

### ISSUE THREAD

**Issue by dougwaldron** [leggett/simplify#354]
While viewing a message, opening the new message pop-up causes the message and toolbar buttons to shift, but the direction of shift is inconsistent.

In a wide window, the buttons and message shift to the left. (I assume this is the desired behavior since it keeps the message more visible.) In a narrow window, though, the button & message shift to the right. In a medium-width window, the message shifts left and the buttons shift right.

**Comment by leggett** [comment]
You're right (of course). I'm using different minimums of left-margin for when a compose mole is open and when it isn't which is making things jump in unexpected ways. Good eye.

**Comment by leggett** [comment]
Have a fix for this in the next release.
