### ISSUE TITLE
The Simpilify Shuffle

### ISSUE THREAD

**Issue by scottjenson** [leggett/simplify#355]
Moving from Inbox to MessageView and back creates an odd 'shuffle that is very distracting.
![SimplifyShuffle](https://user-images.githubusercontent.com/1055674/92000084-f7fc4500-ecf1-11ea-9bfa-9ae131b1e284.gif)

**Comment by leggett** [comment]
This was changed in the last update. I'm no longer hiding the nav on opening a conversation... I'm dimming it and hiding the unread counts instead.
