### ISSUE TITLE
v2 - the searchbar is clearly not centered in inbox zero mode - 24.5" screen 1920*1080

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#356]
![image](https://user-images.githubusercontent.com/21956756/92003201-07ef4580-ed41-11ea-8fb0-23b5f9e57a86.png)
the dropdown is.

**Comment by KraXen72** [comment]
* when side menu is expanded

**Comment by moikirsch** [comment]
It is centered to the content section... I'm not sure if that is the intended behavior.

**Comment by leggett** [comment]
This is partly an artifact of the search box jumping for vertical split reading pane + inbox zero. Generally, yes, the search box and the advanced search drop down are meant to be centered on the content, not the whole page. 

A related issue is when the window is small enough that the search box shrinks. But it still grows when focused. Opening advanced search options de-focuses the search box (so it shrinks) but the advanced search align with where it was. Blah blah blah... I need to fine tune all this some more.

**Comment by leggett** [comment]
Fix coming in v2.1.12. You use vertical split pane and the search box now stays above the list (even in inbox zero). So for you, the advanced search options will be to the far left under the search box.
