### ISSUE TITLE
Return "Attach from Google Drive" to default available actions

### ISSUE THREAD

**Issue by Kw-git** [leggett/simplify#358]
SImplify V2 Beta moved the "Insert files from Drive" option behind the "three button" menu; I use this far more often than the traditional "Attach" (paper clip) action. 

Would it be worth while to return this particular icon to its usual location?
![simplify v2 action bar](https://user-images.githubusercontent.com/32313784/92005254-440ab200-ed11-11ea-9839-1a377f19dc45.png)

**Comment by leggett** [comment]
Yes. This is an area where I was more aggressive with the beta to see what happens. Someone else asked where the emoji button went. I'd hate for Simplify to be a bad offering just because I take a hard line on things like this.

I'd like it to still be hidden by default BUT only if I can make it super obvious how to have it shown for you. I don't want to depend on people digging through Simplify's settings to figure that out... stay tuned.

**Comment by Kw-git** [comment]
That makes sense :-)

In my pwn experience, from building Web sites, a few years ago, I would have offered a configuration option to allow folks to select the items they want shown; for me, that would be "Insert files from Drive" and "Emojis". I use those more than anything else. But, doing this sort of stuff (configuration options) for a while, we ended up with a very flexible interface, which had so many options, it was a bear to configure -- the configurability became overwhelming to the point of becoming useless.

These days I would EXPLORE moving buttons based on prior actions: if somebody uses a particular button a few times, perhaps it should just slide over to be shown by default. Perhaps limit the number of items shown there by a setting???? That could cross the threshold into "nifty but not for the average user who just wants things to work"....  I don't know....  I really don't have much hands on experience with this sort of dynamics... that's why I said "EXPLORE," above....

**Comment by leggett** [comment]
This is coming back in the next update (should go out tomorrow), v2.1.14. 

You can now fully customize which icons appear there and which don't. All the hidden ones are behind a simple expander:

![gmail_compose](https://user-images.githubusercontent.com/8763662/99757755-e468ab00-2aa4-11eb-929b-13c17e56c87e.gif)
