### ISSUE TITLE
Chat button visible but doesn't do anything [V2]

### ISSUE THREAD

**Issue by Henboy10** [leggett/simplify#359]
I don't want chat, but I still have a spot for it.
![image](https://user-images.githubusercontent.com/22181579/92011778-2ccbc480-ed11-11ea-99be-e79d8ff1afc7.png)

**Comment by ScottESanDiego** [comment]
FYI, I see the same thing with Hangouts.  I have Meet and Hangouts disabled in the GMail settings, and the the Hangouts "double quote" placeholder, similar to what is in the screenshot above.  The bug isn't Meet specific.

**Comment by leggett** [comment]
I was never able to reproduce it being super wide like that but I now hide chat when it is disabled (coming in v2.1.11)
