### ISSUE TITLE
Safari Version

### ISSUE THREAD

**Issue by manuelrego27** [leggett/simplify#36]
Because Mac users also deserve the simple gmail love 🙏

**Comment by leggett** [comment]
You can use Chrome on Mac too 😛 

Seriously though, it is on the list along with Firefox once I get things settled down for Chrome.

**Comment by manuelrego27** [comment]
And I do! But I still use Safari on Mac for non-work stuff (its more power efficient), hence the need :p 

Thanks for the quick reply :D

**Comment by leggett** [comment]
Guidelines: https://developer.apple.com/safari/extensions/

**Comment by eemi** [comment]
Hey! As a quick hack I used Safari's ["Extension Builder"](https://developer.apple.com/library/archive/documentation/Tools/Conceptual/SafariExtensionGuide/UsingExtensionBuilder/UsingExtensionBuilder.html) with Michael's js/css. I'd love to use an "official" extension, but for the moment it working just fine.

**Comment by kurko** [comment]
FYI, I created a custom extension from @eemi's link in under 3 minutes and it's working. Fairly simple.

<img width="775" alt="Screen Shot 2019-04-29 at 09 21 27" src="https://user-images.githubusercontent.com/70312/56895723-48112a80-6a60-11e9-9d08-30ef929f06a3.png">

Given the simplicity, @leggett, I'd suggest you launch an official version. It'd have a greater reach (I use Safari for everything except development).

**Comment by lukasvermeer** [comment]
I tried the same using @eemi's link, but it doesn't quite work for me. Seems the css is not applied with same importance as in Chrome, so some elements end up not being styled.

<img width="229" alt="Screenshot 2019-05-01 at 08 36 13" src="https://user-images.githubusercontent.com/552432/57007910-6441d280-6bec-11e9-9958-9920dcae2e2b.png">

JS Console also complains about "chrome" not being defined, but removing the offending lines does not resolve the style issues.

Adding !important to some of the css seems to work.

**Comment by kurko** [comment]
@lukasvermeer FYI, I only imported the `script.js` JS file, not `pageActionHandler.js`. The latter has mentions to `chrome` so I decided to not include it. Have you included it?

**Comment by lukasvermeer** [comment]
@kurko Thanks for the suggestion! I did try both with and without `pageActionHandler.js` and got the same result both times.

There [are also two instances](https://github.com/leggett/simplify/blame/master/gmail/script.js#L35) of `chrome` in `script.js`, but perhaps these were added after you tested it?

**Comment by leggett** [comment]
Ok... I paid the ridiculous $99/yr fee to get a dev cert so I can distribute Simplify to Safari users. It says it can take a couple days to process.

**Comment by manuelrego27** [comment]
🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by kurko** [comment]
@leggett amazing! Maybe we could try the sponsorship thing where we can donate some 💰

**Comment by bflack** [comment]
*refreshes Safari extensions gallery incessantly*

**Comment by leggett** [comment]
I'll update here when I push it out... my wife was out of town all weekend and I had the kids. So I didn't get very far on packaging it and testing.

**Comment by leggett** [comment]
Made progress. Not done. Safari is a major pain in the ass. 

- I'm having to add a TON more "!important" flags after css lines :(
- My understanding is Safari Extensions now [require a macOS app](https://developer.apple.com/documentation/safariservices/safari_app_extensions) built in Swift... so dumb. I sort of got that working but it seems really buggy. The best tutorial I could find was [this one](https://ulyngs.github.io/blog/posts/2018-11-02-how-to-build-safari-app-extensions/). If anyone has a better one, please send along. 
- Just using the Safari Extension Builder for now to find and fix all the Safari-related issues. 
- WTF Safari, why don't you let me tell you to only add the script to the top frame and not all frames?!?
- Detecting Add ons tray opening/closing isn't working
- I haven't tested a ton of scenarios
- And when it is all done, I'll have to go back and make sure I didn't break Chrome and Firefox to support Safari. Le sigh.
- Code is here if you want to download and load locally to test: https://github.com/leggett/simplify/tree/master/safari

**Comment by mortenjust** [comment]
I rolled a sample project if you need some pointers. https://github.com/mortenjust/simplify-gmail-safari/. There's a developer signed binary in `releases`

**Comment by bcomnes** [comment]
Works great @mortenjust !

**Comment by microust** [comment]
Salute!
Any progress in your work? 
I love Safari but cant look at Gmail. 

Occasionally I use Firefox (with Simplify) but prefer the way how Safari is integrated with system.Thats is why I ask. ;-)

**Comment by leggett** [comment]
Sadly, no update. But still on my list. 

Good-ish news: I recently left my full time job and am spending my work hours on Simplify (only half days b/c of child care and COVID-19). 

After clearing out the backlist of bugs last week, I've started working on v2 which is a total re-write (improving performance and reliability) + new functionality (to be announced) + support for Safari and more. 

My personal goal is to launch v2 by July 4th. Safari support will probably be the last thing I do as I'm hoping Apple announces improvements to how one builds and launches browser extensions for Safari at WWDC this year.

**Comment by microust** [comment]
Thanks for response. I understand how dev for Safari looks. But again I appreciate what you are doing.

ps. take care in this crazy times.

**Comment by manuelrego27** [comment]
Thank you! 🙌

**Comment by niccolomineo** [comment]
Looking forward to this thread getting updated with the greatest news for us Safari users. 🙌

**Comment by niccolomineo** [comment]
Looking forward to this thread getting updated next month with the greatest news for us Safari users. 🙌

**Comment by earllee** [comment]
Thank you @leggett for your hard work on this! Recently switched over from Chrome to Safari and missing Simplify has been the hardest part.

**Comment by daniocean** [comment]
It seems with the new extension standard, it should be easier to build extensions for all browsers

**Comment by leggett** [comment]
Yes, very much so. I watched some of the dev videos yesterday and it looks very promising. You still have to wrap the extension in a macOS app but they will release a tool to do that for you.

Hope to get a beta installed soon and explore more.

**Comment by niccolomineo** [comment]
Any news? :)

**Comment by leggett** [comment]
Well I missed my July 4th launch target :/

Other than that, things are coming along nicely. I'm going to start posting soon about the details of Simplify v2 at [on.simpl.fyi](https://on.simpl.fyi).

Safari 14 / macOS 11 should make supporting Safari much easier. But I don't think I want to wait that long so my plan is to finish Simplify v2 and launch support for Safari at the same time on Safari 13. My new goal is to do that by Labor Day... I have hope it will be out sooner.

**A rough outline of what I've done so far (probably more than you were hoping for)**

1. Read some books on modern Javascript and HTML5 programming so I'm not just hacking it together based on my mostly outdated knowledge.
2. Rebuilt the extension from scratch and improved reliability, performance, ease of maintenance, and more. For instance, you used to have to reload Gmail for Simplify to detect things like a theme change or change to the Inbox setup. Those things are now detected live -- no refresh required.
3. Switched to using SASS instead of just writing straight CSS which makes it a lot easier to only write the CSS but also easier to apply detected changes to Gmail classnames across all the CSS (I just update the SASS variables).
4. Since SASS is largely meant to be run server side or locally before you deploy the CSS, I built a SASS compiler so I can re-compile the SASS into CSS with and apply any updated variables on the fly. I did this after abandoning [Less.js](http://lesscss.org/) (not robust enough) and [Sass.js](https://github.com/medialize/sass.js) (too bloated IMO). I'll open source this separately.
5. I redesigned a lot of things (especially the reading pane setup, search, and the app/action bar).
6. And I've adding a lot of things on my v2 wish list (inbox zero state, detecting and blocking email trackers, group emails by date -- good enough now to have on by default, move the conversation over when compose is open, show the nav on hover over the menu button, added new keyboard shortcuts to make getting around a breeze, and more).

The things left on my list before I think v2 is good enough are:

- Some more tweaks to how search works / looks (what I'm working on now)
- True dark theme (invert simple messages and maybe HTML messages too)
- Some more tweaks to compose
- Move chat out of the left nav into it's own menu (similar to add-ons)
- Cmd+K menu (like Superhuman's) that lets you do almost anything / go anywhere via a single auto-complete menu.
- Support Safari
- Testing, testing, testing. And then more testing
- Monetization (I might punt on this for the initial launch and just tell people it is coming)

I've got a start on a lot of these remaining tasks. Ideally I finish these tasks by the end of July giving me August to do testing and make sure everything is rock solid before it launches.

**Comment by microust** [comment]
Good news. So we get more than expect. Can't wait for it.

**Comment by benoitgrelard** [comment]
That sounds excellent @leggett! Thanks for all your hard work.

**Comment by hmarsili** [comment]
Thank you! regular gmail makes my eyes bleed :p

**Comment by sebask** [comment]
@leggett Would love to help you test the beta.

**Comment by leggett** [comment]
@sebask I'm only testing on Chromium based browsers initially. If that's your main browser, email me at hi@simpl.fyi.

**Comment by gabrielizaias** [comment]
I believe this is good news:

> Safari Web Extensions can add custom functionality to Safari 14 beta using the same WebExtensions API used in other browsers, such as Chrome, Firefox, and Edge.
> — https://developer.apple.com/news/?id=kuswih5l

**Comment by leggett** [comment]
Yes -- publishing Simplify for Safari 14 should be easy. BUT, I've still got questions...

1. Safari 14 requires macOS 11 as I understand it. Will macOS 11 be a smart upgrade right out of the gate? I've fallen into a routine where I wait 6-12 months before upgrading to the latest version of macOS as Apple has gotten worse about launching without bugs. 

2. Will an extension published in this new way work on Safari 13? I don't think it will.

3. So should I still work out how to publish for Safari 13? When most people are on Safari 14, can I update the extension published for Safari 13 to be a Web Extension? Or will I have to publish a new extension to make that switch?

I plan to dig into all this soon. I'm trying to fix a few remaining bugs in Simplify v2 so I can launch a beta for Chrome first. 

Here is the top of my backlog:
<img width="635" alt="Screen Shot 2020-08-28 at 7 47 38 AM" src="https://user-images.githubusercontent.com/8763662/91581044-cd317b80-e902-11ea-9a35-ef3955f689f2.png">

**Comment by leggett** [comment]
GREAT NEWS EVERYONE!!!

"Safari web extensions are available in macOS 11 and later, and **in macOS 10.14.6 or 10.15.6 with Safari 14 installed**." So macOS 11 is not required. Installing the Safari 14 beta right now. Excited to get this out to y'all.

**Comment by microust** [comment]
This is really fantastic news!

**Comment by manuelrego27** [comment]
amazing thank you!

**Comment by benoitgrelard** [comment]
Ohhhh this is so good!

**Comment by microust** [comment]
> GREAT NEWS EVERYONE!!!
> 
> "Safari web extensions are available in macOS 11 and later, and **in macOS 10.14.6 or 10.15.6 with Safari 14 installed**." So macOS 11 is not required. Installing the Safari 14 beta right now. Excited to get this out to y'all.

So, any progress with Safari version? ;-)

**Comment by leggett** [comment]
I launched the beta in early September and have been fixing / improving things since. I'm almost done with that after which I will work on the v2 launch plans which will include Safari.

**Comment by microust** [comment]
Im really glad to hear that. 👍

**Comment by ymolodtsov** [comment]
Any updates on the Safari version?
Wanted to try Safari after Big Sur but there's no way I can live without SimplifyGmail.

**Comment by fareastenders** [comment]
Like many I've just moved over to Big Sur and decided to go with Safari and discovered Simplify isn't on Safari yet! 😱

**Comment by leggett** [comment]
I pushed 6 weeks of updates and fixes to trusted testers today and have started working on Safari support now (including if I can test it with some of you that have been waiting so patiently). I will post updates here. Stay tuned!

**Comment by itsJurij** [comment]
How I can join trusted testers team/ 👍

**Comment by bmiselis** [comment]
🤚🏼

**Comment by blondie0604** [comment]
Following! I have never been so happy to find information on the internet.

**Comment by leggett** [comment]
**Update:**

I'm getting close. 
- I've fixed a number of bugs that were Safari specific and am down to some issues around Simplify options (default options aren't applied + changing options is requiring a refresh). 
- I've also made a lot of progress on ramping up on the ins and outs of publishing an extension for Safari and how to setup my code base in general so I can make changes and see them in Safari (it is not nearly as straightforward as it is with all other browsers). 

And I've decided I'm going to silently launch Simplify Gmail v2 on Safari first. 
- There might be a way to limit the release via Testflight but I'm not sure I have the desire to figure that out.
- So I'm just going to launch it. It will be free for now and I will only announce its launch here. 
- My ask is that you **keep it private for now** (e.g., don't tell others) and instead help me test it for a couple weeks to make sure I caught all the bugs. In that time, I'm going to prepare for a launch of v2 across all browsers (along with any bugs y'all find). My target for that launch is Jan 11th. 

Thumbs up if that sounds good.

**Comment by microust** [comment]
Sounds very good. ;-)

**Comment by CarlosRebolledo** [comment]
It sounds great, although I will have to wait for it to get to Chrome because I use Windows

Happiness and joy for this Christmas and the year 2021

**Comment by flightresponse** [comment]
👍👍👍👍👍👍👍‼️

**Comment by leggett** [comment]
@CarlosRebolledo you're on the beta, right? You should already have v2.

**Comment by CarlosRebolledo** [comment]
Yes, I have the Simplify Gmail v2 Beta version
2.1.15.

I thought you were releasing version 2.1.16 or the final Beta v2.

My apologies

**Comment by leggett** [comment]
I'll update the beta to v2.1.16 when I ship Safari

**Comment by benoitgrelard** [comment]
That sounds awesome! Can't wait to try it!

**Comment by leggett** [comment]
**Bad news:** I'm 99% sure that the bug with Simplify Options is a bug in Safari's implementation of browser.storage.local where changes to local storage are not triggering the listener function attached via browser.storage.local.onChanged().

**Good news:** This bug doesn't break Simplify on Safari and I'm not going to wait for a fix to launch on Safari. It just means you have to reload Gmail after changing any Simplify Options and that the default options aren't loaded. I'm looking into work arounds on this 2nd bit as it is kind of annoying. At the very least, a message that pops up on install saying you should setup your options.

**Comment by leggett** [comment]
Trying to publish Simplify Gmail for Safari for you all and all I can say is Apple makes this SO f-ing hard. Anyone have any idea what these errors mean or what I can do to fix them? I've searched the dev forums and internet at large and found nothing helpful.

<img width="692" alt="Screen Shot 2020-12-29 at 2 00 00 PM" src="https://user-images.githubusercontent.com/8763662/103318028-ec8c0280-49e1-11eb-8758-1fae2b4c8a1c.png">

**Comment by leggett** [comment]
Breakthrough. Hit a few walls figuring out how to get all the certificates I need, package the extension correctly, and submit it to the App Store for review. But it is done!

I will post here if/when approved.
<img width="1479" alt="Screen Shot 2020-12-29 at 6 53 56 PM" src="https://user-images.githubusercontent.com/8763662/103326936-671b4900-4a07-11eb-80e8-5f1960b66fcc.png">

**Comment by microust** [comment]
This is fantastic news! Cant wait for it.

**Comment by CarlosRebolledo** [comment]
Felicitaciones @leggett 👍👍💪💪

**Comment by leggett** [comment]
It is live! Please test it out and report any bugs you find on [issues.simpl.fyi](https://issues.simpl.fyi). 

https://apps.apple.com/app/id1544668450

**Comment by leggett** [comment]
One thing to note: upon giving access the first time, you have to reload Gmail. Not sure why.

**Comment by leggett** [comment]
Oh, and please **DO NOT SHARE** that this is live. This the first place v2 is live outside of trusted testers and there are a few more things I want to change to get ready for a public launch.

**Comment by enwin** [comment]
I just installed it. So many options! So far no issue. Thanks for all the work!

**Comment by flightresponse** [comment]
Omg it's just so, so, *so* much better! This is a huge relief to my
eyeballs. Thank you so much for all your hard work in getting this made!

**Comment by jmarquis** [comment]
Wow, incredible work! So happy to finally have Simplify in Safari as well as Chrome.

@leggett Do you have any kind of donation thing set up for this project? I'd love to be able to say thanks for something I'll be using every single day going forward.

**Comment by leggett** [comment]
@jmarquis Thanks! No need as I'm going to start charging for Simplify in 2021. 

I've written some about this shift at https://simplify.substack.com/p/the-future-of-simplify and I will write more in the next week or so detailing the exact pricing / business model. I hope it is worth paying for.

**Comment by CarlosRebolledo** [comment]
@leggett confianza!!! El 2021 será un gran año y apenas salga la versión de pago ahí estaré.

Muchas gracias por tú trabajo y visión

**Comment by jmarquis** [comment]
Nice! I just read the whole post and I'm really intrigued by the idea of building a business around improving existing products. I'll be following (and subscribing 😄) to see what you accomplish in 2021 — thanks for sharing!

**Comment by manuelrego27** [comment]
omg, thank you so much for your work @leggett 🙇‍♂️🙏
