### ISSUE TITLE
Detect Right-side chat enabled but chat disabled

### ISSUE THREAD

**Issue by Henboy10** [leggett/simplify#360]
It makes it so the message isn't actually centered and feels weird
![image](https://user-images.githubusercontent.com/22181579/92012004-7caa8b80-ed11-11ea-8e9e-873420483ec0.png)

**Comment by leggett** [comment]
Simplify thinks either quick settings or add-ons are open. If you refresh the page, it should correct itself... if you can reproduce the issue, I would love any information you can provide so I can figure out why it glitches and fix it.

**Comment by Henboy10** [comment]
I seem to have fixed the problem. The chat was set to be on the right side in settings, so after disabling that it looks fine

**Comment by leggett** [comment]
Got it... but then chat should show up there, no? Or maybe you had it set to be on the right AND disabled?

**Comment by Henboy10** [comment]
Now the chat button looks normal and seems to function as intended, although I never use it ;)

Yeah I just had to change that setting to move the chat from the right side to the default location

**Comment by leggett** [comment]
I have a fix for this coming in v2.1.11
