### ISSUE TITLE
Grey "selected" bar in v2 looks a little weird

### ISSUE THREAD

**Issue by alecbz** [leggett/simplify#363]
<img width="1240" alt="Inbox__1__-_alec_level_com_-_Level_Mail" src="https://user-images.githubusercontent.com/92369/92033140-2e10e780-ed39-11ea-8f6a-0e5b16f2415d.png">

Might be a matter of taste/perspective, but the grey bar looks a bit weird to me. I feel like it conveys the feeling of something being "receded" or un-emphasized/greyed out, more than it indicates "current selection".

A different color might help? Or some other visual indicator of "this is selected"? An arrow type thing?

**Comment by leggett** [comment]
It is the keyboard focus. 

And this is a dup of #318 -- it looks like you don't have v2.1.9 yet which toned this down until you use up/down. Curious how you feel about that change.
