### ISSUE TITLE
Search bar animation is lopsided

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#365]
Very minor issue.

When search bar appears the right-hand side animates in from the right. But the left-hand side just appears in-place (no animation). This looks lopsided to me (see attached screen capture).

[SearchBarAnim.mov.zip](https://github.com/leggett/simplify/files/5164882/SearchBarAnim.mov.zip)

**Comment by leggett** [comment]
Yeah... I can make it animate symmetrically by stretching the search box in both directions when hidden behind the actions... or I may do something entirely different when search is hidden.

**Comment by ScottESanDiego** [comment]
I cannot unsee this now....darn you @nhojb for bringing it into my brain. :-)

**Comment by leggett** [comment]
Hahaha... love the attention to details. Hope to get rid of this in the next version when I change how I minimize search. It will result in a smaller click target (a button instead of a big but hidden search box) but it will be more visible / obvious.

**Comment by leggett** [comment]
This is fixed in v2.1.12 as I no longer stretch the search box behind the action bar.
