### ISSUE TITLE
search field overlays action buttons

### ISSUE THREAD

**Issue by andymand** [leggett/simplify#366]
![screenshot-mail google com-2020 09 03-00_05_46](https://user-images.githubusercontent.com/51393001/92070261-89fb6080-ed79-11ea-87a5-c16108b4ddf4.png)

A refresh of the page fixed it, but then the search field became invisible (until I hover over it and then I see the magnifying glass, but not the field; a click in that area surfaces the search field (center-justified)):

![screenshot-mail google com-2020 09 03-00_08_52](https://user-images.githubusercontent.com/51393001/92070351-bca55900-ed79-11ea-96b0-3356083297ca.png)

(I've tried the above with and without Bitmoji extension enabled, as that extension was giving me some action buttons left-justifying issues with Simplify v1, but doesn't seem to be involved with this.)

**Comment by leggett** [comment]
Interesting... It doesn't look like you have a message selected (the select all check box is not mixed state) but it does (blue background on the first item).

Was there something selected?

**Comment by leggett** [comment]
P.S. the search box is supposed to be hidden when the actions are shown. But I'm starting to think the invisible search button is too invisible.

**Comment by andymand** [comment]
> It doesn't look like you have a message selected (the select all check box is not mixed state) but it does (blue background on the first item).
> 
> Was there something selected?

I'd clicked on the message (header? summary?) and was looking at the message in the same way that I was looking at this one:

![screenshot-mail google com-2020 09 03-00_27_12](https://user-images.githubusercontent.com/51393001/92071360-81f0f000-ed7c-11ea-8b36-05c4fa2e2bfd.png)

(Agree that I'd not touched the (header? summary?) checkbox or the select-all checkbox...)

>  I'm starting to think the invisible search button is too invisible.

I don't disagree with that assessment.  :)  (Took me some mouse-hunting to realize it was even up there.  :)

**Comment by andymand** [comment]
Super!

Also curious about the blank(?) oval in the lower left of that last screenshot.  Is that capsule supposed to display information that might be ad-blocked or something else?

**Comment by leggett** [comment]
No... it is the chat roster but I suspect you have chat disabled or are using the right-hand-side chat setting. It needs to be hidden in either case. There is a separate issue tracking it.

**Comment by andymand** [comment]
Ah, that makes sense, thanks.  Yes, I have chat disabled in Gmail.

**Comment by andymand** [comment]
Not sure if this is the same issue surfacing slightly differently or a new one, but I clicked on my _COUPONS label and noticed that the search field appears to be tangled up with the action buttons:

![screenshot-mail google com-2020 09 07-00_34_13](https://user-images.githubusercontent.com/51393001/92348774-0fe11980-f0a2-11ea-9970-d323e9ac07eb.png)

I performed a Hard Refresh (https://chrome.google.com/webstore/detail/hard-refresh/ichmdelihgokllcnibkcpciljnggojkj) and that seems to have fixed it (temporarily?).

When no messages are bulk selected, I see the search field (and no action buttons, which makes sense):

![screenshot-mail google com-2020 09 07-00_37_59](https://user-images.githubusercontent.com/51393001/92348901-7cf4af00-f0a2-11ea-8d4f-3d0fb964eb1c.png)

When messages are bulk selected, I see the action buttons (and no search field which might be an oversight since I might want to revise my search?):

![screenshot-mail google com-2020 09 07-00_38_17](https://user-images.githubusercontent.com/51393001/92348938-9ac21400-f0a2-11ea-9c08-0cf20a9ccc50.png)

**Comment by leggett** [comment]
Thanks for the report!

Some other things seem odd in your first screenshot... the scrollbar is super close to the content AND the pagination controls are further right. Did you have an add-on open at the time? Or maybe right-side chat or quick settings?

Also, the blue highlight suggests you are using a reading pane setup. Maybe horizontal reading pane?

**Comment by andymand** [comment]
I typically size my mail (and other) tab to occupy the left 2/3 of my 27" display and Hangouts window taking up the right 1/3), but I maximized it for this screenshot:

![screenshot-mail google com-2020 09 07-17_08_35](https://user-images.githubusercontent.com/51393001/92416769-18326680-f12d-11ea-9027-ad3441707572.png)

I see what you mean by the scrollbar (and now that you mention it, I do sometimes wonder why it's so hard to grab that widens-when-I-hover scrollbar handle!), but not sure what pagination controls you're referring to?

By "Did you have an add-on open?", I assume you mean Chrome extensions and apps?  If so, I have a couple dozen extensions and a dozen or so apps.  Not sure if I can test Simplify v2 without them, as some are "necessary" for my day-to-day (e.g., Auto Text Expander, Google Hangouts, Google Voice, Honey, KeepAwake, password vault, VPN, Zoom)...

> Maybe horizontal reading pane?

Yes (I think?) -- my Gmail settings says:

READING PANE
(o) Below inbox

**Comment by leggett** [comment]
Thanks for the extra context and screenshot @andymand. 

**My best guess is you have "Right-side chat" _enabled_** but Chat _disabled_. You can check under Gmail Settings > Advanced > Right-side chat: https://mail.google.com/mail/u/0/#settings/advanced

If that isn't the case, then I think something outside Simplify is causing an issue here or maybe it is something unique to your platform? 

**A few points:**

- The "pagination controls" are the next/previous message buttons in the top right. 
- "Add-ons" are the Gmail mini-apps you can open on the right side _inside_ Gmail (the default ones are Keep, Tasks, and Calendar). You can access them via hover over the profile photo > click on an add-on below the profile photo. 
- I'm **not** talking about other extensions (like Honey, KeepAwake, VPN, etc). Those should not alter Gmail in any way or interfere with Simplify. 

**Why do I think something is broken?**

There is a large area to the right of everything that is empty. The compose button should be in the bottom-right of the screen. The scrollbar for the message and list should be on the right edge of the screen. The actions should line up with the content. Everything looks wonky in your screenshot. Here is what my Gmail looks like with Simplify and Horizontal Reading Pane:

<img width="1574" alt="Screen Shot 2020-09-07 at 2 56 52 PM" src="https://user-images.githubusercontent.com/8763662/92418234-5161db00-f11b-11ea-8dc4-25f23b3275fa.png">

**Comment by andymand** [comment]
> My best guess is you have "Right-side chat" enabled but Chat disabled. You can check under Gmail Settings > Advanced > Right-side chat: https://mail.google.com/mail/u/0/#settings/advanced

Yep, that was the case.  I disabled Right-side chat and no longer see the search field tangled up with action buttons.  (To be fair, when I went back in an enabled right-side chat and reloaded the page, I can't go to a label and effect the tangle as I did above, so I'm guessing that it was solved in some other way, but thank you for taking the time to educate me about the right-side chat thing!  (I see where you mentioned it once or twice above and it didn't register that I should even look for something else since I had chat disabled -- exactly as you predicted.  Thanks again!)

**Comment by andymand** [comment]
Despite my having disabled this right-side chat stuff, I'm still seeing some left-shifting of the action buttons:

![screenshot-mail google com-2020 09 11-07_50_48](https://user-images.githubusercontent.com/51393001/92922414-d3941d00-f403-11ea-8b5f-380cb0ef8ed0.png)

Open to the possibility that there is a setting on my side that I've overlooked (since it's happened before :)

**Comment by leggett** [comment]
This might be a new bug as I removed hiding the nav in message view. I've definitely seen some issues as I had to rush out the update to fix the search box. 

I'll also say the horizontal reading pane (what you're using) has several issues I hope to fix in the next release. So it should get fixed whatever it is.

**Comment by leggett** [comment]
I've got the last (hopefully) of the fixes for the original bug (search field overlapping with the action buttons) going up with v2.1.11. So closing this issue.

I have some separate bugs tracking the numerous issues with horizontal split pane (email below inbox).
