### ISSUE TITLE
Changing width of message list and message content

### ISSUE THREAD

**Issue by SRB008** [leggett/simplify#367]
With the folder list not visible the width of the messages (list of messages) is reasonably width.  Selecting a message to read the message width reduces (and centres which is great).
Is this action - changing width - intended, as I notice on v1 the width doesn't change (or appear to change)?

![image](https://user-images.githubusercontent.com/70689137/92087995-2fd3bd00-edc4-11ea-96a3-29d9f41ab94f.png)

**Comment by leggett** [comment]
It is intended.
