### ISSUE TITLE
Trash banner covers search in vert. reading pane

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#369]
<img width="445" alt="Screen Shot 2020-09-03 at 1 22 06 PM" src="https://user-images.githubusercontent.com/8763662/92163413-8652f280-ede8-11ea-9a41-b97cc7e26b06.png">

**Comment by crockwave** [comment]
Also Spam banner

**Comment by leggett** [comment]
These banners got moved to the bottom of the page a long time ago -- finally closing the issue
