### ISSUE TITLE
Unfinished rounded corners and borders (High Contrast Theme) 

### ISSUE THREAD

**Issue by moikirsch** [leggett/simplify#370]
When reading a single email using the High Contrast theme some borders and corners are overlapped or incomplete (see screenshots).
![Screen Shot 2020-09-03 at 19 11 04](https://user-images.githubusercontent.com/7026768/92185398-7dc6e000-ee19-11ea-9361-40bd393ff838.png)
![Screen Shot 2020-09-03 at 19 10 54](https://user-images.githubusercontent.com/7026768/92185399-7e5f7680-ee19-11ea-8103-6c75ca36a508.png)

**Comment by moikirsch** [comment]
A similar/related issue happens on the inbox list of emails.
![Screen Shot 2020-09-03 at 19 14 42](https://user-images.githubusercontent.com/7026768/92185527-ce3e3d80-ee19-11ea-9a4e-3ee70bfd683f.png)
![Screen Shot 2020-09-03 at 19 14 36](https://user-images.githubusercontent.com/7026768/92185528-ced6d400-ee19-11ea-8fdc-e4382db895bf.png)

**Comment by khaister** [comment]
This is still an issue. In addition, the snooze and search icons are white instead of black as seen in other icons on the toolbar.

![image](https://user-images.githubusercontent.com/1192669/108022996-83367200-6fd6-11eb-912a-72b779c0ec24.png)

**Comment by leggett** [comment]
Correct -- I haven't gotten to the high contrast theme yet. 

The snooze icon isn't broken though. I've noticed the snooze icon happens when there is an update. Usually a hard refresh fixes it (Shift + click on refresh in the browser). Safari is worse and sometimes requires restarting the browser. Let me know if that doesn't fix it.

**Comment by leggett** [comment]
Can anyone tell me how Gmail's high contrast theme is actually high contrast? It seems lower contrast. The fonts aren't darker. The background is gray (reducing contrast) and the search box is almost the same gray. Everything has a darker border (does this help?) Should I fix any of this? At least make the fonts 100% black?

**Comment by leggett** [comment]
I've got a fix for the borders in conversation view in v2.2.5... the inbox and other parts of the theme need more work though

**Comment by leggett** [comment]
I dramatically improved high contrast theme last month in v2.3.3

**Comment by khaister** [comment]
Hi, I'm not sure if this is as designed: blue (selection) vertical bar on left is not rounded. Should I reopen this bug/open new one?

![image](https://user-images.githubusercontent.com/1192669/111821427-e1899580-889f-11eb-9ddb-cafa1f985947.png)

**Comment by leggett** [comment]
I agree this is unideal but it is working as intended. 

- I can't round the blue highlight (it is a border itself)
- I'm trying to minimize one-theme customizations (e.g., I didn't want to special case this one theme to remove the rounded corners on the list -- it is more complicated than you would think to remove)

**Comment by leggett** [comment]
To clarify, I can't round the blue highlight border **enough** because it is only a few pixels wide. I can maybe make it a little better but it still overflows outside the item border:
 
<img width="223" alt="Screen Shot 2021-03-19 at 11 11 03 AM" src="https://user-images.githubusercontent.com/8763662/111824943-17c91400-88a4-11eb-9f99-da95c7a578b5.png">

**Comment by leggett** [comment]
I'll round it as much as I can to reduce the effect but it isn't a total fix.

**Comment by khaister** [comment]
Yeah looking at your screenshot I don't even notice it unless I really zoom in. 👍

Thanks!
