### ISSUE TITLE
enabling Bitmoji extension left-aligns action buttons

### ISSUE THREAD

**Issue by andymand** [leggett/simplify#373]
When I enable the Bitmoji extension (https://chrome.google.com/webstore/detail/bitmoji/bfgdeiadkckfbkeigkoncpdieiiefpig), the action buttons align to the far left side of the tab/window (indicated by the short red line):

![screenshot-mail google com-2020 09 04-08_06_30](https://user-images.githubusercontent.com/51393001/92255792-cbd2f680-eea0-11ea-827f-7fb73303266f.png)

and when I disable Bitmoji, the action buttons (properly, IMO) align with the left edge of the message pane:

![screenshot-mail google com-2020 09 04-08_07_55](https://user-images.githubusercontent.com/51393001/92255910-f624b400-eea0-11ea-897d-f7dd46460aa9.png)

**Comment by leggett** [comment]
THis is no longer an issue in Simplify v2.
