### ISSUE TITLE
Tabs showing up as empty when navigating through with ` and ~ shortcuts

### ISSUE THREAD

**Issue by jayarr100** [leggett/simplify#375]
When I have a _new_ message showing up in one of my tabs (in the default Gmail tabbed inbox view) and I move over from Primary using the ` or ~ shortcut keys, I'll occasionally run into a glitch where the tab comes up as blank — even though I know there's something within it.

If I click around with my mouse and go out of tab and back in, the message(s) will show up. But in that initial shortcut-driven navigation, I've had that fake blank effect come up a few different times now. Seems to be mostly with the Promotions tab for me, but that may or may not be relevant.

I'll try to capture a screengrab the next time the situation presents itself, but I figured I'd leave it here in the meantime in case you're able to replicate.

**Comment by jayarr100** [comment]
Interesting! That makes sense. Thanks. (And just to state what I hope is already apparent: Despite the fact that I'm focusing solely on these sorts of tiny issues in my reports here, I'm very much enjoying v2 thus far and think it's a fantastic update. :-))

**Comment by leggett** [comment]
Appreciate that and love the attention to detail. Trying to figure out how to break it is exactly what I want.

**Comment by leggett** [comment]
I cut the delay in half to 100ms in v2.1.12 to make this less common. I'm having a hard time getting to occur again so closing this bug.
