### ISSUE TITLE
Chat button / "No New Mail" Bubble overlap

### ISSUE THREAD

**Issue by quickdraw-m** [leggett/simplify#376]
("Always show chat" = Yes) + Empty inbox =
![nonewmail](https://user-images.githubusercontent.com/70546828/92315360-aafac600-efb2-11ea-8ba6-bb3cdcb81ce4.png)

I actually really **really** like the minimalism of the "no new mail" bubble.  Total +1 there.  Just a display glitch.

**Comment by leggett** [comment]
Fix coming in v2.1.12
