### ISSUE TITLE
"Hit Enter to Reply To" vs. MixMax

### ISSUE THREAD

**Issue by Vog1K** [leggett/simplify#379]
Just an FYI for later as I know you're not yet thinking hard about other extensions, but with MixMax installed the 3rd press of Enter (first: open a message, second: focus the most recent message) opens MixMax' "share this email" functionality rather than doing a "reply to".

I'll note that, outside of that, v2 seems to be working with MixMax much better than v1.  It's been great!

**Comment by leggett** [comment]
I think this was fixed but let me know if there are still any issues with MixMax
