### ISSUE TITLE
Vertical Split format after opening full-screen email

### ISSUE THREAD

**Issue by chendysworld** [leggett/simplify#380]
When using vertical split, on occasions when opening the full compose screen or an email from search results, when turning back to split mode by clicking back, the formatting on the inbox list changes removing the subject line and body preview of the email.

This does not happen 100% of the time, and from some testing, I was only able to replicate on purpose when some of the emails in the inbox had attachments.

Before and after screenshots attached.
![Screenshot 2020-09-08 at 07 44 55](https://user-images.githubusercontent.com/16207094/92443434-69803b80-f1a9-11ea-8d08-b973f110c027.png)
![Screenshot 2020-09-08 at 07 42 20](https://user-images.githubusercontent.com/16207094/92443444-6b49ff00-f1a9-11ea-905d-2b285275deff.png)

**Comment by danielanewman** [comment]
+1, I've noticed this as well.

**Comment by leggett** [comment]
fantastic detail -- will look into it

**Comment by leggett** [comment]
I'm finally digging into this bug and am unable to reproduce it. Perhaps I accidentally already fixed it? Can you re-open it if you're still seeing it after the next update (v2.1.12) please? Thanks!
