### ISSUE TITLE
The highlight in the priority inbox is the same width even if its empty

### ISSUE THREAD

**Issue by ymolodtsov** [leggett/simplify#383]
I use Priority inbox. It seems that the highlight for the categories you mouse over always positioned the same way on the left side. But if the category is empty, there's no arrow and it breaks things. 

The desired outcome would probably be decreased the width of the highlight. 

<img width="240" alt="Screen Shot 2020-09-09 at 17 14 24" src="https://user-images.githubusercontent.com/2446078/92610120-0503d000-f2c0-11ea-9a1b-b2350332c182.png">

**Comment by leggett** [comment]
I assume it is like this without Simplify enabled, yes? I don't think I do anything to the highlights on section titles.

**Comment by ymolodtsov** [comment]
Apologies, I've almost forgotten Gmail without Simplify and attributed the glitch to it.

**Comment by leggett** [comment]
Closing this as there is no bug with Simplify. 

FYI: You can set a section to hide if it is empty.
