### ISSUE TITLE
v2.1.10 Broke Dark Theme

### ISSUE THREAD

**Issue by chendysworld** [leggett/simplify#385]
Since the app updated to v2.1.10 the dark theme is not applied to the email background, but the background colour and the colour of the text still is.

I have tried switching the extension off and on again, changed the theme to another and back and changes the invert messages setting all without any luck. 

Latest Build of Chrome
Invert messages for dark theme = All Emails

![Screenshot 2020-09-10 at 08 12 34](https://user-images.githubusercontent.com/16207094/92693711-e17f6a80-f33d-11ea-86b1-ea27b11707c1.png)

**Comment by leggett** [comment]
I also wonder if you have any other Chrome extensions installed that could be interfering somehow?

**Comment by chendysworld** [comment]
I tried the hard refresh, completely closing chrome and changing the them with no luck.

I have a number of browser extensions, I have turned these off and refreshed and that did not make any difference. The only ones that I am aware of interacting with Gmail are Grammarly for Chrome, Salesforce and Teamwork Projects for Chrome, Vidyard - Free Video and Screen Recorder

One thing I did not mention, this is in split view.

![Screenshot 2020-09-10 at 18 50 44](https://user-images.githubusercontent.com/16207094/92776374-15d34500-f397-11ea-8bfb-4330ae39f777.png)

**Comment by cy2k** [comment]
I'm having the same issue. No other gmail related extensions installed.

![image](https://user-images.githubusercontent.com/3419396/92935880-668a8280-f417-11ea-960f-b03726891cc8.png)

**Comment by leggett** [comment]
Ok, multiple reports... I'll try harder to reproduce the issue. Is like that on all messages or just some?

For now, you might want to use a different theme so you can read your email.

**Comment by cy2k** [comment]
Just some messages, for me.

**Comment by leggett** [comment]
Got a fix for this now. Will be in v2.1.11
