### ISSUE TITLE
Feature Request: Bring back the done button

### ISSUE THREAD

**Issue by FraserThompson** [leggett/simplify#39]
Funnily enough one of my favourite things about Inbox was the "Done" button. It was a much better metaphor for what people do when they're done with their email than "Archive" which is a relic of a time when email meant something completely different...

Would there be a way to replace the archive button with a tick icon "Done" button?

**Comment by leggett** [comment]
I agree (was a big proponent of changing it for Inbox). But changing Archive to Done in Gmail would not be any easy task as the action is in a lot of places.
