### ISSUE TITLE
some sort of (cut-off) forwarding-messages message at the bottom of the screen

### ISSUE THREAD

**Issue by andymand** [leggett/simplify#390]
Not sure what to call this message (a footnote?), but I added a new forwarding address and -- even after a hard refresh of the Gmail tab -- I still see a reminder message at the bottom of my inbox:

![screenshot-mail google com-2020 09 13-15_28_47](https://user-images.githubusercontent.com/51393001/93026718-160d5380-f5d6-11ea-977c-3fddec0e6ca1.png)

**Comment by leggett** [comment]
Simplify is keeping you from seeing the whole banner which says it won't go away for a few days.

**Comment by andymand** [comment]
Forgive my ignorance, but I'm not sure what that means.  (The aforescreenshotted banner is gone now, FWIW.)

**Comment by andymand** [comment]
Ah, I caught a glimpse of the whole banner when I looked at an empty tab.  But when I went to a non-empty tab, I saw the cut-off banner again (so nvm my nvm :)

**Comment by leggett** [comment]
Fix for this coming in v2.1.12
