### ISSUE TITLE
Promotions tab ad display

### ISSUE THREAD

**Issue by jayarr100** [leggett/simplify#391]
Happy Monday! Here's a new one — something I've seen a couple times now but that plays out very quickly and that I can't _consistently_ get to happen (thus no screenshots as of yet):

When I move over to the Promotions tab in my inbox, I'll occasionally see the standard Gmail ad lines in a separated section at the top of the screen — in an interface kind of reminiscent of how Simplify separates emails by date, when that feature is activated. But after a second or so, they flick away and are gone from the screen altogether.

I'm guessing maybe this is a built-in ad-blocking system and that at certain times, it's just taking a second to kick in, for some reason? And that may or may not be a glitch, if so, or anything that can be addressed. But since I've seen it at least twice now, I thought I'd pass it along, just in case it's of interest.

I am also running uBlock Origin, so it's _possible_ that could be playing some sort of role in this. I haven't yet been able to figure out for sure how much of this might be from it vs. Simplify, but I don't recall ever noticing this happen before I had the v2 software in place.

**Comment by leggett** [comment]
I'm blocking the ads in a way that will ensure I never hide non-ads... but I too have seen oddities where they are there and then they are gone. One of the crazy things Gmail does is any time they make *any* change to the message list, they remove the _entire_ list and add back a whole new list. So I have to detect when that happens and rescan everything. It should all happen in a way that you never notice it. But something fishy is going on it is visible.

**Comment by leggett** [comment]
I think I have a fix for this and will push it in v2.1.11. I'm going to close this for now but will re-open if I see it again.
