### ISSUE TITLE
MixMax SideBar breaks Simplify (MixMax 4.7.14 & Simplify v2.1.10)

### ISSUE THREAD

**Issue by Vog1K** [leggett/simplify#392]
EDIT: Had a brainstorm on what might have changed, and it turns out it was turning on MixMax' Sidebar functionality.

Simplify v2 and MixMax had been working great, but as of today it doesn't work (when I turned on the MixMax Sidebar).

The issue is you can no longer click any of the icons at the top of the screen when you're in an email thread.

![image](https://user-images.githubusercontent.com/70934418/93144490-f2faa680-f69e-11ea-8024-afb527b00a13.png)

If you hover over the exclamation point (spam) you get a label that says "Search".  None of the other icons have any interaction capability (can't click, no label).  If I change the screen dimensions, what you hover over to get the "Search" label changes.

Clicking on the blank area still pulls up the search box - that works correctly.

This issue does not happen with Simplify v1 (I checked).  Turning off the MixMax Sidebar also stops the issue.

Let me know if you need any other info - thanks!

**Comment by leggett** [comment]
Thanks for the detail... I'm trying to change how I handle hiding search. I'm not sure if it will fix this but it might. Fingers crossed.

**Comment by leggett** [comment]
I believe I fixed the issues with MixMax and Simplify in v2.3.3 when I dug deep into issues with other extensions. Let me know if any issues remain.
