### ISSUE TITLE
search field still overlapping action buttons

### ISSUE THREAD

**Issue by andymand** [leggett/simplify#393]
Hard refreshed to Simplify v2.1.11

![Screenshot 2020-09-17 at 18 29 04](https://user-images.githubusercontent.com/51393001/93534890-e29f3180-f913-11ea-9ccd-584451393b4a.png)

(and the filter forwarding banner thing still cut off, but I imagine that will resolve itself in a few days  :)

**Comment by leggett** [comment]
Yeah, I didn't get to horizontal preview pane or the forwarding banner in this release. Both slated for the next one. I have bugs tracking both of these so closing this one.
