### ISSUE TITLE
Consider switching to 1-line view on reading pane at a wider list view width

### ISSUE THREAD

**Issue by danielanewman** [leggett/simplify#394]
![2020-09-18_09-29-47](https://user-images.githubusercontent.com/5234389/93603169-a0b4d080-f991-11ea-9a58-2bfdad0f3a08.png)
This is 2.1.11. Additionally, the items are only showing in this condensed format across all tabs now, vs. the multi-line subject+ teaser version, which I preferred.

**Comment by leggett** [comment]
Whoa! I've never seen this grouping before. I don't have it myself so maybe something Gmail is testing? I think the hierarchy works pretty well here. (date groups below the the top level categories). And my decision to not label the items for "Today" also help. But if you had stuff from earlier, I could see it breaking... 

As for the one line format, that is based on the width of the list pane. I swap to a one line view at the same breakpoint Gmail does. It doesn't seem super valuable at this width as you can only barely see the subject, so I wouldn't be apposed to keeping at the multi-line format a bit longer. But you should be able to shrink the width of the pane and return to the wrapped UI.

**Comment by leggett** [comment]
I tried to change where Gmail changes to one line and it was too buggy. I'm going to leave this as is..
