### ISSUE TITLE
Incorrect detection of nav state on load

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#395]
![image](https://user-images.githubusercontent.com/21956756/93609884-aaa7f500-f9cc-11ea-96d3-55fd7307ae2b.png)

**Comment by leggett** [comment]
I'm pretty sure it isn't disappeared and instead Simplify is incorrectly detecting it as open when it is closed. (Definitely a bug, but a different one)

If you toggle it closed/open, it should correct it. Let me know if that doesn't work.

**Comment by KraXen72** [comment]
yes that corrects it. but its still a bug.

**Comment by leggett** [comment]
Thus far, I'm not able to reproduce this issue. Can you give me a little more detail about your setup (browser, OS, and any other extensions you're running that modify Gmail)?

**Comment by leggett** [comment]
Actually, I don't think that's the problem. I've tried it on Chrome and Edge on Mac and Windows and have yet to reproduce the bug.

But I suspect it is something that happens intermittently. 

New questions: 

- Does this happen to you only on the initial load of Gmail, randomly while using Gmail, or both? 
- If randomly while using Gmail, have you noticed any pattern to what causes it (e.g. when you click on a label in the nav or open a message)?

**Comment by KraXen72** [comment]
it only happes on load. i have gmail as a pinned tab and i use vivaldi latest stable windows 10.  also it doesen't happen every time
i power off my computer every time i go to school etc and when i come home and launch vivaldi it loads gmail and simplify and it happens like 80% of the time

**Comment by leggett** [comment]
Super helpful... I think it may have something to do with a cold start (starting up the browser). I'll see if I can repro the issue on Windows that way. I bet if you just sit there and reload Gmail, it never happens.

**Comment by KraXen72** [comment]
i tired it several times, but i could'nt get it to trigger just by reloading.

**Comment by leggett** [comment]
Ok, I still can't get this to happen for me but I'm thinking it might be that the nav state isn't initialized yet when I check it. So I'm going to add a case for this where I revert to whatever it was last time I saw the nav state in v2.1.12. Let's see if that fixes it. Re-open the bug if it doesn't.

**Comment by KraXen72** [comment]
ok, i'll keep you updated.
