### ISSUE TITLE
Search bar seriously collapsed using Edge

### ISSUE THREAD

**Issue by Gomat** [leggett/simplify#396]
I am running Simplicity v 1.7.17, Edge version 85.0.564.51 (Official build) (64-bit). 
The search bar is collapsed even though there is a large blank space in the middle of the tool bar. We saw this problem before and thought you had fixed it but it's still a major problem.
![Capture](https://user-images.githubusercontent.com/1144504/93830681-dd592400-fc3e-11ea-90ef-fa732acb258f.JPG)

**Comment by leggett** [comment]
This is what it is supposed to look like unfortunately on smaller screens like this. If you click on the text of the search, the search box will expand. 

Simplify v2 takes a different approach with search making this not a problem. Hoping to launch soon.

**Comment by Gomat** [comment]
Thank you, Michael.

  - Scott
    413 210-0032
________________________________
