### ISSUE TITLE
Date Divider Coloration in v1 vs v2

### ISSUE THREAD

**Issue by Henboy10** [leggett/simplify#397]
I prefer the way that v1 handles the coloration of the date dividers. My gray background color is used and looks better in my opinion. v2 seems to just use white which can be a little difficult to differentiate. Any chances of that getting an update?

v1
![Screenshot 2020-09-23 120855](https://user-images.githubusercontent.com/22181579/94046554-7189cf00-fd96-11ea-8b22-447e391e0c7b.jpeg)

v2
![Screenshot 2020-09-23 120947](https://user-images.githubusercontent.com/22181579/94046583-7ea6be00-fd96-11ea-98b8-d4c1109748f8.jpeg)

**Comment by leggett** [comment]
I hear ya. I went back and forth on this one... it looks a lot better in other themes having the same background color (it also ensures the date group names are readable). It also looks a lot better when mixed with a sectioned inbox (like Priority Inbox or Unread First). 

So my plan for now is to stick with how it is in v2... maybe make the labels darker so they pop more and keep an eye on it at launch. I doubt I'll revert to how it was in v1 but _maybe_ I'd consider adding an option (I hate adding options).

**Comment by CarlosRebolledo** [comment]
Estoy de acuerdo con Michael
