### ISSUE TITLE
Snooze icons much too faint when using theme with picture

### ISSUE THREAD

**Issue by pruchkin2** [leggett/simplify#398]
Love your stuff.

Snooze icons much too faint when using theme with picture, hoping you can fix soon?  

See screenshot and this on Chrome Version 85.0.4183.121 (Official Build) (64-bit) running windows 8.1. Thanks much.

![Simplify snooze too light](https://user-images.githubusercontent.com/27218191/94349102-62618600-000f-11eb-9173-0e7148b502ce.PNG)

**Comment by leggett** [comment]
I dim these so they aren't so loud in the inbox. That's less important here in the Snoozed list so maybe I can change it there... Also, this is a little better in Simplify v2 but maybe not better enough? 

**Here is v1:**
<img width="171" alt="Screen Shot 2020-09-28 at 3 11 01 PM" src="https://user-images.githubusercontent.com/8763662/94491400-09275d00-019d-11eb-8125-7037bc3fbf6c.png">

**vs v2:**
<img width="147" alt="Screen Shot 2020-09-28 at 3 11 45 PM" src="https://user-images.githubusercontent.com/8763662/94491419-10e70180-019d-11eb-9c83-df6d9942561d.png">

**Comment by leggett** [comment]
Ok, I increased the opacity and reduced the saturation instead. 
<img width="174" alt="Screen Shot 2020-09-29 at 5 35 51 PM" src="https://user-images.githubusercontent.com/8763662/94630328-4ada0580-027a-11eb-8cd4-498e5735a0ec.png">
