### ISSUE TITLE
Add "Yesterday" to date groups

### ISSUE THREAD

**Issue by marcavila** [leggett/simplify#399]
Hello. Love the product. Any chance to include "Yesterday" to the date groups? I typically follow the Yesterbox process of starting with yesterday's email first, then switch to today's email. Thanks!

**Comment by leggett** [comment]
Hmm... there should be a yesterday group. I just confirmed it is working for me so you may be seeing a bug preventing it from working as expected. I've improved date grouping a bunch in Simplify v2 (currently in beta testing) including addressing a number of edge cases around snoozed and nudged emails. So if it isn't working for, it definitely will soon with v2.
