### ISSUE TITLE
Feature Request: Clicking off of emails closes them

### ISSUE THREAD

**Issue by boboysdadda** [leggett/simplify#4]
In inbox, one of the features was if you clicked off of an email it would close it. I would appreciate that instead of going all the way to the top left to click the back button. Awesome work BTW.

**Comment by leggett** [comment]
Will consider but probably unlikely. Part of what makes that work well in Inbox is (1) you only expand items in Inbox and are still in the inbox where as in Gmail you open items and leave the inbox and (2) there is the background (gray) is clearly defined as separate from the message card (white). I'm not excited about adding a gray background behind the message and app bar and then trying to get that to work with themes. 

Fwiw, you can use the "u" keyboard shortcut to go back as well.

**Comment by boboysdadda** [comment]
Thanks,

I'll go enable keyboard shortcuts.
#BringBackInbox
