### ISSUE TITLE
Mix of dark mode and light mode? 

### ISSUE THREAD

**Issue by judehansen** [leggett/simplify#40]
The extension was working fine for me when I first installed it, I like using one of the Google themes with it set to light mode. Then, the next day, all my read messages were in dark mode but my unread messages were in light mode. I'm running dark mode on Mojave. In Gmail, I'm using a theme that is set to light mode. If I set it to dark mode in the Gmail theme, it is fine (everything is dark themed) but in light mode, it's now mixed. I tried turning off Dark mode at the OS level but the issue persisted. I also uninstalled and reinstalled the extension to no avail. Any suggestions?

**Comment by leggett** [comment]
All you should have to do is refresh Gmail and it **should** detect the correct theme color. 

If that doesn't work, mark your first message unread and try refreshing again. What I do is find the first message in the inbox and detect the background color. Then I apply a global filter depending on if that background was light or dark. On top of that, I save the state (so I don't have to wait for the theme to load) and use that as the initial default. I still detect it every time it loads so it might start wrong and then flash to the correct setting. Then it should always just be right every load after. 

Re-open this issue if it doesn't resolve itself.
