### ISSUE TITLE
Add blurred background for messages list

### ISSUE THREAD

**Issue by panaghia** [leggett/simplify#400]
![Schermata 2020-09-29 alle 12 26 38](https://user-images.githubusercontent.com/236285/94547096-14d35c00-024f-11eb-8950-0967ad40cb0a.png)

**Comment by leggett** [comment]
Simplify Gmail v2 changes the opacity of the list so it isn't as transparent to improve readability. Also, I think blurring the background (presumably with something like `backdrop-filter:` blur(20px)`) would be a sizable performance hit.
