### ISSUE TITLE
Chat window flickering and unusable

### ISSUE THREAD

**Issue by quickdraw-m** [leggett/simplify#401]
Conditions: Current major release of Chrome running on Windows, updated browser and extension.

Problem: with left sidebar nav _collapsed_ , hovering over the Chat button sometimes causes my conversation list to flicker rapidly in and out of existence.  Moving off the chat button causes it to vanish entirely.  It is impossible to select a chat participant and initiate a chat.

Caveats: Problem does not occur consistently.  It appears possible that "click to keep the nav open" prevents the problem, but I can't be certain.  Also, sometimes it persists through a reload of the tab, but sometimes reloading resolves the problem.  This most recent instance, it persisted through a reload and then stopped after a minute or two.

**Comment by leggett** [comment]
Geez -- that's one hell of a bug. 

As I recall, you have the "Always show chat" setting enabled? I think I broke support for this setting in the last update. But I can't reproduce the larger issues of it hiding your conversation list to flicker. I'll look at adding back proper support for "Always show chat" and let's see if that fixes it.

![chat](https://user-images.githubusercontent.com/8763662/94715479-60930d80-0302-11eb-956d-6eac0ec0d55a.gif)

**Comment by quickdraw-m** [comment]
Yup, I have "always show chat" enabled, and my use case is likely  going to stay that way until Google gets around to killing Chat entirely.

I just tested this on my Chromebook too.  Over there, this problem manifests as the always-on chat button not displaying Chat on-hover, but on-click, and even then only blipping up for a split second.  However, if I first hover over the collapsed nav to expand it, and _then_ go down to the Chat button, it properly (persistently) displays Chat on-hover and allows me to to use it normally.

**Comment by leggett** [comment]
Your experience on your Chromebook mirrors what I'm seeing. I'll test more on Windows and figure out what is going on.

**Comment by leggett** [comment]
I think I found the problem and should have a fix in the next update (v2.1.12)

**Comment by leggett** [comment]
I wasn't able to reproduce the issue on my end but I found some issues with how the "Always show chat" setting worked which I fixed in v2.1.12 (just released). Please re-open this issue if you see the problem again.

**Comment by quickdraw-m** [comment]
I've just tested on both Windows Chrome and ChromeOS, and the issue is not happening any more.  Looks like you got it.
