### ISSUE TITLE
Chat icon is positioned below the fold

### ISSUE THREAD

**Issue by raess** [leggett/simplify#403]
Scrolling on the sidebar causes the toolbar and the chat icon to scroll

MacBook Pro 13"
Chrome 85.0.4183.121

![Screen Recording 2020-10-04 at 20 29 01](https://user-images.githubusercontent.com/1557805/95024003-4ba6d900-0678-11eb-8462-dd3cc6b69e9f.gif)

<img width="463" alt="Screenshot 2020-10-04 at 20 22 04" src="https://user-images.githubusercontent.com/1557805/95023891-80fef700-0677-11eb-8f45-516e73022ff1.png">

**Comment by leggett** [comment]
Hmmm... I can't reproduce this (also on a Mac with Chrome). Something is clearly wrong in that your chat button is off the screen which makes the entire app scrollable when it shouldn't be. Could you send me a full screenshot of your entire Chrome window to hi@simpl.fyi? You can use your spam folder.

**Comment by leggett** [comment]
Got in touch with Simon and he wasn't able to repro the issue after he restarted his computer.
