### ISSUE TITLE
[discussion] Toolbar moves between views

### ISSUE THREAD

**Issue by raess** [leggett/simplify#404]
The moving toolbar makes it harder for me to understand the actions stay the same between list view (with a selected message) and reading view. Because of the moving toolbar, the pointer highlights the spam action after clicking the back button, which I find a bit confusing.

Personally, I prefer the toolbar to stay at the same location in both views. This would allow for the global checkbox in list view to be replaced by the back arrow in reading view. The rest of the toolbar would remain unchanged and therefore, makes it a bit easier to understand how both views play together.

![Screen Recording 2020-10-04 at 20 41 17](https://user-images.githubusercontent.com/1557805/95024607-ff5d9800-067b-11eb-9705-8dd4b325a3aa.gif)

**Comment by leggett** [comment]
This is because the max-width is wider for the list than it is for the conversation and I want the actions to align in both cases. The actions jumping only happens if you open a message while it is selected (not a common workflow) so I think this is fine as is.
