### ISSUE TITLE
Hovering search icon shows pagination

### ISSUE THREAD

**Issue by raess** [leggett/simplify#405]
Hovering the search icon shows pagination:
- when a message is selected in list view
- in reading view

This feels a bit confusing as it implies that the search is scoped by the current pagination (list view) or number of messages (reading view), which it is not.

![Screen Recording 2020-10-04 at 21 04 54](https://user-images.githubusercontent.com/1557805/95024842-96771f80-067d-11eb-9ec8-f2e99de43ea3.gif)

**Comment by raess** [comment]
Please consider not to show the search icon and the action bar at the same time. This means to hide the search icon in reading view and when a message is selected in list view. Both the keyboard shortcut and clicking the empty space (with magnifying glass icon) would still work.

**Comment by leggett** [comment]
- Showing the pagination numbers on hovering over the search button is not desired but is an unavoidable byproduct of how/where I insert the search button.
- I had the "click in the empty space to search" as the only solution for a while but some people couldn't find it. I might remove that solution but I still like it personally so I'm toying with keeping both. ¯\_(ツ)_/¯
