### ISSUE TITLE
Nav has semi-opaque, dark grey overlay in secondary account

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#409]
See attached screenshot. It works perfectly in my main Gmail account.

Chrome 85.0.4183.121

<img width="370" alt="Screenshot 2020-10-09 at 10 01 01" src="https://user-images.githubusercontent.com/312540/95564771-31be1b00-0a17-11eb-96e3-357c7e0b9850.png">

**Comment by leggett** [comment]
Strange. This is when the nav is hidden and you hover over the menu button to peek at the nav? Is that right? 

The dark background on the nav goes with dark themes or themes with a background image. My guess is you use a theme of some sort in your other account or maybe you were trying out a few themes and something got out of wack. But that once you refreshed, the problem went away. 

Is that right? Is this still a problem or did it go away?

**Comment by nhojb** [comment]
Yes, this is when I hover over the menu button only (all ok when I click the menu button to toggle the nav bar).

Both accounts are virgin, no themes or other extensions are installed. The secondary account is a managed account.
I can reproduce the bug all the time in Chrome on both my Macs.

**Comment by leggett** [comment]
Interesting! I've tried to replicate this in two different managed accounts on my end and am not having success.

One other thing to try is switch your theme to something else and then switch back. Don't do this via quick settings (which sometimes only half way changes the theme). Do it via https://mail.google.com/mail/#settings/oldthemes

If that does't fix it, would you be up for helping me figure out how to reproduce the issue so I can fix it?

- From your screenshot, I see you use Unread First inbox and have Chat disabled but not Meet. 
- And it looks like you aren't using reading pane. Is it disabled or set to "No Split"? You can tell under https://mail.google.com/mail/u/0/#settings/inbox > Reading pane.
- Do you use any other chrome extensions that modify or add to Gmail?
- When you switch accounts, I assume that is via the account switcher in Gmail. Or is it via Chrome profiles?
- What version of Simplify do you have? You can check by going to Simplify Settings (click on Gmail's settings gear and there should be a button at the top under "See all settings" for "Simplify Settings"). 
- Anything else special I should know about?

**Comment by nhojb** [comment]
Speaking from experience, bugs which cannot be reproduced are the worst kind :-(

Interestingly I cannot access the "Themes" setting from the managed account. See attached settings screenshots from my main account and the managed account. The semi-opaque, grey background is also present in the settings menu (in the managed account). I've never installed / used a theme in either account.

> From your screenshot, I see you use Unread First inbox and have Chat disabled but not Meet.

Inbox is Unread first. Chat isn't available in the managed account. Meet is enabled.

> And it looks like you aren't using reading pane. Is it disabled or set to "No Split"? 

Reading pane is disabled.

> Do you use any other chrome extensions that modify or add to Gmail?

No.

> When you switch accounts, I assume that is via the account switcher in Gmail.

Yes.

> What version of Simplify do you have?

2.1.13

Anything else special I should know about?

I don't think so. Same setup in my main Gmail account and I'm not seeing any problems there.

![MainAccount](https://user-images.githubusercontent.com/312540/95774721-db700700-0cb8-11eb-95a0-9c6d5a2a71f1.png)
![ManagedAccount](https://user-images.githubusercontent.com/312540/95774725-dca13400-0cb8-11eb-8003-0252ae9fc8e3.png)

**Comment by leggett** [comment]
Thanks for all the details! It looks like the vanilla white theme is somehow different in the managed account where you can't set the theme. I'll see if I can disable themes for my test GSuite account and replicate the issue.

**Comment by leggett** [comment]
Found the issue. The element for themes is not there at all when themes are disabled (makes sense) and Simplify ends up thinking it is a theme with a background image. I should have a fix in the next release. Thanks for the detailed report and helping me figure it out!
