### ISSUE TITLE
Replace empty checkboxes with profile picture

### ISSUE THREAD

**Issue by damjanuzelac** [leggett/simplify#41]
Is it technically possible to bring the profile icons (of senders) to the mail list instead of those pointless empty checkboxes - just like Inbox did?

**Comment by leggett** [comment]
Closing for now... will re-open if we start working on it.

**Comment by leggett** [comment]
I'm now doing this in v3 beta along with bundles: https://canary.simpl.fyi

**Comment by leggett** [comment]
Note: I'm not using an API or anything. I'm just caching the image urls from conversation view locally and then showing them in the inbox. Downside is it takes a little while to build up the local cache of URLs and it doesn't sync across computers, browsers, or Chrome profiles (yet).
