### ISSUE TITLE
Formatting wrong in Edge when it suggests using GDrive for attachments

### ISSUE THREAD

**Issue by jstride** [leggett/simplify#411]
I was unable to get a screenshot, but if you click the attachment button GMail will prompt you to try with GDrive. It loads in a modal but the formatting of the help text escapes the bounding of the box.

**Comment by leggett** [comment]
Can you say a bit more about the steps to reproduce this? 

I assumed it was when you tried to attach a file larger than 25MB and Gmail instead uploads it to Google Drive, but that doesn't appear to be the case (or at least that dialog looks fine for me).

**Comment by jstride** [comment]
No it was actually a small file but the first time I'd tried to attach one
on that account (it was a new workspace account).

It's a very edge case. I'll try and see if I can repeat it by adding a new
account.

**Comment by jstride** [comment]
![image](https://user-images.githubusercontent.com/1501958/97554661-0b860c80-1a12-11eb-8378-fcee82ce14f9.png)

**Comment by leggett** [comment]
Got it.

Looks like you have other extensions that modify Gmail too, yes? I've never seen the compose window float like that. It is also restyled in a way that Simplify doesn't do. And I see a Calendar button in compose and Grammerly. 

And any other tips on how to get this dialog to trigger? I've tried opening new accounts (both consumer and GSuite) and I can't get it to come up.

**Comment by jstride** [comment]
Just that, lastpass and simplify. This is a Gsuite/Workspace account if it makes a difference.

**Comment by leggett** [comment]
I finally ran into this dialog and got all the classnames I need... fix in v2.3.8
