### ISSUE TITLE
Profile Picture formatting wrong on G Suite accounts

### ISSUE THREAD

**Issue by ChristianVaughn** [leggett/simplify#415]
The icon for the profile picture is slightly off on an account through G Suite. You can see it in the upper right corner of the screenshot
![Untitled-1](https://user-images.githubusercontent.com/4643028/97373108-67199400-1872-11eb-8f23-d21f8a24f903.png)

**Comment by CarlosRebolledo** [comment]
+1 Bis

**Comment by leggett** [comment]
Thanks for the report. This happens when your domain doesn't have a logo and it uses the "Google Gsuite" logo (which I assume will be switched to "Google Workplace" at some point). 

Fix coming in next update (v2.1.14)
