### ISSUE TITLE
Hover does not show Google Apps nine squares

### ISSUE THREAD

**Issue by chrisb323** [leggett/simplify#416]
Hovering over the settings Gear or near the Search box has stopped revealing the Google Apps nine squares icon. Please help!

**Comment by leggett** [comment]
Thanks for the report. Will check in a fix for this shortly. Look for v1.7.18

**Comment by chrisb323** [comment]
Hi, v1.7.18 doesn't seem to have fixed this issue

**Comment by leggett** [comment]
Yeah, I fixed it and broke it at the same time. I pushed v1.7.19 which should actually fix it this morning. It is already live for Chrome and Firefox.
