### ISSUE TITLE
Email overlapping reply and forward button V2

### ISSUE THREAD

**Issue by Henboy10** [leggett/simplify#418]
I think this is the first time I've encountered this, but here's the problem. 
![image](https://user-images.githubusercontent.com/22181579/97585891-a1487a00-19c7-11eb-8538-ed5303462000.png)

**Comment by leggett** [comment]
Whoa! That's crazy. Would you be willing to remove any personal info and forward the email to hi@simpl.fyi?

**Comment by leggett** [comment]
And I assume if you disable Simplify (Alt+S), the problem doesn't persist, yes?

**Comment by Henboy10** [comment]
Yup! I've forwarded to that email :)
Disabling Simplify does fix the problem

**Comment by leggett** [comment]
Got the email. I see it on my end too. I'm adding this to my set of test emails I check when I make big changes. Thanks for sharing it.

When I disable Simplify, the bottom of the email is cut off. This is certainly better than covering the reply buttons.

The email has some bad HTML in it where they set the height of a table to be a fixed number of pixels and then the content is a lot taller than that. Gmail cuts it off. I also tried it in a few other email apps and see they cut it off as well. Simplify made a change to allow content to be visible when it goes outside the bounds of the email but that was intended for images that are really wide. So I'm changing this to only allow overflow to be visible when it is wider, not taller. This should match how Gmail itself works without Simplify. 

Update will land in v2.1.14. Thanks again for sharing.
