### ISSUE TITLE
Oval-shaped New Message button

### ISSUE THREAD

**Issue by dru212** [leggett/simplify#419]
> On my Gsuite account only... The latest update (v1.7.17) changes the shape of the "New Message" button to an oval and chops off the company logo (which is 320 X 132px) in the upper right corner. 

![Screenshot 2020-10-29 160317](https://user-images.githubusercontent.com/31677159/97641960-54819500-1a01-11eb-9d9f-ba261b6a4999.png)

**Comment by dru212** [comment]
Disregard.. I manually updated to 1.7.18 which fixed the issue.

**Comment by leggett** [comment]
Thanks for the report though... I just fixed this a couple days ago so the auto-update hasn't made it to everyone yet.
