### ISSUE TITLE
Line spacing became really big today (April 9)

### ISSUE THREAD

**Issue by guptas4** [leggett/simplify#42]
I prefer to use the compact layout of Gmail.
This was working for me in Simplify.
Unfortunately with todays update the default is wide height spacing.
can we revert and provide the user an option. Thank you!!

**Comment by leggett** [comment]
Just checked in a fix in v1.1.2. You might have to reload Gmail. Let me know if you have any issues.

**Comment by guptas4** [comment]
Thank you. will wait for ver 1.1.2. Not available yet

**Comment by leggett** [comment]
Appears to be live now: https://chrome.google.com/webstore/detail/simplify-gmail/pbmlfaiicoikhdbjagjbglnbfcbcojpj

**Comment by guptas4** [comment]
yes. thanks it works perfectly.
