### ISSUE TITLE
New Message Button too wide in Edge

### ISSUE THREAD

**Issue by jstride** [leggett/simplify#421]
![image](https://user-images.githubusercontent.com/1501958/97979519-47eaab80-1e0a-11eb-8a05-5cce9b196421.png)

**Comment by leggett** [comment]
This is on v2, right? If so, a fix for this is coming in the next update (2.1.14)

**Comment by leggett** [comment]
If it is v1 (the public version), I fixed this in v1.7.18. Microsoft just approved that update (it takes them 1-2 weeks to approve updates). If you install it from the Chrome Web Store instead, you will get the updates much faster.

**Comment by CarlosRebolledo** [comment]
Hi Micahel, when else do you release v2.1.14? Thank you now and
congratulations on your work

**Comment by jstride** [comment]
Yup it is V2
