### ISSUE TITLE
Account Icon Missing - Firefox

### ISSUE THREAD

**Issue by camillecelone** [leggett/simplify#422]
The icon to switch between accounts is missing. The spot is still clickable so I can switch accounts but the hover interaction that allows opening the google apps menu does not appear.

**Comment by leggett** [comment]
Thanks for the report. In fixing this last week, I seem to have broken it in some cases. Will get a fix out today.

**Comment by leggett** [comment]
Got a fix. Uploading now. Thanks again for the report.

**Comment by leggett** [comment]
And already live for Firefox. You can force an update by going to about:addons and clicking on the gear in the top right and choosing "Check for updates"

<img width="974" alt="Screen Shot 2020-11-03 at 7 32 00 AM" src="https://user-images.githubusercontent.com/8763662/98006101-b564f080-1da6-11eb-8072-786ba1e3a5d0.png">
