### ISSUE TITLE
Compose Button is Stretched

### ISSUE THREAD

**Issue by stevebertan** [leggett/simplify#424]
Compose button is stretched. Only happens when the left navigation sidebar is toggled to be always visible. Also only happens when I'm using my Google Workspace account, does not manifest for my personal Gmail account.

![compose](https://user-images.githubusercontent.com/12550061/98402724-a5564680-201c-11eb-8de6-b7bb02d240a2.png)

**Comment by leggett** [comment]
Fix coming in v2.1.14 (hopefully in the next day or two -- compose settings have taken longer than expected, but I'm getting close)
