### ISSUE TITLE
Screen moves up as replying to emails

### ISSUE THREAD

**Issue by SoheilSalehian** [leggett/simplify#425]
Hey!

I have noticed in the last few days that while replying to emails, while typing the box keep moving vertically up as you type.

Thanks for working on this great extension!

**Comment by leggett** [comment]
I've seen this a few times myself and tried to fix it. Each time I think I fix, it seems to come back. It is an odd bug that typically goes away after a hard refresh. I'll keep looking for it and trying to fix it for good.

**Comment by leggett** [comment]
I finally figured out the issue here and fixed it a few weeks ago!
