### ISSUE TITLE
Compose "send"/formatting  shifted off page when Chrome extension button in send bar

### ISSUE THREAD

**Issue by group7access** [leggett/simplify#428]
By **Btmoji** and **Canned Responses - Tray** Chrome extensions add a button to the compose window's "formatting/send" bar. When Either of these extensions are enabled, the bar shifts down off of the window:
![image](https://user-images.githubusercontent.com/70614907/99928671-bc30b480-2d0f-11eb-9f1b-766390806f8d.png)

**Comment by leggett** [comment]
Yeah, I haven't done much work on trying to play nicely with other extensions yet. Will add this to the list of extensions to look into.

**Comment by leggett** [comment]
This was eventually fixed.

**Comment by leggett** [comment]
Actually, not for Bitmoji... re-opening.

**Comment by leggett** [comment]
I found the route problem was with InboxSDK (a library a lot of extensions use to modify Gmail). I have have fixed that root problem which fixes this for not just for Btmoji and Canned Responses but a lot of other extensions too.
