### ISSUE TITLE
[v2] Formatting issue when selecting SPAM message

### ISSUE THREAD

**Issue by jaketame** [leggett/simplify#429]
#### Issue description
When selecting a spam message, the notification about the message being deleted has some formatting issue.

![Screenshot 2020-11-23 at 08 57 03](https://user-images.githubusercontent.com/1787973/99944543-f4191580-2d6a-11eb-9cec-f151983b40ae.png)

#### Steps to reproduce the issue

1.  Select spam message

#### What's the expected result?

- Hide search?
- Margins on message?

**Comment by leggett** [comment]
To clarify, the issue is the "Messages that have been in Spam..." banner that is cover the search box, yes? Or is the issue something else?

**Comment by leggett** [comment]
I moved this banner to the bottom of the page.
