### ISSUE TITLE
hovering over new message button shows side menu resizer

### ISSUE THREAD

**Issue by derylseale** [leggett/simplify#430]
When hovering over the new message button, the side menu resizer control is shown even when the menu is hidden. For some reason, this only seems to happen on a personal gmail account -- I can't reproduce on a business account. This happens on version 2.1.15. 

<img width="424" alt="Screen Shot 2020-11-23 at 8 32 19 AM" src="https://user-images.githubusercontent.com/1426718/99968054-a39fb900-2d66-11eb-9e93-c9a91bb6676a.png">

**Comment by leggett** [comment]
Thanks for the report -- good catch -- an oversight from allowing the old chat roster to be visible again.

Fix checked in for the next update (v2.1.16)
