### ISSUE TITLE
Zero-inbox background images are positioned poorly on very wide devices

### ISSUE THREAD

**Issue by TomHigson** [leggett/simplify#431]
I use an ultra-wide (21:9) monitor. Many of the zero inbox backgrounds look odd as they are significantly cut off at the top (the dog one is especially noticeable). This also applies to any window positioned to be wide and short. Perhaps consider centering the image vertically.

![image](https://user-images.githubusercontent.com/6135663/100076264-ea5de380-2e38-11eb-8086-a1ad46dc9d0e.png)

**Comment by leggett** [comment]
Agree -- the focal point for the original background was the bottom but I
should make it dynamic depending on the background. Will do.

**Comment by leggett** [comment]
Thanks again for the report. Fix checked in for next update (v2.1.16)
