### ISSUE TITLE
[v2]  compose stays at the same position when opening settings

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#433]
![Screenshot_2020_11 27_08;24](https://user-images.githubusercontent.com/21956756/100422173-14f2ab00-308a-11eb-9d3b-0953b577e5ae.png)

**Comment by leggett** [comment]
This is more of a Gmail bug... ish. But I think I've got a work around. I find the compose actions move over as soon as I click in the body of the compose mole. So I'll just check if any compose moles are open like this and move the focus to the body in each mole. 

Will put that out in v2.1.16. Re-open if it doesn't go away.
