### ISSUE TITLE
Nit: GMail Favicon not replaced  when "Unread message icon" is enabled (Advanced settings)

### ISSUE THREAD

**Issue by Kw-git** [leggett/simplify#434]
I've been running the latest milestone with all of its terrific fixes since it first became available; by now, all of my GMail accounts have switched to the old GMail Favicon, except the one inbox for which I have "Unread message icon" enabled (in Advanced settings, see attached screen snapshot). 

![image](https://user-images.githubusercontent.com/32313784/100524280-bc540880-3184-11eb-9954-82078a616012.png)

Once I turned the "Unread Message Icon" off, the old Favicon was loaded. This is certainly not a big issue....

**Comment by leggett** [comment]
Hmm... let's see. 

That number is actually part of the favicon ([example](https://ssl.gstatic.com/ui/v1/icons/mail/rfr/unreadcountfavicon/2/100+_2x.png)). So I would need to build 100 favicons (not impossible) and then figure out how to keep it in sync with the unread count (probably a mutation observer on the Inbox item in the nav). 

I think I'm going to skip fixing this for now but if others ask for it, I'll come back to it.

**Comment by Kw-git** [comment]
I think I can very readily agree to leave this at extremely low - the lowest possible - priority...; the first line fix is to turn off the numbers, and then the substitution works just fine.  May I suggest we consider this a "so noted" and address the things in life that actually matter... :-)

**Comment by leggett** [comment]
So noted. And I appreciate the report even if it is low priority. You never know -- it might have been an easy fix. :)
