### ISSUE TITLE
The *open* state of the search box doesn't work well when text is zoomed

### ISSUE THREAD

**Issue by krschacht** [leggett/simplify#435]
I think the search input box needs to be wider.

First, let me describe the default behavior:

When the browser font is at its default (zoom set to Cmd+0) and there is information entered into the search box, the text is visible, but the search box is not very wide. When you click to focus inside the search box it expands into a very nice size. I would like to recommend that the *normal* state of the textbox is this expanded size. To put that another way, let's not have a smaller textbox when it's un-focused and a wider textbox when it's focused. Part of the reason I recommend this change is that for people who want to minimize the textbox, there is already a setting that enables you to have it collapsed when not in use.

This brings me to the bug report:

I normally have my browser zoomed two font sizes bigger (Cmd+plus twice). With this setting enabled, none of the textbox contents is visible unless it's focused. So if the above recommended change is made it would solve this issue.

Thanks for considering this!

**Comment by leggett** [comment]
Totally agree -- this is addressed in Simplify v2 (and looks good even if you zoom the font size). You can see a preview here: https://simplify.substack.com/p/search-navigation-and-add-ons-oh

I'm racing to finish and launch v2. Hope to have it out early next year.
