### ISSUE TITLE
Inbox icon overlapping when sidebar is closed

### ISSUE THREAD

**Issue by macintacos** [leggett/simplify#436]
See screenshot:

<img width="216" alt="Inbox (37 : 37) - julian torres@mongodb com - 10gen Mail 2020-12-09 at 10 08 18" src="https://user-images.githubusercontent.com/8128941/101647293-8de8ef80-3a06-11eb-898f-1bb1f844c89b.png">

**Comment by leggett** [comment]
Thanks -- the nav icons should all be hidden when the sidebar is closed. I see Gmail's new nav breaks that. Will get a fix out shortly (in v1.7.21)
