### ISSUE TITLE
Old favicon not applied on Safari

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#440]
Safari doesn't support PNG files as favicons. Detect it is Safari and use an ICO file instead.

**Comment by leggett** [comment]
Ok, it isn't that Safari doesn't support PNG favicons... just that if there is also an ICO favicon specified, it overrules it. Oddly, even setting a ICO favicon doesn't appear to be working so this feature may just not work on Safari. ¯\_(ツ)_/¯

**Comment by seattleowl** [comment]
You could remove the favicon using js, or replace the `href`.

Example:
```javascript
const favicon = document.querySelector("link[rel=icon]");
favicon.href = "path/to/old/favicon.png";
```

**Comment by leggett** [comment]
I replace the href and that doesn't work on Safari for some reason.

But I haven't tried removing the <link> element all together and adding a new one. Will try.

**Comment by leggett** [comment]
Ok, I tried removing and adding it back and I tried injecting a base64 encoded image -- neither changed the favicon for Safari. So I'm hiding the option for Safari.
