### ISSUE TITLE
compose, cannot scroll down to additional aliases

### ISSUE THREAD

**Issue by andymand** [leggett/simplify#442]
I might be exception with a bunch of aliases (and I didn't see this mentioned elsewhere), but I can't scroll past the one that's at the bottom of the screen:

Thanks!

**Comment by leggett** [comment]
Thanks Andy. I'll set a max-height on this so it scrolls.

I deleted your screen shot so your email addresses don't stay public.

**Comment by andymand** [comment]
Thanks for both, Michael!

**Comment by leggett** [comment]
Fix for this coming in v2.1.16. Let me know if you still see it after that update.
