### ISSUE TITLE
add action buttons to bottom of body?

### ISSUE THREAD

**Issue by andymand** [leggett/simplify#444]
When I click on a message summary (is that the right term?) and mouse-scrollwheel scroll down through the body, when I want to delete that message after reading it (which is the case about 99% of the time), I have to mouse up, left to the nearest Delete icon or up, right to the next-nearest one:

![image](https://user-images.githubusercontent.com/51393001/102695038-eaac8d00-41f2-11eb-9eb3-4d05edcabe2c.png)

I might be the lone oddball here (and I think I use a "horizontal layout", yes?  so maybe even a more-minor minority?!), but what do you and others think about adding a row of action buttons (I think that's what they're called) at the bottom of the message body, perhaps next to the Reply All, Reply, Forward buttons?

I'm aware that there are keyboard shortcuts for deleting messages, but when chewing through my inbox, I prefer to mouse as much as I can vs. mouse + keyboard.

Thank you all for any consideration/discussion about this idea!

**Comment by leggett** [comment]
I don't think this would be easy or really a good experience. I think your best bet is keyboard shortcuts. 

I do have plans to make an action menu (one keyboard shortcut that shows you all actions along with their keyboard shortcut and let's you just type what you want to do).

**Comment by leggett** [comment]
The next release of Simplify adds a setting that lets you use the Backspace key to delete messages. You don't even have to have the Gmail keyboard shortcuts enabled.

**Comment by andymand** [comment]
Nice, thanks, Michael!  (At work, I am forced to use Outlook -- in which I use the Delete key to delete messages -- so I'm hopeful that I can mentally switch, depending on "where" I am!)

**Comment by leggett** [comment]
That might be the same key... Backspace is the big on that every keyboard has and deletes the last letter typed. Delete is small key on some keyboards that deletes the letter in front of the carot.

**Comment by leggett** [comment]
Actually, I see no reason not to support both keys! Will add.
