### ISSUE TITLE
Cannot navigate label pages with Simplify activated

### ISSUE THREAD

**Issue by a2brute** [leggett/simplify#446]
When I view a label with more than 100 items, I can only see the first 100 items.  After I deactivate Simplify I can navigate to any page.  When I then reactivate Simplify I can only see the 100 items on that "current page".  With Simplify activated there are no label page navigation controls, unless I am just missing them.

**Comment by leggett** [comment]
Thanks for the report. 

They should be in the top right. Can you send a screenshot (here or to hi@simpl.fyi)?

**Comment by a2brute** [comment]
The navigation buttons *are* there in the upper right, and work.  I had no
idea they were there.

Thank you for the education - this ticket may be closed.

Karl

**Comment by leggett** [comment]
In some setups / screen sizes, they are easily to miss sadly. If you think this is such a case, I'd love to see a screenshot. Can be of your spam folder and emailed is fine (to hi@simpl.fyi)

**Comment by a2brute** [comment]
[image: image.png]
