### ISSUE TITLE
Feedback: Esc to close the Alt + i "Simplify details" tooltip window

### ISSUE THREAD

**Issue by group7access** [leggett/simplify#447]
When I opened your latest email about 2.1.16 coming out, I saw the note about **Alt  + i** (using lower case as due to the font, I didn't know if it was "i" or "L"). When the tooltip popup thingy opened, I instinctively pressed Esc to close it, but instead the email closed/I went back to my Inbox. However, I may just be wrong about this :)

**Comment by leggett** [comment]
Interesting... I might be able to close Simplify dialogs before I close the message. I'll see how easy it would be. Nice catch.

**Comment by leggett** [comment]
I added this in 2.1.22
