### ISSUE TITLE
Feedback: background is not consistent when switching between tabs

### ISSUE THREAD

**Issue by bmiselis** [leggett/simplify#448]
With the default Simplify settings, the `Primary` tab's background is white, as expected. The same applies to `Forums`. However, I've noticed it strangely becomes a kind of mountain for the remaining three categories: `Social`, `Promotions`, and `Updates`. Maybe there's a hard-coded background for these categories somewhere? I'm not sure, but I guess it's not expected behavior.

**Comment by leggett** [comment]
It is expected... It is the zero-inbox reward when you don't have a theme. BUT you are not the first to be confused instead of delighted by this. 

I'm working on a graphic I can put in the center of the screen instead of an entire background.

For now, you can disable it under Simplify Options.

**Comment by bmiselis** [comment]
Ahh, okay, thanks for the clarification 😊 well done Michael!
