### ISSUE TITLE
Offline icon is not correctly placed in message view

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#450]
The offline button is in a different place in the DOM between list view and message view. The CSS is only correct for list view.

**Comment by citydelver** [comment]
I don't know if this is the same, but the offline sync and the help buttons overlap:

![image](https://user-images.githubusercontent.com/1512515/106255911-64c03080-61f9-11eb-9c41-b865b0d5e6b2.png)

**Comment by leggett** [comment]
Thanks for the report. I'll look into this.

**Comment by leggett** [comment]
Have a fix for this going out with the big v2 launch. It turned out to be caused by a different state of offline that changes the selector I was using.
