### ISSUE TITLE
[Safari] "Hide unread count in nav" is not working

### ISSUE THREAD

**Issue by benoitgrelard** [leggett/simplify#453]
The counts do get hidden when you're looking at a message with the nav open (faded) but they don't hide otherwise when looking at the list.

**Comment by leggett** [comment]
Safari has a bug in browser.storage.local that requires you to reload Gmail after changing any Simplify options. Is that the problem? Does a refresh fix it?

**Comment by benoitgrelard** [comment]
No it's not, I have refreshed everytime I make a change.

**Comment by joebGer19** [comment]
Same here with Chrome beta 88.0.4324.47. Seems not only related to Safari?

**Comment by leggett** [comment]
Not related to Safari -- bug in parsing settings. Have a fix checked in for v2.1.17 -- will go out this week. Thanks for the report!
