### ISSUE TITLE
Empty spam folder messages are misaligned

### ISSUE THREAD

**Issue by dougwaldron** [leggett/simplify#456]
<img width="1190" alt="Screen Shot of empty spam folder" src="https://user-images.githubusercontent.com/737326/103839299-1639cf00-505d-11eb-9bd7-11594fdcb71f.png">

**Comment by dougwaldron** [comment]
I meant to mention: issue exists in Safari and Edge on Mac for me.

**Comment by leggett** [comment]
Thanks for the report. I've tried to duplicate this and am unable. 

Can you use Option+I / Alt+I to get your Simplify configuration and paste here?

**Comment by dougwaldron** [comment]
Simplify v.2.1.16

Configuration:
simplify highDensity ca3 caI caL cfC cfI cfO cfQ cfR cfU composeActions dateGroup bgDefault invertAddons minimizeChat aAX chatOff meetOff mediumTheme inList inLabel hPane

More info: I get the same issue using Edge on Windows. Also, it occurs whether or not there is spam in the mailbox: 

![image](https://user-images.githubusercontent.com/737326/103942092-da0a7b00-50fd-11eb-8382-e384dbe5b35d.png)

This full width screenshot seems to confirm it's the top message that is misaligned:
![image](https://user-images.githubusercontent.com/737326/103942335-3a99b800-50fe-11eb-860c-154fe8dc2137.png)

**Comment by leggett** [comment]
This got fixed at some point.
