### ISSUE TITLE
Disable Tracker Protection?

### ISSUE THREAD

**Issue by ymolodtsov** [leggett/simplify#457]
It seems there's no option to stop Simplify v2 from blocking email trackers since the last updates. Personally, I don't have an issue with them and would love that functionality to be optional.

Thank you for thinking about privacy though!

**Comment by leggett** [comment]
It is not an option... but it would be easy to make it one. I would have it on by default for sure. Does having them blocked break your experience in any way?

**Comment by ymolodtsov** [comment]
I personally don't have an issue with them and always thought that it's quite helpful, you know when your teammates or partners have missed a message or actually read it and might be thinking about it. I'd want to give them the same privilege for me: they can see the status of the messages they sent to me in Telegram or Slack.

**Comment by jenllip** [comment]
Seconded. I also do not mind this tracking and have found the "hey, we noticed you haven't opened our last few emails" messages helpful at times. If tracking is disabled, I might miss out on email-open-based alerts from some companies.

**Comment by leggett** [comment]
I've decided not to add this option for now. I don't want SImplify users getting badgered to disable tracking (probably unlikely). I'll revisit after I launch subscriptions.

**Comment by marcavila** [comment]
I would actually want to block tracking since I use a different extension to turn this on. I would welcome an option to toggle it.

**Comment by leggett** [comment]
@marcavila What other extension do you use? I've looked at all the extensions I could find that block trackers, and at over 200 trackers, I am confident that I block way more than all the others (I couldn't find one that blocked more than 54). I even open sourced this part of Simplify and then reached out to most of the other extensions to share my list of trackers so they could catch up... but last I checked, none of them had updated anything.

Compare [Simplify](https://github.com/leggett/simplify-trackers/blob/main/js/simplify-tracker-blocklist.js) vs [Ugly Email](https://github.com/OneClickLab/ugly-email-trackers/blob/master/list.txt). [Pixel Blocker](https://chrome.google.com/webstore/detail/pixelblock/jmpmfcjnflbcoidlgapblgpgbilinlem?hl=en) hasn't been updated in over 2 years and Trocker only has about 25 trackers that they explicitly block and relies on a complex process where they first block ALL images, then check the size of every image and allow any that are stated to be larger than 0x0 or 1x1 to be loaded. They still have an [open issue](https://github.com/trockerapp/trocker/issues/11) to add my list of trackers. This process won't be possible soon as the browsers are moving to a less permissive API for blocking traffic. Even hey.com only [blocks about 50 trackers](https://www.hey.com/spy-trackers/).

**Comment by marcavila** [comment]
I have used the one from CloudHQ here: https://www.email-tracking-blocker.com/ Would welcome using yours instead to eliminate another Chrome extension.

**Comment by leggett** [comment]
I have looked at that one too. They block ~120 trackers. I will look it over again to make sure they don't block any that I don't already block.

**Comment by leggett** [comment]
They don't block anything meaningful that I don't already block. 

And beyond blocking more trackers, it looks like there are several instances where I block the platform and they block an instance. One example, they block `intel.com/e/footerimages/footerimage1` -- but that is actually an Oracle service that Intel is using / hosting. I block anyone using that service as it always seems to contain `*/e/footerimages/footerimage1`.

**Comment by leggett** [comment]
Yikes, and there are places where I think they are over aggressive. They block any image with `track`, `/o/`, `open`, or `followup` in the url. Those could be legit images.

**Comment by marcavila** [comment]
Thanks. Do you intend to keep the Tracker Blocking? I wasn't sure if you said you were removing the tracking blocking or the option to disable it. I definitely would prefer to use your tracker blocking.

**Comment by leggett** [comment]
I am not removing it. So if you are using Simplify, you can uninstall the other tracker blocker.

I do not intend to add an option to disable it... mostly because to do so, I would have to make the feature an opt-in feature instead of opt-out.

And just in case you haven't gotten the update yet (it is rolling out this week), Simplify is no longer a free product (just in case you don't plan to sign up). More details at the bottom of [simpl.fyi/plans](https://simpl.fyi/plans)
