### ISSUE TITLE
Add-on popup doesn't show all add-ons 

### ISSUE THREAD

**Issue by citydelver** [leggett/simplify#459]
Hello and, first of all, thank you for the great work!

The add-on popup is not showing all sidebar add-ons, neither all the default/built-in ones (as there is now a "contacts" add-on) nor any third-party one. :-(

**Comment by leggett** [comment]
Hmm, I'm not seeing that problem. Can you send a screenshot of your whole window (can be in your spam folder or an empty label) either here or to me at hi@simpl.fyi?

**Comment by leggett** [comment]
It might be a simple hard refresh (hold down the shift button when you click to refresh the whole window) fixes it. Simplify is supposed to count the add-ons and make space for them all.

**Comment by citydelver** [comment]
Hello. I tried hard refreshing, and even disabling and re-enabling Simplify, but nothing changed:
![Screenshot_2021-01-17 Gmail add-ons with Simplify disabled](https://user-images.githubusercontent.com/1512515/104887511-25b4f400-594a-11eb-93c7-e81f6be04afa.png) ![Screenshot_2021-01-18 Gmail add-ons with Simplify enabled](https://user-images.githubusercontent.com/1512515/104887515-277eb780-594a-11eb-874e-99e6f56e1d35.png)

**Comment by citydelver** [comment]
Sorry, you mentioned a whole-window screenshot. Here it is:
![Screenshot_2021-01-18 Gmail add-ons with Simplify enabled full window](https://user-images.githubusercontent.com/1512515/104891655-015c1600-5950-11eb-8c69-0834eb7a06ab.png)

**Comment by citydelver** [comment]
Hello. An update: when the split pane icon is enabled (even if the pane splitting itself is disabled) all add-on icons load properly. Maybe there's a connection there. Just found that out by chance.

**Comment by leggett** [comment]
Thanks for all the screenshots. Very helpful.

I have an idea of what the problem is. And I think I already fixed it in Simplify v2 which is set to launch soon. 

Would you be up for joining the v2 beta to see if it is fixed for you? If so, email me at hi@simpl.fyi

**Comment by leggett** [comment]
This is no longer an issue in v2.
