### ISSUE TITLE
Settings (gear/cog) icon obscured in delegated gmail

### ISSUE THREAD

**Issue by rcdailey** [leggett/simplify#46]
Similar to #21, but only occurs when opening a delegated gmail account:

![image](https://user-images.githubusercontent.com/1768054/55884129-21508a00-5b6d-11e9-8f23-e9fdda247e0c.png)

**Comment by leggett** [comment]
Closing this and merging with issues 21.

**Comment by rcdailey** [comment]
@leggett I specifically opened a new issue because the fix for #21 did not fix this issue. Since you closed this issue, what is the plan to resolve the delegated account? As of today it is still broken, but differently:

![image](https://user-images.githubusercontent.com/1768054/55998703-040edf00-5c85-11e9-8cab-53647ba4dd54.png)

**Comment by leggett** [comment]
I said I was merging it so I could deal with it all at once (handling delegated accounts)

**Comment by rcdailey** [comment]
Oh sorry, I missed that detail apparently. Thanks for clarifying.
