### ISSUE TITLE
Date label for two months ago(?) "undefined"

### ISSUE THREAD

**Issue by freste** [leggett/simplify#462]
Labels display as:

- YESTERDAY
- THIS MONTH
- LAST MONTH
- undefined
- EARLIER

This is 2.1.18, Chrome on OS X

![simplify](https://user-images.githubusercontent.com/2577130/105536952-2d182c80-5cbf-11eb-9be6-4033746fe807.png)

**Comment by freste** [comment]
Ah, just saw the previous issue; if I understand it was thought to be fixed in 2.1.17?
Here's the relevant output from the js you requested in that issue (I omitted a lot of older msgs.)

document.querySelectorAll("div[role='main'] .ae4:not([style*='none']) .Cp:not(.adverts) tr.zA").forEach((thread, i) => {
  let date = thread.querySelector(".xW > span")?.title;
  let dateAttr = thread.getAttribute("date");
  console.log(i, date, dateAttr);
});

VM124153:4 0 "Fri, Jan 22, 2021, 2:21 PM" "today"
VM124153:4 1 "Thu, Jan 21, 2021, 3:22 PM" "yesterday"
VM124153:4 2 "Thu, Jan 14, 2021, 4:56 PM" "month0"
VM124153:4 3 "Thu, Jan 14, 2021, 11:06 AM" "month0"
VM124153:4 4 "Tue, Jan 12, 2021, 6:31 PM" "month0"
VM124153:4 5 "Mon, Jan 11, 2021, 2:57 PM" "month0"
VM124153:4 6 "Mon, Jan 11, 2021, 2:46 PM" "month0"
VM124153:4 7 "Mon, Jan 11, 2021, 11:51 AM" "month0"
VM124153:4 8 "Wed, Dec 23, 2020, 3:50 PM" "month1"
VM124153:4 9 "Tue, Dec 22, 2020, 4:17 PM" "month1"
VM124153:4 10 "Thu, Nov 12, 2020, 2:10 PM" "month2"
VM124153:4 11 "Tue, Nov 10, 2020, 12:21 PM" "month2"
VM124153:4 12 "Fri, Oct 9, 2020, 9:41 AM" "earlier"
VM124153:4 13 "Mon, Sep 28, 2020, 7:54 PM" "earlier"

**Comment by leggett** [comment]
Thanks for flagging. Super strange. This is fixed for me... but something is clearly wrong still... can you try a hard refresh (hold down the shift key while pressing the refresh button... or ⌘⇧R)

**Comment by freste** [comment]
Certainly - looks like that fixed it :-)

(I had checked the version via right-click on "S" plugin icon ---> Options; it showed 2.1.18. Still does of course.)

PS I really do like those date labels (I keep a lot of old stuff hanging around.)

**Comment by leggett** [comment]
Great! In case anyone else runs into this, the problem was in a different place. 

If you are comfortable running some code in the developer console, this is what I'd need to see:
```
let css = get("style#simplifyCss").sheet.cssRules;
for (i=0; i<css.length; i++) { console.log(css[i].cssText) }
```
