### ISSUE TITLE
Old Gmail favicon should be off by default

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#463]
At least for me the "Use old Gmail favicon" preference is enabled by default.

I think it should be off by default. Most users won't care, so it's better (and more consistent) to go with Google's branding.

I also happen to like the new favicon :-)

**Comment by leggett** [comment]
You are correct -- the setting to use the old icon is enabled by default for everyone right now. 

I don't mind the new branding but think it is pretty bad as a favicon. But you might be right that it is better to have it off by default. I'll think about it. Thanks for the note.

**Comment by leggett** [comment]
I thought on this some and even [took a poll](https://twitter.com/leggett/status/1354608915015553026) and decided to stick with the old favicon as the default. I think it looks better and makes it easier to spot the Gmail tab when your eyes scan your browser tabs.

**Comment by nhojb** [comment]
I saw the poll and voted. Seems I'm in the minority...  Thanks for looking into this though 😄
