### ISSUE TITLE
Option to change favicon not working

### ISSUE THREAD

**Issue by CarlosRebolledo** [leggett/simplify#464]
Estimado 

La opción de utilizar favicon de Gmail antiguo lo tengo activado pero no funciona.

Adjunto captura y system report

![2021-01-28 Desktop-screenshot](https://user-images.githubusercontent.com/19577294/106154881-d8612f80-615e-11eb-8aff-7f542237200c.png)

Simplify v.2.1.20

Configuration:
simplify lowDensity ca3 caI caL cfC cfI cfO cfQ cfR cfU composeActions composeFormat debug hideSignatures bgOff minimizeChat showChat aAX newUI lightTheme defaultTheme nPane dateGroup inMsg appMenuOpen

Browser:
:5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36; 1536px by 824px (100% zoom)

**Comment by leggett** [comment]
Try a hard refresh (Ctrl+Shift+R)... sometimes it gets cached and doesn't apply.

**Comment by CarlosRebolledo** [comment]
Lo intenté y no funciona.

**Comment by leggett** [comment]
WAIT! I see the problem. I can not change the favicon if you have the unread favicon advanced feature turned on.

Ajustes → Avanzadas → Icono de mensaje sin leer

**Comment by CarlosRebolledo** [comment]
Yes!!!! 👍✨

It works and you can see the old Gmail favicon

Excellent !!!

Thank you very much
