### ISSUE TITLE
Date grouping not working in all languages

### ISSUE THREAD

**Issue by CarlosRebolledo** [leggett/simplify#465]
Estimado,

Desconozco la razón, pero la agrupación de correos por fecha no funciona. 

Desactive extensiones de terceros para ver si era el problema y sigue igual.

Adjunto captura y report 

![2021-01-28 Desktop-screenshot](https://user-images.githubusercontent.com/19577294/106155314-4ad20f80-615f-11eb-85f2-41c33d652cc3.png)

Simplify v.2.1.20

Configuration:
simplify lowDensity ca3 caI caL cfC cfI cfO cfQ cfR cfU composeActions composeFormat debug hideSignatures bgOff minimizeChat showChat aAX newUI lightTheme defaultTheme nPane dateGroup inMsg appMenuOpen

Browser:
:5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36; 1536px by 824px (100% zoom)

**Comment by leggett** [comment]
Looks like it is broken for Spanish. Thanks for flagging this. I'll see what I can do.

**Comment by CarlosRebolledo** [comment]
Ok. Gracias 👍

**Comment by leggett** [comment]
Ok, I have this working in a random set of languages now (Spanish, Dutch, Italian, French, Portuguese, Chinese, and Korean). Will ship with 2.1.21.

I'll close this when I support all the languages Gmail supports... but it will take a while to go through each one (I have to change Gmail's interface language and then run a script I wrote across a sample of emails to see how Gmail writes the date).

**Comment by leggett** [comment]
The other thing I should do at some point is translate the strings used for labeling the different sections:

- Yesterday
- This week
- This month
- Last month
- Name of 2 months ago (will probably just skip this one in non-english)
- Earlier

**Comment by CarlosRebolledo** [comment]
Gracias Michel 

Abrazos y éxito

**Comment by leggett** [comment]
Ok, I added more languages. Calling this done for now. I haven't translated the other strings I use (will create a separate ticket for internationalization in general)

- Chinese (China)
- Chinese (Hong Kong)
- Chinese (Taiwan)
- Czech
- Danish
- Dutch
- English (United Kingdom)
- English (United States)
- Finnish
- French
- French (Canadian)
- German
- Greek
- Hebrew
- Hungarian
- Indonesian
- Italian
- Japanese
- Korean
- Norwegian
- Polish
- Portuguese (Brazil)
- Portuguese (Portugal)
- Russian
- Spanish
- Spanish (Latin America)
- Swedish
- Turkish
- Ukrainian

**Comment by leggett** [comment]
P.S. Those languages are all the ones used by current users on Chrome according to my Chrome Web Store Dashboard.

**Comment by CarlosRebolledo** [comment]
Big Michael !!!

Excellent and again congratulations

I hope I can load my payment soon

A hug from Chile
