### ISSUE TITLE
Hiding Inbox tab icons causes tab labels to left-align.

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#466]
v2.1.21
Chrome 88.0.4324.96

See attached screenshot. Disabling the "Hide inbox tab icons" preference fixes alignment.

I've tried refreshing the browser tab and restarting Chrome.

<img width="1217" alt="Screenshot 2021-02-01 at 11 21 37" src="https://user-images.githubusercontent.com/312540/106452932-78c99380-6480-11eb-958c-e7524b36b17c.png">

**Comment by leggett** [comment]
This is working as intended.

**Comment by leggett** [comment]
Turns out this doesn't quite work well as the drag-n-drop targets don't move too. So I am letting them spread out.
