### ISSUE TITLE
Keyboard shortcut preview information density is too low.

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#467]
Simplify v2.1.21
Chrome 88.0.4324.96

In the default Gmail I can view all keyboards shortcuts at a glance - they are displayed within the browser window.

The new Simplify keyboard shortcut preview information density is much lower, so I have to scroll (2-3x window height) to view all shortcuts. I find this much slower and less helpful.

**Comment by leggett** [comment]
You can see ALL the shortcuts? Simplify definitely makes them less dense and adds shortcuts at the top. But Gmail's list is quite long and scrolls too. I guess I can see them all on an 30" external display.

I'll consider reducing the density some but I think Gmail's screen is a really hard to read.

**Comment by nhojb** [comment]
You're right: I have to scroll to see the "Application" shortcuts in default Gmail. This is on a 27" monitor running macOS.

I was going by my (unreliable) memory :-(

**Comment by leggett** [comment]
No worries... it is still going to be way less dense. But I went ahead and made it as dense as I'm comfortable making it without sacrificing readability. This is subjective. You may not like it still. But I appreciate the nudge.

<img width="1680" alt="Screen Shot 2021-02-01 at 9 32 19 AM" src="https://user-images.githubusercontent.com/8763662/106495533-a9093600-6470-11eb-92ff-1f6032e5d10e.png">
