### ISSUE TITLE
Group by date no longer works

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#468]
Simplify v2.1.21
Chrome 88.0.4324.96

Group by date no longer seems to work (default Inbox view).

I've tried refreshing tab, restarting Chrome, toggling the preference on and off etc.

**Comment by leggett** [comment]
I can't reproduce this issue. Can you try a hard refresh (⌘ ⇧ R)

**Comment by leggett** [comment]
Is your interface language something other than english?

**Comment by leggett** [comment]
Oh snap... UK english also breaks it.

**Comment by nhojb** [comment]
Yes, UK english it is.

**Comment by leggett** [comment]
Fix landing shortly.
