### ISSUE TITLE
Simplify version & info keyboard shortcut no longer works

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#469]
Simplify v2.1.21
Chrome 88.0.4324.96

Opt+I does nothing. All other Simplify shortcuts appear to work for me.

**Comment by nhojb** [comment]
JS exception:

```
chrome-extension://kgmfphgflhecbmihdpgamkkgienkllif/js/alerts.js:23 Uncaught TypeError: Cannot set property 'textContent' of null
    at Object.show (chrome-extension://kgmfphgflhecbmihdpgamkkgienkllif/js/alerts.js:23)
    at showSimplifyDetails (chrome-extension://kgmfphgflhecbmihdpgamkkgienkllif/js/util.js:74)
    at onKeydown (chrome-extension://kgmfphgflhecbmihdpgamkkgienkllif/js/keyboard.js:297)
```

**Comment by leggett** [comment]
Interesting. I assume you're on a mac (as you're using the Option key)?

**Comment by nhojb** [comment]
Yes. Big Sur 11.1

**Comment by leggett** [comment]
Ok, sounds like the alert element (which I add on Gmail loading) somehow got thrown out? Odd. A hard refresh might fix it. 

But to be safe, I'll make sure it is still there when I show an alert.

**Comment by nhojb** [comment]
I did do a hard refresh and then restarted the browser, didn't fix it. Strange, it was fine before 2.1.21
