### ISSUE TITLE
Search overlaps with things when using delegated account

### ISSUE THREAD

**Issue by rcdailey** [leggett/simplify#47]
When opening another delegated gmail account inbox, the email address of that account is shown in the top right corner. This overlaps the Search box, as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/1768054/55884332-8310f400-5b6d-11e9-8970-eb4ccabd3b73.png)

**Comment by leggett** [comment]
There are also issues with the settings cog

**Comment by aravindhp** [comment]
The older and search icons also are getting overlapped.
![image](https://user-images.githubusercontent.com/11638995/57240086-b2474380-6ffb-11e9-9cc8-3108cad4133e.png)

**Comment by jaminroe** [comment]
Also when the right side panel is open, it overlaps the Settings cog and also the Prev/Next buttons when searching:
![image](https://user-images.githubusercontent.com/1559447/57331782-6e316d00-70e7-11e9-8b34-122233806bca.png)

**Comment by leggett** [comment]
I just added some fixes for this... both for delegated accounts and for when things overlap at low resolutions with the Add-ons pane turned on. 

It also looks like you have an older version of Simplify as your support button is showing (which it shouldn't be). Can you check that you are running v1.3.0?

**Comment by jaminroe** [comment]
@leggett I just update to v1.3.0 and it's fixed! I had to update my Brave browser since extensions don't auto-update.
