### ISSUE TITLE
When message is selected, message action buttons do not appear.

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#470]
Simplify v2.1.21
Chrome 88.0.4324.96

Selecting one or more messages should cause the action buttons to appear in the top toolbar. They no longer appear.

Hovering the mouse over the toolbar area causes the buttons to appear, however they are overlaid on top of the search field.

See attached screenshots.

<img width="1179" alt="Message Selected" src="https://user-images.githubusercontent.com/312540/106456331-45d5ce80-6485-11eb-88d0-f55bbd32d459.png">
<img width="1159" alt="Message Selected Hover" src="https://user-images.githubusercontent.com/312540/106456332-466e6500-6485-11eb-94b8-15bfcbd2b6ea.png">

**Comment by leggett** [comment]
Fix going out now
