### ISSUE TITLE
New composer not detected

### ISSUE THREAD

**Issue by CarlosRebolledo** [leggett/simplify#471]
Hola Michael

Cuando corto una frase de un texto de correo abierto en modo redacción y lo pego en otro sector del párrafo queda en rojo.

Se inserta captura de pantalla:

![Captura de Pantalla - Cortar y pegar en email](https://user-images.githubusercontent.com/19577294/106470916-d8736f00-647f-11eb-8189-d1072c5a6328.png)

Traducción al Inglés:

Hello Michael

When I cut a sentence from an open mail text in composition mode and paste it in another sector of the paragraph, it turns red.

**Comment by leggett** [comment]
Thanks for the report! 

**In english**
Can you share more about how you started composing the new message? Was this an inline reply or a new message? Was it in the small mole in the bottom corner or was it a full-screen composer?

**En español**
¿Puede compartir más sobre cómo comenzó a redactar el nuevo mensaje? ¿Fue una respuesta en línea o un mensaje nuevo? ¿Estaba en el pequeño lunar en la esquina inferior o era un compositor de pantalla completa?

**Comment by leggett** [comment]
Ok, I added some additional checks. 

Let me know if you see it again.
