### ISSUE TITLE
Pipe in keyboard shortcuts is yellow.

### ISSUE THREAD

**Issue by seattleowl** [leggett/simplify#472]
Thanks for v2.1.21! I found that in the keyboard shortcuts menu, the pipe character at the top is yellow.

**Screenshots**:

![Screen Shot 2021-02-01 at 7 03 54 AM](https://user-images.githubusercontent.com/32573897/106476450-f038fc00-645b-11eb-9da7-6230be6250e7.png)
![Screen Shot 2021-02-01 at 7 03 58 AM](https://user-images.githubusercontent.com/32573897/106476451-f0d19280-645b-11eb-93d1-c4a5510c8eee.png)

Fix (`color: white;` to `.wd`):

![Screen Shot 2021-02-01 at 7 03 31 AM](https://user-images.githubusercontent.com/32573897/106476447-efa06580-645b-11eb-954d-6065dba04d26.png)

**Comment by leggett** [comment]
Good catch!
