### ISSUE TITLE
Purchases, Finance, Trips inbox tabs don't appear even when turned on in Simplify preferences

### ISSUE THREAD

**Issue by astanush** [leggett/simplify#473]
What I did:
Simplify preferences → Add Purchases, Finance, Trips categories → Enabled

What happens:
In my Inbox, I only see tabs for the Primary, Promotions and Updates.

Is there some other setting to change in either Gmail or Simplify?

Version: Simplify beta 2.1.21

**Comment by astanush** [comment]
I can also confirm that I have messages that are in the "Purchases" category and not archived, which should make them eligible to display in the inbox tab.

**Comment by leggett** [comment]
Thanks for the report. They are added under "Categories" in the left nav -- not as inbox tabs. Please reopen this if you don't see them in the nav.
