### ISSUE TITLE
Black background to text in Gmail, after copy-and-pasting in Simplify

### ISSUE THREAD

**Issue by group7access** [leggett/simplify#475]
Perhaps irrelevant, but I happened to notice it by chance while moving between laptop and phone. Everything still works - just mentioning it because it is weird, like me.
![image](https://user-images.githubusercontent.com/70614907/106540727-1dba8f80-64c6-11eb-8264-e54764e489ff.png)

**Comment by leggett** [comment]
Whoa... Super interesting. I know exactly what is going on and how to fix it (will go out in the next release).

Thanks for the report!
