### ISSUE TITLE
Mountain image in Zero Inbox

### ISSUE THREAD

**Issue by a2brute** [leggett/simplify#476]
Even though I have my theme set to default, when I go to Zero Inbox there is a mountain with a dark base that obscures my labels list.  I can turn Simplify on and off and the problem appears and disappears respectively.

**Comment by leggett** [comment]
I changed this but didn't overwrite everyone's settings. If you go into Simplify settings and set the background to the default, it will use a small centered illustration instead of the full screen background (this is the new default too).

**Comment by a2brute** [comment]
It is already set to the default, in Simplify and in GMail, but the
mountain takes up the whole width.

**Comment by leggett** [comment]
Oh, then that would be a bug. Can you send me a system report (⌥I or Alt+I on Windows)?

And to be sure, your Simplify Settings look like this:
<img width="740" alt="Screen Shot 2021-02-01 at 6 14 28 PM" src="https://user-images.githubusercontent.com/8763662/106542865-78012380-64b9-11eb-8aa6-95a0486b1af2.png">

**Comment by a2brute** [comment]
Hmmm.  I think I have the older version -- your screenshot has the newer
logo.

**Comment by leggett** [comment]
That happens sometimes. You can force an update by removing the extension and adding it back. Go to [beta.simpl.fyi](https://beta.simpl.fyi) and click to remove the extension -- then go there again and add it. Please re-open this issue if the problem persists.
