### ISSUE TITLE
CTRL A no funciona 

### ISSUE THREAD

**Issue by CarlosRebolledo** [leggett/simplify#477]
Hola Michael

El atajo de teclado CTRL + A no funciona. No selecciona ningún correo

Simplify v.2.1.22

Configuration:
simplify lowDensity ca4 caD caI caL cfC cfF cfI cfO cfQ cfR cfS cfU composeActions composeFormat dateGroup debug hideSignatures hideTabIcons bgDefault minimizeChat showChat aAX newUI lightTheme defaultTheme hideSelectRefresh inInbox inList nPane appMenuOpen

Browser:
:5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36; 1536px by 824px (100% zoom)

Muchas gracias por tú gran trabajo

**Comment by leggett** [comment]
Yikes! Big miss on my part. I thought event.metaKey mapped to the Ctrl key on Windows but it does not. Fix going out now. Let me know if it works in v2.1.23

**Comment by CarlosRebolledo** [comment]
Now it works perfect

Thank you Michael
