### ISSUE TITLE
Text remains highlighted in red

### ISSUE THREAD

**Issue by thesarahs** [leggett/simplify#478]
You asked us to report anytime text remained highlighted in red, so here I am! I am running version 2.1.23 of Simplify Gmail v2 Beta.

I am a teacher using Google Classroom. Using the People page, I selected "Email parents" so a separate tab opened with a new composition. I pasted in my text, which included a bulleted list originally created in Gmail. I went to delete one of the items in that list and the remaining item suddenly turned red. 

![scrn](https://user-images.githubusercontent.com/78432220/106624617-da066b00-6543-11eb-8516-46406b774bdd.JPG)

**Comment by leggett** [comment]
Thank you so much for the report. The path to how you started your email is SUPER helpful.

**Comment by thesarahs** [comment]
I figured! Just a heads up, when I went to create the next email (same path), I copied the text from this one (from my Sent email box) and the ENTIRE pasted text immediately highlighted red. I tried pasting that same text into a Reply box of a random email in by personal inbox and the highlighting didn't happen. There were small changes to spacing in the formatting, but I didn't care - copied that text back into the tab I was working on and all was well. Let me know if any of that needs clarification!

**Comment by leggett** [comment]
Just in case this is preventing you from getting work done... you can turn off the red highlighting. 

The red highlighting is so I know when the font-size is being pasted in with the text (something I can't prevent but I am trying to remove). You can turn off debug mode in Simplify options (all the way at the bottom) and you won't see the red highlighting any more. Your email will go out with a slightly larger font size still. 

I've got to get my kids to school but I will fix this case as soon as I'm back.

**Comment by leggett** [comment]
Ok, I have a fix coming in. Will push in the next few hours. Thank you again for the report!
