### ISSUE TITLE
+ is not centered on the Compose button 

### ISSUE THREAD

**Issue by ericherve** [leggett/simplify#480]
The + is not centered on the Compose button

On Chrome Version 88.0.4324.96 (Official Build) (x86_64) / MacBook 13'''

What other details should I bring?

<img width="994" alt="Screen Shot 2021-02-04 at 20 54 23" src="https://user-images.githubusercontent.com/7199370/106978902-38da0900-672b-11eb-8870-80d42266a2c8.png">

**Comment by leggett** [comment]
Is this on Simplify v1 or v2?

**Comment by leggett** [comment]
Simplify v2 hasn't launched... so unless you are a trusted tester, this should be Simplify v1 which will be replaced in 24 hours with Simplify v2 (which fixes this).

**Comment by ericherve** [comment]
Simplify Gmail v2 Beta
2.1.24

**Comment by leggett** [comment]
Got it. In that case, can you send a system report (Opt+I) and I'll try to figure out what is going on?

**Comment by ericherve** [comment]
Simplify v.2.1.25
Simplify v.2.1.25

Configuration:
simplify highDensity ca3 caI caL cfC cfI cfO cfQ cfR cfU composeActions dateGroup hideSignatures hideTabIcons bgDefault invertAddons minimizeChat aAX navOpen darkTheme nPane inMsg htmlEmail

Browser:
:5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36; 1920px by 1055px (100% zoom)
Configuration:
simplify highDensity ca3 caI caL cfC cfI cfO cfQ cfR cfU composeActions dateGroup hideSignatures hideTabIcons bgDefault invertAddons minimizeChat aAX navOpen darkTheme nPane inMsg htmlEmail

Browser:
:5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36; 1920px by 1055px (100% zoom)

**Comment by leggett** [comment]
Fix coming in v2.2.2.

**Comment by ericherve** [comment]
Thanks!
*Éric Hervé*
1 514 557 0098 | ericherve@gmail.co <ericherve@gmail.com>m
