### ISSUE TITLE
Group By Date - v2.1.25 Appears Non Functional

### ISSUE THREAD

**Issue by SRB008** [leggett/simplify#481]
I notice that the "Group email by date" options is no longer having an effect.  Previous versions had groups (when turned on), however in 2.1.25 the groups are not being formed (Yesterday, This Week, etc).
(Edit: language = English UK)

**Comment by nhojb** [comment]
Same here. English UK.

**Comment by CarlosRebolledo** [comment]
También en español.

**Comment by SRB008** [comment]
I should had noted that I was set to English UK in my original post

**Comment by leggett** [comment]
What a dumb bug. I've been trying to really fine tune performance and make sure I'm not checking things needlessly and I flipped a check on date grouping. Will work when I launch.
