### ISSUE TITLE
Lost Ability to Group Emails By Date

### ISSUE THREAD

**Issue by BickitySnow** [leggett/simplify#482]
Not sure which version this happened but I lost the ability to group emails by date (TODAY, YESTERDAY, THIS MONTH etc). Am I missing something? 

<img width="1151" alt="Screen Shot 2021-02-05 at 1 49 10 PM" src="https://user-images.githubusercontent.com/59098468/107076468-7a18fa00-67b9-11eb-9cfb-6ef315101cbb.png">

Setting is on:

![image](https://user-images.githubusercontent.com/59098468/107076517-8a30d980-67b9-11eb-83d1-7784cf2b9e95.png)

Any thoughts, Gary

**Comment by leggett** [comment]
Nope -- I broke it on the last update. Fix will go out today.

**Comment by BickitySnow** [comment]
@leggett Thanks for the quick response. Cheers.
