### ISSUE TITLE
Suggestion Bar Width stuck when dragging the separator(to change width) in Vertical Split mode

### ISSUE THREAD

**Issue by iam-Shashank** [leggett/simplify#484]
I use vertical split mode. When changing the width of the split, the suggestion bar (with pill shaped suggestions liike "Any Time" "Has Attachment") on top doesn't resize along with it. Attaching a few images showing the procedure to replicate.

1. Open gmail in vertical split. (everything's fine right now)
![image](https://user-images.githubusercontent.com/34963991/107121089-9353a080-68b6-11eb-9c4c-6d031144d309.png)

2. Now search for any time (for the suggestion bar to pop up) by typing in search bar.
![image](https://user-images.githubusercontent.com/34963991/107121148-ea597580-68b6-11eb-8e7f-2fa5dafabb24.png)

3. I've highlighted the suggestions pill bar with red brackets and arrow. Now, drag the split divider to resize it.  
![image](https://user-images.githubusercontent.com/34963991/107121224-42907780-68b7-11eb-9ad9-8858ef524e41.png)

![image](https://user-images.githubusercontent.com/34963991/107121271-83888c00-68b7-11eb-9e51-a7949d460fde.png)

I've highlighted 2 cases, making width less and more. Orange "?" indicate the problems. I hope I made it clear what the issue is, tried to be as detailed as possible. Let me know if you need more details :)

**Comment by leggett** [comment]
Thanks for such detailed feedback. Keep 'em coming!

AND, I have news for you. ALL of this (and much more) is fixed in Simplify v2 which launches today.
