### ISSUE TITLE
Inbox zero + horizontal preview issues

### ISSUE THREAD

**Issue by macintacos** [leggett/simplify#487]
If you're using the horizontal preview and have an email open, and then you switch to a tab that has no emails, the illustration clashes with the "toolbar" that is typically at the top of the preview. Here's a screenshot:

![image](https://user-images.githubusercontent.com/8128941/107167514-10e6e180-6987-11eb-9677-c1b774ee3318.png)

---
Simplify v.2.2.0 - Configuration: simplify highDensity inInbox inList ca5 caD caE caI caL cfC cfO cfQ cfR cfU composeActions dateGroup hideTabIcons bgDefault invertAddons minimizeChat aAX navOpen darkTheme hPane msgOpen inboxZero quickSettings - Browser: 5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.40 Safari/537.36 - Window: 1308x1400 (101pct zoom) - Language: en

**Comment by leggett** [comment]
Well that's a fun one! Thanks for the report. Will try to fix this in the next release.

**Comment by leggett** [comment]
Fix landing today in v2.2.2
