### ISSUE TITLE
Settings - Check mail from other accounts not available

### ISSUE THREAD

**Issue by bstmedia** [leggett/simplify#488]
There is an option to configure and most importantly "Check mail now" for third party pop3 accounts in classic view.  This option is not available when using the extension.

![image](https://user-images.githubusercontent.com/4271632/107177860-1ff38100-69d3-11eb-88b9-acb64348d4ec.png)

Would be great to expose at least the check mail now button. 

Otherwise GREAT WORK!

**Comment by leggett** [comment]
Thanks for the report. A few quick thoughts...

1. What does it look like with Simplify enabled? These links should still be there in Settings / Accounts. 
2. Clicking the refresh button in Gmail [should also check for mail on these accounts](https://workspaceupdates.googleblog.com/2012/08/three-gmail-labs-graduation-into.html). 
3. I added a keyboard shortcut (⌘R / Ctrl+R) to click on that refresh button when you are in a list view so it should be even easier with Simplify, not harder.

**Comment by leggett** [comment]
P.S. The added keyboard shortcut is in Simplify Gmail v2 which just launched. It isn't live for Firefox or Edge yet though and you may not have gotten the update. If you have v2, you should see the [new logo](https://cdn.substack.com/image/fetch/w_96,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Fa74b1477-df37-417c-99b7-0d1153d7cfda_1024x1024.png) as the extension icon.

**Comment by bstmedia** [comment]
I'm so sorry. We can totally close this. I overlooked the settings that are moved to the left. Its all working !! 

![image](https://user-images.githubusercontent.com/4271632/107242192-04689480-6a2c-11eb-94c9-c0e4e89687ea.png)
