### ISSUE TITLE
Emails breaking because of narrower max-width in conversation view

### ISSUE THREAD

**Issue by poldyaev** [leggett/simplify#489]
Greetings!

Thank you for such a great extension. Please give an opportunity to adjust the width of conversation view. Some emails break at the current block width. In version 1, this problem was not observed.

**Comment by leggett** [comment]
Thanks for the report. 

Can you forward me one of those emails that breaks (to hi@simpl.fyi) or a screenshot of part of it if you don't want to share the email? I did a lot to keep emails from breaking the max-width. I have a collection of emails I use for testing.

**Comment by leggett** [comment]
@poldyaev sent me a screenshot and some more detail. I'm going to remove the max-width on the message in the pop-out so you can stretch any thread as wide as you want. Will be included in v2.2.1.
