### ISSUE TITLE
Hide add-on chooser fab?

### ISSUE THREAD

**Issue by melissachang** [leggett/simplify#49]
I liked how it was hidden, I didn't realize that was a bug. :)

I don't suppose you would be open to hiding it? (Do you use it?)

How about hiding the add-on chooser fab, and having the add-ons appear via speed dial when hovering over main fab?

**Comment by leggett** [comment]
I don't use it personally but supporting the add-ons pane was a top request. So I'd rather it wasn't there either but it also needs to be easy to find for those that do want it. I'll keep thinking on it and if I think of something better, I'll push it to be more hidden when not used.

**Comment by lukasvermeer** [comment]
FTR this was the first thing I changed when I forked this awesome repo. Maybe other people use it, but I found it clutter. 🤷‍♂️

**Comment by leggett** [comment]
I thought on this (maybe show it when you hover over compose for instance) and decided the current solution is the best balance of visibility and accessibility for those that use Add-ons and hiding it for those that don't.
