### ISSUE TITLE
Width of the central pane has shrunk on the new version of simplify

### ISSUE THREAD

**Issue by userbob999** [leggett/simplify#490]
Please describe the issue and the steps to reproduce it.

I cannot show my emails clearly but from this you should be able to see the central pane which hosts the list and preview has shrunk in the new version of simplify (you can see the white border of the top of my email list is very un-wide. Ta

![image](https://user-images.githubusercontent.com/76950643/107202478-280ee900-69f2-11eb-9e41-e47f46f70d5e.png)

---
Simplify v.2.2.0 - Configuration: simplify lightTheme highDensity inList ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup hideTabIcons bgDefault invertAddons minimizeChat js-focus-visible aAX navOpen newUI inInbox hPane msgOpen - Browser: 5.0 (Macintosh Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 - Window: 1920x1080 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Thanks for the report and screenshot (enough to understand your concern). 

You're right: the horizontal split pane was allowed to be the full width of the screen before. In Simplify v2, that setup is no longer a special case (it was hard to support it as a special case). So this is working as intended. I hope the other improvements to this view offset this change but understand if Simplify no longer works for you.

**Comment by userbob999** [comment]
sadly it looks better now with some tweaks to google itself and simplify removed. best of luck with this in the future though :)
