### ISSUE TITLE
Selectet colour and gray bg theme is identical

### ISSUE THREAD

**Issue by thomas-evensen** [leggett/simplify#491]
See screenshot. 

When choosing the grey bg theme, the colour on selected emails is identical with the bc colour. This makes it look strange.

<img width="1282" alt="Screenshot 2021-02-08 at 11 58 13" src="https://user-images.githubusercontent.com/42618969/107210871-05d29680-6a05-11eb-8608-265afb339f03.png">

**Comment by leggett** [comment]
Agree. Thanks for the report!

**Comment by thomas-evensen** [comment]
Additional info: the issue exist only after returning to the list of mails from reading a mail. When using arrow-keys to navigate - the select colour is a darker grey, but when returning back from reading an email; the selected email has the same bg color as the theme grey.

**Comment by thomas-evensen** [comment]
Screen capture of issue:
https://user-images.githubusercontent.com/42618969/107212459-46cbaa80-6a07-11eb-8e6b-8b2e2d664a46.mp4

**Comment by leggett** [comment]
Fix coming in update today
