### ISSUE TITLE
Feedback: New logo uncomfortably similar to PrusaSlicer

### ISSUE THREAD

**Issue by Iodine-** [leggett/simplify#493]
Was a little confused when the PrusaSlicer logo was appearing on an announcement for simplify - took me a minute to realize it wasn't _exactly_ the PrusaSlicer icon, but uncomfortably similar...I suspect you may want to reconsider the branding decision if its not too late!

![Screen Shot 2021-02-08 at 6 14 40 AM](https://user-images.githubusercontent.com/2114576/107231297-f9364a00-69d4-11eb-8954-96399d133efa.png)

**Comment by leggett** [comment]
Yeah, turns out a few companies have a similar half-circles-offset = an S. Thanks for flagging.
