### ISSUE TITLE
Chrome Dev/Canary appears to cascade CSS differently... unclear if bug or impending change

### ISSUE THREAD

**Issue by Xalaxis** [leggett/simplify#494]
Since the v2 update appeared, my inbox design has become incredibly broken, some screenshots below. The onboarding process was also transparent, so I couldn't read any of the introductory text if it was important.

## Broken text spacing and UI elements overlapping

![image](https://user-images.githubusercontent.com/12937964/107240696-1b09ee00-6a22-11eb-8ca5-c6924f4f09cb.png)

## Compose button goes off-screen

![image](https://user-images.githubusercontent.com/12937964/107240710-20673880-6a22-11eb-9f4e-c0b0f1f418f8.png)

## Google logo says "Goo"

![image](https://user-images.githubusercontent.com/12937964/107240738-29580a00-6a22-11eb-82d7-605ba116cf93.png)

Leaves a bit of a bad taste when v1 was working fine 😅, is there a way to revert temporarily?

---
Simplify v.2.2.0 - Configuration: lowDensity inInbox inList ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup hideTabIcons bgDefault invertAddons minimizeChat aAX navOpen newUI mediumTheme simplify nPane - Browser: 5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4408.0 Safari/537.36 - Window: 2560x1400 (100pct zoom) - Language: en-GB

**Comment by Xalaxis** [comment]
I can confirm that the issue is present even after a hard refresh, and in incognito mode with no other extensions enabled.

**Comment by Xalaxis** [comment]
I've also just tested on a separate install of Chrome canary, to rule out something in my user profile. I can confirm the issue is still present there too.

**Comment by leggett** [comment]
Thanks for being so thorough. Can you send me a full screenshot (can be of your spam folder) either here or to hi@simpl.fyi. No one else has reported the kinds of issues you are seeing and it is very concerning.

**Comment by leggett** [comment]
Nevermind. I see this is a bug with Chrome Canary... I'm trying to get to the bottom of it: 
https://twitter.com/leggett/status/1358957033714638851

For now, I will look at adding a warning for anyone using Chrome Canary.

**Comment by Xalaxis** [comment]
Excellent detective work! I look forward to finding out the resolution.

**Comment by Xalaxis** [comment]
Just adding Dev to the title as well so it comes up for anyone else looking

**Comment by leggett** [comment]
Google got back to me -- it is a bug in Chrome. A fix should be landing soon: https://bugs.chromium.org/p/chromium/issues/detail?id=1175506

**Comment by Xalaxis** [comment]
Great! I can confirm the canary warning just came up for me as well :). Thanks for finding the cause of this and working to get it resolved.

**Comment by Tgo1014** [comment]
was going crazy and the warning brought me here to explain why it's so broken right now. Thanks!

**Comment by leggett** [comment]
Fix went live on Canary (v90.0.4421.5). Still broken on Dev which is a bit behind (v90.0.4421.3)

**Comment by Spurlos** [comment]
Using Chrome version 90.0.4421.5 (Official Build) dev (64-bit) which updater few hours ago, layout works fine.

**Comment by Xalaxis** [comment]
> Using Chrome version 90.0.4421.5 (Official Build) dev (64-bit) which updated few hours ago, layout works fine.

I can confirm this update fixes the issue.

**Comment by leggett** [comment]
Great! I will kill the warning.
