### ISSUE TITLE
Large spacing between top nav and email subject

### ISSUE THREAD

**Issue by lukedyson** [leggett/simplify#498]
Is it deliberate to have so much space between the top navigation bar and the email subject? It feels like a large patch of wasted space. 

<img width="866" alt="Screenshot 2021-02-08 at 20 34 54" src="https://user-images.githubusercontent.com/52576638/107278319-82896300-6a4d-11eb-95d2-3bcfa001b351.png">

<img width="1792" alt="Screenshot 2021-02-08 at 20 38 36" src="https://user-images.githubusercontent.com/52576638/107278384-a51b7c00-6a4d-11eb-92e2-8e7748c15ab3.png">

**Comment by leggett** [comment]
Yes, it is deliberate. It lets the eye easily find and read the subject quickly. The space also calming as things aren't all smashed together. I can make it half as big for those that choose the "Compact" density Gmail setting.

**Comment by leggett** [comment]
P.S. This is a subconscious and somewhat subjective thing.
