### ISSUE TITLE
Option for max-width of vertical split pane

### ISSUE THREAD

**Issue by jasonwarta** [leggett/simplify#499]
When accessing gmail on different sized screens or windows, the email list pane can be a pain, because if its just a little too wide the subject gets truncated instead of being on the next line.

![image](https://user-images.githubusercontent.com/3441269/107279145-226dcf00-6a03-11eb-8bb7-8d51d436e55c.png)

![image](https://user-images.githubusercontent.com/3441269/107279193-331e4500-6a03-11eb-8462-5fbf2b9448d5.png)

Currently I'm setting a max-width on the pane with this custom css:
```
.Nu.tf.aZ6 {
  max-width: 510px !important;
}
```

It would be amazing if there could be an option within simplify to force this behavior.

**Comment by leggett** [comment]
Yeah, Gmail decides when to flip between one line and wrapping. A setting to keep it wrapping by setting a max-width is an interesting idea. Will consider.

**Comment by leggett** [comment]
Ok, support for this is being added in v2.3.8. And oh how I need to redesign Simplify Options... it pains me how many options there are now as just one long list. :(

<img width="585" alt="Screen Shot 2021-03-16 at 9 45 25 PM" src="https://user-images.githubusercontent.com/8763662/111416346-fba95500-86a0-11eb-9c14-383dc1b1e214.png">
