### ISSUE TITLE
Action buttons placement in an email view

### ISSUE THREAD

**Issue by delfick** [leggett/simplify#5]
Hi,

Is it possible that when viewing an individual email, that the action buttons (especially archive) is at the top of the email rather than in the top bar. It's quite far away from the email to move the mouse when I want to archive the email.

Thanks

**Comment by leggett** [comment]
Not really. The icons are put in the same app bar element that is used in the inbox and those elements are outside the scrolling page. It would be very hard (maybe even impossible) to get them to inline with the scrolling page / pin when you scroll them off the page. I'd have to track scrolling and a number of other things. Keyboard shortcuts are your best bet (hit the ? key to see them and turn them on).

**Comment by delfick** [comment]
Ok, fair enough, thanks

**Comment by JayTeeHaitch** [comment]
Ah, damn, I was just going to request the same thing. It's annoying having the archive button on the right of the emails in list view and then have to go to the left when you open the email. An additional archive button in a similar location to where it is when you're looking at the list of emails would work if that is something that is a little easier?

**Comment by leggett** [comment]
I'm actually reconsidering this as part of #101. Stay tuned

**Comment by Danny-Engelman** [comment]
+1
I have uninstalled Simplify because of this.

The most actions I do is read and delete emails. 
I use Stylish to make that delete button bigger/wider so the 'target area' to delete an email is way bigger and I do not have to be accurate with mouse movement.
(and I don't want to move my hand(s) to the keyboard to hit #)

That part still works, but I now have to move the mouse literally halfway across the screen.

**Comment by leggett** [comment]
Working on it right now... 
<img width="1680" alt="Screen Shot 2019-05-04 at 11 31 50 PM" src="https://user-images.githubusercontent.com/8763662/57189542-dce2b080-6ec4-11e9-8273-ce3fc3c737be.png">

There are a ridiculous number of combinations to account for to make this really work:

- 3 resolution brackets
- 6 different views / inbox setups (basic label/search view, default inbox / priority inbox, preview pane vertical, preview pane horizontal, multiple inboxes vertical, multiple inboxes horizontal)
- 5 different use cases (Nav menu open/closed, Search open/closed, Text button labels, Add-ons open, Right side chat enabled)

I'm just trying to get this working at above 1441px wide for starters to cut it down from 90 to 30 setups to account for.
