### ISSUE TITLE
File chips have lost their colour?

### ISSUE THREAD

**Issue by CyborgSemon** [leggett/simplify#50]
For some reason the file type icon on chips seem to loose their colour.
What they look like with simplify turned on:
<img width="170" alt="Screen Shot 2019-04-11 at 6 11 13 PM" src="https://user-images.githubusercontent.com/26075792/55934742-b9419700-5c85-11e9-9c05-8bec415fc348.png">
<img width="169" alt="Screen Shot 2019-04-11 at 6 11 19 PM" src="https://user-images.githubusercontent.com/26075792/55934745-b9419700-5c85-11e9-863c-862585c86d98.png">
What they look like with it turned off:
<img width="171" alt="Screen Shot 2019-04-11 at 6 15 52 PM" src="https://user-images.githubusercontent.com/26075792/55934801-e726db80-5c85-11e9-9220-66236c446d97.png">
<img width="172" alt="Screen Shot 2019-04-11 at 6 15 56 PM" src="https://user-images.githubusercontent.com/26075792/55934802-e726db80-5c85-11e9-9355-c9a2d69e5f75.png">

**Comment by leggett** [comment]
Intentional... they are grey once the thread is read and stay colored when the messages is unread. I tried again to use this density that shows the files and switched back... so if people don't like it, I don't mind switching it back.

**Comment by CyborgSemon** [comment]
Maybe have it an option that people can turn off of they want?

**Comment by leggett** [comment]
I'll switch to using opacity instead of making them gray.

**Comment by leggett** [comment]
Checked in change on v1.1.5. Re-open the issue if you're still not happy with it.
