### ISSUE TITLE
Pegs CPU in Firefox 85.0

### ISSUE THREAD

**Issue by mgalgs** [leggett/simplify#501]
The past few days or so I've noticed my gmail tab really bogging down. I finally took the time to bisect my extensions and Simplify appears to be the culprit. Anything I can do to help debug? I tried removing and re-installing but the runaway code came right back after moving around with keyboard shortcuts a bit.

**Comment by leggett** [comment]
Simplify v2 is way WAY better than v1 (what you are using). But, it hasn't shipped to Firefox yet (there were some unexpected bugs I'm working through today). 

I hope to get it out this week and complete the retirement of Simplify v1.

**Comment by mgalgs** [comment]
Yeah, I'm stoked! I'll just tolerate the eyebleed inducing default gmail for now until v2 ships. Thanks again for the great software.
