### ISSUE TITLE
Styling on help unstable when first opened

### ISSUE THREAD

**Issue by rhulse** [leggett/simplify#502]
Brave Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (x86_64)

When I open the help `?` there is a moment of instability with the styling.

https://user-images.githubusercontent.com/30732/107327307-cfcf0880-6b11-11eb-8fd6-62a0b233f80c.mov

**Comment by leggett** [comment]
I tried a bunch of things to avoid this. Gmail creates and injects it into the DOM when you press `?` -- close the dialog and it stays there. Press it again and they _then_ remove it and create it again. So I have to wait 50ms before I clean it up or I beat them to the punch (clean up the dialog that gets replaced). 

I'm going to try one more thing that might get rid of the flicker. Fingers crossed.

**Comment by rhulse** [comment]
OK, I suspected this might be a tricky one, and frankly not a deal breaker. 

Could you steal the '?',  create you own overlay, then fire the Google one which appears underneath (hidden)? You then copy over what you need, which would have stable styles. On close, let Google remove theirs first. Seems a bit of a mission though... ;-)

**Comment by leggett** [comment]
I'm using a couple MutationObservers... seeing I can use more to avoid the delay.

**Comment by leggett** [comment]
Ok, all fixed in v2.2.2
