### ISSUE TITLE
Tabs/head margin excessive

### ISSUE THREAD

**Issue by Cygnusfear** [leggett/simplify#503]
The margin above the header is excessive for smaller window sizes and not a practical use of available vertical real-estate:
<img width="852" alt="Screenshot 2021-02-09 at 08 36 00" src="https://user-images.githubusercontent.com/2925132/107337161-e5144a80-6ab1-11eb-972b-f2f15307b65f.png">

Ideally the margin is collapsed with a media query determining the window width is too narrow for the margin. 

---
Simplify v.2.2.0 - Configuration: simplify lowDensity inInbox inList ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup hideTabIcons bgOff invertAddons minimizeChat aAX newUI lightTheme defaultTheme - Browser: 5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 - Window: 1791x1043 (100pct zoom) - Language: en

**Comment by leggett** [comment]
I do this for the message in vertical reading pane... reasonable to look at doing it here too. Thanks for the feedback.

**Comment by leggett** [comment]
I'm going to drop the top padding from 40px to 10px for windows below 1050px wide.
<img width="1050" alt="Screen Shot 2021-02-09 at 4 18 47 PM" src="https://user-images.githubusercontent.com/8763662/107446069-87542280-6af2-11eb-8aae-c96224785828.png">
