### ISSUE TITLE
"Loading..." appears during draft, persists.

### ISSUE THREAD

**Issue by rhulse** [leggett/simplify#504]
Expected behaviour: "Loading..." disappears when loading is done.

What happens: When I go to an existing draft, 'Loading...' appears, but does not disappear, and persists even after the email closes.

To replicate:

1. Open an email
2. Hit reply
3. Create a draft response
4. Hit `<ESC>` a couple of times to get back to inbox
5. open email with draft

'Loading...' will appear, and not go away, even when you browse away from the draft.

Using hotkeys or mouse does not seem to make a difference.

Brave, Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (x86_64)
Simplify 2.2.1

**Comment by leggett** [comment]
Interesting... I suspect this is a Gmail bug as I never control if the `loading` bar shows or hides. I tried your repro steps and it didn't happen for me. Is it consistently happening for you? How about after a hard refresh (⌘⇧R or Ctrl+Shift+R)?

**Comment by rhulse** [comment]
Yes, it is pretty consistent, and it goes away with a hard refresh. I'll close this and see if I can find a way to report this as a gmail bug.

**Comment by freste** [comment]
I've been seeing it too, reproducible as above (maybe not every time? most of the time.)
Note that an empty draft doesn't seem to cause it, need to have typed something before backing out.

![Screen Shot 2022-03-02 at 11 01 05 AM](https://user-images.githubusercontent.com/2577130/156399811-5a12e1b8-6554-451b-bc4f-8c092baf314e.png)

**Comment by leggett** [comment]
I still think this must be a Gmail bug as I don't do anything with the Loading banner. 

Are you opening a message in the inbox? Are you typing anything in the draft reply before you hit escape to close it?

**Comment by freste** [comment]
Aha, you are correct! It does happen in plain gmail. I was finally able to reproduce it w/simplify off. It looks like navigating rapidly using keyboard shortcuts causes it.

I opened a msg from the inbox, and opened a reply to that message; typed a few characters. Then esc/click to get out of the composition area; then j/k to previous next messages rapidly, again escaping when you get put back in the reply box. Eventually that "Loading" banner doesn't go away.

Seems more likely to happen w/simplify on, but definitely can do w/out it.

I've reporting to gmail, thanks! (I'm not holding my breath.)
