### ISSUE TITLE
Multiple Inboxes disappear when main inbox is zero and minimized

### ISSUE THREAD

**Issue by diva-D** [leggett/simplify#505]
I use the 'multiple inboxes' feature in Gmail to separate out 'Newsletters' from normal email.

With the new update when my normal inbox hits zero I lose my other inbox - if **minimized**. The only way for it to return is to get a new email in my inbox, or to leave it unminimized

I'd like the option to still show the other inbox (if minimized) even if the main one is at zero.

In Action:
![CleanShot 2021-02-10 at 09 45 16](https://user-images.githubusercontent.com/28694272/107426180-c5018b80-6b84-11eb-907d-515ba3f7d0f5.gif)

**Comment by leggett** [comment]
Ack! That's not good. Simplify is only supposed to go to Inbox Zero for Multiple Inboxes if all the sections are expanded AND empty (when you collapse them, I have no way of knowing if they are empty or not).

Thanks for the report!

**Comment by leggett** [comment]
Ok, I think I have this working right now. 

IF all the sections are expanded AND empty, then I give you the super clean zero inbox. If anything returns to those sections OR they somehow were collapsed, you would see everything again. 

https://user-images.githubusercontent.com/8763662/107570777-d8215500-6b9e-11eb-9770-3ec3c6e6f7d7.mp4

**Comment by diva-D** [comment]
Works great! Thanks for the quick turnaround.
