### ISSUE TITLE
When tasks sidebar is open, the status dropdown selector is broken and collides with the "x"

### ISSUE THREAD

**Issue by R-XS** [leggett/simplify#507]
![image](https://user-images.githubusercontent.com/38081720/107507289-4235fc00-6b97-11eb-9c20-ae65ae6fa7c3.png)

**Steps to reproduce**
Open Gmail tasks sidebar with simplify extension activated

**Actual**
Green status icon is pushed to far right and collides with the close tasks pane "x"

**Expected**
Status icon should not collide with the close tasks pane "x", it should sit in the bottom right corner of the user's profile circle button

**Comment by leggett** [comment]
Thanks for the report. Hope to take care of this one today.

**Comment by leggett** [comment]
Fix will go out today with v2.2.2.
