### ISSUE TITLE
Spacing between Canned Responses is much wider than it used to be in Simplify V1

### ISSUE THREAD

**Issue by CliffWade** [leggett/simplify#508]
Since updating to Simplify V2, the spacing between Canned Responses is now greater than what it used to be which means less fit on the screen at one single time. 

Below is a screenshot from V2, and I unfortunately don't have from V1 to compare, though I'm sure you'll be able to notice the difference.

It would be nice to have the V1 spacing back to make it more compact.

This is on Windows 10, using Chrome Version 88.0.4324.150 (Official Build) (64-bit)
OS Build: 19041.746
Experience: Windows Feature Experience Pack: 120.2212.551.0

![Simplify](https://user-images.githubusercontent.com/4813948/107534509-efa41200-6b8d-11eb-9be8-fdfd1d79e77f.png)

**Comment by leggett** [comment]
Yeah, I redid all the menus. I showed a before and after at the end of this post under "Bonus round: Menus can look nice too!": https://on.simpl.fyi/p/search-navigation-and-add-ons-oh

But I agree with you that I might have added too much padding around menu items. And using compact mode should make that spacing even less than that.

**Comment by CliffWade** [comment]
Ah yeah, I had forgotten you had showed them off there. The spacing to me is just a bit too much. While it certainly looks nice, I would personally like to have it a bit more compact.

I just appreciate you taking the time to look at this and even respond to it as I know you are extremely busy. I absolutely love Simplify and can't wait until the paid tiers roll out, as I will for sure be paying for it once that happens!

**Comment by leggett** [comment]
Ok, I'm dropping this from 10px top/bottom padding on each item to 6px. And if you have density set to compact, I drop it to 4px. Here is what 6px (the default) looks like:

<img width="610" alt="Screen Shot 2021-02-10 at 1 33 14 PM" src="https://user-images.githubusercontent.com/8763662/107575260-93002180-6ba4-11eb-9bfb-bb75a169f532.png">
