### ISSUE TITLE
Message list background doesn't change when selecting different theme.

### ISSUE THREAD

**Issue by landonblaine** [leggett/simplify#509]
The message list background (with preview pane on right) doesn't change when selecting a different theme. Only the background behind the actual message preview is affected.

**Comment by landonblaine** [comment]
I closed as this has been discussed a few times and is the intended behavior. It's a shame though, previous layout was much better.

**Comment by leggett** [comment]
Thanks for the report. It is intentional and I think there are benefits to what I've done BUT I've got it on my list of things to reconsider.
