### ISSUE TITLE
Settings toggle to move labels to the right side in message list

### ISSUE THREAD

**Issue by landonblaine** [leggett/simplify#510]
Interested in having the ability to move labels to the right side of the message list. This used to be a main feature of Gmelius but they have deprecated all features it seems.

Moving labels to the right side provides a much cleaner/efficient interface.

**Comment by leggett** [comment]
Thanks for the suggestion! This was actually the original design for Google Inbox. So I like it in principle. 

But I don't think this would be a good experience in Gmail as it is today with the many things that can be on the right side (quick settings, add-ons, and right-side-chat).
