### ISSUE TITLE
Reading Pane – Put the same shadow for Apps

### ISSUE THREAD

**Issue by timjub** [leggett/simplify#511]
Hi! 

Loving V2. Is there a way to have the same border to separate the inbox from the Apps pane (on the right) to the one separating the inbox pane from the message view.

See screenshot.

The one on the left is simpler. The shadow on the right is a little bit distracting.

Thanks!
![Screen Shot 2021-02-11 at 12 49 45 PM](https://user-images.githubusercontent.com/78710877/107677107-e38c8300-6c67-11eb-8d16-4fc799a6e59c.png)

**Comment by leggett** [comment]
Yeah, this bugs me too. I think I tried to do this and had trouble but I probably didn't try hard enough. 

The only case I can make for it is that the add-on pane is a different app and is sitting on top of Gmail. But that is a pretty weak case. :/ 

I'll look into it.

**Comment by leggett** [comment]
Yeah, I like that better. Will go out in the next release.

**Comment by timjub** [comment]
The case for it being on top would work for me, if the shadow went all the way to the top. ☺️ 
Glad to know it'll be fixed, thanks for your reactivity.

**Comment by leggett** [comment]
Well I'm ditching the shadow AND making the border stretch all the way to the top.
