### ISSUE TITLE
Dark mode for composers

### ISSUE THREAD

**Issue by Julian88Tex** [leggett/simplify#512]
Reply box is not in dark when dark mode is enabled for gmail with Simply 2.0. Previously this area was dark.

<img width="924" alt="Screen Shot 2021-02-11 at 12 10 59 PM" src="https://user-images.githubusercontent.com/459099/107693071-7b876e00-6c62-11eb-9056-dbe12dc78a68.png">

**Comment by leggett** [comment]
At one point I did try to invert this but there were issues and there are risks that the formatting gets embedded in the actual email you send. I will leave this open and look at it again. If I do it, I'd probably make it an opt-in setting.

**Comment by Julian88Tex** [comment]
@leggett makes sense and looking forward to it! I'm a Quality Engineer so also down to test :-).

Happy to begin contributing when it becomes a paid product :-).

**Comment by leggett** [comment]
I looked back into this and I remember now why I didn't do it. Writing it here as much for future Michael as anyone else...

The edit bar switches to position:fixed when it is scrolled off the screen. Using filter:invert(1) to make the whole composer dark conflicts with position:fixed and super weird things happen (the bar jumps across the screen as pos:fixed no longer holds).

So, to do dark compose, I would have to theme every element and icon in the compose. And I would have to make sure the style didn't get inserted into the message itself (easily happens with copy/paste). And make sure it doesn't mess up the major other extensions. 

Not impossible, but not a quick fix.

**Comment by Julian88Tex** [comment]
@leggett Ah yeah sounds challenging indeed. Not sure if this helps at all, but I noticed [Dark Reader](https://github.com/darkreader/darkreader) is able to accomplish this to a certain degree. I realize a lot of the text formatting icons are way too dark, but personally, I still prefer this (as an optional beta feature of course). Not sure what they are doing to get it to work, but maybe a starting place at least.

<img width="879" alt="Screen Shot 2021-02-11 at 9 28 53 PM" src="https://user-images.githubusercontent.com/459099/107733692-78b36a00-6cb0-11eb-9ab8-1654ad1121bd.png">

Sidenote: I feel like "Dark Mode Front-end Engineer" should a legit title nowadays.

**Comment by leggett** [comment]
Interesting... Two things to test if you're up for it while you have it on:

1. Write some gibberish, hit enter, write some more gibberish, then put the cursor at the start of the second line and hit delete to combine the second line with the first. Now send that email to yourself (or me if you want at hi@simpl.fyi) -- this will test if the formatting leaked into the email itself
2. Start a draft reply on the last message a long-ish thread. Type some gibberish and hit enter a bunch of times so the reply is like 10-20 lines long. Now scroll the whole page back towards the top. Does the action bar on the inline reply (with the send button) jump?

**Comment by Julian88Tex** [comment]
asdfasdfwasdfsadf

<http://www.utexas.edu>

*Julian Joseph <https://www.linkedin.com/in/juliandjoseph/> ☁️
<https://trailhead.salesforce.com/en/me/julianjoseph>*
Salesforce Quality Engineer | The University of Texas at Austin
<http://www.utexas.edu>
512.743.6385 | Pronouns: He/Him/His
<https://www.linkedin.com/in/juliandjoseph/>LinkedIn
<https://www.linkedin.com/in/juliandjoseph/> | Facebook
<https://www.facebook.com/julianjoseph> | Twitter
<https://twitter.com/Julian88Tex> | Instagram
<https://www.instagram.com/julian88tex/>

**Comment by leggett** [comment]
Looks good -- so they aren't trying to invert anything directly inside the contentEditable div... it must be above it. I'll try to check out what they are doing.

**Comment by Julian88Tex** [comment]
@leggett Hah forgot you could reply to GitHub threads...

Not positive I covered both correctly but here videos of the tests:



https://user-images.githubusercontent.com/459099/107734775-0a23db80-6cb3-11eb-9280-f7369d929861.mp4

https://user-images.githubusercontent.com/459099/107734783-114ae980-6cb3-11eb-9aa0-e89d6d746110.mov

**Comment by Julian88Tex** [comment]
@leggett great thanks :)

**Comment by leggett** [comment]
I have it working but I want to test this a lot more to make sure it doesn't do anything funky with messages you send. I also have concerns for scroll performance (look at the lag on the bar going from position:fixed to relative at the end)

Uploading dark_inline_compose.mp4…

**Comment by leggett** [comment]
I also need to do the compose mole and full-screen composer.

**Comment by Julian88Tex** [comment]
@leggett thanks so much for the quick turnaround. Looks plenty good enough for a beta feature imo. I can say for myself, the Reply is 10x more important than the full-screen or compose mole (because who writes new emails anymore 🙈), but still would be nice to have.

Not sure about the process of beta testing Extensions, but would happy to give it a try by setting it up locally or as a hidden feature flag in a release across browsers.

**Comment by leggett** [comment]
I'm working on opening up the beta (will call it the Canary channel) to anyone who wants to live on the bleeding edge. I need to tend to a few other things first but should be able to get this out in some form next week. 🤞🏻

**Comment by Julian88Tex** [comment]
@leggett Made my day!


<img width="918" alt="Screen Shot 2021-02-27 at 4 52 36 PM" src="https://user-images.githubusercontent.com/459099/109404570-45addf00-791c-11eb-8ab6-72b9f8aca6d7.png">


<img width="646" alt="Screen Shot 2021-02-27 at 4 52 12 PM" src="https://user-images.githubusercontent.com/459099/109404567-447cb200-791c-11eb-94fe-8b950f68f3a1.png">
