### ISSUE TITLE
Chat status indicator overlaps calendar close button

### ISSUE THREAD

**Issue by tdhoward** [leggett/simplify#515]
When the calendar side panel is closed, and the user is not hovering over the profile image, the chat status indicator looks proper:
![3](https://user-images.githubusercontent.com/5395302/107704928-dcb73d80-6c72-11eb-91f1-a0c9aba28bda.png)

When you hover over the profile image, the expanded chat status indicator looks normal.
![4](https://user-images.githubusercontent.com/5395302/107704929-dd4fd400-6c72-11eb-987e-2127b2ef9e17.png)

However, when the calendar is left open and the chat status indicator returns to the mini version, it overlaps the calendar close button, making it confusing and difficult to use either.
![5](https://user-images.githubusercontent.com/5395302/107704925-dc1ea700-6c72-11eb-8769-dbd8d156e6be.png)

Hovering over the close button:
![1](https://user-images.githubusercontent.com/5395302/107704926-dcb73d80-6c72-11eb-9011-a41bc010a095.png)

Selecting the chat status indicator. (Notice the pointer is over the "Chat notification settings" menu item, although there is no icon for it.
![2](https://user-images.githubusercontent.com/5395302/107704927-dcb73d80-6c72-11eb-9338-9dd29c173782.png)

**Comment by leggett** [comment]
This should be fixed in v2.2.2 (went out last night). Please re-open if you're already on that version and I'll dig in.

**Comment by tdhoward** [comment]
Excellent!  I thought I was already on 2.2.2, but I refreshed my Gmail tab, and everything worked.  Thanks!
