### ISSUE TITLE
Chromecast beta issue

### ISSUE THREAD

**Issue by tbruning** [leggett/simplify#518]
The latest beta version of chromecast (Version 89.0.4389.48 (Official Build) beta (64-bit)) appears to have 'broken Simplify.  I have attached two screenshots, one with simplify on and one without.
![without_simplify](https://user-images.githubusercontent.com/1384829/107849567-249ca880-6dca-11eb-8682-4aa7cf7cdb56.png)
![with_simplify_enabled](https://user-images.githubusercontent.com/1384829/107849568-25353f00-6dca-11eb-967c-b97629924234.png)

**Comment by leggett** [comment]
Not broken, this is Simplify v2. I've written about the update on the newsletter. This post talked about the [vertical reading pane](https://on.simpl.fyi/p/simplify-gmail-v2-sneak-peak).

**Comment by tbruning** [comment]
Thanks Micheal

My bad.


As Ever,


Tom Bruning

(c) 201.204.0585


#StayPositive

#TestNegative
