### ISSUE TITLE
Warn people to not use 'one key auto-select' if they use Gmail's custom keyboard shortcuts

### ISSUE THREAD

**Issue by alok** [leggett/simplify#521]
i mapped `e` in gmail to go to next email, but with the 'one key auto select', it just archives the mail, ignoring my custom binding.

**Comment by leggett** [comment]
Correct -- I don't have a way of knowing custom mappings. 

I should add a warning to not enable the one key auto-select if you use custom shortcuts.

**Comment by leggett** [comment]
I added a disclaimer in Simplify Options:

<img width="577" alt="Screen Shot 2021-03-16 at 9 17 45 PM" src="https://user-images.githubusercontent.com/8763662/111414357-1679ca80-869d-11eb-95ad-0e4b016d2d13.png">
