### ISSUE TITLE
Reply All Text Button Causes Overflow on Firefox

### ISSUE THREAD

**Issue by aaronblair** [leggett/simplify#523]
When "Button Labels: Text" is turned on and "Default Reply Behavior" is set to "Reply All", in the conversation view, Reply All causes the buttons to overflow:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/1298050/108110138-1233a080-7050-11eb-872e-b94811b724cf.png">

**Comment by leggett** [comment]
Boy, Firefox strikes again. I fixed this in a recent update but I guess it didn't work for Firefox. Will look.

**Comment by leggett** [comment]
Ok, have a fix. Will go into next release.
