### ISSUE TITLE
Extra bottom border of last email in thread

### ISSUE THREAD

**Issue by khaister** [leggett/simplify#524]
When viewing an email thread, the last email has a bottom border. IMO, it shouldn't have one.

![image](https://user-images.githubusercontent.com/1192669/108146726-8be48200-7082-11eb-8017-f60679570b05.png)

---
Simplify v.2.2.5 - Configuration: simplify lightTheme lowDensity ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFormat hideListCount hideMsgCount hideSignatures hideUnreads izBg1 invertAddons listWidthLg matchFontSize minimizeChat msgWidthSm aAX meetOff grayTheme nPane inMsg - Browser: 5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 - Window: 1494x1338 (101pct zoom) - Language: en

**Comment by leggett** [comment]
I believe this is the high contrast theme I believe which adds borders everywhere. I haven't dug into supporting this theme yet (I think you are on the other issue about this - #370). 

If you want a light gray theme without the borders, you can use Gmail's Soft Gray theme.

It also appears you have another extension installed as your conversation is in reverse order. No idea how this impacts things.

**Comment by leggett** [comment]
I take it back, you ARE using the grayTheme. That border isn't there for me so I'm guessing it added by whatever other extension you are using to reverse the order of the conversation. Please re-open if I'm wrong.

**Comment by khaister** [comment]
You're right! I was using [this extension](https://chrome.google.com/webstore/detail/gmail-reverse-conversatio/kfgepjmmgamniaefbjlbacahkjjnjoaa). Once I disabled it:

![image](https://user-images.githubusercontent.com/1192669/108170051-71c09900-70ae-11eb-96c4-5c28ea8ec7cf.png)

Would you consider adding this feature sometime in the future?

**Comment by leggett** [comment]
Sigh... maybe?

You're the 3rd person to ask for reverse sorting the conversation. It seems like such a horrible experience to me. I explained why I think so in this thread: https://on.simpl.fyi/p/choosing-a-business-model/comments#comment-1236665

But people keep asking for it. And wow, the extension you linked to has 200k users. I just don't get why you would want the default order to be backwards like this...

**Comment by leggett** [comment]
Ok, I've got this working and will include it as an option in v2.3.0 (which will have a lot of new stuff).

**Comment by khaister** [comment]
Thank you!
