### ISSUE TITLE
Simplify shortcut clash

### ISSUE THREAD

**Issue by benoitgrelard** [leggett/simplify#525]
Hi,

It seems there's a global shortcut for showing a simplify info dialog using `alt + i`.
Unfortunately it clashes with an accent I need to type for my name every time I sign an email.
In order to type Beno*î*t I have to do `alt + i` and then `i`.

Would it be possible to think of another combination?

Cheers!

**Comment by leggett** [comment]
Would alt + shift + be better?

You can disable the shortcut in Simplify options now so it doesn't conflict. And you can still report an issue via the Simplify extension menu.

**Comment by benoitgrelard** [comment]
Ah I didn't realise I could remove just that shortcut, that's great!

**Comment by leggett** [comment]
Quick question though... where was `alt + i` triggering the report issue dialog when you were typing? **None** of the keyboard shortcuts should trigger when you are typing into an input or compose body.

**Comment by leggett** [comment]
I'm going to rework how I make sure that doesn't happen. I'd love if you would re-enable the keyboard shortcut after the next update (v2.3.0) and see if the issue persists. I'll try to send a reminder after the update.

**Comment by benoitgrelard** [comment]
Yeah it was in the main body. Let me know and I'll re-enable.

**Comment by leggett** [comment]
This was reworked in v2.3.0. if you have that or newer (v2.3.3 is the latest) can you re-enable alt+I and see if it is still an issue?

**Comment by benoitgrelard** [comment]
I can confirm that it doesn't trigger when composing now. 🙏 

However, I now see this weird layout issue:

![image](https://user-images.githubusercontent.com/1539897/109526244-42485e00-7aaa-11eb-8bb0-27d904d68910.png)

That send later button is out of place, and somehow also it moves/grows (the white element behind it grows) when scrolling up/down.

**Comment by leggett** [comment]
That was fixed in v2.3.3 which is out on all browsers except Safari. 

You can fix it now by disabling "Show schedule send inline" under Simplify options > Compose.

**Comment by benoitgrelard** [comment]
Do you know when the fix goes out to Safari?

**Comment by leggett** [comment]
I don't... Apple blocked the update because I'm not using their in-app payment system. But I'm not using any payment system. Turns out they don't like that I link to the blog post on pricing because they think I could turn that into a bypass of their payments system... sigh. I'm appealing it.
