### ISSUE TITLE
Simplify Options Appear Twice (Canary Build)

### ISSUE THREAD

**Issue by derylseale** [leggett/simplify#527]
Just installed v2.3.0 on the latest version of Brave, and it looks like the extension options appear twice at the bottom of the Gmail settings menu. As well, if you select one, then the options open twice. Screenshots below.  

<img width="325" alt="Screen Shot 2021-02-20 at 8 40 07 AM" src="https://user-images.githubusercontent.com/1426718/108597546-8e332e80-7357-11eb-8395-7200b67cf90c.png">
<img width="523" alt="Screen Shot 2021-02-20 at 8 40 20 AM" src="https://user-images.githubusercontent.com/1426718/108597549-8ffcf200-7357-11eb-80a9-641298e7fb0b.png">

**Comment by leggett** [comment]
I wonder... do you have two versions of the extension installed? Weird things can happen if so.

**Comment by leggett** [comment]
I'm 99% sure this is due to having both v2.3.0 and v2.2.5 running at the same time. Disable v2.2.5 and it should be fine. Re-open if you didn't have multiple builds running at the same time.

**Comment by derylseale** [comment]
That was the issue. I thought I had removed the main release, but I had not.
