### ISSUE TITLE
New Messages Appear Faded (Canary Build)

### ISSUE THREAD

**Issue by derylseale** [leggett/simplify#528]
New messages in the list appear properly bolded,  but now are a faded gray in color. It makes it hard to identify them at a glance. Simplify v2.3.0 in Brave (latest version)

<img width="514" alt="Screen Shot 2021-02-20 at 9 05 28 AM" src="https://user-images.githubusercontent.com/1426718/108598317-03543300-735b-11eb-92dc-67c8f117ff0c.png">

**Comment by leggett** [comment]
Ack, that's no good. What theme are you using? Is it the default theme?

**Comment by leggett** [comment]
I'm 99% sure this is due to having both v2.3.0 and v2.2.5 running at the same time. Disable v2.2.5 and it should be fine. Re-open if you didn't have multiple builds running at the same time.

**Comment by derylseale** [comment]
That was the issue. I thought I had removed the main release, but I had not.
