### ISSUE TITLE
Spacing in Lists

### ISSUE THREAD

**Issue by aaronblair** [leggett/simplify#530]
I'm not sure if this is intended or not, but the spacing between list items is much wider than in default gmail. Almost too much for my liking, but that might just be personal preference.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/1298050/108640803-ebfb6f80-7458-11eb-867d-55f8d82f013c.png">
<img width="196" alt="image" src="https://user-images.githubusercontent.com/1298050/108640811-f4ec4100-7458-11eb-8d38-550ec2aee765.png">

**Comment by leggett** [comment]
It is international. No space between bullets is a typographic pet peeve of mine that makes it hard to read lists. Will consider yet another setting or making it a little smaller. But no promises.

**Comment by aaronblair** [comment]
Makes sense. I do agree with you that some extra space is good. However, at first I thought there was an extra full line stuck in there. It kind of sticks out when compared to the line spacing in the rest of an email. I'm not sure if it deserves it's own setting, but I'd consider tapering it back a touch.

**Comment by leggett** [comment]
**It is 70% of a line. I might be up for dropping it to 60%.** 
Here is a comparison of different amounts of padding. And I fully admit this is subjective.

**padding-bottom: 0em (0% of font size - Gmail's default)**
The list of single words isn't my favorite but is fine as each line is clearly a new bullet. But the paragraphs all run into each other. The edge of text is where your eye goes to at the start of each line, not to the bullet so the bullets alone do not do enough to separate each item.
<img width="592" alt="Screen Shot 2021-02-21 at 5 26 45 PM" src="https://user-images.githubusercontent.com/8763662/108646340-58329f00-746a-11eb-8687-368b394d779e.png">

**padding-bottom: 0.4em (40%)**
This is the smallest I'd be willing to go. Anything less has the same issue as no space in my opinion. It is almost enough but I think the paragraphs still run into eachother.
<img width="587" alt="Screen Shot 2021-02-21 at 5 27 19 PM" src="https://user-images.githubusercontent.com/8763662/108646390-831cf300-746a-11eb-8b35-e1cd00ab673c.png">

**padding-bottom: 0.5em (50%)**
Getting closer but still not quite there IMO.
<img width="592" alt="Screen Shot 2021-02-21 at 5 27 33 PM" src="https://user-images.githubusercontent.com/8763662/108646521-02aac200-746b-11eb-914b-8cde2936d021.png">

**padding-bottom: 0.6em (60%)**
Now we're getting somewhere. I'd be comfortable reducing to this amount.
<img width="595" alt="Screen Shot 2021-02-21 at 5 27 47 PM" src="https://user-images.githubusercontent.com/8763662/108646554-2837cb80-746b-11eb-88ff-c630b752b41f.png">

**padding-bottom: 0.7em (70%)**
I like this more than 0.6em for the paragraphs and a little less than 0.6em for the one-word bullets. Given there is no setting for this, it might be prudent to reduce to 0.6.
<img width="594" alt="Screen Shot 2021-02-21 at 5 28 01 PM" src="https://user-images.githubusercontent.com/8763662/108646606-53bab600-746b-11eb-8faa-a0779c49ba18.png">

**padding-bottom: 1em (100%)**
Just for comparison, this is double spacing (a full line) and is way too much in all cases IMO. 
<img width="570" alt="Screen Shot 2021-02-21 at 5 28 18 PM" src="https://user-images.githubusercontent.com/8763662/108646661-806ecd80-746b-11eb-8c8e-c7855ef707ed.png">

**Comment by aaronblair** [comment]
Totally up to you as it's somewhat subjective. I agree that the spacing helps, but I'd air on the side of less is more. That way it's more universal and less jarring to those who do not expect it. If it were me, I'd pick 0.5em. It's the smallest size (for me) that immediately provides the visual cue of the break at a quick glance without scanning for the bullets. If your going any less than 0.4em, it becomes functionally useless and I'd just stick with the default. At the same time, I don't get anything more from the larger spacing and at >=0.7em I find it starts breaking the flow and the cohesiveness of the list (especially when you have several small & short lists separated by a header/title).

I just took a look through some of the other apps that I use, and I felt that Notion seems to strike a good balance. For reference it's visually closer to 0.4/0.5em. Not that they are the authority of perfect UI or anything.

**Comment by aaronblair** [comment]
The other thing that I think that they do well is force proportionally slightly large bullets. I think that this helps the visual separation as well. Notion for reference: 

![image](https://user-images.githubusercontent.com/1298050/108650560-119a7000-747d-11eb-8cf7-61e4ed8164c3.png)

**Comment by leggett** [comment]
Agree Notion isn't necessarily the gold standard but happy to compare to another product that has thought about this issue. They have some padding which means they thought about how much to add.

- Standard Gmail bullets are in a 13px font, 1.5em line height, and zero padding between bullets
- Simplify Gmail bullets are in a 14px font, 1.5em line height, 9.8px padding between bullets (70% of line height)
- Notion bullets are in a 15px font, 1.5em line height, 8px padding between bullets (53% of line height padding)

Notion's The 53% works better because of the larger font size (which makes the padding in absolute terms larger and makes the bullets larger).

I'm going to drop to 60% and call it a day. Thanks for the report & discussion.

**Comment by aaronblair** [comment]
Good call. I respect that.
