### ISSUE TITLE
Moving mouse out of browser window often leaves menus open

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#531]
If the mouse passes over the hamburger menu or account avatar then immediately leaves the Gmail (browser) window, the menu will remain open.

e.g. move mouse out of Gmail via the hamburger icon. The main navigation menu will appear, but does not hide again until I mouse back into the browser window. This is annoying me :-)

Suggest:
1. Add a hover delay before showing the hover menu(s).
2. Detect mouse leaving the window and hide any hover menus.

Standard Gmail seems to take the latter approach.

---
Simplify v.2.3.0 - Configuration: lightTheme lowDensity ca3 caI caL cfC cfO cfQ cfR cfU composeActions hideMsgCount hideSelectRefresh izBgDefault invertAddons invertCompose listWidthLg matchFontSize minimizeChat msgWidthSm aAX newUI grayTheme inList simplify inInbox - Browser: 5.0 (Macintosh Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 - Window: 1555x1415 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
I didn't think there was a way to detect that the mouse has left the window. I was wrong. Will fix in next update.

**Comment by leggett** [comment]
In for v2.3.1
