### ISSUE TITLE
Follow Up Reminder Styling Needs Improvement

### ISSUE THREAD

**Issue by derylseale** [leggett/simplify#532]
The follow up reminder message that Gmail provides has some styling issues. It's currently vertically aligned with the top of the message, and it perhaps lack some shadowing (as, e.g., the delete spam message has). 

<img width="1043" alt="Screen Shot 2021-02-23 at 3 35 11 PM" src="https://user-images.githubusercontent.com/1426718/108905152-5d6c2700-75ed-11eb-894d-c1c6ffaa2133.png">

**Comment by leggett** [comment]
Fix in for next update. I must have done the CSS for this one with the default theme (where you can't see the card background).
