### ISSUE TITLE
Styling Issue when Reverse order of messages in conversation is Enabled

### ISSUE THREAD

**Issue by Ryan-Efendy** [leggett/simplify#534]
![image](https://user-images.githubusercontent.com/12979345/109260385-e41e3100-77b2-11eb-8e99-73d34e00258a.png)

It looks like there's some styling issue when `Reverse order of messages in conversation` is enable, some of the suggested reply and buttons such as "Reply all". Attached screen shots below.

![image](https://user-images.githubusercontent.com/12979345/109260354-d9639c00-77b2-11eb-85a5-27dbfa438e68.png)

---
Simplify v.2.3.0 - Configuration: simplify lowDensity nPane inMsg ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFormat dateGroup hideListCount hideMsgCount hideSelectRefresh hideSignatures hideTabIcons hideUnreads izBgDefault invertAddons invertCompose listWidthLg matchFontSize minimizeChat msgWidthSm aAX lightTheme defaultTheme newUI reverseMsgs - Browser: 5.0 (Macintosh Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36 - Window: 1706x1440 (100pct zoom) - Language: en

**Comment by leggett** [comment]
I have a fix for this in v2.3.1 (which will go to canary tomorrow when I push v2.3.0 to public)
