### ISSUE TITLE
Ability to hide "multiple inbox" sections when empty (Feature Request)

### ISSUE THREAD

**Issue by SOL4RIS** [leggett/simplify#535]
Hello! I am new to Simplify (and Github for that matter), so I hope this is an appropriate "feature request" post.

Would it be at all possible to, when using multiple inboxes, have Simplify hide any inbox sections that are empty? I've attached a screenshot showing the wasted screen real estate when there are no emails in the section. I would love to get some of that space back!

Thank you for the consideration!

![2021-0225-234756-Clipboard](https://user-images.githubusercontent.com/79487317/109265985-a0ccbe00-77c4-11eb-9b25-3e21acefbd25.png)

**Comment by leggett** [comment]
Here is a fine place to ask for things! 

And a reasonable request it is. Gmail supports this with the sectioned inboxes (Priority Inbox, Starred First, etc). I think I could support it as a global setting (hide any empty inboxes in Multiple Inbox). Doing it on a case-by-case basis for each section would be a fair bit harder.

I'll add this to my list for after I launch subscriptions.

**Comment by SOL4RIS** [comment]
I think a global settings makes perfect sense to me! I can't see a use-case for enabling/disabling it individually, at least not for myself.  Appreciate the quick response; this one feature alone to me would definitely be worth subscribing for!

**Comment by leggett** [comment]
I have this in for the next update (v2.3.4)
