### ISSUE TITLE
Weird loading animation glitch?

### ISSUE THREAD

**Issue by quickdraw-m** [leggett/simplify#536]
Running Simplify Canary in Chrome.  Freshly rebooted and browser opened/closed, problem persists.  Animation plays properly with the color and all that, but the large white diamond remains.

![Screenshot 2021-02-26 at 08 14 05](https://user-images.githubusercontent.com/70546828/109305032-27a48980-780b-11eb-8e14-e123cf09a0dd.png)

**Comment by leggett** [comment]
Thanks... Fix coming in v2.3.1
