### ISSUE TITLE
Notify when there are messages in the spam filter

### ISSUE THREAD

**Issue by yshyonli2** [leggett/simplify#537]
Hello! I like keeping the main menu hidden most of the time, since I don't usually need it, but that also means I have to manually check for new spam messages. Spam is spam, but I always like double checking just to make sure nothing important has been accidentally caught by the system.

My current workaround for this issue is to expand the main menu using Alt+M, quickly glance at my spam label to see if it's bolded, and then rehide the menu using the same shortcut. It doesn't take a lot of time, but it's also a bit tedious.

Would it be possible for Simplify to notify the user whenever there's something in the spam filter, whenever the menu is hidden? One idea would be to automatically expand the main menu if there are spam messages, and then automatically hide the menu if there are none.

This might be a niche issue, but thanks for considering it all the same.

**Comment by leggett** [comment]
Hi, thanks for the feature suggestion. 

I'm going to pass on this one. Notifications of any kind are antithetical to my vision for lowering the stress around email... _especially_ on the spam folder.

But you can certainly get what you want if you don't use Simplify as Gmail will show a small red badge on any label that has mail when the navigation menu is collapsed:

<img width="263" alt="Screen Shot 2021-02-26 at 5 03 58 PM" src="https://user-images.githubusercontent.com/8763662/109370319-aeca1f80-7854-11eb-9397-25788c81eedd.png">
