### ISSUE TITLE
When in "small email list" vertical split mode, allow the labels to take up more space

### ISSUE THREAD

**Issue by macintacos** [leggett/simplify#538]
I use labels for work email... a lot. Unfortunately, this means that for any given email, there are 3-5+ labels attached to it, and thus using the vertical split view for looking at the message a lot of my labels get cut off in the email list view.

What I really want to have is the ability to keep the "small" email list layout that looks like this:

```
<from>									| email
<subject>								|
<small excerpt of message> <labels>		| 
```

But have the labels take up more of that third row's space. If anything, it'd be nice (for me!) if the labels took up the _entire_ space of that last line line; for my use-case, it's worthless. Right now when I go to drag the divider to make the email list larger (in an attempt to see all of the labels), it switches to the "larger" email list view where everything is on a single line, which is honestly even worse for me since the labels are in-line with the subject, and thus take up all of the visual space and I can't see the subject until I drag it out way further.

Hopefully this request makes sense; please let me know if you need any further clarification on this.

**Comment by leggett** [comment]
I understand the request... and it may be possible to support. But I'm not sure if it is a better experience or not. 

- I don't think having the labels cover all of the snippet (the small excerpt of the message) is good.
- So instead, what will happen is the labels will wrap to a 4th line when there are too many. 
- I do not want to add this as a setting (I already have too many settings).
- So the question becomes: is this better than them truncating and staying in-line for the majority of users / uses? 

I'll have to think about it.

**Comment by macintacos** [comment]
Yeah I understand that it's a niche request, and it likely rubs up against the philosophy of what you're trying to accomplish. Doesn't hurt to ask, and I respect whatever decision you decide to take 🙂

**Comment by leggett** [comment]
Ok, I'm including this in the next update (v2.3.4) as an option: "Right align labels after snippet." In list view, it right-aligns the labels. In vertical split reading pane (where they are already right aligned), it allows long lists of labels to expand and make a 4th row. No ETA on when the update will go out as I'm trying to focus on building subscriptions at the moment.

**Comment by macintacos** [comment]
Thank you very much!
