### ISSUE TITLE
Make email width in vertical split mode match the email with in horizontal split mode

### ISSUE THREAD

**Issue by macintacos** [leggett/simplify#539]
I want to use the vertical split mode more in Gmail, however one thing that makes the horizontal split mode superior for me is the fact that the emails in that mode take up more width. I get a lot of emails from subscriptions that I've set up with Jira, and the emails that are sent to me are a tad on the wider side, which makes it so that I don't need to horizontally scroll when I'm viewing the email in horizontal split mode, but I _do_ need to horizontally scroll when I'm viewing the email in the vertical split mode.

**Comment by leggett** [comment]
You're in luck -- I added a setting in today's update (v2.3.3) where you can change the max-width of the emails or the list. 

Look under Simplify Options > Message width
