### ISSUE TITLE
Inlined scheduled send button not aligned with other buttons

### ISSUE THREAD

**Issue by perler** [leggett/simplify#540]
![image](https://user-images.githubusercontent.com/623092/109411470-a67ffa80-79a2-11eb-8586-ebcdfb7ca46f.png)

beside the alignment, I love the idea of a separate schedule send button, but putting it in the compose action row it somehow feels wrong. It should at least be blue and separated from the attachment row shouldn't it? 

---
System: Mozilla/5.0 (Windows NT 10.0

**Comment by leggett** [comment]
Agree the alignment isn't perfect. Will leave this open for that.

I think it is fine having the button there and gray. I played with having it be blue but thought it drew too much attention to itself for how often it is used by your average user (not often). I settled on having it turn blue when you hover over it.

**Comment by erikgeurts** [comment]
I use the 'schedule' feature rather frequently, and I very much like it being its own little button. In fact, I like it so much I'd love to see the same repositioning for the feature when I'm writing a reply, so that there is consistency for both new mails and replies.

**Comment by leggett** [comment]
It is near impossible to reposition in an inline reply. BUT, I have a plan to create a fake button that when clicked, clicks on the real button. And that would let me do it in all views. Stay tuned.

**Comment by leggett** [comment]
Fixed in v2.3.7
