### ISSUE TITLE
Reverse order of messages in inbox

### ISSUE THREAD

**Issue by yshyonli2** [leggett/simplify#541]
Hello again!

I'm currently trying out the option to reverse the order of messages in conversations. I wonder if it would be possible (and useful) to do the same for emails in the inbox.

I like going through emails from oldest to newest, so this would save me from scrolling to the bottom of the page each time or holding the down button to get to the last message. I think Gmail already has a limited version of this feature, but it only reverses the page order rather than the individual message order.

There are already quite a few settings in Simplify, so I understand if this isn't something you'd be able to work in. Thanks for considering it all the same.

In any case, I'm really enjoying this extension, so thank you for working on it.

**Comment by leggett** [comment]
I can't change the order of the items in the inbox because Gmail uses a separate data structure for the next/previous buttons and keyboard shortcuts. 

I also can't reorder any further than the visible page.
