### ISSUE TITLE
Update readme to reflect Simplify is no longer open source

### ISSUE THREAD

**Issue by GorvGoyl** [leggett/simplify#542]
I like your extension, however, It got disabled saying I need to provide new permission to googleusercontent.com. May I know why is this required as extension is already given mail.google.com access.

![image](https://user-images.githubusercontent.com/7106086/109415152-02677500-79dd-11eb-809e-c9163dc8883c.png)

Also, I couldn't find this change in your repo, Is the source code different for the extension deployed on chrome store?

**Comment by leggett** [comment]
This is for blocking email trackers. More info at https://on.simpl.fyi/p/v233-new-permissions

The extension is no longer open source and this is just a place to track issues now. I should update the Readme to reflect that.

**Comment by GorvGoyl** [comment]
thanks for clarification

**Comment by leggett** [comment]
Readme updated.
