### ISSUE TITLE
Option to move labels to the right in list

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#543]
Feature request:

In the distant past, I used to have GMelius installed, back when they were primarily trying to improve the look & feel of Gmail. That role has been taken over by Simplify now (and I love it!).

One feature of Gmelius I used to like is that it was possible to move the labels assigned to each email conversation to the right in the list. That made the list much more usable by decluttering the list, while also making the labels stand out better.

Would you consider adding this as an option in Simplify?

**Comment by leggett** [comment]
Yeah, that wouldn't be too hard to add as an option. 

I want to get the subscriptions done first and redesign Simplify Options first (hopefully all done in the next month or so), but I'll do this soon after.

**Comment by erikgeurts** [comment]
Yes, sure, no rush. I'll make sure to subscribe once that's available. Let me know if you need any additional input.

**Comment by leggett** [comment]
Ok, I have this implemented as an option for the next release (v2.3.4). Trying to focus on subscriptions so that release may not go out for a little while.
