### ISSUE TITLE
Feature: Make "hangouts" quote icon visible when main Menu is hidden

### ISSUE THREAD

**Issue by alanhoyle** [leggett/simplify#544]
I've started hiding the Main Menu in my Gmail view, but this has the disadvantage that it also hides the big "quote" icon for accessing Hangouts chat.  Now, if I want to access that, I have to "mouseover" the main menu hamburger icon at the top of the window, and then move the cursor all the way to the bottom of the window to click the icon and bring out.  

It would be nicer if the hangouts icon remained accessible , say next to the "(1-100 of 5,000 >)" bubble.  

This is the icon I'm referring to:

![Screen Shot 2021-03-01 at 10 36 22 AM](https://user-images.githubusercontent.com/289779/109520202-f978b100-7a79-11eb-89b6-d32c0f810f05.png)

And this is a screenshot showing the main menu hamburger icon at the top and how far I have to move my cursor to access hangouts at the bottom:

![Screen Shot 2021-03-01 at 10 38 07 AM](https://user-images.githubusercontent.com/289779/109521236-19f53b00-7a7b-11eb-912f-d0689abbe492.png)

**Comment by leggett** [comment]
You can! This is the downside of so many options is the ones you want are hard to find.

Look under Simplify options > Chat > Keep Chat visible when nav is closed

**Comment by alanhoyle** [comment]
Thanks @leggett!  I especially like that the actual implementation is exactly what I had imagined.
