### ISSUE TITLE
Feature Request: More contrast for unread items

### ISSUE THREAD

**Issue by rcdailey** [leggett/simplify#545]
Using dark mode, at the moment the only thing differentiating between read and  unread items in the email listing is bold text. It's pretty difficult to tell the difference between bolded and non-bolded text without squinting. Would it be possible to give the background (row) for that item a lighter shade of black/gray as well? I think this would make unread items more visible.

**Comment by leggett** [comment]
I have a change pending to increase the different in the font color which looks like this:

<img width="1113" alt="Screen Shot 2021-03-01 at 9 55 51 AM" src="https://user-images.githubusercontent.com/8763662/109537950-5ffad080-7a74-11eb-86c0-328ec6395402.png">

I'm trying to avoid adding a background color to unread items as it adds a lot of zebra-striping to the inbox.

**Comment by rcdailey** [comment]
That's much better, I personally think coloring the rows would look nicer, but that's not a very useful argument to have. Thank you for the quick response.

**Comment by leggett** [comment]
I say this not to convince you but to give a little more background into my thinking... I feel like any kind of background not only adds visual noise (the zebra striping) but also makes the unread items jump out at me too much like they are shouting – I'M UNREAD! READ ME NEXT! And that makes my inbox more stressful. 

Even if the background is really close to the background color like this:
![image](https://user-images.githubusercontent.com/8763662/109539406-21661580-7a76-11eb-8016-2aa62bff2819.png)

I acknowledge that this is **super** subjective and subtle.

**Comment by rcdailey** [comment]
I personally think that's perfect. I do want unread items to scream at me. Because they need my attention. But not everyone will feel that way. I'm also hesitant to say you could make this a feature toggle (or add some basic CSS styling to the settings page) but adding too many options is itself an issue. I think getting the right amount of contrast in dark themes is harder than with light themes. So maybe extra options like this may help out.

Up to you but just wanted to share my personal thoughts and opinions with you. Thanks for hearing me out.
