### ISSUE TITLE
Spam display issue

### ISSUE THREAD

**Issue by error9900** [leggett/simplify#547]
Just installed the extension, went to the Spam folder/label and it doesn't seem to be displaying properly:

![image](https://user-images.githubusercontent.com/19411194/109601209-662c9380-7aec-11eb-9f88-c7bf165e44c5.png)

---
Simplify v.2.3.3 - Configuration: aAX ca4 caD caE caI cfA cfC cfF cfI cfK cfO cfQ cfR cfS cfU cfZ composeActions darkTheme dateGroup hideListCount hideMsgCount hideTabIcons highDensity inLabel inList invertAddons invertCompose izBgDefault listWidthLg matchFontSize minimizeChat msgOpen msgWidthSm newUI simplify textButtons vPane - System: Mozilla/5.0 (X11 CrOS x86_64 13597.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.186 Safari/537.36 - Window: 1536 x 816 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Well that's no good. :/

I must have broken this when I was moving the "Select all" banner off the search box when the nav is closed. 

I have a fix already. Will go out with v2.3.4.

**Comment by error9900** [comment]
Thanks for the quick response. Looks like I can work around it in the mean time by expanding the side menu. 👍
