### ISSUE TITLE
Misaligned compose toolbar when minimizing mole view alongside a full-screen response

### ISSUE THREAD

**Issue by jayarr100** [leggett/simplify#549]
This is a weirdly specific situation, I realize, but I just encountered what seems to be a bug with the latest Simplify Canary release.

In Chrome (stable) on Windows, I was in the midst of composing a new message in the mole window when I opened up an existing thread alongside it and started to write a response there — using the standard full-screen in-line reply window.

I then minimized the mole window, and....well, see this screenshot: https://drive.google.com/file/d/11S47S_-wnMdttpdGaA-Ef7z-VP6SLIOI/view

The toolbar (with the Send buttons, the formatting commands, and so on) for the reply window remained shifted over to the left, despite the mole window being minimized and no longer in its way, and it consequently became misaligned with the reply window's adjusted placement.

I'm able to reproduce this consistently by replicating those same steps.

**Comment by leggett** [comment]
Yeah, this is a tough one where the stars are out of sync. To trigger it, the inline reply has to be partially scrolled off the bottom of the page (long reply and/or a long thread you are replying to). If you click into the message body, it gets back into sync. I haven't figured out a way to force it to stay in sync.

https://user-images.githubusercontent.com/8763662/109707296-d79d2e00-7b4e-11eb-908b-283e1a48219a.mp4

**Comment by leggett** [comment]
I might be able to grab document.activeElement and focus the message body and then switch focus back to the activeElement.

**Comment by jayarr100** [comment]
I noticed that, too — extremely quirky. Probably not the biggest deal in the world or something that'd come up all that often for most people, either, but I figured I'd pass it along just in case it was something you had any reasonable way to fix...

**Comment by leggett** [comment]
A fix for this is in v2.3.8
