### ISSUE TITLE
White bar appearing over text on Safari

### ISSUE THREAD

**Issue by eneerhut** [leggett/simplify#550]
I opened an email in Gmail and clicked reply. The UI from the reply box appears over text when I scroll down. 
I am using Safari `Version 14.0.3 (15610.4.3.1.6, 15610)` on `macOS Catalina`.

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/11349863/109728051-56539480-7b6a-11eb-86af-c8bf4beac1c8.png">

---
Simplify v.2.3.0 - Configuration: simplify lowDensity nPane sendLater caL cfQ hideMsgCount hideListCount cfC cfO invertAddons ca3 matchFontSize izBgDefault cfU hideTabIcons caI listWidthLg minimizeChat invertCompose msgWidthSm dateGroup composeActions cfR aAX navOpen lightTheme defaultTheme inMsg - Browser: 5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15 - Window: 1414x957 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
v2.3.2 just got approved for Safari and fixes this problem. Took a little while because Apple rejected the update because I linked to the blog post on pricing and they thought I was trying to avoid using Apple's in-app payments. :/

**Comment by eneerhut** [comment]
Excellent!
Yeah, that's one way to get on their radar ;)
