### ISSUE TITLE
Schedule Button Turns into a Column

### ISSUE THREAD

**Issue by ymolodtsov** [leggett/simplify#551]
The scheduling button turns into a giant column for me in the last few days.

<img width="920" alt="Screen Shot 2021-03-03 at 11 42 40" src="https://user-images.githubusercontent.com/2446078/109778346-c539f780-7c15-11eb-925b-2e442f0c9870.png">

This is Simplify 2.3.0 in Safari.

**Comment by leggett** [comment]
This is fixed on Safari with v2.3.2 (finally got approved yesterday)
