### ISSUE TITLE
delete spam message panel is enormous

### ISSUE THREAD

**Issue by derylseale** [leggett/simplify#552]
The "delete spam messages" panel, which used to be at the bottom of the message list, is now in the message reader panel, and it's huge. Version 2.3.3.

<img width="1175" alt="Screen Shot 2021-03-03 at 9 24 54 AM" src="https://user-images.githubusercontent.com/1426718/109819705-57380500-7c02-11eb-8e32-227b086844c2.png">

**Comment by leggett** [comment]
Have a fix coming in v2.3.4.

It is normal if the nav is open.
