### ISSUE TITLE
Unresponsive Gmail Tab

### ISSUE THREAD

**Issue by JaceHensley** [leggett/simplify#553]
I leave two Gmail tabs pinned in Firefox Dev Edition, one is for my work gmail (GSuite/Workspace) and the other is just my personal gmail. The work gmail tab never has a problem but every couple days I have to unpin my personal gmail tab close it and create a new one.

---
Simplify v.2.3.3 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions darkTheme dateGroup hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBg2 listWidthLg lowDensity matchFontSize minimizeChat msgWidthSm simplify vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10.15 rv:87.0) Gecko/20100101 Firefox/87.0 - Window: 1920 x 1175 (100pct zoom) - Language: en

**Comment by leggett** [comment]
You are the second person to report some performance issues on Firefox. I'm reviewing the code for the entire extension to see if I can find any possible issues and am adding some logging to try and help figure out what is going on. But if there was an issue, I would expect a lot more people to be reporting problems. So maybe it is specific to a certain setup or situation? 

It is interesting that your Workspace account is fine but not your personal account. 

- Do you use them differently in any way? Different configurations or anything else?
- Do you use the tabbed inbox on your personal? Are those tabs all full or do you keep a pretty empty inbox?
- Any other guesses or things I might try to replicate the issue?

**Comment by JaceHensley** [comment]
- Both are setup up pretty much the same, reading pane to the right
- I don't delete emails out of my inbox and I've had my personal account for a while, so there's like 60k emails in my personal account and 3k in my work email
- I use FF's Containers, so I have a separate container for work and personal tabs. That might be related

Thank you for looking into this!

**Comment by leggett** [comment]
I pushed out an update to Firefox this morning (v2.3.4). Let me know if that helps at all.

**Comment by leggett** [comment]
I found one issue with the Firefox version of Simplify and made some changes in v2.3.7. I'm going to close this issue but let me know if you are still having problems.
