### ISSUE TITLE
Disable empty sections when using Priority Inbox

### ISSUE THREAD

**Issue by rcdailey** [leggett/simplify#555]
Could you please add an option to hide empty categories when using priority inbox?

In the below screenshot, I do not want to see "Unread", "Woohoo!", "Important". Those are empty and create clutter.

![image](https://user-images.githubusercontent.com/1768054/110261339-770a5880-7f75-11eb-99fd-c0028c89960f.png)

---
Simplify v.2.3.3 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions darkTheme dateGroup hideListCount hideMsgCount hideTabIcons htmlEmail inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity matchFontSize minimizeChat msgWidthSm nPane newUI simplify - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36 Edg/89.0.774.45 - Window: 1666 x 1359 (101pct zoom) - Language: en

**Comment by leggett** [comment]
Gmail has this built in already. Check the overflow menu to the right of the section > Hide when empty
