### ISSUE TITLE
Simplify Gmail link in Settings opens the extension settings page twice

### ISSUE THREAD

**Issue by error9900** [leggett/simplify#556]
Clicking the `Simplify Gmail` link in Gmail's Settings opens the extension settings page twice.

![image](https://user-images.githubusercontent.com/19411194/110265760-50a2e800-7f8a-11eb-9d59-8b5f61d09d6e.png)

(Also looks like it's not properly pre-populating this Issue with my system info:
Chrome: Version 88.0.4324.208 (Official Build) (64-bit)
Simplify Gmail: 2.3.3)

---
System: Mozilla/5.0 (X11

**Comment by leggett** [comment]
Nice find -- thanks. Fix will be in next update.
