### ISSUE TITLE
Cursor/focus when starting to compose a new email

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#557]
When I click the Compose (+) button in regular Gmail, the new message dialog appears with my cursor blinking in the TO field so I can start adding the recipient(s) right away.

With Simplify enabled, when I click Compose, the new mail dialog appears but as far as I can tell, the cursor isn't positioned anywhere, so I can't simply start typing the message or adding the recipient(s).

Would it be possible to mimic Gmail's default behavior and put the cursor in the TO recipients field?

I'm experiencing this using Simplify v2.3.3 on Chrome 89 for Windows. For reference, I also have the Textblaze extension enabled. The issue described above occurs both in my personal Gmail account and my work G Suite account (the latter has multiple senders configured).

_Edit: typo_

**Comment by leggett** [comment]
Unfortunately, I can't reproduce this issue... even with Textblaze enabled. It definitely should be focused in the TO field. 

Do you have any other extensions installed that have access to Gmail? Or maybe you can send a system report via email (instructions at the bottom of [simpl.fyi/support](https://simpl.fyi/support))

**Comment by erikgeurts** [comment]
Good to hear that it's supposed to focus in the TO field. I don't rule out it's something specific to my way of using Gmail/Chrome. I did just check it on my Chromebook (Chrome OS 88) and the same issue occurs there as well.

Here is my system report (from my Chromebook):

> Simplify v.2.3.3 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU cfZ composeActions composeFormat dateGroup defaultTheme hideMsgCount hideSelectRefresh hideTabIcons highDensity inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg matchFontSize minimizeChat msgWidthSm newUI sendLater simplify - System: Mozilla/5.0 (X11 CrOS aarch64 13597.105.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.208 Safari/537.36 - Window: 1152 x 675 (100pct zoom) - Language: en

I don't have many other extensions installed, and none that I think have a lot of impact on Gmail. I do have "Office Editing for Docs, Sheets & Slides" which I think is pretty common, and another is "Go Back with Backspace" (see https://chrome.google.com/webstore/detail/go-back-with-backspace/eekailopagacbcdloonjhbiecobagjci ). I tried if disabling the latter makes any difference in this respect, but it does not.

**Comment by leggett** [comment]
I think I found it -- do you default to full screen compose? And if you disable that (see below), do you still have the issue?

<img width="380" alt="Screen Shot 2021-03-09 at 11 29 18 AM" src="https://user-images.githubusercontent.com/8763662/110526517-be562d80-80ca-11eb-8a28-405b626da1e3.png">

**Comment by erikgeurts** [comment]
I did just disable that and in the tiny compose window that remains, the cursor is positioned in the TO field automatically when I start a new email.

However, full screen (which is actually not that full ;) ) is my way to go. I wished it would be even bigger, in fact. I have fond memories of when a new mail simply looked almost identical to what it looks like when replying. Perhaps you could make that a reality again as well.

But for now, if the cursor would end up in the TO field when composing a new email in full screen mode as the default would be great.

**Comment by leggett** [comment]
P.S. I will consider allowing the full screen composer to be wider... maybe match the width of the conversation which I now allow to be wider via options. But I don't think you want it to be the entire height of the screen unless you have written a long email.

**Comment by erikgeurts** [comment]
Yes, I'm talking mostly about the width of the box. And the current look of the full-screen compose dialog isn't bad, don't get me wrong. I do actually tend to write pretty long emails, by the way. In your screenshot (you appear to have a very large screen), it could also be a bit higher, then the user would have a better overview of the entire email without having to scroll to much. Perhaps an option for height as well (I'd go for 80% myself)?

What I appreciated the most in the past was that the "Label" dropdown was so much easier to reach, in just a single click, whereas now I have to click the triple dots bottom right first, then move to the Label entry and then the list appears. I'm a huge Labels user, and it's very easy to add a label (or more) when reading an incoming email, but not so much when writing a new one. This could easily be improved by adding a little label icon in the bottom bar of the new mail dialog.

**Comment by erikgeurts** [comment]
I updated the extension to 2.3.4 and the cursor is now positioned in the TO field when starting to compose a new message with full screen mode enabled. Very nice!

However, there is now a extra empty space between the button row and the bottom of the dialog:
![image](https://user-images.githubusercontent.com/5102461/110594460-22d1c500-817d-11eb-8646-a3737607f6ef.png)
Perhaps that's intentional?

I do still think that the compose dialog is a little bit too short now in comparison to the overall size of my screen and Gmail window. And I'd prefer the dialog to be a bit wider as well. Both of these would probably be handled better in a separate issue here.

**Comment by erikgeurts** [comment]
In my work G Suite account I do have multiple From addresses and there the gap is not present, so that makes sense. I very much appreciate all your effort to perfecting this!
