### ISSUE TITLE
Improve UI for multi-page tag prev/next page

### ISSUE THREAD

**Issue by alanhoyle** [leggett/simplify#559]
If you have a tag that extends to multiple pages, it would be better if the widths of the prev/next page control was a consistent width and the previous/next buttons stayed in the same location between page flips.

If you're going fast, you might click next, then previous really quickly as the control expands and moves around.  

![Screen Shot 2021-03-12 at 5 03 03 PM](https://user-images.githubusercontent.com/289779/111008644-8f0c1e80-835f-11eb-9879-544bf55aeea9.png)
![Screen Shot 2021-03-12 at 5 03 10 PM](https://user-images.githubusercontent.com/289779/111008645-8fa4b500-835f-11eb-916e-5c5bc591b28e.png)
![Screen Shot 2021-03-12 at 5 04 02 PM](https://user-images.githubusercontent.com/289779/111008646-8fa4b500-835f-11eb-89cd-4ec0f402dcc4.png)

**Comment by leggett** [comment]
This is a tricky one. I hide the buttons when they are disabled which is nice in the most common cases: 

- you have fewer than 100 items in a list (you see no buttons)
- or if you are at the start of the list (you just see the next button)

But if you are jumping between pages, it is worse as you point out. 

It is difficult to hide the buttons only when they are both disabled. I can keep them both visible on the last page (a disabled button after an enabled button). I'll do that to minimize the jumping around.
