### ISSUE TITLE
Alt+D conflicts with browser-level shortcut

### ISSUE THREAD

**Issue by yshyonli2** [leggett/simplify#560]
Hello! When pressing Alt+D to temporarily reverse the order of messages, the focus also switches to the browser address bar in Chrome. This means I have to click/tab back to my inbox in order to continue interacting with it. As far as I can tell this is a browser-level shortcut, and not the cause of an extension (though I could be wrong).

Would this be possible to fix? Thanks!

---
Simplify v.2.3.5 - Configuration: aAX ca3 caD caI composeActions composeFormat dateGroup defaultTheme hideEmptySections hideListCount hideMsgCount hideSelectRefresh hideSignatures highDensity inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg matchFontSize minimizeChat msgLabelsRight msgWidthSm newUI reverseMsgs sendLater simplify - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36 - Window: 2560 x 1400 (100pct zoom) - Language: en

**Comment by leggett** [comment]
So it is! Thanks for the report. 

Since Ctrl+L is the more widely used/known shortcut, I think I'll just take over Alt+D (e.g., stop the event from getting to the browser). Will change in next update.
