### ISSUE TITLE
Feature Request: Hide Gmail Categories

### ISSUE THREAD

**Issue by stevebertan** [leggett/simplify#561]
I don't use Gmail's categories (Social, Updates, Forums, etc.) and would love to hide them altogether from the interface. In particular the label selector where I sometimes inadvertently select these categories when applying a label.

**Comment by leggett** [comment]
You can drag them to being under the "More" section in the nav. 

I could probably add an option to hide them in the Add Label / Move to menu. It would be based on the name though, so it would take some work to do across languages.

**Comment by stevebertan** [comment]
Yes moving them to "More" is helpful for cleaning up the sidebar.

I'm not sure if this is a safe assumption but the Gmail categories always appear at the end of the Add Label / Move menu so maybe just hiding the last 4 items so it wouldn't need to be language specific.

**Comment by leggett** [comment]
Yeah, they are at the end of the Move To menu and at the end of the Add Label menu UNLESS they are already applied in which case they are at the top. So can't do it based on position alone.
