### ISSUE TITLE
Auto-switch between light and dark theme based on OS preference

### ISSUE THREAD

**Issue by duttaoindril** [leggett/simplify#562]
Hi, I just have a feature request - auto switch the theme of Gmail based on the system setting.

https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/

Thank you!

**Comment by leggett** [comment]
This is on my list. It will be a little tricky because Gmail can be touchy about changing the theme (it doesn't always fully change and sometimes requires you reload Gmail). But I'm going to give it a try.

And thanks for the article... that is a slightly more elegant way of detecting the system preference changing.

**Comment by duttaoindril** [comment]
> This is on my list. It will be a little tricky because Gmail can be touchy about changing the theme (it doesn't always fully change and sometimes requires you reload Gmail). But I'm going to give it a try.
> 
> And thanks for the article... that is a slightly more elegant way of detecting the system preference changing.

Awesome, I don't mind a reload, and your welcome!

**Comment by rajadain** [comment]
I'd love it if we could just make the dark theme show up in the quick settings menu. The light theme is here, but the dark theme must be accessed by opening the View All modal and scrolling down to find it.

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/1430060/209350727-7968c0fb-be1a-4c7c-aad9-f6f1cb328bb8.png">

**Comment by megaroeny** [comment]
Is this still not implemented? I thought it was, but not sure if it's working @leggett 

I don't quite understand the "Enhanced Dark mode" preferences. There's a "Sync with OS" but it doesn't seem to work, at least on my Windows PC. This screenshot was taken at night when my Windows is in dark mode, but as you can see, Gmail is still in Light theme.

![image](https://github.com/leggett/simplify/assets/1559447/39d59660-8d30-44ca-85b8-d811a3089a77)

---

### My system info

Simplify v.3.1.11 configuration: aAX avatarsInList avatarsZoom caA caI caL cfC cfO cfQ cfR cfU composeActions composeFab defaultTheme fontList fontMsg fontNav hideAds hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons importantBadge inInbox inList invertAddons invertCompose izBg3 lightTheme listWidthLg lowDensity maDone maPin matYou msgWidthSm nPane navOpen newNav newUI reminders rightImportance rightLabels rightStar sendLater simplify simplifyCanary simplifyPrefsOpen unreadDot- 

System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0 - gmail.pinto-server_20240128.06_p0 - Window: 1974 x 915 (114pct zoom) - Language: en - Errors: / 2219:49: doWhenReady(.aiL .a7J) timed out / 2390:22: Something went wrong with the click series / 0:0: Something went wrong when trying to dynamically change the theme

**Comment by leggett** [comment]
This is implemented (I just haven't gone back through old open issues to close them out since launching v3). 

From your system info, it looks like there was an error when it tried to change the theme. I would bet that it works if you refresh Gmail. Let me know if it isn't.

**Comment by megaroeny** [comment]
> This is implemented (I just haven't gone back through old open issues to close them out since launching v3).
> 
> From your system info, it looks like there was an error when it tried to change the theme. I would bet that it works if you refresh Gmail. Let me know if it isn't.

No worries!

Yeah, unfortunately, it doesn't. ☹️

**Comment by leggett** [comment]
I'll add two things:

1. I didn't add a shortcut in Gmail's quick settings for the dark theme, but I did add a keyboard shortcut to switch to/from the dark theme (⌥D on Mac, Alt+D on Windows).

2. Your app menu icons look strange... unless you took a screenshot mid-transition?
<img width="425" alt="image" src="https://github.com/leggett/simplify/assets/8763662/f4780f28-7022-4661-bfdc-a00d5af5901a">

This is what it should look like:
<img width="459" alt="image" src="https://github.com/leggett/simplify/assets/8763662/1e500cd4-d6e9-4864-95ae-22b73db5d788">

**Comment by leggett** [comment]
Ok... checking a really basic thing: You see themes in your Gmail quick settings, right? (Workspace accounts can have themes disabled by the admin.)

<img width="290" alt="image" src="https://github.com/leggett/simplify/assets/8763662/073ddcfb-10fc-406e-9a93-e8a1cfd0c227">

**Comment by leggett** [comment]
@megaroeny Feel free to email me at hi@simpl.fyi to troubleshoot further
