### ISSUE TITLE
Favicon not working?

### ISSUE THREAD

**Issue by megaroeny** [leggett/simplify#565]
For some reason, I don't see the favicon change? (I'm using the new vertical tabs if you're confused lol)

![image](https://user-images.githubusercontent.com/1559447/112168497-ba94d180-8bc7-11eb-855d-d0ee7100aa5e.png)

I'm on Edge (Chromium) v89.

**Comment by leggett** [comment]
It doesn't work if you have Gmail's advanced feature to change the favicon to show the unread count. I need to add a disclaimer to the feature.

**Comment by megaroeny** [comment]
> It doesn't work if you have Gmail's advanced feature to change the favicon to show the unread count. I need to add a disclaimer to the feature.

Got it! Okay no worries. I'm gonna turn that off anyway, since I don't need it. I use an extension to show a little inbox icon in my extensions anyway.
