### ISSUE TITLE
Simplify Canary extension does not auto-update

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#566]
Simplify Canary extension never seems to auto-update. I have to manually remove, then re-install the extension - with consequent loss of settings every time :-(

This has been an issue for me for the entire beta testing period.

---
Simplify v.2.3.9 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions grayTheme hideListCount hideMsgCount hideSelectRefresh inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matchFontSize minimizeChat msgWidthSm newUI simplify - System: Mozilla/5.0 (Macintosh Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 - Window: 1572 x 1415 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Uhg, that's awful. 

v2.3.9 was submitted on Tuesday but **just** got approved in the last 12 hours. So maybe it would have updated on its own? But if you've been having this issue all along, I'm guessing not. 

If you enable developer mode and click on the "Update" button, does that update it?
<img width="965" alt="Screen Shot 2021-03-25 at 7 25 55 AM" src="https://user-images.githubusercontent.com/8763662/112489440-ab369500-8d3b-11eb-8439-3879007f0d35.png">

Maybe if you are not signed into Chrome or you are signed in with an account other than the one that has access? I'm planning to make the extension public as I recently learned it being a private extension doesn't improve the review times (which have unfortunately gone back up to multiple days with Google recently). No idea if this will help.

**Comment by nhojb** [comment]
> So maybe it would have updated on its own? But if you've been having this issue all along, I'm guessing not.

It seems to have been an issue all along. I've certainly never noticed the extension auto-update itself and always end up doing a manual update.

> If you enable developer mode and click on the "Update" button, does that update it?

This didn't seem to work for 2.3.8 -> 2.3.9. I only had chance to try the one time

**Comment by leggett** [comment]
Ok, I changed it to unlisted instead of private (still waiting to have it approved) and then will push v2.3.10. I'll update this  when that has gone out and we'll see if it updated.

**Comment by nhojb** [comment]
Apologies for the delay replying.

This seems to have fixed the issue. For the first time Simplify canary updated automatically 😄. Now on 2.3.11 without any manual intervention on my part 🎉 . Thanks!

**Comment by leggett** [comment]
Awesome! Thanks for reporting back.
