### ISSUE TITLE
Tracker blocked icon not visible when running Chrome as a separate window/desktop app

### ISSUE THREAD

**Issue by tojoko** [leggett/simplify#568]
I'm running gmail as a "desktop app" by using Chrome's create shortcut feature with "open as window" selected. It works great otherwise, but I noticed that the tracker blocked icon is not visible even through simplify does block the tracker. 

I spent some time today to debug the issue, and it seems the issue is in the getTabId function in the trackers.js script. When running as desktop app, the windowType is "popup" and not "normal". So I found 2 ways to make it work:
- remove windowType from chrome.tabs.query's queryInfo
or
- try with windowType normal first and if it doesn't work try with windowType popup. 

The 2nd option is given as an example code below. I'm sure there's better ways to accomplish the same, I'm just not so good with Javascript :) Anyway it would be awesome if the trackers.js could be modified to support running in a separate window too. 

In any case I love running gmail with simplify, thanks for this awesome extension!

Revised getTabId function:
```javascript
const getTabId = (windowTypeEnum = chrome.tabs.WindowType.NORMAL) => {
  chrome.tabs.query(
    {
      active: true,
      currentWindow: true,
      windowType: windowTypeEnum
    },
    (tabs) => {
      if (tabs[0]) 
      {
        tabId = tabs[0].id;
      } 
      else if (windowTypeEnum == chrome.tabs.WindowType.NORMAL)
      {
        // see if we're running as shortcut in a separate window
        getTabId(chrome.tabs.WindowType.POPUP);

      }
    }
  );
  console.log("Updated tab ID", tabId);
};
```

---
System: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36

**Comment by leggett** [comment]
Nice catch! Removing the windowType doesn't seem to work for me but your function nearly does. If we're adding a parameter to `getTabId` then we need to also add one for the tab object that gets passed in when `chrome.tabs.onActivated` fires. 

This also made me realize that I need a listener for the window changing. Final code:

```
// Getting active tab's ID
let tabId = null;
const getTabId = (event, windowTypeEnum = "normal") => {
  console.log("getTabId", event, event?.tabId, windowTypeEnum);
  if (event && event.tabId) {
    tabId = event.tabId;
  } else {
    chrome.tabs.query(
      {
        active: true,
        currentWindow: true,
        windowType: windowTypeEnum,
      },
      (tabs) => {
        console.log("Tabs", tabs);
        if (tabs[0]) {
          tabId = tabs[0].id;
        } else if (windowTypeEnum === "normal") {
          // See if we're running as shortcut in a separate window
          getTabId(null, "popup");
        }
      }
    );
  }
  console.log("Updated tab ID", tabId);
};
getTabId(null, "normal");

// Update tab id when active tab or window is changed
chrome.tabs.onActivated.addListener(getTabId);
chrome.windows.onFocusChanged.addListener(getTabId);
```

**Comment by leggett** [comment]
This will go out in the next update (2.3.11)

**Comment by tojoko** [comment]
Awesome thank you so much! Looking forward to the new version!

btw I noticed that I forgot one debug line ( console.log("Tabs", tabs); ) in my example, maybe something to remove from the final code.
