### ISSUE TITLE
Add missing categories to left nav.

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#57]
Inbox had three categories that Gmail doesn't show:

- Purchases
- Finance
- Trips

These categories actually still exist and mail is still being categorized into them. But they aren't visible in Gmail anywhere. You can see them by searching for:

- category:purchases
- category:finance
- label:trips

I could at least add links to these labels in the nav. If I can find a way to show the label for these categories, I could also possibly bundle them in the inbox.

**Comment by leggett** [comment]
Look what we have here...
<img width="266" alt="Screen Shot 2021-01-27 at 2 31 28 PM" src="https://user-images.githubusercontent.com/8763662/106063002-67613f80-60ac-11eb-8a26-23ae5711254c.png">

**Comment by CarlosRebolledo** [comment]
Genial!!

Sería posible crear una etiqueta de tareas - por hacer, haciendo y terminadas?

También me imagino el agregar Etiquetas como pestañas. Es posible?

**Comment by leggett** [comment]
You can create any other label already. These are links to searches for hidden categories from Google Inbox.

**Comment by leggett** [comment]
Will be added in v2.1.20
