### ISSUE TITLE
Change screenshots on website

### ISSUE THREAD

**Issue by jaredzimmerman** [leggett/simplify#570]
No matter what setting I choose the photo background never work, only the gmail default ones. 
---
System: Mozilla/5.0 (X11

**Comment by leggett** [comment]
The background images currently only changes if you use the default white theme or the dark theme.

**Comment by jaredzimmerman** [comment]
unfortunately, they still aren't working even with that configuration.

![Screenshot 2021-03-28 9 35 03 PM](https://user-images.githubusercontent.com/430427/112765458-98f37a00-900d-11eb-8339-d95ab942911d.png)

![Screenshot 2021-03-28 9 35 14 PM](https://user-images.githubusercontent.com/430427/112765492-bcb6c000-900d-11eb-8f8d-1597ba2e0b93.png)

![Screenshot 2021-03-28 9 35 23 PM](https://user-images.githubusercontent.com/430427/112765496-c0e2dd80-900d-11eb-95fc-f7f11959bcf9.png)

**Comment by leggett** [comment]
It is only applied in the inbox when you reach inbox zero.

**Comment by jaredzimmerman** [comment]
ah, the image on your site makes it look like it would be there all the time. 

![image](https://user-images.githubusercontent.com/430427/112765740-cf7dc480-900e-11eb-8f2e-d751a630358b.png)

**Comment by leggett** [comment]
Yeah, I actually use it as my theme bg. I should change those screenshots so it isn't confusing.

**Comment by jaredzimmerman** [comment]
makes sense, thanks for clarifying.
