### ISSUE TITLE
Drag Email to Tasks seems to be broken now. 

### ISSUE THREAD

**Issue by BickitySnow** [leggett/simplify#571]
Trying to drag and drop emails to the Tasks window to create a new task and doesn't seem to work. Seems like a v2.3.9 thing. 

Please describe the issue and the steps to reproduce it. Screenshots are useful.

---
Simplify v.2.3.9 - Configuration: aAX addOnsOpen ca4 caE caI caL cfC cfF cfI cfO cfQ cfR cfS cfU dateGroup debug grayTheme hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgOff lightTheme listWidthMd lowDensity matchFontSize minimizeChat msgWidthMd nPane navOpen newUI simplify - System: Mozilla/5.0 (Macintosh Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 - Window: 1920 x 1055 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Hmm, it still works for me. Does refreshing Gmail fix it by chance?

https://user-images.githubusercontent.com/8763662/112905096-b6245900-909e-11eb-8012-0e36cb725a92.mp4

**Comment by BickitySnow** [comment]
Refreshing didn't help, but good to know it's just me. I toggled Simplify Gmail off and still doesn't work. I will close ticket. Thanks.

**Comment by leggett** [comment]
Sorry to hear that. Hope you figure it out.
