### ISSUE TITLE
Emails from Promotions tab randomly disappear until a Gmail refresh

### ISSUE THREAD

**Issue by CliffWade** [leggett/simplify#572]
This is in response to issue #567 

If there's any further information needed, please don't hesitate to let me know and I will provide it as quickly as possible.

---
Simplify v.2.3.10 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup defaultTheme hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matchFontSize minimizeChat msgWidthSm navOpen newUI simplify - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.41 Safari/537.36 Edg/90.0.818.22 - Window: 1920 x 1040 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks!
