### ISSUE TITLE
Enabling/disabling the Backspace key with Google's "Go Back With Backspace" extension present

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#574]
Having been a user of browsers for as long as they exist, I have extremely strong muscle memory for using the Backspace key to navigate back to the previous page in any browsing session. That's why I was sad when Google removed this from Chrome and happy when they created a browser extension to use Backspace again, see https://chrome.google.com/webstore/detail/go-back-with-backspace/eekailopagacbcdloonjhbiecobagjci .

However, once I started using Simplify, I discovered that I had accidentally deleted several email conversations by pressing Backspace. since that's the default functionality with Simplify.

My question: would it be possible to add a detection for this browser extension and warn users that they should consider disabling the Backspace key to delete conversations in Gmail & Simplify?

**Comment by leggett** [comment]
I can't detect another extension unless it injects something unique into Gmail. 

You can disable the backspace keyboard shortcut in Simplify options.

I will think more about how to introduce what Simplify does by default, and asking if anything should be changed.

**Comment by erikgeurts** [comment]
I'm aware (now) that I can disable this, but it surprised me when I first noticed I had deleted an entire conversation.

Also, it turns out that I have the adjust this setting (and every other setting) on each device I use. Are the settings supposed to sync between devices, or is that perhaps something that will be part of the feature set on your paid plan gets introduced?

**Comment by leggett** [comment]
Understand and agree that being surprised by that is not good, especially when it results in deleting things.

Syncing options across devices is high on my list as part of an overhaul of options all together.

**Comment by erikgeurts** [comment]
Great, looking forward to that!
