### ISSUE TITLE
Inbox Zero Google Image Appears in Sidebar

### ISSUE THREAD

**Issue by derylseale** [leggett/simplify#575]
When I choose the Google Image for Inbox Zero, it appears in the sidebar, as opposed in the full window. All the other Inbox Zero images occupy the entire window.

<img width="1136" alt="Screen Shot 2021-04-08 at 12 52 34 PM" src="https://user-images.githubusercontent.com/1426718/114066119-5d587b80-9869-11eb-8f6a-ce810cc8f542.png">

**Comment by leggett** [comment]
This is working as intended -- the illustration only goes where the list is. 

However, the gray box around the illustration is a bug and is be fixed in v2.3.10.
