### ISSUE TITLE
Disappearing Emails In Promotion

### ISSUE THREAD

**Issue by danielanewman** [leggett/simplify#576]
As an avid inbox zero person, I've noticed that, with some regularity, the Promotions tab will "blank out" when I attempt to read a new message there (not the "empty" state, but rather hiding the list view and the email body entirely)—seems to happen most reliably when there's one and only one message, unread, in the tab. I haven't noticed it on other tabs, though it's possible that it would happen elsewhere too... I have a couple read messages in other places. Here's a video:

https://user-images.githubusercontent.com/5234389/114209046-30b96800-992c-11eb-81a9-7aabbf69b560.mp4

---
Simplify v.2.3.9 - Configuration: aAX ca3 caI caL cfC cfI cfO cfQ cfR cfU composeActions dateGroup debug grayTheme hideListCount hideMsgCount hideTabIcons inInbox inList inboxZero invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matchFontSize minimizeChat msgWidthSm simplify vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 - Window: 1309 x 1027 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the report and video. I am actually working on this issue right now and I think I have it fixed. But your video gives me pause. Can you check, do you have "Enable bundling of top promo emails in Promotions" turned on in Gmail Settings > Inbox?

**Comment by danielanewman** [comment]
> do you have "Enable bundling of top promo emails in Promotions" turned on in Gmail Settings > Inbox?

I do! Although, I'll likely turn that off, didn't know that was a setting I could control and I find "Top Promotions" rather annoying!

**Comment by leggett** [comment]
Great. I'm 99% sure this is only an issue if you have that enabled (it is a new setting and I think it is on by default). If you disable it, it shouldn't be an issue on the current version.

**Comment by leggett** [comment]
I'm going to close the issue but re-open it if (a) disabling top promotions doesn't fix it now or (b) the next update (v2.3.11) doesn't fix it should you leave top promos on.
