### ISSUE TITLE
The alignment of the search bar and the emails list is off by a couple pixels.

### ISSUE THREAD

**Issue by Eenna** [leggett/simplify#577]
This corner is always just a little off, no matter how I resize it.

![image](https://user-images.githubusercontent.com/32325204/114282132-5499ae00-99ff-11eb-87e8-e1e7206b4929.png)

---
Simplify v.2.3.10 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup debug hideEmptySections hideListCount hideMsgCount hideSignatures hideTabIcons inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity matchFontSize mediumTheme msgWidthSm newUI simplify vPane - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64 rv:87.0) Gecko/20100101 Firefox/87.0 - Window: 1295 x 735 (101pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the report. I think this is due to Gmail's scrollbars being different on Firefox than any other browser. I'll look into it.

**Comment by leggett** [comment]
Fix coming in v2.3.11

**Comment by leggett** [comment]
Or at least I think I fixed it... I wasn't totally able to reproduce this issue (I tried on Mac and Windows). But I found some other issues around this area in Firefox that I did fix. Pushing out the update today and we'll see if it is any better.

**Comment by Eenna** [comment]
The update fixed the look of it on idle and when you have the left side menu open. (Thank you!) But it goes back to being a little off when you're hovering over the "main menu" button.

![image](https://user-images.githubusercontent.com/32325204/114729551-51ebd100-9cfd-11eb-9299-8ee8b636d465.png)

(I haven't changed any settings.)

**Comment by leggett** [comment]
Thanks for reporting back. Glad it is aligned now when idle. And yes, I noticed something is jiggling when you hover over the menu. I couldn't / haven't figured out what that is yet but will keep hunting for it.
