### ISSUE TITLE
Add scroll keys to keyboard shortcut overlay

### ISSUE THREAD

**Issue by rhulse** [leggett/simplify#580]
It's be nice to have up/down keyboard navigation on the help page. Up/down arrows?

Extra points for <home> to return to the top of the page, <end> to the bottom.

**Comment by leggett** [comment]
Are you talking about this?
<img width="396" alt="Screen Shot 2021-04-20 at 2 21 49 PM" src="https://user-images.githubusercontent.com/8763662/115465704-d77eed80-a1e3-11eb-9213-9299f032150b.png">

You can use tab / shift+tab to move between topics in that screen.

**Comment by rhulse** [comment]
The hotkey help page.... :-)

**Comment by leggett** [comment]
AHH... got it. Looks like the page doesn't get focus. If you click anywhere on the page you can scroll with your keys. I'll figure out how to focus the page automatically.

**Comment by rhulse** [comment]
Sounds good, thanks. (Focus may also be an accessibility consideration.)

**Comment by leggett** [comment]
Will go out in v2.3.12
