### ISSUE TITLE
Pencil icon on New mail button slightly off center

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#581]
The revised New mail button showed up in my Gmail and Google Workspace accounts earlier this week.

The Pencil icon is slightly to the left of center of the button for me:
![image](https://user-images.githubusercontent.com/5102461/115989112-010d8f80-a5bd-11eb-843e-79fa8cd953a0.png)

The button works perfectly, it's just the visual appearance that's a little bit distracting.

Simplify v.2.3.11 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFormat dateGroup defaultTheme hideListCount hideMsgCount hideSelectRefresh hideTabIcons highDensity inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg matchFontSize minimizeChat msgLabelsRight msgWidthMd newUI sendLater simplify - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 - Window: 1324 x 820 (101pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the report -- fix will go out today with 2.3.12
