### ISSUE TITLE
Suppress "external" warning labels?

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#582]
Given that I operated a tiny company (a one man band), essentially all of my emails come from or go to external mail addresses.

As such, the new External label that Google have put in my emails are just a distraction, they don't add any value for me.

Would it be possible to add an option that enables me to suppress these? I've already adjusted the toggle in Workspace settings that's supposed to disable these several days ago, but it does not work, the label is still being displayed today:
![image](https://user-images.githubusercontent.com/5102461/116853518-7c42f700-abf6-11eb-9f26-6bceb4091c23.png)

And also the one at the bottom while composing a new reply, could that optionally be suppressed as well?

![image](https://user-images.githubusercontent.com/5102461/116853588-9c72b600-abf6-11eb-9b89-fd4ab4417c45.png)

Not only is it very distracting, but it also seems to displace the formatting buttons from where they're supposed to be.

**Comment by leggett** [comment]
You can disable them via the Admin console: https://support.google.com/a/answer/7380041

I will look into options to make them more subtle or hide them altogether.

**Comment by erikgeurts** [comment]
I already disabled that last week, but it doesn't do anything, the labels still appear.

**Comment by leggett** [comment]
Got it. Sorry I missed you said that in your initial report. Strange that the setting doesn't work. 

I don't see these on my own test Workspace account. Hopefully it will show up soon so I can work on it.

**Comment by leggett** [comment]
I have these in my test account now and will work on suppressing them in the next update. I'll probably make it an option but default it to on (suppressing).

**Comment by leggett** [comment]
I suspect the option for this will have multiple options, one where I get rid of all decoration for external addresses and one where it is heavily muted (just decorate external addresses, but hide all warnings/labels), and one where I leave it as is.

For that middle case, I'm thinking about adding a bit of background (20% opacity yellow) to external addresses to balance dropping the massive warning banner. Thoughts?

<img width="829" alt="Screen Shot 2021-05-19 at 1 01 20 PM" src="https://user-images.githubusercontent.com/8763662/118876923-aa852f80-b8a2-11eb-8de4-9fd563db11ac.png">

**Comment by CarlosRebolledo** [comment]
Hola Michael!!! En mi caso prefiero 20% de opacidad en amarillo. Me permite minimizar distracción sin eliminar por completo las advertencias y etiquetas 

Nota: Aún siento útiles las etiquetas, aunque lo serían más si pudiesen funcionar como Superhuman en que haces click sobre ellas en el mismo correo y te lleva a todos los correos bajo esa etiqueta

**Comment by leggett** [comment]
That is how all the real labels work. But, the "External" label isn't a true label... more of a badge. So no way to click on it.

**Comment by erikgeurts** [comment]
> I suspect the option for this will have multiple options, one where I get rid of all decoration for external addresses and one where it is heavily muted (just decorate external addresses, but hide all warnings/labels), and one where I leave it as is.
> 
> For that middle case, I'm thinking about adding a bit of background (20% opacity yellow) to external addresses to balance dropping the massive warning banner. Thoughts?
> 
> <img alt="Screen Shot 2021-05-19 at 1 01 20 PM" width="829" src="https://user-images.githubusercontent.com/8763662/118876923-aa852f80-b8a2-11eb-8de4-9fd563db11ac.png">

I like that idea, because it does the job of warning the user, without being so much in your face and distract from what you're doing. I'll personally expect to turn it off completely, but at least it gives everyone a choice.

**Comment by CarlosRebolledo** [comment]
> Así funcionan todas las etiquetas reales. Pero, la etiqueta "Externa" no es una etiqueta verdadera ... más bien una insignia. Así que no hay forma de hacer clic en él.

Sí, entiendo que son distintas. 

Y las etiquetas funcionan así cuando está el correo abierto, pero no cuando está en la bandeja de entrada, caso en el cual, al primer click en la etiqueta abre el correo y al segundo click en la etiqueta te lleva a todos los correos bajo esa etiqueta. Lo ideal sería ir al primer click

**Comment by leggett** [comment]
Ah, yes, you can't click on the label from the inbox. That's because they don't want to make it too hard to open the message. Some people use a lot of labels. But even if you only used one, you'd have to be a lot more careful where you clicked to open a message so you didn't go to the label instead. I think it is the right trade off.

**Comment by leggett** [comment]
I'm including a setting for this in the next update (v2.4.0). I default to a suppressed version (what I showed above) but allow you to set it to "Don't suppress" or "Hide completely."

I don't seem to have the warnings on my test Workspace account so you'll have to let me know if it doesn't work as expected.

**Comment by leggett** [comment]
P.S. The Simplify setting is **Message view** > **Suppress external recipient warnings**
