### ISSUE TITLE
extension compatibility issue with "voice in" extension?

### ISSUE THREAD

**Issue by perler** [leggett/simplify#587]
can you have a quick look, why this extension isn't working when using simplify gmail? https://chrome.google.com/webstore/detail/voice-in-voice-typing/pjnefijmagpdjfhhkpljicbbpicelgko?hl=en - I will ask the devs of "voice in" the same, maybe you can find a way..

**Comment by leggett** [comment]
Thanks for the report -- I haven't seen this extension before and will look into it. 

I track the extensions I've tested or done work to play nicely with here:
https://github.com/leggett/simplify/issues/554

**Comment by leggett** [comment]
I'm able to use this extension in Gmail with Simplify enabled. Can you give me more information about what wasn't working?

**Comment by perler** [comment]
oh.. suddenly it works on my end as well.. magic. thanks! :)
