### ISSUE TITLE
Small avatar missing from right top corner of browser in GSuite

### ISSUE THREAD

**Issue by gearfab** [leggett/simplify#590]
The small avatar is now gone from right top corner of browser in GSuite, so the automatic hiding and showing on mouseover for settings, support, Google apps, etc. is all missing as of this morning. Working normally in regular Gmail.

![avatar](https://user-images.githubusercontent.com/2294947/121368167-7aa8d500-c900-11eb-8bf0-ae9e2e65036f.jpg)

---
System: Mozilla/5.0 (Macintosh

**Comment by leggett** [comment]
Ok, fix checked in. Will be out to everyone as soon as update is approved.
