### ISSUE TITLE
Delete key in list view wired to trash(delete)

### ISSUE THREAD

**Issue by rhulse** [leggett/simplify#592]
It would be useful to have the delete key wired up to delete the highlighted item in list view.

The use case is for alerts and other emails that you don't actually need to open. In my case I get emails from a test server that I do not need to read unless it is me doing the testing.

If you think a single key is too risky, a combination (command/ctrl + delete) might be better, and this should probably be off by default.

A key for the undo option (that appears for a few seconds) to be used with this would also be useful too.

**Comment by leggett** [comment]
It is a feature already but it is the one keyboard shortcut I don't have on by default. Check Simplify options.

**Comment by rhulse** [comment]
OK, thanks. I found the issue - I did not also have "Auto-select message in list for one-key shortcuts" on as well. My bad. :-)
