### ISSUE TITLE
Select no longer prompts to "Select all N conversations in ..." if there are more than fit on the screen

### ISSUE THREAD

**Issue by alanhoyle** [leggett/simplify#593]
I have run a search or am in a label with more entires than can display on the screen, I can click the checkbox at the top to select items there (or use the associated drop-down for All/None/Read/Unread/Starred/Unstarred).

Under regular Gmail, it offers me the ability to "Select all conversations that match this search" 
![Screen Shot 2021-06-11 at 4 56 13 PM](https://user-images.githubusercontent.com/289779/121747806-f314bf00-cad5-11eb-94d8-d8f7614b0c17.png)

or "Select all conversations in &LT;LABEL&GT;"

![Screen Shot 2021-06-11 at 4 47 48 PM](https://user-images.githubusercontent.com/289779/121747043-c613dc80-cad4-11eb-88bb-7768f3731656.png)

WIth Simplify enabled, these prompts no longer appear.  To delete large numbers of things, I either have to do them 100 at a time (the number I allow on my screen), or go to a non-Simplify browser to get the prompt.  

Please restore the prompt.  

I'm running Simplify in WaveBox for macOS, version 10.0.542.2, which is a Chromium-based browser, and appears to tell servers that it's Chrome/91.0.4472.77

**Comment by leggett** [comment]
Thanks for reaching out. 

Unfortunately, I can't reproduce this bug. Maybe it is an issue with using WaveBox? What version of Simplify do you have? Can you attach a system report? Directions on how to do that are at the bottom of [simpl.fyi/support](https://simpl.fyi/support)

**Comment by leggett** [comment]
A screenshot of your whole window (you can use a search in your spam folder) with Simplify enabled might also help.

**Comment by alanhoyle** [comment]
By habit, I clear my spam filter daily, so it would be a few days before I could accumulate enough mail there.

However, the issue I'm running into is that Simplify isn't showing the regular version's "select all conversations" prompt in any way.  The screenshots in my original report are from _regular_ Gmail, not aided by the extension.  

I discovered today that the same issue exists in the Windows version of WaveBox as well (same version.  

Below you'll find the system report from the macOS Wavebox, my primary platform and the one from the original report.  (As an aside, the keystroke there is ⌥ i  aka option i, not Alt i.)     

----

Simplify v.2.4.1 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity matchFontSize mediumTheme minimizeChat msgOpen msgWidthSm navOpen showChat simplify supExtWarn vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 - Window: 1564 x 1440 (94pct zoom) - Language: en

**Comment by alanhoyle** [comment]
Below are two screenshots.  in both cases, I brought up the "Forums" page which happens to have this bug report at the top of my inbox.  Then I clicked the checkbox at the top:  just below the search box in regular Gmail, and just to the right of the search bar in Simplify.  

Regular Gmail in Brave browser:
![Screen Shot 2021-06-12 at 2 56 15 PM](https://user-images.githubusercontent.com/289779/121786642-2404fa80-cb8f-11eb-9038-81623358fdf6.png)

Simplify Gmail in WaveBox

![Screen Shot 2021-06-12 at 2 55 52 PM](https://user-images.githubusercontent.com/289779/121786645-2c5d3580-cb8f-11eb-83f5-2bbe5f747ef1.png)

**Comment by leggett** [comment]
Thanks for the screenshots, I see the issue now and will fix it in the next release.

For now, here are some workarounds:

- If you close the nav, you will see the option to select all-all. 
- You can also use Simplify's ⌘⇧A shortcut (Selects all including beyond current page whereas ⌘A only selects all on the current page)

**Comment by alanhoyle** [comment]
Thanks!  that work-around will work for now.

**Comment by alanhoyle** [comment]
My Spam folder has finally exceeded my pagination limit:  is there any reason for me to add more screenshots?

**Comment by leggett** [comment]
Nope, I was able to reproduce the issue once I got your system report. Thanks for checking!

**Comment by leggett** [comment]
I think I fixed this a long time ago (in v2.4.3). Please re-open if it is still an issue.
