### ISSUE TITLE
Navigation More/Less Toggle

### ISSUE THREAD

**Issue by craigerskine** [leggett/simplify#595]
![simplify-more-less](https://user-images.githubusercontent.com/56437/122401158-f8dd2b00-cf41-11eb-99f3-bc311e639cd1.png)

Is it possible to visually "separate out" the more/less toggle so it's easier to find and use (especially when it's expanded)? It looks just like the other nav items which is misleading. [See example - this is just an example, I'm not trying to dictate a design direction]

**Comment by leggett** [comment]
Good suggestion. Definitely agree it gets lost when expanded.

**Comment by leggett** [comment]
Finally fixing this in v2.5.8 by just adding some margin below the toggle:
![image](https://user-images.githubusercontent.com/8763662/145667340-8ea9eda3-0bbc-493d-981f-000465fffe9b.png)
