### ISSUE TITLE
free trial ended -12hs ago

### ISSUE THREAD

**Issue by osbyrne** [leggett/simplify#597]
![image](https://user-images.githubusercontent.com/68084397/126883638-d624e23c-ba92-4884-b5aa-dc2da940b166.png)
my trial ended 12 hs ago apparently. im glad to have it but it's still a bug to report
---
Simplify v.2.4.4 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU changeFont composeActions hideListCount hideMsgCount hideSelectRefresh hideTabIcons hideUnreads importantBadge inInbox inList izBgOff listWidthMd lowDensity mediumTheme minimizeChat msgWidthSm nPane simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (X11 Linux x86_64 rv:90.0) Gecko/20100101 Firefox/90.0 - Window: 1280 x 702 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Kind of you to report. It should stop working next time you refresh Gmail. I didn't want to suddenly disable it while you were in the middle of a task. Let me know if it doesn't.

Related: it looks like you are on Firefox. I *just* launched the subscription on Firefox so you should have 12-14 days. And I only launched it to 1% on Chrome so far and that was 5 days ago. 

So, either 

- you also have the Canary build installed on Chrome and happened to open it there 2 weeks ago to start your trial (I launched there a few weeks ago)
- there is a bug with updating how much time is left. Refreshing Gmail may fix it showing you have days left, not -12 hours
- there is a bug with calculating how much time you have left (not just what to show) and refreshing Gmail disables Simplify

**Comment by osbyrne** [comment]
It's working now! As you advised, i refreshed gmail and I got the update.
Thank you!

**Comment by leggett** [comment]
Ok, so the original time calculation was wrong then? You had the update (v2.4.4 is the latest) when you first reported the issue. But maybe something didn't load right after the update until you refreshed? 

Either way, glad it's working now.

**Comment by leggett** [comment]
I figured out the issue on this. It only breaks on the initial trial registration. Thanks again for reporting this -- it was super helpful and preventing confusion for a lot of customers.
