### ISSUE TITLE
Support split-pane view

### ISSUE THREAD

**Issue by rpartha** [leggett/simplify#6]
1) The settings and view density buttons overlap.
2) The account logo at the top right has an ugly white border surrounding it, which is more noticeable when using non-default themes.
![image](https://user-images.githubusercontent.com/3248921/55578980-2fbe2200-56e5-11e9-96f4-a6bf4dd7c6f1.png)

**Comment by leggett** [comment]
Thanks, both are known issues and should be addressed soon.

**Comment by leggett** [comment]
By the way, that button isn't actually a density setting button, it is part of split pane view. If you don't use split pane, you can turn it off under Settings > Advanced > Preview Pane. If you do use it, give me a few days for proper support. (I didn't dig into the advanced options before launching so taking care of them now.)

**Comment by rpartha** [comment]
Ok thank you for the quick response. I didn't know you could disable it.

**Comment by leggett** [comment]
Both of these are fixed in the latest code. Will check into Chrome Web Store soon.
