### ISSUE TITLE
[feature request] search bar location

### ISSUE THREAD

**Issue by t0mmyz7** [leggett/simplify#600]
Hi there

I must prefer the original search bar location, as I find that I have to scroll up and to the right to hit the search bar, while with the original I just scroll straight up.

so maybe have an option to keep it in the original place, control it's width, or something along those lines:

original (preferred by me)

![image](https://user-images.githubusercontent.com/31729091/127276349-eedc1bb2-149f-44db-91ca-d30c49b3fd66.png)

simplfy:

![image](https://user-images.githubusercontent.com/31729091/127276405-548446ea-00f1-45bb-8703-430595f4de3c.png)

what do you think?

**Comment by leggett** [comment]
Putting search in the middle of the screen is crucial to merging the action bar and the search bar into one bar. If I put search on the left, the actions can not line up with the items.

**Comment by t0mmyz7** [comment]
is there a shortcut to search? that would help I supposed.

or could you add a feature to disable top-bar modification? or to allow this option to have search bar as deafult and some customization to the right of it ?

**Comment by erikgeurts** [comment]
Yes, just press the / key to start searching.

**Comment by leggett** [comment]
As Erik said, you can use the `/` key to focus the search box. You have to enable keyboard shortcuts to do so which you can do in the middle of the keyboard shortcuts overlay (press `?` to show that).

I try to add as few options as possible as each option doubles the number of use cases I have to test when making any change. Also, a lot of Simplify depends on the bar being the way it is (merged into one bar). So I'm not inclined to add an option for this.
