### ISSUE TITLE
Firefox issues?

### ISSUE THREAD

**Issue by Kw-git** [leggett/simplify#601]
I'm encountering two issues on Firefox, one of which is trivial, the other is not:
Trivial: the Simplify Gmail icon does not appear in the toolbars
Not so trivial: Simplify Gmail on Firefox does not recognize my existing subscription; I'd be happy to share account info outside GitHub. 

Please let me know how I can assist in debugging - MANY THANKS!
---
Simplify v.2.4.4 - Configuration: aAX ca5 caD caE caI caL cfA cfC cfF cfI cfK cfO cfQ cfR cfS cfU changeFont composeActions composeFormat dateGroup hideListCount hideMsgCount highDensity inInbox inList invertAddons invertCompose izBgDefault listWidthLg mediumTheme minimizeChat msgWidthSm nPane navOpen newUI simplify supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64 rv:90.0) Gecko/20100101 Firefox/90.0 - Window: 1549 x 837 (101pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks. Can you email me at hi@simpl.fyi to troubleshoot further

**Comment by Kw-git** [comment]
Hi Michael, I just emailed, including more details on what I found. MANY THANKS for getting on top of this this quickly! :-)

And I finally found the missing icon among the apps... I was expecting it in the toolbar, based on my prior use of simplify. :-S

**Comment by leggett** [comment]
Firefox made a change recently where the Add-on button shows up in the address bar only when you are on a site where it is active. I'm not sure if you can even hide it.

So I added the Simplify menu inside Gmail and plan to make the browser button monochromatic soon so it doesn't stand out as much.
