### ISSUE TITLE
[Feature request] Hotkey for 'move to inbox'

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#607]
I archive as many mails as possible to achieve an inbox that looks less distracting. However, from time to time I want to move mails back into my inbox so that I can pick things up again, like revisiting a project after a clients calls me, and sending a reply.

When I search and find an email in the archive, the 'move to inbox' button on the toolbar does just that, but it would be great if there could be a hotkey I could press on my keyboard to do this as well.

Frankly, I don't know what would be the best key or key combination for this, it's more or less the opposite of the 'e' to archive (which is a bit arbitrary to me as well, but of course the A is taken for Reply all).

**Comment by leggett** [comment]
You'd be surprised how many of the letters are already used up with shortcuts. 

Given E archives... maybe ⇧E should move to inbox (unarchive)?

**Comment by leggett** [comment]
Two other things to consider with this:

1. Currently ⇧E also archives... I'd have to make sure it does nothing if the message was already in the inbox.

2. There is only a "Move to inbox" button in some views (search and All Mail). There isn't a button in a label view. But I _think_ I can map the shortcut to the "Move to" menu > Inbox.

**Comment by erikgeurts** [comment]
What "move to inbox" actually does is to simply label the message with "inbox" again, right? Any other labels are retained.

I kind of like the Shift-E idea, it's the reverse of E for Archive, i.e. unarchive. As long as other labels are retained, it would work for me.

I only just realized that 'move to inbox' isn't available in label view, I tend to look up and actually open the message or conversation first to check if it's the right one, and then move it to the inbox so that I can follow up on it later. But having a move to inbox action in label view (if that's what you mean, even if there isn't a button on the toolbar) would work for me ;)

**Comment by leggett** [comment]
Yes, it appears that "Move to Inbox" simply adds the `Inbox` label in all views. And I think it always returns to the previous list view.

Since I do not have API access to Gmail, the way keyboard shortcuts work with Simplify is I map a key press to simulating a click on a button in the interface. That's why I brought up the button not always being there. But I think I can make it work in all views.

**Comment by leggett** [comment]
Ok, I have this working. It will go out to [Canary](https://canary.simpl.fyi) first in v2.5.1.

**Comment by leggett** [comment]
P.S. I also have it working with auto-select so you don't have to even select a message in list view to use the shortcut.

**Comment by erikgeurts** [comment]
If I'm not mistaken, this should have made its way to the production version. I have v2.5.4 by now.

However, I'm not sure if I've misunderstood, but my use case doesn't work as expected. My way of working is:
- I find that I need to get an email that's been archived back into my inbox
- I search for the email I need and then open it to make sure it's the right one
- I click the "Move to inbox" button on the toolbar

My hope was that the last of those 3 steps could also be achieved with the Shift-E hotkey.

**Comment by leggett** [comment]
Hmm... I'm not able to reproduce this. I searched for an email, found one not in the inbox, and when I open it and press Shift+E, it moves it back to the inbox and the email is closed.

You don't have the shortcut disabled in settings by chance, do you?

![image](https://user-images.githubusercontent.com/8763662/136990667-cb9c8e8d-bec8-4493-8af7-4c8a28fc26eb.png)

**Comment by erikgeurts** [comment]
I have the shortcut enabled, but whenever I press Shift-E while having an email open that's not in the inbox, all I get is "No conversation selected" in the bottom left corner. The mail stays open and nothing happens. Clicking the button on the toolbar does work. For the record, I tested with emails that have labels and emails that have no labels.

My config:
Simplify v.2.5.4 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFormat dateGroup defaultTheme fontList fontMsg hideListCount hideMsgCount hideSelectRefresh hideTabIcons highDensity inMsg invertAddons invertCompose izBgDefault lightTheme listWidthLg minimizeChat msgLabelsRight msgSelected msgWidthMd newUI sendLater simplify supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 - Window: 1516 x 824 (101pct zoom) - Language: en

**Comment by leggett** [comment]
The "No conversation selected" banner makes me think Simplify is trying to click on the "Move to inbox" button that is in the threadlist instead of the one in message view. 

I'm not currently trying to make sure it is the "Move to inbox" button in the current view (it didn't seem necessary in testing and that extra specificity makes bugs more likely across different Gmail setups) but maybe somehow in your setup it is an issue.

Revisiting your scenario, it sounds like you:

1. Do a search
2. Open a message
3. Hit Shift+E

A few questions:

- When you do a search, if you select a message, do you see the "Move to inbox" button?
- When you open the message, do you see the "Move to inbox" button there too? (it is for me if it was in list view)

Here is how all that looks for me:
https://user-images.githubusercontent.com/8763662/137013216-eb4f8cbe-f807-41e8-8ec7-81e7a7d49d02.mp4

**Comment by erikgeurts** [comment]
Yes, that's exactly the scenario that I also follow (as seen in your video) as well.

And at both stages, after a search and selecting a message, and after opening the message, the Move to Inbox button is present on the toolbar.

Now for the surprising part: I'm currently working on my office Windows PC, and with this machine, Shift-E does work, whereas it doesn't on my Windows laptop. Both run Windows 10 and both are on the latest Chrome release.

I posted the config details of the laptop where it doesn't work in yesterday's comment, this is the config on my office desktop PC where Shift-E does work:

Simplify v.2.5.4 - Configuration: aAX appMenuOpen ca3 caI caL cfO cfQ cfR cfU cfZ composeActions composeFormat dateGroup defaultTheme fontMsg hideSelectRefresh hideTabIcons highDensity inMsg izBgDefault lightTheme listWidthLg minimizeChat msgLabelsRight msgSelected msgWidthLg newUI sendLater simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 - Window: 1530 x 993 (101pct zoom) - Language: en

I also have several Chromebooks, I haven't tested specifically with those yet although I seem to recall that Shift-E didn't work on at least one of them. Syncing of Simplify settings between devices would be a god send :)

**Comment by erikgeurts** [comment]
New information:
I've found something that might help figure out where it does wrong:
- if I search for an archived mail, open it immediately, and press Shift-E, it doesn't work
- if I search for an archived mail, select it first by ticking the box to the left of it, then opening it, Shift-E does work

So your theory as described in your last comment might very well be true. I hope this is useful information.

**Comment by leggett** [comment]
My next question was going to be if maybe you have Gmail's big update... but if you're trying it on the same account on different computers and getting different results... man, I just don't know. Super weird. 

I've added more specificity to the selector to get the "Move to inbox" button and am testing that today. It will go out with the next update. That should fix it. If you want to make sure it fixes it, you could inspect the "Move to inbox" button on a computer that isn't working and send me a screenshot of the inspector. 

Here is how (I need to see both the button and the 8-10 elements above it):
https://user-images.githubusercontent.com/8763662/137149123-20e617e4-3783-4809-94b2-1254e2840ea4.mp4

I definitely plan to sync settings across computers (you'll probably have to be signed into Chrome for that to work).

**Comment by erikgeurts** [comment]
As far as I know, I haven't had Gmail's big update...

But if you review the second of my two previous comments, you'll notice that the issue may not be device related after all, but rather related to having the message selected or not before opening it and then trying to unarchive it...

**Comment by erikgeurts** [comment]
I went to my work laptop to make sure I wasn't fooling myself (or you).

And there I also have this behavior that I noticed on my desktop PC:

- searching for a message
- opening it
- pressing Shift-E does not work, displays "no conversation selected"

whereas

- searching for a message
- selecting it first
- then opening it
- then pressing Shift-E does work, the Inbox label is applied

So this is on both devices, there is no difference between the two devices after all.

**Comment by leggett** [comment]
Right, so it is trying to click on the button in the thread list instead of conversation view. I'm changing the selector to try and fix that but since I can't reproduce the issue, I won't know for sure it fixes it until I push the update. 

I can be sure now if you have time to take a screenshot of your inspector. (Sorry to ask after you've done so much to troubleshoot)

**Comment by erikgeurts** [comment]
Not to worry, I kind of enjoy this kind of stuff (even though I don't fully understand it ;) ).

I think these are screenshots of what you're looking for (this is with the email opened):
![image](https://user-images.githubusercontent.com/5102461/137164901-19115c36-fcb3-4c1e-b671-602bcd5b1f2d.png)
and
![image](https://user-images.githubusercontent.com/5102461/137165137-57fbd425-8a7b-411c-a906-f843e2214329.png)

**Comment by leggett** [comment]
Perfect. My fix will work. Thanks.

**Comment by erikgeurts** [comment]
I just received v2.5.5 and I'm delighted to be able to report back that the Shift-E hotkey works now!

**Comment by leggett** [comment]
Thanks for the help and for your patience.

**Comment by erikgeurts** [comment]
Thank you for your product, and for actually listening to your subscribers and considering their requests.
