### ISSUE TITLE
Select mutliple conversations with shift + arrow down / shift + arrow up

### ISSUE THREAD

**Issue by voshond** [leggett/simplify#608]
Hi!

I come from using Superhuman and am now user simplify, as my Job changed and i am getting way less emails i need to react super fast to anymore.

However one shortcut that i really loved in superhuman is the ability to hover over/focus an element and then being able to hold shift and press arrow down for selecting multiple elements. If they are something i want to get rid of our archive, i would perform a bulk action on these elements.

### Current Behaviour

1. Focus an element
2. Press arrow down
3. Press x
4. repeat point 2 & 3 until all desired items are selected

### Desired Behaviour

1. focus an element
2. hold shift
3. press arrow down/up
3.1 focused element gets selected and the next element
4. Repeat point 3 until all desired items are selected

**Comment by leggett** [comment]
This is already live in canary.simpl.fyi and will go out to everyone next week.
