### ISSUE TITLE
wierd visual bug

### ISSUE THREAD

**Issue by KraXen72** [leggett/simplify#609]
![image](https://user-images.githubusercontent.com/21956756/130329384-0d25c7c3-e2c0-444c-9b96-26f52d98f53c.png)
this happens quite often, refreshing the page seems to fix it but its annoying.
windows 10 1440p 27"" monitor, simplify: latest canary idk what other info is needed

**Comment by leggett** [comment]
Can you attach a system report? Instructions on how to do that are at the bottom of https://simpl.fyi/support -- you can just use "Email" and copy and paste the blob of text on this issue. That will tell me how you have Simplify configured and other things so I can investigate.

**Comment by KraXen72** [comment]
Simplify v.2.5.1 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU changeFont composeActions dateGroup hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity minimizeChat msgOpen msgWidthSm navOpen newUI simplify supExtWarn vPane - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 - Window: 2560 x 1400 (100pct zoom) - Language: sk

**Comment by leggett** [comment]
I left my own Gmail on Swedish for a few days with the rest of your configuration and am not able to reproduce this issue. I just pushed out v2.5.2 and while I don't expect it to fix this issue, I wonder if you are still seeing it.

**Comment by KraXen72** [comment]
nope, good news, it does not occur, i think 2.5.3 fixed it. thanks.

**Comment by KraXen72** [comment]
still happens 😢

**Comment by leggett** [comment]
Bummer. Can you send me a screenshot of the whole page next time? Spam label is fine. You can email it to hi@simpl.fyi so you aren't sharing it here.

**Comment by KraXen72** [comment]
its fine i can send it here
![image](https://user-images.githubusercontent.com/21956756/132061380-485a4ddb-5521-463e-aa25-6f456d1a9756.png)
i wanted to send a screenshots with devtools open where like it shows the element boundaries etc, but when i opened them it refreshed the page and it got fixed..

**Comment by leggett** [comment]
Ok, hopefully the last question: is there a series of actions that reliably causes this issue? 

Is it on initial loading? Or switching views? Or maybe after you've been away from your computer for a while and you come back to it to find it busted?

**Comment by KraXen72** [comment]
it when reboot pc, open browser, all tabs are still there but not loaded (hibernated), and i am initially on a different tab and click the mail tab. after i refresh it fixes itself and is usually fixed for like a day or so. it used to be every time i launch browser but now its like every 2-3rd time

**Comment by KraXen72** [comment]
also when it is broken i can do whatever, click tabs, anything on the page, nothing fixes it. only refreshing fixes it.

**Comment by leggett** [comment]
Interesting... it sounds like Gmail isn't always needing to be fully reloaded but Simplify needs to be re-initialized. Do you have offline enabled?

**Comment by KraXen72** [comment]
i don't think so? where do i check

**Comment by leggett** [comment]
I expect you would know if you did. It is under Gmail Settings > Offline: https://mail.google.com/mail/#settings/offline

**Comment by KraXen72** [comment]
![image](https://user-images.githubusercontent.com/21956756/132099493-0e8dad65-11e3-4aaa-bf0b-f266a463c93f.png)
nope its off

**Comment by leggett** [comment]
I finally figured out this bug and fixed it in v2.5.5. It was actually that Gmail was loading so fast, it was skipping the loading screen. Simplify waits for the loading screen to be hidden before it loads (so it doesn't slow down Gmail's loading). But with no loading screen, it waits forever and only half initializes. 

Let me know if you're still seeing it with 2.5.5+
