### ISSUE TITLE
Add support for custom CSS

### ISSUE THREAD

**Issue by jahirfiquitiva** [leggett/simplify#610]
Hey

I wanted to ask if you could add an option to add custom CSS for the extension...

I've been using UserCSS extension, but for some reason it doesn't work always.

Thanks in advance

**Comment by leggett** [comment]
Hmm, maybe? I worry a little that it could make supporting the extension even harder as it introduces a wild card variable. Can I ask what you do with custom CSS in Gmail? Maybe it is something I plan to support soon.

**Comment by leggett** [comment]
I do have plans for a Simplify Chrome extension and with that, I am considering adding a way to inject CSS into any page. But only if I can start without access to any site and add just the sites you want to inject CSS for. So I might support this that way too.

**Comment by jahirfiquitiva** [comment]
Some of the things I'd like to do are:

Make the left panel items sligthly taller (36px)
<img width="267" alt="Shot 2021-08-23 at 13-51-28@2x" src="https://user-images.githubusercontent.com/10360816/130501642-2d2e881f-e3cb-4ce0-9598-029c87f75e81.png">

Change font sizes and colors and height for the emails list items
<img width="1031" alt="Shot 2021-08-23 at 13-51-40@2x" src="https://user-images.githubusercontent.com/10360816/130501634-b57753dd-c5de-4159-b3ce-c5cd31a31040.png">

**Comment by leggett** [comment]
I've got some changes coming this week to calm down the contrast in the dark theme a bit more. 

I also have plans to let you customize the font face/size for the inbox.

No current plans to let you customize the line height on nav items but that might be easy to add.

Anything else?

**Comment by jahirfiquitiva** [comment]
I don't think so, but maybe colors? I don't like the blue shade for selected items 😅

**Comment by hlwoodcock** [comment]
One thing that would be nice is more granular control of the font-family. For example, I like the system font for the message list, but would prefer a nice monospace font (like Roboto Mono, Sans Source Pro, etc.) for the actual body of the messages. Currently, I do this myself with an extension that allows injection of CSS (e.g., Tampermonkey, Stylus, etc.), but it would be better if this could be done directly with Simplify!! 

I also do other tweaking via CSS injection... like adjusting the padding of the message list to get finer control than Google gives, changing the background highlight color of selected messages for greater contrast, etc. Implementing options like these in simplify would be great, but it could be just as easily done with per user CSS injection.

**Comment by hlwoodcock** [comment]
> I don't think so, but maybe colors? I don't like the blue shade for selected items 😅

Agreed, and I do this with injected CSS... 

html.simplify:not(.contrastTheme) .zA.btb:not(.aps) {background-color: #fff7c7 !important;}

An option to change this would be nice!

**Comment by hlwoodcock** [comment]
Just another point about this... I also use CSS to increase the height of the little reply window that pops up out to the right when hitting Shift-R. I have a tall monitor and like having more vertical space showing from the start. 

html.simplify .dw .no .GP div[contenteditable] {
    min-height: 300px !important;
  }

Again, it would be nice if things like this could be changeable in the settings.

**Comment by leggett** [comment]
@hlwoodcock Allowing for variable heights on the compose mole for tall screens isn't an unreasonable request. I'll add that to my list of things to look into as I revamp settings.

**Comment by leggett** [comment]
As for supporting the addition of custom CSS, I've decided I'm not going to do that in this extension. Maybe I'll build my own extension that lets you do that on any webpage, but I don't want to add that complexity directly to Simplify Gmail at this time.

**Comment by hlwoodcock** [comment]
> @hlwoodcock Allowing for variable heights on the compose mole for tall screens isn't an unreasonable request. I'll add that to my list of things to look into as I revamp settings.

Thanks!! I'm sure I can't be the only one that would find that helpful/more visually pleasing to look at.
