### ISSUE TITLE
Backspace to delete selected email not functioning

### ISSUE THREAD

**Issue by davidjdixon** [leggett/simplify#611]
This was first noticed in Google Chrome (92.0.4515.159) and also identified in Shift (both MacOS 11.5.2 M1 MBP).

When selecting messages, and attempting to use backspace/delete key, no action is taken. This is despite the backspace shortcut being enabled in settings, and separately confirmed using the google shortcut help "?".

Other simplify shortcuts have been tested (eg ⌘+z for undo) and appear to work fine.

<img width="467" alt="Inbox_-_david_bricklane_com_-_Bricklane_Mail" src="https://user-images.githubusercontent.com/452007/130496648-f670ae29-91c3-4243-9744-d2964b55cf56.png">

---
Simplify v.2.4.5 - Configuration: aAX appMenuOpen ca4 caE caI caL cfC cfO cfQ cfR cfU changeFont composeActions dateGroup defaultTheme hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity minimizeChat msgOpen msgWidthLg navOpen newUI reverseMsgs simplify simplifyMenuOpen supExtWarn vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) Shift/7.1.14-beta Chrome/92.0.4515.159 Safari/537.36 - Window: 1765 x 802 (105pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Thanks for the report. I can reproduce this in vertical reading pane with auto-select disabled. It should work regardless of the auto-select setting.

**Comment by leggett** [comment]
A fix for this is in the next update (v2.5.2)
