### ISSUE TITLE
Simplify-added Categories get bolded even when there's no new content

### ISSUE THREAD

**Issue by timfee** [leggett/simplify#612]
When Simplify adds categories (like Finance, etc.), they get a bold treatment even when there are no new items.

I'm not sure if it's optimistically bolding based on another value - but there's no new messages in these buckets:

<img width="266" alt="Screen Shot 2021-08-23 at 11 18 18@2x" src="https://user-images.githubusercontent.com/3246342/130497010-052a15cd-ecb9-4ff4-935c-f351bcb805a7.png">

---
Simplify v.2.4.5 - Configuration: aAX appMenuOpen ca3 caI caL cfC cfO cfQ cfR cfU changeFont composeActions dateGroup defaultTheme hideListCount hideMsgCount hideSignatures hideTabIcons inMsg invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity minimizeChat msgLabelsRight msgWidthSm nPane navOpen newUI simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 - Window: 1349 x 1103 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Good catch. Thanks for the report.

I think I know why it's doing that. I bet if you read the message under "Updates" and refresh Gmail, it isn't bold.

**Comment by timfee** [comment]
You bet correctly :-)

**Comment by leggett** [comment]
A fix for this is included in the next update (v2.5.2)
