### ISSUE TITLE
Hide unread email count in chrome tabs?

### ISSUE THREAD

**Issue by joaquinvanschoren** [leggett/simplify#614]
Not sure if Simplify can do this, but it would be great if the unread count in chrome tabs could be hidden.
Here's an example showing 3 unread emails:

<img width="161" alt="Screenshot 2021-08-31 at 12 38 52" src="https://user-images.githubusercontent.com/1724503/131489059-c084ea05-1c41-487c-b9b6-158d9935556c.png">

I know I can 'pin' the tab and hide it that way, but could this also be an option in Simplify?

Thanks!

**Comment by leggett** [comment]
Yes -- there is a Simplify option to do just that. Scroll to the very bottom of Simplify's options and play with this option:

![image](https://user-images.githubusercontent.com/8763662/131514300-6ec7fc60-a66a-410b-b0b3-daab3dfe9cad.png)

**Comment by joaquinvanschoren** [comment]
Sorry I missed that. Thanks!

**Comment by leggett** [comment]
Not at all! It's my fault -- I've got too many settings and this is yet another sign that I need to redesign settings so you know what you can do.
