### ISSUE TITLE
Inbox icon in navigation changes to "on-off switch" icon when hovering

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#615]
I've noticed something peculiar, not entirely sure if it's related to Simplify, but I thought I should report it nevertheless.

When I hover over the "inbox" line in the folder navigation, the symbol changes into an "on-off switch" icon.

Not hovering:
![image](https://user-images.githubusercontent.com/5102461/132345298-d0b16f6d-81bd-4a4f-a354-b0f50ed24b99.png)

Hovering:
![image](https://user-images.githubusercontent.com/5102461/132345337-8cb6f9c1-9d3b-494c-9080-88dc6f7b4029.png)

I've never noticed this before, but I must admit that I haven't been looking extremely frequently, since I tend to use the G - I hotkey nowadays.

---
Simplify v.2.5.3 - Configuration: aAX appMenuOpen ca3 caI caL cfO cfQ cfR cfU cfZ composeActions composeFormat dateGroup defaultTheme fontMsg hideSelectRefresh hideTabIcons highDensity inInbox inList izBgDefault lightTheme listWidthLg minimizeChat msgLabelsRight msgWidthLg navOpen newUI sendLater simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 - Window: 1530 x 993 (101pct zoom) - Language: en

**Comment by leggett** [comment]
That's a new feature I launched last month: you can now hide/pause the inbox :)

https://twitter.com/leggett/status/1426653213210472451?s=19

I need to get better at announcing new features.

**Comment by erikgeurts** [comment]
Can you then please also add a setting to disable this feature? I have no reason to ever want to pause my inbox...

**Comment by leggett** [comment]
Understood. Not for everyone but some appreciate getting to choose what they focus on (starred messages, drafts, etc) before distracted by their inbox. 

The keyboard shortcut has a setting. And turning off notifications when the inbox is off by default. 

So if I added another setting, it would be just to not show the toggle when you hover over Inbox in the nav.

**Comment by erikgeurts** [comment]
Perhaps if the keyboard shortcut to pauze the inbox is disabled, the corresponding Inbox toggle could also be hidden?
