### ISSUE TITLE
Gmail inbox ads appearing again

### ISSUE THREAD

**Issue by jayarr100** [leggett/simplify#616]
Hey Michael,

I know this has come up on and off over the months and that it's a bit of a game of whack-a-mole, but FYI, it looks like the Gmail inbox ads are showing up once again in the Social and Promotions tab for me.

This is with Simplify Canary, running on Chrome stable (seen here on a Chromebook, at present).

![Screenshot 2021-09-07 5 37 53 PM](https://user-images.githubusercontent.com/40185140/132419435-3a5a118e-adce-4031-a770-91efaa88dac4.png)

**Comment by leggett** [comment]
Thanks for the report! I need to rethink how I find the ads.

**Comment by leggett** [comment]
I may also ask you to inspect the class name on the ad tag. I'll send a video or something if I do

**Comment by jayarr100** [comment]
No problem. I think I've got it now, though let me know if I was looking at the wrong value here.

The same div class seems to be repeated in the main (actual non-ad message) email area. But if I zoom in a bit more, I also see a table class in the ad area that may or may not be relevant for your purposes.

I'll attach screenshots of both for full reference.

![Screenshot 2021-09-07 8 02 31 PM](https://user-images.githubusercontent.com/40185140/132429182-c39ca5a5-905b-42ec-8f5e-560042eb27e5.png)

![Screenshot 2021-09-07 8 02 57 PM](https://user-images.githubusercontent.com/40185140/132429204-490ef2e6-095a-409d-8c53-093907488732.png)

**Comment by leggett** [comment]
I'm not seeing these on my test accounts (surprise). Sometimes the ads detector breaks if you change the type of inbox. Can you try a hard refresh (Shift+Ctrl+R   or   Shift + click on browser refresh) and see if the problem persists? 

If it does persist, I need the classname on the "Ad" label deep below inside `.Cp` -- it is `.ast` or .`a3x` on my test accounts. 
<img width="338" alt="Screen Shot 2021-09-07 at 6 08 02 PM" src="https://user-images.githubusercontent.com/8763662/132429546-8cb31bba-a4c7-45f8-9686-9051e5a663f3.png">

It seems to change every month or two and so I need to build a path to detecting it instead.

**Comment by jayarr100** [comment]
Interesting! I hadn't changed anything in terms of inbox configuration (or anything else, really) in quite a while, but upon a hard refresh, the ads have indeed vanished — at least, for now. 

I'll continue to keep an eye out and dig in deeper to find that class if/when they do reappear.

**Comment by leggett** [comment]
Not sure why it stopped working then but glad a refresh fixed it. 

I'm going to build a more stable selector anyways as it changes every so often.

**Comment by leggett** [comment]
A better way to detect these went out in v2.5.3
