### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by gabrielecirulli** [leggett/simplify#618]
Hey, I just signed up for the paid version of Simplify and it's really enjoyable to use.

I would love it if infinite scroll was an option. I often find myself clearing an inbox that has amassed about 500 messages and being able to quickly select and clear stuff without having to manually jump pages would be awesome.

**Comment by leggett** [comment]
I'd love if I could add infinite scrolling, and maybe with full API access, I could. But with the limited access I have today, it is not possible.
