### ISSUE TITLE
Text is compressed into single column for long email threads

### ISSUE THREAD

**Issue by diazdc** [leggett/simplify#621]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

Is there a way to enable horizontal scrollbars so this doesn't happen? Thanks.

![Screenshot 2021-10-20 093359](https://user-images.githubusercontent.com/32173539/138134350-9133f48c-2d9c-4864-9638-040f7c893579.png)

---
Simplify v.2.5.4 - Configuration: aAX appMenuOpen ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup fontMsg hideListCount hideSignatures hideTabIcons highDensity inMsg invertAddons invertCompose izBg2 lang-en listWidthLg mediumTheme minimizeChat msgWidthLg nPane newUI oeHubspot otherExtensions reverseMsgs simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 - Window: 1536 x 816 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Holy quoted text Batman! That does not look fun. 

There are two ways to deal with this kind of situation:

1. Pop out the message and expand the window (I allow the message to span the entire screen) -- good for a one-off need
2. Change the message width setting in Simplify settings -- good if this is a recurring need

Neither of these will allow you to have the message stretch beyond the window size and scroll horizontally though (that would be a pretty awful reading experience). Open to other suggestions though!

Here are my two solutions in action:
https://user-images.githubusercontent.com/8763662/138158782-9adec0e2-bebb-4d42-b103-afc034385c0a.mp4
