### ISSUE TITLE
Simplify not applied when a pinned tab is loaded on launch

### ISSUE THREAD

**Issue by adriankarlen-old** [leggett/simplify#622]
I have a gmail-tab pinned in my browser, when the tab loads on browser launch the simplify-extension is not applied. If I however perform a reload of the tab, it is applied. This occurs on both windows and mac for me. 

---
System: Brave browser (chrome extension) (Macintosh & Windows)

**Comment by leggett** [comment]
Thanks for your report. I've heard of this happening to one other person on a Chromebooks only once and not on other systems. I can't reproduce the issue either unfortunately.

What version of Simplify are you using?

Here is what happens for me:
https://user-images.githubusercontent.com/8763662/138506633-77146a92-6b72-410b-b8e6-c1387e86df47.mp4

**Comment by leggett** [comment]
I believe I fixed this in the last update. What was happening was Gmail was loading so fast that it was skipping the loading screen which I used to trigger initializing Simplify (that way I'm not trying to load while Gmail is loading). I now detect this and initialize.
