### ISSUE TITLE
Inbox disappears without messages

### ISSUE THREAD

**Issue by bryansmithsf** [leggett/simplify#623]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

When I get to inbox zero (no messages in the inbox) and a new message comes in it does not appear unless a page refresh is done. Switching to a new tab and back to the inbox works as well. 

---
Simplify v.2.5.4 - Configuration: aAX addOnsOpen ca4 caC caI caL cfC cfF cfO cfQ cfR cfU composeActions composeFormat fontMsg hideListCount hideMsgCount inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity mediumTheme minimizeChat msgWidthSm nPane navOpen newUI outreach-everywhere-sidebar-hidden outreach-everywhere-site-gmail simplify supExtWarn supported-by-outreach-everywhere - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 - Window: 2052 x 1252 (100pct zoom) - Language: e
![Inbox (2)](https://user-images.githubusercontent.com/17604285/138776480-ec3fe088-ae8b-4245-b733-ef9d81e37bfc.jpg)
n

**Comment by leggett** [comment]
It should definitely show the inbox as soon as new messages come in. 

I can't reproduce this issue on my test accounts but maybe Simplify isn't working for your specific setup.

What kind of inbox do you use? Is it the tabbed inbox? And if so, are the new messages in one of the non-primary tabs?

Another possibility is if you have other extensions installed that are somehow interfering. It looks like you have Outreach Everywhere installed. Do you have others?

**Comment by bryansmithsf** [comment]
I have my inbox split between read and unread. No tabs. 
<img width="630" alt="Screen Shot 2021-10-26 at 11 23 46 AM" src="https://user-images.githubusercontent.com/17604285/138910616-fce175d2-68fc-43e8-ac12-f210ed917eba.png">

**Comment by leggett** [comment]
I've tried a few times and still can't reproduce this issue with the Unread first inbox. 

Are you still having the issue? I wonder if a hard refresh (⇧ ⌘ R) would help.

Also, do you have other extensions installed?

**Comment by leggett** [comment]
I still haven't been able to reproduce this issue. I suspect it is some kind of conflict with another extension or maybe something that went away after a hard refresh. Please let me know if you're still seeing it and if so, what other extensions you have installed.
