### ISSUE TITLE
Send button and toolbar buttons outside of the compose window

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#628]
I believe this is something that started when Chrome was updated to v96, but it may also be purely a coincidence.

When I hit C or click Compose, the overlay where I write a new mail appears. I always use full screen. Initially the cursor is positioned in the "To"field.

Starting recently, I've noticed that the send button and all other buttons appear outside of the compose window, as in this screenshot:
![image](https://user-images.githubusercontent.com/5102461/142587958-2b81f3a6-97c1-403d-98d1-444775bf0528.png)

As soon as I've completed entering the recipient(s) and move the cursor to the Subject field, the buttons "jump back" into the compose window. While writing the email, when I decide to add another recipient, the buttons jump out again.

---
Simplify v.2.5.5 - Configuration: aAX appMenuOpen ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFormat dateGroup defaultTheme fontList fontMsg hideListCount hideMsgCount hideSelectRefresh hideTabIcons highDensity inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg minimizeChat msgLabelsRight msgWidthMd newUI sendLater simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 - Window: 1316 x 832 (101pct zoom) - Language: en

**Comment by leggett** [comment]
Arg... Fix one thing and break another. Gmail made some changes to compose and I fixed Simplify in v2.5.5 to work with them but see that Gmail only made some of those changes when you have a "From" drop down above your "To" field.

Short version: I see it. I will fix it. Thanks for the report.

**Comment by leggett** [comment]
Have a fix ready. I'll upload it this weekend as part of 2.5.6. Thanks as always for the report!

**Comment by erikgeurts** [comment]
Very nice!

It must feel for you like you're trying to hit a moving target, with the target actually firing back at you...

**Comment by leggett** [comment]
Very much so. If you've never seen it, I wrote about the challenge here: https://on.simpl.fyi/p/complexity-of-simplify

**Comment by erikgeurts** [comment]
I got v2.5.6 and I am glad to be able to confirm that the buttons are in the right place again!
