### ISSUE TITLE
Bug: Chats don't update when hamburger menu is collapsed

### ISSUE THREAD

**Issue by velicanu** [leggett/simplify#629]
It seems like toggling the hamburger menu to hidden stops updating chat messages. Toggling it back on or hovering over it has chat update normally again. See attached video:

https://user-images.githubusercontent.com/5022772/143056934-a8783628-4817-4a95-8bf1-55785cc9ffbd.mp4

---
System: Mozilla/5.0 (Macintosh

**Comment by leggett** [comment]
Very strange. I actually use Chat at work with the nav closed and it works fine. Can you try a hard refresh (Shift + the browser's refresh button) and see if the problem persists?

**Comment by leggett** [comment]
I'll add that it doesn't make sense for chats to not appear or send just because the nav is hidden. I'm not removing anything, just changing the appearance of the roster with CSS. Then again, sometimes strange things happen so I don't want to say it is 100% not Simplify.

**Comment by velicanu** [comment]
I see the same behavior even after a hard refresh. Just tried chrome and the issue is not there, so far I only see it in Firefox.

**Comment by leggett** [comment]
Got it. Thanks for checking. I'll look into it on Firefox.

**Comment by leggett** [comment]
Definitely one of the strangest bugs I've run into. I finally found a way around this. Pushing a fix in v2.5.7 shortly.
