### ISSUE TITLE
Search and minimise crashes gmail

### ISSUE THREAD

**Issue by mightymouse2045** [leggett/simplify#63]
Hi,

I can recreate this on two different computers. There are multiple ways to reproduce but this should do it:

Search for anything and click the search icon to minimise search and click somewhere else gmail crashes and reloads.

**Comment by mightymouse2045** [comment]
![gmail-crashing- 2019-04-17 14-09](https://user-images.githubusercontent.com/878160/56265511-571ce200-611c-11e9-9f9c-cf2dc2919a28.gif)

**Comment by mightymouse2045** [comment]
If you crash it a few times in a row it won't reload properly as per below:

![image](https://user-images.githubusercontent.com/878160/56266584-24281d80-611f-11e9-83cf-b3c11dc8c872.png)

**Comment by leggett** [comment]
Yikes! Thanks for the detailed report.

- I got it to repro once but it isn't consistent. I'll keep trying to figure it out.
- The crash is actually not a crash (I think) but an interaction where clearing the search tries to go back to the previous screen. If you clear and close the search via the X, you see it working correctly. Somehow this seems to be half-firing when you minimize search (it shouldn't fire at all). 
- As for the reload not being right... Simplify thinks you're not using split pane for some reason. A simple refresh should fix it (it might take 3-5 seconds to detect it after load). If that doesn't work, try toggling split pane to different setups (vertical then no split then back to vertical).

**Comment by leggett** [comment]
Ok, I think I found the issue. I'm not complete sure why it is a problem but removing the `event.stopPropagation();` from line 168 (the code that runs when you click on the search button) seems to fix it. I don't even remember why I added that there. I know it was critical on the close button event to prevent focus going into the search input when you click to close search.

I will remove it and push an update for 1.1.8 now. Please re-open if it doesn't fix it for you.

**Comment by mightymouse2045** [comment]
Nice one yep that works now - thank you sir

**Comment by leggett** [comment]
Now I remember why I added the event.stopPropagation() -- without it I can't focus the input when you click on the search button. I'll just set a delay the call to focus for now by a 100ms (bit of a hack) until I can figure out what is going on here. :/

**Comment by leggett** [comment]
Ok... figured out a solution. I needed to have both event.preventDefault() and event.stopPropagation(). 

The default action for the search button is to do the search IF there is text in the search box (which is odd for a button that is to the left of the search text). Otherwise, the search button doesn't do anything. So I guess it was trying to do the search again? 

Either way, fixed in v1.2.2.
