### ISSUE TITLE
Font-family not applied on Firefox

### ISSUE THREAD

**Issue by brampitoyo** [leggett/simplify#631]
### Steps to reproduce
- Simplify → ‘Simplify Options’
- Set ‘Font Face’ to any value

### Expected result
Font-family is set to a system font stack or equivalent (San Francisco on macOS, Segoe on Windows, etc.)

![expected result](https://user-images.githubusercontent.com/51007/144317688-dee1e2d2-fde3-4bfd-ab15-fac3d3b9686e.png)

### Actual result
Font-family is a mixture of Roboto (mailbox headings), Google Sans (email section headings), and Arial (email titles and snippets).

![actual result](https://user-images.githubusercontent.com/51007/144317734-273d4200-1ab5-4e3b-8257-52b532bb6a51.png)

**Comment by leggett** [comment]
Are you using Firefox? I can't reproduce this issue on any other browser but do see it on Firefox.

**Comment by brampitoyo** [comment]
Hi @leggett; yes, I’m using Firefox – although I’m unsure whether this problem appears on Windows, or just macOS.

**Comment by leggett** [comment]
Finally got a fix in for this. Should land shortly. Thanks for your patience.
