### ISSUE TITLE
Bundle Date or Time Retains Last Received Email Timestamp

### ISSUE THREAD

**Issue by nilnocb** [leggett/simplify#634]
On receiving a newly bundled email, such is one that is bundled into Updates, the bundle turns bold and the time received is updated (plus bundle goes to top); all good there. Then, when opening bundle and reading the one new email, and then archiving that new email and returning to the inbox, the time of the bundle stays with that recently archived email. I don't see this behavior with Promotions.

---
Simplify v.3.0.0 - Configuration: aAX appMenuOpen bundleInbox ca3 caI caL cfC cfI cfO cfQ cfR cfU composeActions composeFormat darkTheme dateGroup fontMsg hideListCount hideMsgCount hideSelectRefresh hideSignatures hideTabIcons inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity minimizeChat msgLabelsRight msgWidthLg nPane newUI reverseMsgs rightStar showAvatars simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 - Window: 2256 x 1460 (200pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the detailed report. I'll look into it.

**Comment by freste** [comment]
Not sure if this is related, but w/already received messages, turning bundling on/off moves a message from TODAY to YESTERDAY. With bundled on, msg w/time 4:52AM is TODAY, turn bundles off it moves to YESTERDAY. See screenshots.
![no bundles](https://user-images.githubusercontent.com/2577130/145586218-a534eee0-b63f-418f-9fd4-219adab16531.png)
![bundled](https://user-images.githubusercontent.com/2577130/145586219-60533fc1-f2f7-4ced-830d-35c48f3e0405.png)

**Comment by leggett** [comment]
Weird! I'll look into it. Thanks for the screenshots and detailed report.

**Comment by leggett** [comment]
I think I've fixed this... but please re-open if you're still seeing the issue.
