### ISSUE TITLE
Group by date stopped working

### ISSUE THREAD

**Issue by furilo** [leggett/simplify#637]
The Group by date feature stopped working for me several days ago (and I realize I can't live without it!! ;) I've tried disabling enabling Simplify, disabling the rest of extensions I have and only leaving Simplify, but this doesn't seem to work. 

In Chrome I get the same problem. 

<img width="1279" alt="imagen" src="https://user-images.githubusercontent.com/24740/145368142-672cb888-1947-4549-9d25-76c9dc436fe0.png">

---
Simplify v.2.5.6 - Configuration: aAX appMenuOpen ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup defaultTheme fontMsg hideListCount hideMsgCount hideSelectRefresh hideTabIcons highDensity inInbox inList invertAddons invertCompose izBg1 lightTheme listWidthLg minimizeChat msgLabelsRight msgWidthSm nPane newUI sendLater simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10.15 rv:94.0) Gecko/20100101 Firefox/94.0 - Window: 1280 x 1415 (100pct zoom) - Language: es

**Comment by leggett** [comment]
Thanks for the report. Gmail made a slight change to how they format dates in Spanish. About to push a fix.

**Comment by furilo** [comment]
Thanks a lot!

**Comment by furilo** [comment]
Is this supposed to be deployed? I don't see any change ;)

**Comment by leggett** [comment]
It is. What version of Simplify do you have? It is shown in the Simplify menu.

**Comment by furilo** [comment]
Ah, nevermind! I just reviewed preferences and it was turned off 🙃 Sorry and thanks again!
