### ISSUE TITLE
Firefox is missing the top right "more menu button" that contains the email settings button.

### ISSUE THREAD

**Issue by pratyushtewari** [leggett/simplify#645]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

The hover more button next to the profile pic in gmail is missing in Firefox. It is visible in Chrome though. I am attaching the screenshot from both chrome and firefox.

P.S. this is a google work, gmail enterprise account. But the same issue happens on my personal email in firefox as well.

**### Firefox:**

<img width="585" alt="Firefox" src="https://user-images.githubusercontent.com/251768/147706071-067a35f4-3383-47fc-abb4-f66652871d9e.png">

### **Chrome:**

<img width="631" alt="Chrome" src="https://user-images.githubusercontent.com/251768/147706086-9913eded-f4a0-4670-a9a3-4a5383f590e1.png">

---
Simplify v.2.5.8 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup defaultTheme fontList fontMsg hideListCount hideMsgCount hideSignatures hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity minimizeChat msgWidthSm navOpen newUI reverseMsgs simplify supExtWarn vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10.15 rv:95.0) Gecko/20100101 Firefox/95.0 - Window: 1737 x 924 (120pct zoom) - Language: en

**Comment by leggett** [comment]
I'm not able to reproduce this on my end (with Firefox). I think the issue has something to do with your workspace company logo not loading in Firefox. 

If you do a hard refresh (⌘⇧R  OR  hold shift while clicking on the browser refresh button), the problem should go away. Let me know if it doesn't.

**Comment by pratyushtewari** [comment]
Hard refresh fixed the issue. Thanks for your suggestion and a quick check!!.
