### ISSUE TITLE
Visual issue: new message button is off-center

### ISSUE THREAD

**Issue by jamescridland** [leggett/simplify#646]
On both my MacBook and on this Chromebook, the "new message" button's contents are off-center.

Thing I see: this
![image](https://user-images.githubusercontent.com/231941/147713584-c8147ac6-8835-44c3-b6db-cb3b6dd6c513.png)

Thing I'd like to see: the pen in the middle of the circle, not to the right-hand side of the circle.

(Speaking more personally - this action button quite often gets in front of the "delete" icon, and it's quite irritating placement; but that's not a bug.)

---
Simplify v.3.0.4 - Configuration: aAX appMenuOpen ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup fontMsg hideListCount hideMsgCount hideTabIcons highDensity inMsg invertAddons invertCompose izBgDefault lightTheme listWidthLg minimizeChat msgWidthSm nPane navOpen newUI rightStar simplify simplify-canary simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (X11 CrOS aarch64 14324.41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4692.53 Safari/537.36 - Window: 1080 x 675 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
On the pencil not being centered... Gmail does something different on lower resolution devices that I haven't been able to reproduce yet to figure out why the pencil isn't centered. Definitely an annoying bug. If you're familiar with the Javascript console and up for helping me trouble shoot, I can send further instructions. 

On the compose button covering the delete button (I supposed you mean on inline replies)... definitely an unfortunate issue on lower resolution screens (e.g., 1080px wide) with the nav open. I add margin at the bottom of the conversation to make sure you can scroll up to get to it, but still annoying. I haven't thought of a solution for this setup yet but I do have the idea of adding an option to keep compose in the nav (where it will be totally hidden if the nav is minimized).

**Comment by jamescridland** [comment]
Very happy to help troubleshoot. james@crid.land will  find me.

**Comment by leggett** [comment]
Fix going out in v2.5.9 -- thanks for the help!
