### ISSUE TITLE
Show 'Scheduled Send' button inline button not working in Canary build

### ISSUE THREAD

**Issue by jaredzimmerman** [leggett/simplify#649]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

---
Simplify v.3.0.4 - Configuration: aAX bundleInbox ca5 caD caE caI caL cfC cfF cfR cfS cfU composeActions composeFormat dateGroup fontList fontMsg hideEmptySections hideListCount hideMailTitle hideMsgCount hideSelectRefresh hideTabIcons hideUnreads inInbox inList inboxZero invertAddons invertCompose izBgOff listWidthMd lowDensity mediumTheme minimizeChat msgLabelsRight msgWidthMd nPane newUI rightStar sendLater showAvatars simplify simplify-canary supExtWarn - System: Mozilla/5.0 (X11 CrOS x86_64 14268.67.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.111 Safari/537.36 - Window: 1392 x 810 (100pct zoom) - Language: en

**Comment by leggett** [comment]
It works for me... but this is probably an issue of the setting not setting clear expectations. 

It works in compose (or popped out replies):
![image](https://user-images.githubusercontent.com/8763662/148670828-79a5f150-d79e-4d4d-b34d-e456d5f9a1ea.png)

But not in inline replies:
![image](https://user-images.githubusercontent.com/8763662/148670838-da3a3c99-f2b2-4d44-8dd2-a37dbf8cf07c.png)

Background: Initially, when I added this, I tried to support showing it inline everywhere. But pulling the button out of the menu on the inline replies proved irreparable buggy. 

I'll add a clarification in settings.

**Comment by jaredzimmerman** [comment]
its specifically not working in new messages, i didn't test in in-line reply 

![Screenshot 2022-01-08 10 14 32 PM](https://user-images.githubusercontent.com/430427/148671470-fbdabcaa-8e36-45ea-a4e5-808b5a321f93.png)

**Comment by leggett** [comment]
Doesn't work in full screen compose either for the same reason. The bottom bar that the send button and all the compose buttons sit in switches to position:fixed when the message scrolls and it all goes to hell because of where the send-later button sits in the DOM.
