### ISSUE TITLE
Show message counts for labels in left nav

### ISSUE THREAD

**Issue by andyszy** [leggett/simplify#65]
After switching from Inbox bundles to Gmail labels, the biggest pain point for me is that it's easy to forget that I've moved important messages into a label. It's too easy for them to be out of sight, out of mind.

If Simplify could show the message count (not unread count) alongside each label in the left panel, this would solve 80% of my problem.

**Comment by leggett** [comment]
I can't show what isn't there. And only the unread counts are in the nav.
