### ISSUE TITLE
Overlapping icons

### ISSUE THREAD

**Issue by ordotools** [leggett/simplify#651]
Some of the icons are overlapping in Safari on macOS Monterey:
![image](https://user-images.githubusercontent.com/38426287/148948636-3f006e0b-8cfa-4bc0-a67f-33fb7a4f14dd.png)
---
Simplify v.2.5.2 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup fontMsg hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity minimizeChat msgWidthSm simplify supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15 - Window: 1792 x 1055 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the report. It looks like the search button I add when you've selected or open a message is not being placed correctly. 

I don't see this issue when I try those actions. And your config shows you are in the Inbox without a message selected. Are you seeing that at a different time?

Also, it is odd that Simplify thinks you are using the default theme but your screenshot is dark -- are you using Dark Reader or other extensions?

**Comment by ordotools** [comment]
The format is now different. I suppose you updated?

I did not have a chance to try selecting an email.

I only have gmail with a black background image -- just a single color.

**Comment by leggett** [comment]
I didn't update -- sounds like the issue resolved itself somehow. Let me know if it comes back.
