### ISSUE TITLE
Dark Compose Icon Overlap / Incorrect

### ISSUE THREAD

**Issue by rob-pomelo** [leggett/simplify#653]
See screenshot, top icons overlap / aren't actually correct

To repro: Have gmail in dark mode with "make compose dark" toggled to true.

![Screen Shot 2022-01-12 at 2 17 58 PM](https://user-images.githubusercontent.com/97481251/149207190-5ba1d804-0495-4e51-9505-ba81e77dbbcf.png)

Thanks for a great extension!

---
Simplify v.2.5.8 - Configuration: aAX appMenuOpen ca4 caD caI caL cfC cfO cfQ cfR cfU composeActions darkTheme dateGroup fontList fontMsg hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBg2 js-focus-visible listWidthLg lowDensity minimizeChat msgWidthSm navOpen newUI openMole simplify simplifyMenuOpen vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 - Window: 1558 x 1118 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the report. I see this is an issue for lower-density displays (below 144ppi). 

I've got a fix and will include it in the next update (should go out in the next couple days). FWIW, those buttons still work, the icons are just all messed up.

**Comment by robmartorano** [comment]
All fixed, thank you!
