### ISSUE TITLE
Search | Shortcut search filter chips and Select all conversation is missing 

### ISSUE THREAD

**Issue by pratyushtewari** [leggett/simplify#654]
The advanced search chips and **select all conversation** is missing in both chrome and firefox.

These are very useful features and I just realized that they are getting hidden by Simplify. Check the screenshot.

<img width="1844" alt="Simplify issue with search" src="https://user-images.githubusercontent.com/251768/149604918-0c02b8a6-d7f7-40dc-be65-b07648949e38.png">

---
System: Mozilla/5.0 (Macintosh)

**Comment by leggett** [comment]
Neither should be hidden. 

The search chips can be set to be hidden in Simplify settings. This is an opt-in setting (e.g., they are not hidden by default).

The select all option should be floated off the list so you can see it. I'll look into that asap.

I assume you have the latest version of Simplify? I'll write back if I need more info or a system report to reproduce the issue.

**Comment by leggett** [comment]
I confirmed that I see the search chips so long as the Simplify option to hide them is not enabled. I also see the banner which allows you to select all messages across pages does show up if the nav is closed and a message is open:

<img width="1437" alt="Screen Shot 2022-01-14 at 9 24 40 PM" src="https://user-images.githubusercontent.com/8763662/149610420-7c106d5c-0b7d-4a65-894b-587f8cd3d77c.png">

BUT the select banner does not show up when the nav is open OR if the nav is closed and no message is open. I'll work on fixing that for the next update (v2.5.9).

**Comment by leggett** [comment]
Found the issue with the banner not appearing. Fix will go out within 24 hours. Let me know if the search chips still aren't showing for you after checking your Simplify settings.

**Comment by pratyushtewari** [comment]
Hey @leggett  thanks for the fix!

I think I found the issue with the search chips not appearing inspite of the hide search chips options unchecked.

When you click on a any of the label in the left sidebar .. Gmail treats that as a search and uses the search bar to filter the emails. That is the time the search chips are not appearing.

Attached the screenshots:
![label without spimplify](https://user-images.githubusercontent.com/251768/149636045-cb9b620f-60f3-49ec-9ec8-fc85fa6fca58.png)

![label with spimplify](https://user-images.githubusercontent.com/251768/149636046-32580f21-5365-4a3e-b129-ce647d6b2d94.png)

Hope you can reproduce this as well.

**Comment by leggett** [comment]
Ah, yes, I see that now. I think showing those on labels is new? Either way, I'll get that fixed.

**Comment by leggett** [comment]
Nope, not a new thing. Looks like Simplify has just always hidden these outside of search. 

Not sure how I feel about that now. You should at least be able to opt to see them on non-searches. And maybe that should even be the default experience.

**Comment by leggett** [comment]
v2.5.10 is rolling out with a new option to show search chips in labels. It is off by default.

**Comment by leggett** [comment]
Note: I added the setting but forgot to make space above the list when it is enabled... will fix in next update.

**Comment by pratyushtewari** [comment]
Yeah I saw that. But good you found it yourself.

**Comment by leggett** [comment]
About to push a fix (v2.5.11) to make sure there is space for the search chips in a label.
