### ISSUE TITLE
Version 3 on non-Canary

### ISSUE THREAD

**Issue by danfoxley** [leggett/simplify#655]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

1. On a laptop I installed Simplify and version 3.  Now on non-Canary Chrome version 3 is running.  Any issue there?  Any tips to optimize for version 3?
2. Will there be a Sweep feature for version 3?

Thanks,
Dan

---
Simplify v.3.0.4 - Configuration: aAX bundleInbox ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup defaultTheme fontMsg hideListCount hideMsgCount hideTabIcons inList inSearch invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity minimizeChat msgWidthSm nPane navOpen newUI rightStar showAvatars simplify simplify-canary supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 - Window: 3377 x 1440 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Sweep feature will come to v3 soon. 

If you install [Simplify v3](https://canary.simpl.fyi) (regardless of version of Chrome), you get Simplify v3. You can always disable or even remove it and go back to [Simplify v2](https://chrome.simpl.fyi).
