### ISSUE TITLE
Idea: option to add travel (and other reserved labels/categories) to the sidebar

### ISSUE THREAD

**Issue by nevir** [leggett/simplify#658]
Considering that Gmail is actively labeling travel-related emails as "travel", etc - it'd be nice to be able to show that label (and any other reserved labels) in the main side bar and/or the categories section

**Comment by leggett** [comment]
Simplify actually already does this. You can opt into showing the labels in the category folder in Simplify options under the Navigation section:

![image](https://user-images.githubusercontent.com/8763662/152254177-888022a7-cc45-431e-a5a9-565fc1c587bd.png)

**Comment by leggett** [comment]
I will add though, these are not true labels or categories. They are more like saved searches for the categorization label that Gmail applies. There might be a way to upgrade them though. 

First, some background:

- Simplify makes 3 additional categories (Finance, Purchases, and Travel) visible in Gmail's left navigation as links to a search for each category. 
- These categories are from Google Inbox and are still applied to incoming email  in the background by Gmail but Gmail decided to hide them entirely in Gmail's interface. 
- It is not possible to show them as inbox tabs or modify the email in these categories. (I might be able to make them editable one day but do not expect to ever make them work as Inbox tabs.)
- Any message in these categories is also in the Updates category.
- The limited functionality is why the feature is off by default. 

A glimmer of hope:

- I recently discovered a way to make these categories a bit more useful...
- You can create your own label (e.g., Receipts) and then filter mail by category (e.g., has the words: "category:purchases") into that label where you can add and remove email freely. You'll also be able to [bundle](https://www.fastcompany.com/90698042/simplify-gmail-inbox-bundles) email with these labels when bundles launch for everyone. 
- The reason that works is that categories are always applied before any of the user filters are run. So while you can't filter based on labels, you can filter based on categories. 
- I've been testing this for a few weeks and it is working flawlessly for me. 
- But I will have to do some work to figure out how to automate setting all this up (as it involves creating labels and filters).

**Comment by nevir** [comment]
Doh, I'm super blind - thanks for the pointer to the option! The caveats make sense (god I miss Inbox; but glad there's some some vestigial bits left over from it)

---

> The reason that works is that categories are always applied before any of the user filters are run. So while you can't filter based on labels, you can filter based on categories.

Oh, that's handy! it's being classified at ingestion! Nice, I'll definitely set that up for the categories that I care about 👍 

---

> But I will have to do some work to figure out how to automate setting all this up (as it involves creating labels and filters).

And choose labels that don't get confused w/ all those reserved category names :(

**Comment by leggett** [comment]
Yes, and choose labels that aren't confusing or conflicting. Most likely, I'll need to ask them to confirm the labels. I could also put them under another folder (e.g., Categories / Travel) as "Categories" is not a reserved system label as it is not applied to anything... it's just the folder all the other categories are in. But then you would have two Categories labels. 

We'll see.
