### ISSUE TITLE
Search randomly loses conversation list and/or category/tag list

### ISSUE THREAD

**Issue by alanhoyle** [leggett/simplify#659]
Every once in a while when using the Gmail search box, when the results come up on the screen the interface view loses the left-hand navigation sections, either/both the Category/Folder/Tag column and/or the conversation list, just leaving me with a single conversation on the screen.  

I have had trouble getting the issue to happen consistently, it happens maybe once every other day.  

I'm running Gmail on Wavebox 10.97.33.2, which uses a quite recent Chromium release.

**Comment by leggett** [comment]
This isn't a bug actually... it is how Gmail works. 

What is happening is you are clicking on an email in the search auto-complete. When you do that with reading pane on, it will drop the reading pane and just show you the message. I think it sort of makes sense (what would the list be?) but it is jarring.

**Comment by alanhoyle** [comment]
There are still two rendering bugs here that don't occur with generic Gmail:  

1.  the search box disappears making it impossible change the search (work-around is to hit the <- icon)
2. with backgrounds that render white text on  dark backgrounds, all you see is the text in drop-shadow format on a white background

Generic Gmail:

![Screen Shot 2022-02-07 at 5 13 32 PM](https://user-images.githubusercontent.com/289779/152881046-363e83da-761e-44b4-9b49-2aab3f307c71.png)

Simplifi:

![Screen Shot 2022-02-07 at 5 14 07 PM](https://user-images.githubusercontent.com/289779/152881118-52f5fe19-20a3-42f4-84ac-51cc79201244.png)

**Comment by alanhoyle** [comment]
@leggett please see above that this is, in fact, a rendering issue/bug

**Comment by leggett** [comment]
Thanks for the follow up. Sorry to dismiss this prematurely. I'll dig into it.

**Comment by alanhoyle** [comment]
When I play around with the search (e.g. opening closing the hamburger), I often get rendering bugs with Simplify.  E.g. I just got this one:  

![Screen Shot 2022-02-07 at 5 24 44 PM](https://user-images.githubusercontent.com/289779/152882450-8377d0b8-bd85-4069-b345-206c53ca6354.png)

**Comment by alanhoyle** [comment]
The white drop shadow text also happens if the hamburger is closed and one uses mouseover to open it in this context.  

![Screen Shot 2022-02-07 at 5 29 29 PM](https://user-images.githubusercontent.com/289779/152883053-b3b0df17-f623-41ca-bfc0-a617cfbc442c.png)

**Comment by leggett** [comment]
Ok, I've got fixes for:

- Access search from the one-off message view (a search button will appear in the top right near the pagination controls as happens in other setups) 
- Re-setting up the reading pane when you leave a message (that is what is breaking)
- Proper styles for the nav when open or peeked in a one-off message view with reading pane enabled

Will include in the next update (v2.5.12)

**Comment by alanhoyle** [comment]
Thanks!

**Comment by leggett** [comment]
v2.5.12 is out -- let me know if you still have any issues

**Comment by alanhoyle** [comment]
I'm not getting the rendering errors anymore so that's much improved!  The hamburger menu is readable on all variants of this view that I've tried, even super narrow ones.  (as an aside, the current gmail provides a nice fast sliding animation as it contracts/expands the menu, which is slightly less jarring than the instant move with Simplify.)

My comment now on usability is that the native Gmail's search bar is visible at the top and displays the search while still displaying the selected conversation.  Simplify hides the search unless I click on it, and, counterintuitively, moves the location of the 🔍 (magnifying glass icon) to a spot on the other side of the window.  

This turns the "edit the current search" task from:

*  "single click in the search text input box that's in spot I'm always used to finding it" 

into a less efficient: 

* "find the search icon that's moved to a weird spot, click to make the search text input box visible, click in the input box." 

I think it would be better to both keep the current search visible/readable, and keep the text box/magnifying glass icon in the space between the hamburger and the ← (arrow icon).  

In this case, the search bar input box  is not "wasted space" like it is in some other views:   it actively provides context to the user's current task.  Keeping it visible/accessible without an extra click to open would be an improvement, at least IMO.

**Comment by leggett** [comment]
Thanks for the suggestion Alan.

Since, search remains visible in search when using vertical reading pane, this shouldn't be an issue, right? The search box is only minimized when you click directly on a message in search auto-complete at which point, search offers no context. 

In message view, the current placement works across all configurations and screen resolutions. There isn't enough room to put the search box between the message actions and the menu button in all setups and all screen resolutions in traditional message view (the view Gmail dumps you into when you click on a message in search auto-complete even if you use reading pane).

**Comment by alanhoyle** [comment]
Maybe leave the search magnifying glass icon on the left side in the space between the ≡ and the ←, so we don't have to look for it in a new place?  If we click it, it opens from the hamburger to the right, only pushing the other icons out of the way if there isn't room in the space?

Also, if the magnifying glass is clicked, it should automatically open the suggestions drop-down the same way that regular Gmail does, not require second click inside the box.  

Proposed move:

![Screen Shot 2022-02-16 at 11 37 44 AM](https://user-images.githubusercontent.com/289779/154312957-0c0c36cb-f45c-4260-839c-7f5c3beb1835.png)

Regular view:

![Screen Shot 2022-02-16 at 11 40 24 AM](https://user-images.githubusercontent.com/289779/154313268-6127122f-bef3-4edc-8742-0666096806a2.png)

Regular Gmail doesn't suffer from this as it just leaves the search at the top all the time.

**Comment by leggett** [comment]
Agree that clicking on the search magnifying glass should open the suggestions drop down without a second click.

Moving search between the actions and the menu button does not work across setups, screen sizes, and zoom levels.

**Comment by alanhoyle** [comment]
What about putting the ONLY  the magnifying glass icon in that space? That would solve the "control has moved to a weird location" issue while still maintaining compatibility with all but the narrowest windows.  If the window is super narrow, maybe nudge the ← a bit to the right to keep the icon?  Moving a control around is something that I truly believe should basically never happen.

**Comment by leggett** [comment]
**For your situation, I agree with your feedback** You are in vertical reading pane and you're used to search being to the left. Having search minimize there makes sense for this case, in isolation.

**Based on the same reasoning, the current location makes sense 99% of the time:** This one-up message view is the same message view Gmail uses for all that don't use reading pane. For all of them, the search box was centered to begin with and as such, the location of the button is an elegant minimization of the search box, near where it was. And for those that use reading pane, you only ever see this when you click directly on a message in the search suggestions (not in search results).

**Moving the search button to the left is not easy**: a lot goes into making sure things in the unified app bar don't overlap 
across configs, screen sizes, and zooms. If it was easy, I would happily agree to the change as I agree it would be better in this situation.

**Comment by leggett** [comment]
And to be clear, even moving the search button by itself is not a trivial task when you make it work across configs, screen sizes, zooms, etc. There are [billions of unique Gmail setups](https://on.simpl.fyi/p/complexity-of-simplify?r=1fx0i) and so I am careful when I modify the design for a setup.
