### ISSUE TITLE
Show labels inline at bottom of message list, like "bundles lite"

### ISSUE THREAD

**Issue by andyszy** [leggett/simplify#66]
Instead of having labels show in the left panel, show any non-empty labels at the bottom of the message list, like "bundles lite." As I plow through my inbox trying to get to zero, just having the labels in my line of sight, rather than hidden off to the side, would make them way more useful.

I realize this solution might not work for folks who routinely have way more messages in their inbox, but I think this would be a reasonable alternative to #56 which seems way more complex.

**Comment by andyszy** [comment]
Also I'm secretly hoping some current Gmail design team members are lurking here and maybe this will  spark some inspiration :)

**Comment by leggett** [comment]
They aren't. It won't. :(

But interesting idea. Instead of the bottom of the inbox, you can set the ones you care about to only show in the nav when they have unread items. I think that is probably better than any custom solution I'd build.

**Comment by leggett** [comment]
Toyed with this a tiny bit and it is a major pane to support (putting the labels at the bottom of the screen). Moving them there out of the nav isn't going to work. So I'd have to create them and put them down there and read the unread count from the nav. 

I think you're better off managing your nav more to achieve this effect. I spoke more about how I'm using category tabs and labels to decide when I view different mail here: https://twitter.com/leggett/status/1116728321536974850

I won't say for sure no to this (something about it is interesting)... but moving to the someday maybe list for now.

**Comment by leggett** [comment]
Going to close this finally... but I'll keep it in mind with some work I'm doing around making it easy to jump to the next _____ message while in message view (where the blank can be unread, unread with this label, etc.)
