### ISSUE TITLE
Plan has disappeard - app thinks I am on a trial

### ISSUE THREAD

**Issue by rhulse** [leggett/simplify#662]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

Just today I got an popup that said my trial nearly over. Signing into my existing account, it says I am not on any plan (I was on the single user plan). Not sure what has happened, unless it has been a year since I signed up (can't recall).

<img width="370" alt="Screen Shot 2022-02-17 at 1 02 31 PM" src="https://user-images.githubusercontent.com/30732/154378759-5579f01c-791b-4c4e-a9f1-7254a866757a.png">

---
Simplify v.2.5.12 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup defaultTheme fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inMsg invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity minimizeChat msgWidthSm simplify supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36 - Window: 1277 x 1411 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Strange -- I just checked your plan and everything is in order and should be fine. Maybe try a hard refresh and see if it pops up again (it shouldn't).

I'm going to follow up over email at your @gmail.com address.

**Comment by rhulse** [comment]
That is strange because I checked the gmail one. Sadly, that was after a couple of hard refreshes, and I just tried again now (work address) and got the same. Is OK after hard refresh on home account. Both on 2.5.12.

**Comment by leggett** [comment]
When I looked, it said you hadn't logged into the Simplify account with
your Gmail address since originally signing up last summer. But it sounds
like everything is working now?

(Using Simplify in Gmail doesn't involve signing into the Simplify account.
You only sign in to manage the plan. The plan is validated in Gmail without
signing in to Simplify.)

**Comment by rhulse** [comment]
Still playing up on the work account. I tried the add email option, didn't seem to like it. 

Just as an aside, I have been offered the new layout, so happy to do some testing on that for you.

**Comment by leggett** [comment]
Let's discuss on email instead of here on GitHub.
