### ISSUE TITLE
[Feature Request] Show bundles for labels that are configured to skip the inbox

### ISSUE THREAD

**Issue by n1ckd0r** [leggett/simplify#668]
Bundles was always a game changer in Inbox so I'm very pleased to see them in Simplify. However, not having similar functionality in the mobile app is jarring because the nice bundled view makes it easier to leave things in the inbox, which then makes it harder to sift through messages in the app.

Not sure if this is possible, but one idea I had that might help is if there was a way to configure certain labels or categories that get bundled with simplify to hide them from gmail. Something like skip inbox, but let them show in bundles in simplify still. That way, noisy categories would still show bundled on the web client with Simplify so they don't get missed / lost, but would be hidden in the mobile app to keep things more focused there.

**Comment by leggett** [comment]
Not just with Simplify... but with Gmail filters and inbox options and Simplify, kind of? I'm not sure it would be that great though. And it isn't that easy to setup and would only work for categories (this would involve filters and you can't filter on a label, but you can on a category). 

You could setup a filter that has mail for certain categories skip the inbox and then using either Priority Inbox or Multiple Inboxes, bring mail from outside your inbox back to the inbox. The mobile app will mirror any changes to your desktop inbox but gives you the option to look at just one section.
