### ISSUE TITLE
Name of add-on when hovering

### ISSUE THREAD

**Issue by mightymouse2045** [leggett/simplify#67]
I don't see the name of the add-on when hovering over the add-on as per the default Gmail behaviour.

This is nice as I don't know add-ons by icon

**Comment by leggett** [comment]
This is sadly intentional. The labels are a different element and cause the whole add-ons chooser to close. Maybe I can move the label to the left instead of hiding it...

**Comment by mightymouse2045** [comment]
Ah ok - that would work for me at least if you can do it... if not, it's not a painful work around to open and close an add-on
    On Thursday, 18 April 2019, 1:41:31 pm AWST, Michael Leggett <notifications@github.com> wrote:  
 
 
This is sadly intentional. The labels are a different element and cause the whole add-ons chooser to close. Maybe I can move the label to the left instead of hiding it...

**Comment by leggett** [comment]
Moving it to the left wasn't too hard. Will be part of 1.1.9.
<img width="161" alt="Screen Shot 2019-04-17 at 11 06 08 PM" src="https://user-images.githubusercontent.com/8763662/56340046-7e4bd180-6165-11e9-84fc-b300d32388df.png">

**Comment by mightymouse2045** [comment]
Perfect thanks for that :)
    On Thursday, 18 April 2019, 2:07:00 pm AWST, Michael Leggett <notifications@github.com> wrote:  
 
 
Moving it to the left wasn't too hard. Will be part of 1.1.9.
