### ISSUE TITLE
New Workspace Layout Cascades to Formatting Changes for Simplify 

### ISSUE THREAD

**Issue by nilnocb** [leggett/simplify#670]
A couple days ago I opted in for Google Workspace's "new" layout. It appears to interfere with Simplify formatting. It is visible in Dark Mode (no Gmail theme, default density, default inbox type, no split).

Toggling between the Gear icon's Setting to "Try out the new Gmail view" and reverting makes the changes repeatable.

I think there may be navigation issues, but I can't determine it consistently.

The compose button is different as well.

Lastly the sizing of the email view port has changed (old "large" pixel width now extends past width of available screen in new Gmail view).

---
Simplify v.3.0.11 - Configuration: aAX appMenuOpen bundleInbox ca3 caI caL cfC cfI cfO cfQ cfR cfU composeActions composeFormat darkTheme dateGroup fontMsg hideEmoji hideLabelChips hideListCount hideMsgCount hideSelectRefresh hideSignatures hideTabIcons inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity minimizeChat msgLabelsRight msgWidthLg nPane newUI reverseMsgs rightStar showAvatars simplify simplifyCanary simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 - Window: 2256 x 1460 (150pct zoom) - Language: en

**Comment by nilnocb** [comment]
The width issue is visible when one reveals the side-panel (like Calendar)

**Comment by leggett** [comment]
Thanks! I got access on one of my accounts recently and am working through all that is needed to support the new Gmail design. Super helpful hearing about the width size not working correctly: I hadn't caught that one and will add it to my list.

**Comment by leggett** [comment]
Just pushed v2.5.14 that fixes this. Should reach you within 24 hours
