### ISSUE TITLE
Any plan on adapting simplify for the new Gmail view?

### ISSUE THREAD

**Issue by ryan6416** [leggett/simplify#671]
![image](https://user-images.githubusercontent.com/12979345/157355949-66dbb1ec-1cbc-4a31-9199-c6deb999d9d4.png)

![image](https://user-images.githubusercontent.com/12979345/157355951-97c85f3b-237f-4463-b351-9089902013be.png)

**Comment by leggett** [comment]
Working on this now. Am close. If you don't use Chat or Spaces, I recommend you opt out of the new design as it doesn't have any benefit.

Tracking work in #605
