### ISSUE TITLE
Feature Request: Finer date grouping for old emails. 

### ISSUE THREAD

**Issue by hlwoodcock** [leggett/simplify#672]
Do you think it would be possible to break-up older emails that are all grouped by month (e.g., January) into a finer level? For example, maybe by weeks within the month of January? I think it would really make the task of going back through old email easier and less daunting if they can be grouped into a slightly more modular list.

**Comment by leggett** [comment]
Thanks for the request. 

I'm not too keen to do this because I think it might add a lot of noise (tons of date groups with only 1-3 messages in each). 

I also am suspicious that knowing something was the first week of January vs the second is that useful as time goes by. For this week and last week, sure. Beyond that... not so sure (at least broadly speaking).

**Comment by hlwoodcock** [comment]
Thanks, Michael. I definitely see your point, but I have a bunch 30+ old
emails that I need to go through that just show up as a huge block of
emails (i.e., no logical separation) when searching for specific things and
I just wish there was some way of breaking them up so I just didn't see a
wall of emails. To me, at least, this is pretty daunting when trying to
figure out where to start going through things.

Do you have any idea on how to handle a situation like this?

**Comment by leggett** [comment]
We're getting out of Simplify and into general thoughts and advice on dealing with a backlog of email. Different techniques work for different people... so this may or may not be helpful.

**First, have a system for how you process email.** 
Inbox was designed to mostly force you into a system and I still use it today:

- Reply = do it now
- Pin = do it soon (stars in Gmail)
- Snooze = do it later, at a specific time
- Done = it is done (archive in Gmail)
- Unread = I have not read this; it is not used to track tasks or things I want to come back to. I try to not mark things as unread.

Then, decide if you want a in-depth processing of your email backlog (open every message) or a bulk-archive (scan most of the threads in list view, archive large amounts of messages). 

**In depth (opening all threads)**
A lot of time is wasted trying to decide which emails to open. It is better to start at the top or the bottom, open a thread, process it, and go to the next. Don't archive and return to the list view → stay in conversation view and either reply, star, or nothing. 

I've always found that I am SO much faster at deciding if I still need to do anything with a thread when it is open and I can see the thread vs trying to guess staring at it in the inbox. This will take a while but probably less time than you'd think. When you reach the end of a page, select all unstarred and archive.

**Bulk archive** 
Three degrees of email bankruptcy:

1. Total bankruptcy and just archive it all
2. Partial bankruptcy: One page at a time, select all (or unstarred if you use stars to mark things you need to come back to), scan the list view for anything you definitely want to read or reply to, archive the rest. Starting with the last page and working towards more recent email will ensure you don't have to keep rescan the same email.
3. Categorical bankruptcy: Search for each of the categories [ in:inbox category:promotions ] and just archive it or select all, scan, unselect, and archive most.

If you use labels and filters or have specific senders or mailing lists that send you a lot of mail, you might search [ in:inbox from:annoying-mailing-list ] and sweep them away.

**Comment by leggett** [comment]
One last thing I'll say on all this... Inbox's bundles helped a lot with this if you use filters & labels as it let you batch process. 

Simplify is bringing bundles back and you can use them in the v3 beta on [canary.simpl.fyi](https://canary.simpl.fyi). I've made a couple video demos for recent releases: https://www.youtube.com/channel/UCIMATSOLBDNYFhHRYJDtrCg/videos
