### ISSUE TITLE
"Delete all spam messages now" floating view obscures the last conversation in the view

### ISSUE THREAD

**Issue by alanhoyle** [leggett/simplify#673]
I clear out my spam folder every day as I have a higher than usual amount of false-positives.  When the total number of spams is large enough to fill the vertical space, the little floating window with the "Messages that have been in Spam more than 30 days will be automatically deleted//Delete all spam messages now" obscures the last message and makes it hard to impossible to click through on that message.

There's no way to scroll to get it out of the way (see the bottom of the screenshot)

![Screen Shot 2022-03-17 at 6 50 23 PM](https://user-images.githubusercontent.com/289779/158907773-9f1ee7cb-24dc-4051-8f4c-aed17126180f.png)

**Comment by leggett** [comment]
Thanks for the report -- there is supposed to be padding on the end of the list to make sure you can scroll the last message above this banner. I'll get this fixed soon.

**Comment by alanhoyle** [comment]
I don't see an update here, but it looks like this might be fixed now?

**Comment by leggett** [comment]
No updates... But I did try to dig into it and haven't been able to reproduce the error this far. Glad to hear you don't see it either. I'll close this but let me know if it returns.
