### ISSUE TITLE
Feature Request: Whitelist for allowing ads/tracking from specific sites. 

### ISSUE THREAD

**Issue by hlwoodcock** [leggett/simplify#674]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

Hi Michael - it would be great if there was a way to whitelist certain emails so their content isn't blocked. Specifically, I get the "daily deal" emails from Audible/Amazon and these appear to be getting blocked by Simplify. Having a way to allow these to appear (like the old button that allowed users to "show images"). 

Thanks in advance! 

---
System: Mozilla/5.0 (Macintosh

**Comment by leggett** [comment]
Can you expand what you mean by they are "blocked by Simplify"? 

I don't block emails from being delivered... I just block the 1x1 tracking pixel images embedded in the emails from loading. This shouldn't effect the delivery or function of the email.

**Comment by leggett** [comment]
If you can forward me an example of one of these emails to hi@simpl.fyi, I can dig into it more.

**Comment by hlwoodcock** [comment]
Will do right now. Thanks!

**Comment by leggett** [comment]
Ack, I'm too smart for my own good... when you forward a message with Simplify, it will strip out any trackers (so you aren't forwarding them on). So the email works for me.

Can you forward it once more but before you hit forward, temporarily disable Simplify (Alt+S on Windows or Option+S on Mac). Then forward. After sending, you can re-enable Simplify.

**Comment by leggett** [comment]
Simplify isn't blocking this image. Not sure what is but it doesn't match any of the patterns I use/check.
