### ISSUE TITLE
Bundle actions act on all, or alternatively, on any selected emails?

### ISSUE THREAD

**Issue by GollyJer** [leggett/simplify#679]
I often find myself checking a bunch of emails and then clicking the delete button and accidently deleting the entire bundle.

Obviously I can click the normal delete button, but I thought it might be interesting to make these buttons work on "all or selected" emails.
<img width="800" alt="Screen Shot 2022-04-20 at 4 51 05 PM" src="https://user-images.githubusercontent.com/689204/164343271-57193ad5-d555-46d7-b497-1dd58cae0d1a.png">

This is more of a "what do others think" post. I would like it but not sure others would.

**Comment by leggett** [comment]
Interesting! Maybe I should hide the bundle actions (which sweep the entire bundle) when you select items in the bundle.

**Comment by GollyJer** [comment]
Yeah. If the current functionality is maintained then hiding is a really good option when some items are selected. Good idea.

**Comment by GollyJer** [comment]
So far, so good with `v3.0.23`.

Thanks!

**Comment by leggett** [comment]
I fixed this specific issue a while back and hide the bundle actions when specific emails are selected.
