### ISSUE TITLE
Message list keeps scrolling to the top on each click when using split view

### ISSUE THREAD

**Issue by danielanewman** [leggett/simplify#680]
Just updated to 3.0.14; looking good except when I click a message down the list (using split view), the message list immediately jumps back to the top of the list (i.e. most recent messages).

**Comment by leggett** [comment]
Hmm... interesting. A few questions:

- You might just try a hard refresh (sometimes weird things happen right after an update). Shift+Cmd+R on Mac or Shift+Ctrl+R on Windows/Linux.
- I assume "click a message" means that you are clicking to open a message? Or are you doing something else?
- Are you using vertical split or horizontal split?

**Comment by danielanewman** [comment]
- Hard refreshed, no dice.
- Yes, clicking to open a message.
- Vertical split.

More reproduction steps:

1. Upon loading Gmail (after hard refresh), there's no conversation selected BUT the first message has a light gray background. 
<img width="1411" alt="2022-04-22_14-04-41" src="https://user-images.githubusercontent.com/5234389/164772766-00d783c9-de04-421d-a3ff-fb53f9666974.png">

2. If I use the arrow keys, the gray background disappears and the blue background for selected message appears as per normal.
<img width="1411" alt="2022-04-22_14-12-58" src="https://user-images.githubusercontent.com/5234389/164772800-06ac0836-2b5e-4629-b2aa-7508ada4eb84.png">

3. If I click another message, it highlights blue and is displayed, *but* the item I keyboard-navigated to remains gray.
<img width="1411" alt="2022-04-22_14-13-14" src="https://user-images.githubusercontent.com/5234389/164772942-546a6c7a-a579-4cef-b730-5ca58d2da4fb.png">

4. If I then scroll down and click on another item substantially further down the list, it is displayed (and highlights blue), but the message list immediately scrolls back to the the gray-highlighted item.
<img width="1411" alt="2022-04-22_14-28-17" src="https://user-images.githubusercontent.com/5234389/164773579-e7512eaf-4739-4d58-9127-1fe164f21d27.png">

**Comment by leggett** [comment]
**That is some awesome documentation there!** 

I can reproduce the issue and will dig into it. Very much related to the things I tried to fix just recently. 

If you only use the up/down keys, it works but that is a HORRIBLE solution. You should absolutely be able to click on a message further on.

**Comment by leggett** [comment]
Ok, I've got this fixed – will push an update (v3.0.15) in the next day or so. Thanks again for the detailed report!

**Comment by leggett** [comment]
Just pushed the fix.
