### ISSUE TITLE
System configurable dark mode

### ISSUE THREAD

**Issue by erikbrinkman** [leggett/simplify#685]
Simplify has a lot of nice features for dark mode gmail, but currently gmail has no support for matching the theme to the system light or dark mode. It'd be nice to be able to have simplify set the theme to the system light / dark mode.

There are a few implementation details that make this a little complicated, mainly due to the way gmail theming works. I imagine the best approach depends on simplify currently handles gmail dark mode.
- if simplify's dark mode options only affect gmail when set to dark mode and in no other themes then I think the best way to implement this would be a boolean toggle for enable system theme that uses gmails default theme for light and dark theme for dark, thus preserving the simplify options for dark mode.
- if simplifies dark mode options affect arbitrary dark themes (using information I'm not entirely aware of) then I think the best solution would be a feature where you can set the theme for light mode and the the theme for dark mode. This is significantly more complicated though. As a stop gap the first option could still be done, but with less benefit to users who theme and expect dark mode support.

**Comment by leggett** [comment]
This is pretty high on my list. 

The challenge is in how I do dark mode (I enhance Gmail's dark theme). The only way to switch Gmail themes automatically is to simulate a chain of ~5-10 clicks which takes a few seconds. So it is interruptive (not something I should do while you are writing an email). I have thoughts on showing a button that you can click to switch when you are ready or trying to detect if you are idle. And I could cover the interface while it is switching with some kind of "just a sec" screen. 

Or if I were to change how I do dark mode entirely (just invert the whole UI and apply it to any theme), I could do it seamlessly without removing focus from what you are doing. But that switch isn't a small task... 

I am staying focused on finishing bundles for now. But this is definitely high on my list for after that.

**Comment by erikbrinkman** [comment]
Somehow I figured that triggering a theme change would be complicated. Both of those options seem less than ideal, but either seem reasonable enough. I generally trust your design decisions though and appreciate the prioritization!

**Comment by macintacos** [comment]
Not sure what the preference is for this project as far as "+1"s, I really do wish that Simplify could follow the system theme on macOS.

Perhaps Simplify should not rely on the Gmail theme at all, but rather have its own theme toggle? I always thought that the "theme" option that Gmail supplied was always rather clunky, and kind-of an afterthought - so my vote is on abandoning trying to "follow" the Gmail theme entirely.

**Comment by leggett** [comment]
After I launch v3 out of beta, this is at the top of my list. And part of that will be to try having my own theming system that plays nicely with Gmail's theme and allows for things like toggling into dark mode when the OS does. It is not a small task but I have a few ideas for how I could do it.

**Comment by erikbrinkman** [comment]
Seems like this was added in v3, which looks awesome! Thanks for the extensive work!

**Comment by saket** [comment]
@erikbrinkman Interesting, this doesn't seem to work. Did you have to turn it on somewhere?

**Comment by erikbrinkman** [comment]
@saket In the new v3 options > "Enhance Dark Mode"

<img width="391" alt="Screenshot 2024-01-15 at 14 44 34" src="https://github.com/leggett/simplify/assets/858926/135886a7-859d-4d94-90dc-380ba73a9827">

**Comment by saket** [comment]
Interesting, it's only working for one of my two gmail accounts. @leggett how can I help you investigate this?

**Comment by saket** [comment]
@erikbrinkman can I also ask you to reopen this issue?

**Comment by erikbrinkman** [comment]
@saket if it's only working for one of your accounts, then it's a different issue. I think this should remain closed, and I would open up a new one with details of what is not working for your different account.

**Comment by leggett** [comment]
Thanks everyone. 

@saket report an issue from inside Gmail on the account it isn't working on:
https://mail.google.com/mail/?simplify=debug
