### ISSUE TITLE
Support Microsoft Edge?

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#69]
https://partner.microsoft.com/en-US/dashboard/apps/signup

**Comment by leggett** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/extensions/requests/

**Comment by the543Nteam** [comment]
Works with chromium edge.

**Comment by leggett** [comment]
Cool. Is the above link the best reference on getting it up for Chromium edge?

**Comment by the543Nteam** [comment]
You can install any Chrome addon directly from the Chrome store on Edge.  Most work as far as I know.  I'm sure some don't, but your awesome addon works with no issues on my computer (Matebook X Pro).  

As for your link, I'm guessing that is the best way to get it on the appropriate Edge store.

**Comment by leggett** [comment]
Closing this since Edge is now based on Chromium.
