### ISSUE TITLE
Something awesome for reaching inbox zero

### ISSUE THREAD

**Issue by thomas-evensen** [leggett/simplify#70]
To ease the pain of loosing inbox, the extension should swap the generic "No new mail!"-message with the sun when the inbox is empty. 

The gmail app includes better UX on empty inbox, but the gmail on web still only shows a text message.

**Comment by sweinreich** [comment]
What about copying the Gmail app's icon? I had to extract the icon from the app and it is unfortunately low quality (despite high resolution), so the image can't be too large. This also might have copyright issues (?).
![image](https://user-images.githubusercontent.com/5471227/56842999-7e785b00-6850-11e9-93ed-74a605bdda4d.png)
![image](https://user-images.githubusercontent.com/5471227/56843008-9e0f8380-6850-11e9-88bd-673c2e65d30a.png)

I don't think that the sun icon looks as nice, but it's another option: (I probably should move the sun down by another ~20px here)
![image](https://user-images.githubusercontent.com/5471227/56843059-1413ea80-6851-11e9-9116-040c45210f44.png)

Happy to issue a pull request for either of these.

**Comment by thomas-evensen** [comment]
I agree that the Gmail icon fits better than the sun. Both is better than the current text.

Perhaps a possibility to brand the extension with its own image?

**Comment by leggett** [comment]
I would like to find something different to show the user... I never liked the sun that much and don't have much love for the new illustrations in the Gmail mobile app. I don't want to brand it... just find something more rewarding / pleasing (or maybe funny) that also fits the interface.

**Comment by wikichaves** [comment]
I like the idea of not using illustrations but remember i18n if you choose to go text-only. I think just improving "No new mail!" style to feel more pleasant and rewarding would be a great 1st step :D

**Comment by lukasvermeer** [comment]
Showing something quirky to underline the accomplishment of achieving Inbox Zero would be nice.

(I just [hid the message entirely on my own fork](https://github.com/lukasvermeer/simplify/blob/master/gmail/lukas.css#L11).)

**Comment by jeff-hykin** [comment]
Personally, I really liked the Sun and clouds animation. It was always satisfying to me, and I thought it did a good job of saying "go outside, your email work is done". But I'd be open to better alternatives, there can be some really nice lightweight SVG animations.

**Comment by gabrielecirulli** [comment]
@leggett I'd be interested in helping with this, but first I'd like to understand a bit more of what you'd like to see. It's clear that you prefer not to use the sun or an illustration in the style currently used by the Gmail app.

What kind of theme/style would you be more interested in? Are you thinking of animations, simple shapes, specific wordings?

**Comment by leggett** [comment]
Thanks @gabrielecirulli -- happy to have some help (and welcome suggestions from others). 

Here are some random thoughts:

1. I agree that the idea of "get outside" is a nice message. I think the existing illustrations are pretty subtle about it. 

2. My other beef with the current Gmail illustrations on mobile and the old Google Inbox illustration is they didn't feel on brand somehow. The Inbox one felt like a cheap Material Logo rip off. It lacked a special something. The newer Gmail illustrations feel out of left field. Where is that illustration style used anywhere else at Google?

3. Think international -- any actual text would require translations which I want to avoid. So either repurpose the existing text or no text at all. 

4. I've also thought about the original plug for Google Reader: https://66.media.tumblr.com/tumblr_lq2axr5ddh1qea4hso1_1280.png -- but of the two, I prefer encouraging people to get away from their screen.

5. I'd love something that feels like it fits in Gmail but also somehow fits with Simplify (and the idea of minimal design). One idea I've had is a zen like illustration for zero: https://simpl.fyi/zero/index.html

6. I *LOVE* the Apple TV screen savers. Maybe embed that in the screen (though this has the opposite desired effect... I just want to stare at my screen all day): https://www.youtube.com/embed/snNwkuHxTEw

7. For themes with image backgrounds, just hiding everything and showing the image is pretty nice. But I also want to make sure they know it isn't broken... that there isn't anything new. Maybe we take the text in the middle and move it to a corner. 

8. I like humor too. For instance nearly all the Tunnelbear VPN illustrations: https://www.google.com/search?q=tunnelbear+illustration&tbm=isch -- But I fear it might be a turn off for some and I'm not sure if this is the right personality for Simplify.

**Comment by jeff-hykin** [comment]
I'd never seen the Apple screensavers before, but I would love it if I was greeted with something like that after clearing out my inbox. If there was an equivalent SVG animation that would be amazing

**Comment by vialrogo** [comment]
It will be great!! The current no new email message is not simple. I loved the zen ilustration of zero. I think that the choosen behivior has to be compatible with us, the background people. For example, imagine the sun image here:

![gmail](https://user-images.githubusercontent.com/1048874/60672387-9de0c500-9e4b-11e9-8bb9-224f83d940cd.jpg)

No image/text or a very simple svg/transparent image will be better.

**Comment by joaquinvanschoren** [comment]
Thanks for Simplify! I really love it.
I'd also like something awesome to see at inbox zero. There are many good suggestions above, but to keep things simple, I'd prefer:
- an option to hide the 'No new emails' message and the icons (select/refresh/settings) when the inbox is empty
- an option to show either a 'zen' image (like the zen illustration of zero) or an image of choosing

People using a background can then simply choose to not show an image at all.

**Comment by KraXen72** [comment]
any progress on this issue/feature request?

**Comment by leggett** [comment]
Not yet... but I've been spending a lot more time on Simplify lately and it is nearing the top of my queue. So soon.

**Comment by KraXen72** [comment]
temporary slution i made:  
```css
.aRu *{
    display: none;
}
.aRu:before {
    content: "Yay! You're all done here!";
    padding: 10px;
    margin-left: 35px;
    font-size: 18px;
    
    
   
}
.aRu::after {
    content: "\a              You reached inbox zero!";
    white-space: pre;
    color: #797979;
}
```
screenshot: 
![image](https://user-images.githubusercontent.com/21956756/82026813-8e4d2200-9693-11ea-8c32-f933a132c278.png)

**Comment by aakar** [comment]
Superhuman loads images from a third-party.  It's a different one every day to my understanding.

This extension tries to do something very similar: https://chrome.google.com/webstore/detail/gmail-inbox-zero-backgrou/fadepmbdhojcogdjcihbhdcbfpacdbdg?hl=en
— However, the extension only currently works if you have the tab layout setup.

**Comment by KraXen72** [comment]
i tried this extention and it looks really bad if you use reading pane. The image is cut off and you have to scroll to see the bottom of it.

**Comment by leggett** [comment]
Finally have this built for Simplify v2 (which is coming along nicely)!

For now, I am falling back to your theme background image and I hide a lot of Gmail's chrome. And to make sure it works in all languages, I'm not customizing the message that Gmail uses (either "No new mail!" or "Your Primary tab is empty" depending of if you use Inbox tabs or not). I also only go to this if all your tabs are empty if you use a tabbed inbox.

Before I ship v2, I will add a fall back image if you don't use a theme with an image and plan to let the user set a custom background image if you'd like something other than your theme background.

**Comment by leggett** [comment]
Here is a sneak peak of Simplify v2 with the new inbox zero treatment:
<img width="1680" alt="Screen Shot 2020-07-12 at 1 22 22 PM" src="https://user-images.githubusercontent.com/8763662/87255808-c8903100-c442-11ea-8bff-859e6ac4630f.png">

**Comment by KraXen72** [comment]
looks cool, the option to set custom background is definitely cool and i'd use it.

**Comment by KraXen72** [comment]
also please have this as an option, so i can turn it on and off. thanks.

**Comment by leggett** [comment]
@KraXen72 Wasn't planning on a setting for this. Why would you want to turn it off? I'm not hiding any part of Gmail. You can still use the nav, search, compose, and the add-ons. The only thing being hidden here is the table in the middle.

**Comment by joaquinvanschoren** [comment]
Thanks for this! How would this look like for people who don't use a background? Can we choose an image to be shown?

**Comment by leggett** [comment]
@joaquinvanschoren Yes -- I will have a default background (or maybe a set of them) and will allow you to customize it to be something of your choosing.

**Comment by leggett** [comment]
After some feedback from beta testers, I think changing the entire background is off putting. I'm not removing it, but I am changing the default to basically what @sweinreich originally suggested. I might someday replace Gmail's default illustrations with something custom.

<img width="1457" alt="Screen Shot 2021-01-15 at 6 13 25 PM" src="https://user-images.githubusercontent.com/8763662/104794591-761b2e80-575d-11eb-9ca0-fb9ecc99d16b.png">

**Comment by CarlosRebolledo** [comment]
Buena imágen  !!!!! 

Mantendría los temas de fondo que ya existen y tengas la posibilidad de agregar otras imágenes hermosas o representativas de meta cumplida, tranquilidad, equilibrio, o incluso más vinculante aidea país (porque quiero imágenes de mi hermoso país Chile jajaja) o temas de opinión (no discriminación, libertad de opinión, paz, cambio climático, sequía, administración de recursos hídricos, etc).

Darle más valor al fondo ya que a veces una imágen vale más que mil palabras, y la fuerza de ellas, usada positivamente quizás no sea una mala idea. 

Un abrazo y gracias por tú trabajo Michael

**Nota:** Si buscas imágenes de Chile, tales como desierto Florido, Torres del Paines, Queulat, Caleta Tortel, Parque Conguillío, etc., verás lo hermoso que es este país. Ahhhh y el que venga a Chile post Pandemia está invitado a un asado en la Cordillera (Altos de Lircay - Yo invito)

**Comment by paul-brenner** [comment]
I just want to confirm that there is no way to get something like @leggett posted on July 13, 2020? I feel like I must be missing something because inbox zero currently looks like a glitch when I have a background image. 
<img width="1479" alt="Screen Shot 2022-05-24 at 3 21 57 PM" src="https://user-images.githubusercontent.com/13038942/169962726-d76dbad7-f673-493d-b73d-2d4039679fbe.png">

**Comment by leggett** [comment]
Hi @paul-brenner -- it is possible. You can hide the illustration by changing the Simplify preference to "No background" in the Conversation list section:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/8763662/169964671-607341b9-58b4-4fbd-8b7c-2e9e23caccf6.png">

But that you need to change the Simplify preference is a bug. It looks like you're using one of the original themes. I should detect that there is a background and not show the illustration but some of the original themes apply the background in unique ways. I don't recall testing this theme in detail so there is likely a bug with it. I'll look into it.

**Comment by paul-brenner** [comment]
Sorry, I should really have been able to find this myself. Just started trying simplify and honestly missed the simplify specific options until your comment. On the plus side now I know this is a well supported effort that I should is worth spending a few bucks a month on!

**Comment by leggett** [comment]
Honestly, Simplify's settings are a bit of a mess right now (it is what I am going to work on next after bundles are done). So not really your fault. And good software should just work without you scouring long lists of settings.
