### ISSUE TITLE
feature request: color custom groups

### ISSUE THREAD

**Issue by ghost** [leggett/simplify#702]
Would there be a way to have the custom bundles labels coloured like, for instance, the "Promotions" label is green?

**Comment by leggett** [comment]
Yes -- I plan to use the label color on the bundle... just haven't gotten it done yet.

**Comment by leejoramo-d51** [comment]
Just noting that I would like to see this feature too.

**Comment by leggett** [comment]
Almost at the top of my list and one of the few remaining things to do before I launch v3 out of beta.

**Comment by leejoramo-d51** [comment]
Thank you for adding  this! Looks great

**Comment by leggett** [comment]
Launched this weekend in the v3 beta
