### ISSUE TITLE
Can Bundles be disabled?

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#704]
Every time I read a comment about bundles, or see the feature being demonstrated in a video, I wonder what's the big deal. For me, feeling the need to use it just feels like it's just a way to fight a symptom instead of curing the actual problem (which is receiving too many emails). If you have so many newsletters that you need bundles, spend some time unsubscribing from list for messages you end up not reading properly anyway (just as an example).

Which brings me to my question: will I be able to completely disable bundles once the future version of the extension offering the feature gets released?

**Comment by leggett** [comment]
Absolutely. I'm not even sure if I'm going to enable them by default. 

You can already in the beta:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/8763662/179088918-c83f8841-6a4a-480b-9672-038fbcac8b7f.png">

I think the people that love bundles fall into one of the following buckets:

- prefer bundles to Gmail's tabs (both automatically sort your mail and diminish the noise from non-personal email)
- use filters and want to achieve the same effect for other mail that either isn't categorized by Gmail (or they want more narrow categories)
- do periodic clean-outs of their inbox and value the ability to easily batch process email of a similar type or subject

If you love Gmail's tabs, don't get much email, and/or either keep your inbox below 10-20 items at all times or never clean it out, bundles probably don't add much value for you. Let me know if you think there are other use cases for or against them as I try to figure out if I recommend them to or turn them on for certain customers at launch.

**Comment by erikgeurts** [comment]
I fall in the category of not using tabs, not receiving a huge number of emails, and having an inbox that's close to zero at almost all times. I'm also a heavy user of filters and labels. I completely ignore categories and try to avoid seeing them altogether. I found in the past that Gmail was very bad at correctly categorizing my emails.

For me, as you say, bundles won't add a lot of value and probably will only cause more noise. I like Simplify for making the Gmail UI simpler, cleaner, less distractive.

So for me, having the ability to keep bundles disabled is great. Given my email habits and the way my brain works, I can't imagine ever having a need for bundles.
