### ISSUE TITLE
Option to make the search box remain dark while searching

### ISSUE THREAD

**Issue by benguaraldi** [leggett/simplify#706]
When clicking on the search box in dark mode, it goes from looking like this:
<img width="559" alt="Screen Shot 2022-07-20 at 5 00 56 PM" src="https://user-images.githubusercontent.com/852673/180081377-3706223f-27d8-4b18-8a01-3aa38f546208.png">

to looking like this:
<img width="581" alt="Screen Shot 2022-07-20 at 5 01 52 PM" src="https://user-images.githubusercontent.com/852673/180081468-1ef8ac0b-ca04-4450-9482-9feec31e2c4b.png">

...which is pretty blinding.

It would be nice to have an option to leave the search box in dark mode or pick a color for it or the like.

Thanks!

**Comment by leggett** [comment]
Yeah, there are numerous places where I don't make things dark. I've got plans to revamp my dark mode from the ground up... actually started looking into this some last night.

**Comment by benguaraldi** [comment]
Cool, thanks!  So far, this is the only one that bothers me.
