### ISSUE TITLE
Three-dot overflow menu during full screen compose moved

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#711]
In my personal Gmail account (which I've still got on the old view), when composing a new message in full screen, the three-dot overflow menu has moved to an unusual place in the bottom bar:

![image](https://user-images.githubusercontent.com/5102461/182787390-59063291-57a2-4258-a85a-248edf257696.png)

In the Google Workspace accounts (also the old view) I use for my work, it is still in the usual place:

![image](https://user-images.githubusercontent.com/5102461/182787502-2422677e-3ec3-4edb-bf36-0415adea6ffd.png)

This is on the same computer, same browser. I noticed it on other computers as well, including Chromebooks.

Simplify v.2.5.21 - Configuration: aAX appMenuOpen ca3 caI caL cfO cfQ cfR cfU cfZ composeActions composeFab composeFormat dateGroup defaultTheme fontMsg hideLabelChips hideSelectRefresh hideTabIcons highDensity inInbox inList izBgDefault lightTheme listWidthLg minimizeChat msgLabelsRight msgWidthLg newUI sendLater simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36 - Window: 1530 x 993 (101pct zoom) - Language: en

**Comment by erikgeurts** [comment]
I just observed that the three-dot symbol has also moved when I'm replying to an incoming message, both in Gmail and in a Workspace account:

![image](https://user-images.githubusercontent.com/5102461/182788901-973b44b7-2382-4cbe-871c-7a295fd9248b.png)

**Comment by leggett** [comment]
Just pushed a fix for this in v2.5.23 – it is in review across browsers.

**Comment by erikgeurts** [comment]
I already received v2.5.23 here, that was quick.

Surprisingly, the three-dot many has now moved to the 'wrong' place in most but not all of my Gmail and G Workspace accounts, both when composing a new message and when replying to a message.

I've refreshed things a number of times, but that didn't help. Perhaps I'll have more luck after I've rebooted my PC completely, but I won't be able to do that while I'm in the middle of work.

**Comment by leggett** [comment]
Hmm... maybe I need to only apply this fix if you have the new Material You design?

**Comment by leggett** [comment]
I only apply it if you have one of the new designs from this year because I thought they had finished moving everyone from the Feb 2022 design to the July 2022 Material You design. But maybe I should only apply it if you have the July design? Or maybe there are configs where the fix wasn't needed?

**Comment by leggett** [comment]
Nope... it is the opposite. I need to apply this to all versions as they changed it on the old Gmail design too.

**Comment by erikgeurts** [comment]
Thanks for looking into this further. It's weird, the item has moved place in Gmail and in some of my Workspace accounts but not all of them.

**Comment by leggett** [comment]
I just pushed v2.5.24 and v3.0.31 which should fix this. Please let me know if it doesn't.

**Comment by erikgeurts** [comment]
I received v2.5.24 just now and I'm pleased to be able to report that it's now showing up where it was supposed to be in all of my Workspace accounts and in my personal Gmail account, when replying and when composing a new message.

**Comment by leggett** [comment]
Fantastic! Thanks for the report and thanks for checking.
