### ISSUE TITLE
Feature request: hide individual bundles

### ISSUE THREAD

**Issue by cflewis** [leggett/simplify#714]
Perhaps an odd request.

I would like the ability to hide, or otherwise float down, emails with a particular label. I want them to stay in the Inbox and perhaps be shown in a bundle with a different label, I just don't want to see that particular label.

The why is that I have an automated script that is running against my Gmail and tags whether the script has processed the email with a label. I don't want to see a bundle telling me that the script processed them, that just ends up being a mirror of my entire Inbox. I realize this use case is very specific, but there may be other use cases that such a feature would be useful for.

Feel free to ignore this if it feels too esoteric :)

**Comment by leggett** [comment]
Sounds like you want to pin a bundle (when present) to the bottom of the inbox?

Would it serve your needs to just not bundle that label maybe?

**Comment by cflewis** [comment]
Yes, that would work as well!

**Comment by leggett** [comment]
Just to clarify, are you saying it would work to not bundle that one label?

If so, you can do that now: https://youtu.be/6WeIT0k2oY4

**Comment by cflewis** [comment]
Aha, yes, this does solve the purpose. Thank you!
