### ISSUE TITLE
Snooze icon has masking issue

### ISSUE THREAD

**Issue by jaredzimmerman** [leggett/simplify#716]
![image](https://user-images.githubusercontent.com/430427/186289934-d4ef7cd6-3d9e-4969-891a-24fb898cab3e.png)

ChromeOS Version 105.0.5195.42 (Official Build) beta (64-bit)

**Comment by leggett** [comment]
Thanks for the report -- I've got a fix for this ready for the next update. Should go out soon.

**Comment by leggett** [comment]
Thanks Jared -- I half fixed this in the last update and have a full fix ready with v2.5.27.
