### ISSUE TITLE
Feature Request: Add "Report Spam" option to right-click menu

### ISSUE THREAD

**Issue by rcdailey** [leggett/simplify#721]
When I right-click an email in my inbox, I expect to see a "Report Spam" option toward the top that is convenient to click. However, no such option exists. Best workaround I'm aware of is that you have to go to Move To -> Spam. But this is tedious.
![image](https://user-images.githubusercontent.com/1768054/188275835-6d888e03-32a5-41db-9e77-91ac3ea7929d.png)

**Comment by leggett** [comment]
Thanks for the feature request. 

I have no idea why Gmail doesn't have Report as spam in that menu. Adding it isn't super simple (or I would just do it). I'll add it to my list of things to consider once v3 is out to everyone.

You can also use keyboard shortcuts. You can enable them if you haven't already about half way down in the keyboard shortcuts overlay (press `?`). Once enabled, `!` will mark any selected messages as spam. If you enable Simplify's auto-select, you don't even have to select the message... just use the up/down arrow keys to move focus and then hit `!` to report as spam.

**Comment by rcdailey** [comment]
I falsely assumed you created the context menu; I certainly don't mean to ask you to do something unreasonable.

I really love the keyboard shortcuts. Never occurred to me to use them! Thanks for the advice; I'm sufficiently happy with your idea.
