### ISSUE TITLE
v3: Off-by-one error with ads?

### ISSUE THREAD

**Issue by danielanewman** [leggett/simplify#722]
I'm on 3.0.31 using the 'new' Gmail. FWIW, ads are being shown, which might be part of the issue here...

When deleting messages in the categories, upon deletion, the focus shifts to the next unread message until I get to the last unread—then the focus is placed on the second ad unit, rather than the last new message. Furthermore, when I click to and delete the last unread message, the entire tab blanks out, and is non-recoverable without a hard refresh. This happens in both Social and Promotions, though I haven't seen it in the Primary nor Updates categories.

![2022-09-13_13-11-22 (1)](https://user-images.githubusercontent.com/5234389/189965916-49512622-7164-45da-8c4d-a252549e9060.gif)

---
System: Mozilla/5.0 (Macintosh

**Comment by leggett** [comment]
Hi Daniel, Thanks for the report. This should be all fixed now. Let me know if you're still seeing any issues.
