### ISSUE TITLE
Promotions tab keeps changing its place

### ISSUE THREAD

**Issue by ymyke** [leggett/simplify#723]
The Promotions tab seems to change its place every now and again. Currently, it's the 4th (rightmost) slot. Until a couple of days, it was in the 2nd slot for some time. Before that, it was in 3rd slot. – Is this something Simplify does or does Gmail do that? (In order to generate attention to the Promotions tab?)

---
Simplify v.2.5.29 - Configuration: aAX appMenuOpen ca1 cfI cfK cfO cfR cfU composeActions composeFab composeFormat defaultTheme fontList fontMsg hideLabelChips hideListCount hideMsgCount hideSelectRefresh hideSignatures hideTabIcons inInbox inList invertAddons invertCompose izBg3 lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm nPane newNav newUI simplify simplifyMenuOpen - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 - Window: 1280 x 768 (100pct zoom) - Language: en

**Comment by leggett** [comment]
This time it was me -- I changed the tab order with the latest Simplify update. 

The Promotions tab used to be the 3rd tab (after Social) until the big design update this summer where Google made it the second tab. 

I think most would agree that promotional mail is the least important and I've had several users complain (thinking it was Simplify that changed the order) and ask if I could push Promotions to the end of the row. After getting a few separate requests, I decided to give it a shot.

This change will go one of three ways from here based on user feedback:

1. Undo the change and don't mess with the tab order if there is much pushback 
2. Add a setting to turn the change on/off. Listen for the (`) keyboard shortcut and if it is ever pressed, turn the setting off so the visual order matches the order Gmail goes through.
3. Add a more robust setting that (a) gives you full control over the older AND (b) overwrites the (`) keyboard shortcut so it matches the visual order of the tabs.

**Comment by leggett** [comment]
And I guess there is a 4th option if I really want to go crazy: let you drag-n-drop the tabs to change the order.

**Comment by ymyke** [comment]
Thanks!

2 sounds a bit kludgy to me. And 4 like overkill.

I'd prefer 1 and – given time on your end – 3.

Also, I'd love to be able to hide tabs (especially Promotions) altogether. (We had a conversation around this some time ago where you mentioned bundles as a workaround to that end but I can't find it any longer.)

**Comment by leggett** [comment]
Thanks for the feedback.

1. I've submitted an update to revert this change for now... will work on (4) which I don't think will be a lot more work than (3).
2. Bundles are still in beta (you can use them if you switch to [Simplify v3](https://beta.simpl.fyi)) and then make sure you have the categories [set to bundle](https://youtu.be/6WeIT0k2oY4?t=119).
3. You can hide any of the tabs under Gmail quick settings → Inbox type → Customize on the default inbox which will show you this dialog:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/8763662/190313178-4b0c61b6-25f8-4764-8c5a-04c8c5810fb7.png">

**Comment by ymyke** [comment]
Thanks – yes, I can deactivate the Promo tab in Gmail. But then those mails show up elsewhere, I assume? What I would like is to still have the promo mails be labeled as such but the tab itself hidden (but the label still there). That way, I can choose to review those once a week or so. I'd love the same for the Social tab btw.

**Comment by leggett** [comment]
Correct -- disable the tab and those emails will show up in the Primary tab.

With Simplify v3, you can set any label or category to bundle so they only take up one row in your inbox. I don't have an option to snooze or schedule when those bundles show up at this time but hope to add that at some point. 

Since this kind of configuration takes time on your end, I want to make sure those configs are backed up and even synced across devices. So I'm currently trying to rebuild simplify settings as those have all been stored locally only thus far.
