### ISSUE TITLE
Provide xxx-large and xxxx-large options for list width and message width

### ISSUE THREAD

**Issue by raghavendra-talur** [leggett/simplify#724]
I am guessing that you provided 1400px(xx-large) option for list and message width considering monitors that have 2560 horizontal pixels. 1400/2560 comes to around 55% and has a nice look to it.

On monitors that have 3440 or 3840 horizontal resolution, 1400 px is around 40% of the width and some people might benefit from having something close to 55%. Would you consider providing xxx-large(1800px) and xxxx-large options(2100px)?

**Comment by leggett** [comment]
No, I don't think it makes sense to have a specific max-width larger than 1400px as the line lengths are so ridiculously long that it greatly degrades the experience. 

I only added the option for full screen (no max-width) to support people with use cases where a lot of their email is dealing with large inline images (like blueprints or diagrams). 

You might consider using Gmail's vertical reading pane setting (which Simplify improves) to better utilize that kind of window size.

**Comment by raghavendra-talur** [comment]
Thanks for the quick reply and justification. I will try the full width and/or split view option.
