### ISSUE TITLE
Button icons cannot be loaded on Firefox because they use protocol relative URL 

### ISSUE THREAD

**Issue by ZhangYiJiang** [leggett/simplify#729]
Some Gmail icons do not load correctly because they are loaded using protocol relative URL, so Firefox tries to load them using moz-extension instead of https 

<img width="1491" alt="Screen Shot 2022-10-19 at 1 42 27 PM" src="https://user-images.githubusercontent.com/445650/196800129-a6bf313e-c1e5-42d7-a521-3da790920b6b.png">

<img width="1170" alt="Screen Shot 2022-10-19 at 1 42 09 PM" src="https://user-images.githubusercontent.com/445650/196800140-66ef7be5-5b8a-4e8b-8a6f-33625579b008.png">

---
Simplify v.2.5.34 - Configuration: aAX appMenuOpen ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons imgTheme inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity matYou mediumTheme minimizeChat msgSelected msgWidthSm navOpen newNav newUI simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10.15 rv:106.0) Gecko/20100101 Firefox/106.0 - Window: 1837 x 1199 (122pct zoom) - Language: en

**Comment by leggett** [comment]
Yikes! Thanks for the report. Will get a fix out ASAP.

**Comment by leggett** [comment]
Fix went out last night in v2.5.35
