### ISSUE TITLE
Feature Request: Show unread message count in Favicon

### ISSUE THREAD

**Issue by liorgrossman** [leggett/simplify#744]
Gmail has a toggle in its Advanced Settings that is called "Unread message icon", which shows how many unread messages are in your Primary Inbox through the favicon:
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/987284/236901847-6ec88f5c-f6f8-4001-b35d-fd4befec57c7.png">

When turned on, this feature looks as follows (notice the 2):
<img width="109" alt="image" src="https://user-images.githubusercontent.com/987284/236903154-596d31cc-474e-48ce-9162-6fa3af23214a.png">

It's useful because it allows you to always know whether there's anything unread in your primary inbox:
- Even if you're in a page that isn't the primary inbox (e.g. Sent, Promotions, search results)
- Even if you have a lot of tabs open and the tabs are narrow, truncating the page title

Unfortunately, currently having this feature turned on in Gmail overrides Simplify's "Use solid-color Gmail favicon" feature, so there's no way to use both in tandem.

It would be great if next to the "Use solid-color Gmail favicon", there could be an additional feature for "Show primary inbox unread count in favicon". I'm sure there are ways to even further customize and enhance this feature.

**Comment by leggett** [comment]
Thanks for the detailed request -- unfortunately I wasn't able to combine these features. Gmail is a lot better at updating the unread count on the favicon even when the tab isn't in focus (which is when this feature is most useful). 

Simplify doesn't have the same level of access to keep that as accurate and I didn't want to degrade the feature to add a color favicon.

**Comment by liorgrossman** [comment]
Makes sense. Thanks for considering this feature
