### ISSUE TITLE
Feature Request/Question... 

### ISSUE THREAD

**Issue by hlwoodcock** [leggett/simplify#745]
Hello, 

Question... is it possible to make your Google Tasks show up in the Calendar side bar in gmail? 

For example, if you go to full Google Calendar then your Google Tasks show up as entries, however, they do not show up in the side bar Calendar widget in gmail... is there anyway to make this happen so I don't have to switch back and forth between Tasks and Calendar get an overview of my day (i.e., in terms of both meetings and todos/tasks)? 

As always, thanks for all of your efforts with this!!

**Comment by leggett** [comment]
Unfortunately, there doesn't appear to be a way to show Tasks on the Calendar in the side widget. I still have the open request to show two widgets at one time so you can see a task list and your day at once time. Stay tuned on that...

**Comment by hlwoodcock** [comment]
Thanks so much for looking into this!
