### ISSUE TITLE
Favicon doesn't change color for multiple accounts

### ISSUE THREAD

**Issue by littke** [leggett/simplify#746]
Hey team,

These two are two different accounts yet they show up with the same favicon. Isn't that what the setting is supposed to address?

(Alternatively, is there a way to turn on the Google Workspace symbol in the upper right corner to help differentiate between the two accounts? Thx!)

<img width="781" alt="Screenshot 2023-05-11 at 3 52 57 PM" src="https://github.com/leggett/simplify/assets/227383/7b915653-a938-4946-8049-246252f402d9">

<img width="485" alt="Screenshot 2023-05-11 at 3 52 54 PM" src="https://github.com/leggett/simplify/assets/227383/83dfaef5-9aa1-40d3-8134-ccfc6c949d3a">

---
Simplify v.2.5.38 - Configuration: aAX appMenuOpen ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lang-en lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm nPane newNav newUI oeHubspot otherExtensions simplify simplifyMenuOpen - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 - Window: 1919 x 1415 (110pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the report. I don't change the favicon if you have the unread count favicon enabled in Gmail's advanced settings. If you disable that on any of your accounts, it will work.

**Comment by leggett** [comment]
And no, there isn't a way to turn on the Workspace logo in the top right corner. I'll add that to my list of things to consider.

**Comment by leggett** [comment]
I'll add: my solution to this is I use a different profile picture in different accounts (I use three accounts regularly).

**Comment by littke** [comment]
> I don't change the favicon if you have the unread count favicon enabled in Gmail's advanced settings. If you disable that on any of your accounts, it will work.

Understood. So you'd have to generate 10x the favicons to support this I take it? :)

> I'll add: my solution to this is I use a different profile picture in different accounts (I use three accounts regularly).

I guess I'll need to take more good pictures of myself... :) 

(Related request: hotkey for switching between accounts.)

**Comment by leggett** [comment]
It would be 100x (the icon goes up to 99) but it is more that the extension goes to sleep to some degree when you're off the Gmail tab and I wouldn't be able to update the favicon when the unread count changes nearly as reliably as Gmail can.

I've got ideas on making it easier to switch between accounts but nothing built yet. I handle this today by pinning multiple tabs in Chrome:

<img width="265" alt="image" src="https://github.com/leggett/simplify/assets/8763662/22b70873-3a6c-454f-9e6d-5f3b1e43f080">
