### ISSUE TITLE
HubSpot overrides hiding add-on icons

### ISSUE THREAD

**Issue by littke** [leggett/simplify#747]
HubSpot always shows up in the upper right corner:

<img width="152" alt="Screenshot 2023-05-11 at 3 56 46 PM" src="https://github.com/leggett/simplify/assets/227383/87f38030-161a-4295-9474-2c1d5c8e35a3">

But it should only show on hover?

<img width="667" alt="Screenshot 2023-05-11 at 3 57 17 PM" src="https://github.com/leggett/simplify/assets/227383/0f7b14a7-9083-4e4d-8284-7e3ede7fda9a">

Thx

---
Simplify v.2.5.38 - Configuration: aAX appMenuOpen appNavOff ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lang-en lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm nPane newNav newUI oeHubspot otherExtensions simplify simplifyMenuOpen - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 - Window: 1919 x 1415 (110pct zoom) - Language: en

**Comment by leggett** [comment]
This is working as intended. I put other extension buttons (if they have one) in the top right corner so (a) you can access them and (b) you're aware of who you gave access to your Gmail account to.

The add-ons refers to Gmail's Add-on tray that shows as a vertical column of icons (Calendar, Tasks, Contacts, etc). I hide that by default and show it on hover.

**Comment by littke** [comment]
Makes sense. Thanks.
