### ISSUE TITLE
doNotBundle label array not initialized in fresh account

### ISSUE THREAD

**Issue by macx** [leggett/simplify#749]
When I enable an add-on, the menu item from Simplify as the add-on tray and the compose button are placed strict to the right of the screen. I'm afraid that's not right if the add-on tray is opened. It should be placed left the add-on tray.

This is on private GMail as Business as well.

![CleanShot 2023-05-29 at 10 02 23@2x](https://github.com/leggett/simplify/assets/84112/f406ff74-f623-43fc-bc76-89433d245ac6)

---
Simplify v.3.0.46 - Configuration: aAX appMenuOpen appNavOff bundleInbox ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup fontMsg hideEmptySections hideLabelChips hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity minimizeChat msgWidthSm nPane newNav newUI rightStar sendLater showAppNav showAvatars simplify simplifyCanary simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 - Window: 1728 x 1079 (100pct zoom) - Language: de

**Comment by leggett** [comment]
I'm struggling to reproduce this issue (see below). Does a hard refresh (⌘⇧R) fix it by chance?

<img width="598" alt="image" src="https://github.com/leggett/simplify/assets/8763662/28e5c94b-93f9-442f-9650-c345d9b58ba0">

**Comment by macx** [comment]
It's a brand new MacBook Pro with synced Google-Profile. For testing I created a new profile, to make sure no other extension is involved. I added Simplify Canaray without the Google sync, but It's still the same.

**Comment by leggett** [comment]
Something else looks off -- it looks like you are using the default theme and yet the page background is not white. Would you be up for having a short video call so I can troubleshoot further? Email me at hi@simpl.fyi if yes. Shouldn't take more than 5-10 minutes tops.

**Comment by leggett** [comment]
The doNotBundle array isn't getting initialized for some reason. Turning bundles off, refreshing Gmail, and then turning them back on fixed the issue. Needs further investigation.
