### ISSUE TITLE
Grammarly hidden 

### ISSUE THREAD

**Issue by odedharth** [leggett/simplify#750]
The [Grammarly extension](https://www.grammarly.com/browser/chrome) is hidden as you can see in this screenshot:

![Screenshot at Jun 06 14-28-38](https://github.com/leggett/simplify/assets/624023/3e78d344-6e7f-4ca2-8668-3456e0b30ad0)

---
Simplify v.2.5.38 - Configuration: aAX appNavOff ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inMsg invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm newNav newUI simplify supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 - Window: 2560 x 1440 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the report -- this is a Grammarly bug that is made worse by Simplify. You can see more here in this issue report: https://github.com/leggett/simplify/issues/741#issuecomment-1475320094

I fixed it in the v3 beta and need to fix it in Simplify Gmail v2.

**Comment by leggett** [comment]
The fix for this is now live in v2.5.39.
