### ISSUE TITLE
"Quick Links"

### ISSUE THREAD

**Issue by error9900** [leggett/simplify#752]
I'm not sure if this fits into your vision for Simplify, but I would love similar functionality to the Quick Links Lab they used to have:
https://www.bettercloud.com/monitor/the-academy/quick-links-lab-for-gmail-2/

**Comment by leggett** [comment]
Quick Links! This is on my list somewhere... I need to get v3 out first. And thanks for the link to the article/video. I was on the Gmail team when this launched and I only ever thought about it for saved searches -- never for bookmarking an email.

**Comment by gjm** [comment]
+1 for this, please!

**Comment by leggett** [comment]
Some good news: this will launch as part of v3 before the end of the year. I'm starting with saved searches and will consider bookmarks (saving a link to a message) in a future release.

**Comment by error9900** [comment]
Thanks for getting saved searches implemented!
