### ISSUE TITLE
Favicon not changing colors?

### ISSUE THREAD

**Issue by megaroeny** [leggett/simplify#753]
Am I missing something, or is the favicon option not entirely working? I can get it to change the color once, but not to other colors, without switching the option off/on first. See:

https://github.com/leggett/simplify/assets/1559447/940d40a8-3d51-4da2-a9aa-3d8fb7bb4754

I'm using MS Edge Version 114.0.1823.67 on macOS. Thanks!

---
Simplify v.3.0.48 - Configuration: aAX addOnsOpen appMenuOpen bundleInbox ca3 caE caI cfC cfO cfQ cfR cfU composeActions composeFab defaultTheme fontList fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBg1 lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm newNav newUI rightStar sendLater showAvatars simplify simplifyCanary simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67 - Window: 1468 x 1053 (128pct zoom) - Language: en

**Comment by leggett** [comment]
It will update for each tab once you refresh Gmail... _sometimes_ I can update without a refresh. I'll see if I can attempt to update it when you update the color as I do when you toggle the setting.

**Comment by megaroeny** [comment]
Ah okay. Its not a huge deal! Thought it might have been a bug is all.

**Comment by leggett** [comment]
I now update it immediately in v3.0.56+
