### ISSUE TITLE
Safari 17 beta: Images do not load in emails

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#755]
Images do not load in any emails when the Simplify extension is enabled in Safari 17 beta. It makes no difference if I just disable Simplify from the menu in Gmail, the extension has to be disabled entirely in Safari's settings.

Sonoma 14.0 Beta (23A5286i)

---
Simplify v.2.5.39 - Configuration: aAX appMenuOpen appNavOff ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab fontMsg grayTheme hideLabelChips hideListCount hideMsgCount hideSelectRefresh inInbox inList invertAddons invertCompose isSafari izBgDefault lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm newNav newUI simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15 - Window: 1512 x 945 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Yikes! I'll install the beta and look into it. Thanks for the heads up.

**Comment by leggett** [comment]
Is this all images (as in the images in Gmail's interface) or is it just emails in HTML emails?

**Comment by nhojb** [comment]
Just images in HTML emails. The Gmail interface and image attachments work fine.

Example:

<img width="926" alt="Screenshot 2023-07-17 at 19 29 56" src="https://github.com/leggett/simplify/assets/312540/baaae296-83ef-4115-81f7-9fe7942f45aa">

**Comment by leggett** [comment]
Got it. Thanks. My guess is a new bug with Safari regarding declarativeNetRequest (the API used to block email trackers). I've had ongoing issues with them on this and they have not be easy to get a response from.

**Comment by leggett** [comment]
Ok, I'm able to repro. Definitely an issue with the email tracker blocking which has been a nightmare to support in Safari and something changed in Safari 17. 

If I disable blocking email trackers all together, the issue goes away... but I'd rather not do that. I'll try to find a quick patch that doesn't involve disabling blocking email trackers entirely and gives me more time to figure out what is going on in Safari 17.

Thanks for the report.

**Comment by leggett** [comment]
Ok, I think I've fixed it. Just submitted to Apple for approval (v2.5.40). I had to re-write the blocker list for email trackers because of some changes. I'll close this issue when the update is accepted.

**Comment by leggett** [comment]
v2.5.40 is live in the App Store and appears to fix this problem.

**Comment by nhojb** [comment]
Thanks for the fix. Also can confirm HTML images are loading as expected now.
