### ISSUE TITLE
Safari: Inbox list width constraint is no longer respected

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#756]
Inbox list width constraint is no longer respected. The inbox now spans almost the entire viewport.
Message width is constrained and works as expected.

I'm using the default "Large 1100px" list width.

Not sure if this was broken in the latest Simplify update or is due to changes to Gmail itself.

Confirmed in Safari 16.5.2 and 17.0. I've tried force reloading the web page and restarting Safari.

Note: I've not tested on other browsers,. so this may not be specific to Safari?

<img width="1512" alt="Screenshot 2023-07-25 at 13 38 12" src="https://github.com/leggett/simplify/assets/312540/6b801542-8425-4c1b-a380-26a8d0b99a6a">

---
Simplify v.2.5.40 - Configuration: aAX appMenuOpen appNavOff ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab fontMsg grayTheme hideLabelChips hideListCount hideMsgCount hideSelectRefresh inInbox inList invertAddons invertCompose isSafari izBgDefault lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm newNav newUI simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15 - Window: 1512 x 945 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
When it rains, it pours. Gmail is rolling out a change that breaks Simplify. I've identified the issue on one of my test accounts and submitted an update to the various app stores (v2.5.42 and v3.0.51).

Firefox already approved it and Google just approved it for Chrome. I'm still waiting on Apple and Edge. Your extension should auto-update and fix the problem.

**Comment by nhojb** [comment]
Hi Michael,

The issue is still present in v2.5.42. I assume from #758 that there's a v2.5.43 update in the pipeline to fix the fix?

Thanks!

**Comment by leggett** [comment]
Correct -- v2.5.42 only fixed it for some users (I finally figured out that it was only for users that had reading panes enabled, even if it was set to "No split"). v2.5.43 fixes it for all set ups and is live everywhere except Edge.
