### ISSUE TITLE
(Bug) Simplify not reverting back to the Small 850px settings after changing it to something larger

### ISSUE THREAD

**Issue by CliffWade** [leggett/simplify#757]
In Simplify 3.0.51(I updated to this today), Chrome Beta Version 116.0.5845.42 (Official Build) beta (64-bit), if I change Message View to something other than Small(850px) it changes accordingly. Then trying to change to anything smaller simply doesn't work at all and remains on the larger layout view even though it's set to Small(850px).

I have two Gmail accounts that I use all day every day, and the screenshots below show that one account is now stuck in the larger view and the other is not, because I changed the setting and refreshed the page on the one but not the other.

If I disable Simplify 3.0.51 and go back to Simplify 2.5.41 and refresh the screen, the personal email will go back to the smaller view. As soon as I disable 2.5.41 and enable 3.0.51 and refresh the page, it goes back to the wider view even though settings still shows Small(850px).

Personal email where it remains in a larger view: ![Personal](https://github.com/leggett/simplify/assets/4813948/6e7d240c-6651-48e0-bb4c-8954330a4326)

Work email where it's still in the smaller view, which is what I want and have settings set to: ![Work](https://github.com/leggett/simplify/assets/4813948/df499f11-fc2c-4531-af2e-ed8014c6c9f7)

Settings showing where it's set back to Small(850px): ![Settings](https://github.com/leggett/simplify/assets/4813948/9cf103f4-8ea9-49b1-bb8a-9c1a96609d73)

---
System: Mozilla/5.0 (Windows NT 10.0

**Comment by leggett** [comment]
It looks like my fix isn't working for everyone... I'm trying to figure out why right now...

**Comment by leggett** [comment]
Ok... I've submitted another update. This will work on the new version of Gmail but will break on the old one :/
