### ISSUE TITLE
List width not working

### ISSUE THREAD

**Issue by Slurrie** [leggett/simplify#758]
Not sure what happened but yesterday the list width stopped working on all of the attached accounts and it's now showing as the full default width.

version 2.5.42

**Comment by leggett** [comment]
Gmail made a change yesterday that broke Simplify -- a fix is in review in all the app stores. It is live for Firefox (v2.5.43) and on Chrome for the v3 beta ([v3.0.52](https://beta.simpl.fyi)). Still waiting on the v2 update to get approved for Safari, Chrome, and Edge.

**Comment by Slurrie** [comment]
Cool, I'll wait for the update to come though then.

At least this reminded me how much I had the default chrome look :P
