### ISSUE TITLE
Canary does not work

### ISSUE THREAD

**Issue by saket** [leggett/simplify#759]
Hi, I'm trying out the canary version but it doesn't seem to have any effect on my gmail tabs. Is there any way I can investigate what might be up?

**Comment by leggett** [comment]
Hmmm, some companies silently block extensions on company-issued devices. Google is an example of this where I help employees maintain an internal version.

**Comment by saket** [comment]
Hmmm yea that is possible. I did not suspect this originally because Simplify's stable version is whitelisted by Block. Is there a way to quickly confirm this?

**Comment by leggett** [comment]
If it is enabled and there is no "Simplify v3.0.52 loaded" in the console after loading Gmail, I'd guess it is being blocked.

What is Block?

**Comment by leggett** [comment]
I'll add that I'm working to get v3 out on the stable channel... no exact ETA but I'm making steady progress on a re-write of Simplify settings which was the final piece.

**Comment by leggett** [comment]
I'm closing this for now but let me know if you think there is an issue on my end.

**Comment by saket** [comment]
Glad to hear! I'll wait for you to finish. 

> What is Block?

[Block](https://block.xyz) is [Square's](https://square.com) new name.
