### ISSUE TITLE
Buttons disappear after opening extension sidebar

### ISSUE THREAD

**Issue by xhw1** [leggett/simplify#76]
I was using [Clearbit Connect](https://chrome.google.com/webstore/detail/clearbit-connect-supercha/pmnhcgfcafcnkbengdcanjablaabjplo) extension. When I open its sidebar from the extension menu, both the extension button and new email button disappeared. I have to refresh the page so that the buttons reappear. 

Then if I close the sidebar by clicking its icon again in the extension menu. The extension button and the new email button stay at their position and won't move right.

This only happens to Clearbit extension. Google Calendar and Google Keep extension work fine. 

Also, Google Tasks does not show in the extension menu.

**Comment by leggett** [comment]
I'll try and look into this later. 

I suspect that since it is a Chrome extension and not a Gmail Add-on, it is doing something custom and I'm not aware that a side bar was added (I have to monitor the add-ons pane being shown so I move the compose button over).

**Comment by leggett** [comment]
Confirmed. This extension is doing some custom stuff that is different than standard add-ons. I can't detect / adjust for every extension. I will see if I can account for their special case but I don't plan to do this for most extensions in the future.

**Comment by xhw1** [comment]
Thank you so much!

**Comment by leggett** [comment]
I removed my customizations to the composer it stops breaking that. Accounting for how they handle their side-bar is more work though. I'm going to merge this with the work to support other top extensions.
