### ISSUE TITLE
"My Account" page fails to load

### ISSUE THREAD

**Issue by leejoramo-d51** [leggett/simplify#760]
The My Account page has not been loading for a couple of weeks 

https://simpl.fyi/account

This started when I renewed my subscription. After the payment was processed, I could no longer access the account page. Otherwise the subscription did renew, and Simplify works just fine.

Looking at the network requests on the page, it looks like the problem is with a WebSocket request to FireBase that never resolves. I copied that request in `curl` format below replacing the Key with `#` 

```bash
curl 'wss://s-usc1f-nss-2541.firebaseio.com/.ws?v=5&ns=simpl-fyi' \
  -H 'Pragma: no-cache' \
  -H 'Origin: https://simpl.fyi' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Sec-WebSocket-Key: ################# \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203' \
  -H 'Upgrade: websocket' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: Upgrade' \
  -H 'Sec-WebSocket-Version: 13' \
  -H 'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits' \
  --compressed
  ```

I have tried to disable my various Ad Blockers and other extensions. I mostly run Simplify in a dedicated  Microsoft Edge Gmail app. But I am seeing the same behavior in Firefox.

**Comment by leggett** [comment]
Hi Lee -- can you email me at hi@simpl.fyi to sort this out? It looks like there are two plans for you under two different email addresses and I think they are conflicting.
