### ISSUE TITLE
Icons cut off in pop up menu of an email

### ISSUE THREAD

**Issue by johnbcasey** [leggett/simplify#761]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

![image](https://github.com/leggett/simplify/assets/8077253/c54cf29e-9443-4968-97dc-c22005a1762a)

---
Simplify v.3.0.52 - Configuration: aAX appNavOff bundleInbox ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg hideListCount hideMsgCount hideTabIcons highDensity inMsg invertAddons invertCompose izBgDefault lightTheme listWidthXXLg matYou minimizeChat msgWidthLg navOpen newNav newUI oeMailtrack otherExtensions reverseMsgs simplify simplifyCanary supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 - Window: 2086 x 1235 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Interesting -- that menu has never had icons in it before. (below is what my menu looks like) Exciting to see them! I'll keep an eye out for them so I can make sure they are visible in the next update.

<img width="278" alt="image" src="https://github.com/leggett/simplify/assets/8763662/b3adffe4-1ae6-464b-acd1-142a044ad6bf">

**Comment by leggett** [comment]
This was fixed a few releases back. Thanks again for the report.
