### ISSUE TITLE
Top panel layout overlay if out of office is active

### ISSUE THREAD

**Issue by thomich** [leggett/simplify#762]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

1. enable gmail's out of office feature
2. check top panel

![image](https://github.com/leggett/simplify/assets/4398840/cb493c67-39e6-4032-b0a4-f6a62fa39f40)

---
Simplify v.3.0.52 - Configuration: aAX appNavOff bundleInbox ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthFull lowDensity matYou minimizeChat msgWidthFull nPane navOpen newNav newUI no-touch rightStar sendLater showAvatars simplify simplifyCanary supExtWarn - System: Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 - Window: 1897 x 1010 (100pct zoom) - Language: de

**Comment by leggett** [comment]
Thanks for the report -- this recently broke and I'm working to get it fixed this week.

**Comment by thomich** [comment]
seams this is fixed?

![image](https://github.com/leggett/simplify/assets/4398840/b8a119bb-b5e8-4da1-9ccd-f265a0ac28d9)

**Comment by leggett** [comment]
Yes, it is fixed. I just haven't closed out the issue reports.
