### ISSUE TITLE
Vacation banner broken on Arc

### ISSUE THREAD

**Issue by dezertrat** [leggett/simplify#763]
I'm on Vacation, and using the Arc browser with the Chrome plugin. The vacation notice area appears to be broken, as captured in the screenshot.

<img width="1500" alt="Screenshot 2023-10-05 at 07 02 57" src="https://github.com/leggett/simplify/assets/13600856/c76e347b-c4cc-4762-ad09-73acac9b86ae">

---
Simplify v.2.5.43 - Configuration: aAX appNavOff ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm newNav newUI simplify supExtWarn vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 - Window: 1512 x 859 (101pct zoom) - Language: en

**Comment by dezertrat** [comment]
After opening this issue I note that #762 is likely the same thing even though the image looks different.

**Comment by leggett** [comment]
Yes, same issue as #762. Will get it fixed soon.

**Comment by leggett** [comment]
Thanks for the report by the way!
