### ISSUE TITLE
Reply in thread, message delete icon behind big new icon

### ISSUE THREAD

**Issue by thomich** [leggett/simplify#765]
Hey

If reply direct in thread (no new dialog), the message delete icon is behind the big new icon.

Steps to reproduce:

1. open any message in thread view
2. klick reply shortcut (r) or reply button
3. delete icon not visible

![image](https://github.com/leggett/simplify/assets/4398840/6f5a50f3-7d35-41b6-9e5b-a2f4e95d391d)

Workaround:
1. same as above
2. click "open in new window" icon, top right of thread reply
3. delete the reply message

![image](https://github.com/leggett/simplify/assets/4398840/40cb1eb3-f630-46bd-8f5b-1c5ca807aad9)

![image](https://github.com/leggett/simplify/assets/4398840/c307e841-6bae-407d-b0c8-1c537adbdc61)

**Comment by leggett** [comment]
This can happen but should be rare. It should only happen when you have the conversation width set to something wide enough and/or your window narrow enough that the conversation stretches to the edge of the window.

I always add space below the conversation so you can scroll the conversation up and out from under the compose button:
<img width="287" alt="image" src="https://github.com/leggett/simplify/assets/8763662/2ba6b9df-5d62-4d8a-b95f-cde454d8376f">

**Work arounds:**
1. You can set the compose button to stay in the nav (note: it will be entirely hidden when the nav is collapsed)
2. Scroll the conversation up further
3. Set the conversation width to be narrower
4. Make your window wider

Let me know if these don't work. I'm also curious if you have an older version of Simplify as I thought I re-colored the compose.

**Comment by thomich** [comment]
Hey @leggett 

Thanks for help. I used "Message width" with setting "Full screen" and then it happends.
Now i saw about your scroll you added.. means if i scroll down, i can reach the delete icon ;)

Currently set "Message with" to "X-Large" which also works ;)

Thanks
thomi
