### ISSUE TITLE
Chat/spaces affected by reading pane.

### ISSUE THREAD

**Issue by narcan** [leggett/simplify#766]
Please describe the issue and the steps to reproduce it. Screenshots are useful:

With the reading pane toggled, chat/spaces have a block of the window blacked out. This is happening since at least 18/10/2023.

---
Simplify v.3.0.53 - Configuration: aAX bundle bundleInbox bundleOtherLists caA caC caD caE caI caL caM caS caT cfC cfK cfO cfQ cfR cfU composeActions composeFab composeFormat darkTheme dateGroup fontMsg groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarnSome hideImportance hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideNavUnreads hideSignatures hideTabIcons highDensity inChat inList invertAddons invertCompose izBg3 listWidthLg matYou msgWidthSm newNav newUI sendLater showAppNav simplify simplifyMenuOpen vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 - Window: 1440 x 875 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Yikes! That's bad. You can temporarily turn off Simplify when you go to Chat or Spaces with ⌥S. I'll try to figure this out and get a fix out in the next 24 hours.

**Comment by narcan** [comment]
that'd be amazing, thank you!

**Comment by leggett** [comment]
Found the problem. Have a fix ready. Need to do a bit more testing on this and another fix before I deploy.

**Comment by leggett** [comment]
Fix is out in v3.0.54. Let me know if the problem persists.
