### ISSUE TITLE
Out of Office banner interferes with the Simplify button bar.

### ISSUE THREAD

**Issue by ascandroli** [leggett/simplify#767]
If you have an Out of Office banner the button bar is not properly displayed.

To reproduce it just got to settings and set up and Out Of Office message and then go back to the main screen.

![Screenshot 2023-10-18 at 16 22 38](https://github.com/leggett/simplify/assets/449509/e93051a0-2f91-46b1-9cec-7b938d707ac2)

---
Simplify v.2.5.43 - Configuration: aAX appNavOff ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup fontList fontMsg grayTheme hideLabelChips hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matYou minimizeChat msgSelected msgWidthSm navOpen newNav newUI simplify supExtWarn - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 - Window: 2565 x 1309 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Thanks for the report. I have a fix for this on the [canary channel](https://beta.simpl.fyi) and hope to get it out to everyone else soon.
