### ISSUE TITLE
Simplify option menu overlapping with split pane toggle

### ISSUE THREAD

**Issue by narcan** [leggett/simplify#769]
The simplify options menu that is now integrated directly in Gmail is overlapping with the split pane toggle.

![Uploading BqYJHEB9giLdGXQ.png…]()

**Comment by leggett** [comment]
Your screenshot didn't upload... can you try again or email it to me at hi@simpl.fyi?

**Comment by leggett** [comment]
Also, you can disable always showing the Simplify menu button under Simplify preferences:
<img width="384" alt="image" src="https://github.com/leggett/simplify/assets/8763662/0be510d7-f4dd-4647-a47e-124b59a88678">

**Comment by leggett** [comment]
I think I fixed this in the last update... but let me know if it is still an issue.

**Comment by narcan** [comment]
Awesome, thanks for the update! And thanks for being so available to work
on this. Love the product!
