### ISSUE TITLE
Alignment suggestion

### ISSUE THREAD

**Issue by yabhis** [leggett/simplify#77]
<img width="1670" alt="Inbox_-_abhishek291093_gmail_com_-_Gmail" src="https://user-images.githubusercontent.com/5029660/56619865-ab582280-6644-11e9-9367-7c772eec8841.png">
From usability purpose, IMO its better to move the upper section toward bit more right and get it to align with the bottom section, as it happens in default Gmail design. I'm in the habit of it and I guess others will might also be in that. Though you can shrink the search bar (or expand on hover or click kind of thing). Though not sure about the % of people using the search bar regularly. I hardly use once in a month.
Something like:
<img width="792" alt="Inbox_-_abhishek291093_gmail_com_-_Gmail" src="https://user-images.githubusercontent.com/5029660/56619983-0558e800-6645-11e9-868f-3fa199d26408.png">
Its easy to reach and perform action after selecting or reading some mails.

**Comment by leggett** [comment]
Yes and no. If you are only optimizing for using those actions, you are 100% correct. But I'm optimizing for a number of things over that.

Specifically, I'm optimizing for:

1. a pleasant and calming reading and replying experience (by far the top activities in Gmail) and
2. an easy to maintain extension across the various settings and inbox configurations (6 different inboxes x 3 different views x 3 different screen resolutions). 

Keeping the actions near the tabs adds to the visual clutter of me scanning the content of my inbox or reading the conversation. And putting it inline near the content means it either scrolls off the page (super bad) or is pinned as a second bar when you scroll (also bad as it reduces the space for content). In the end, if I were to keep the actions near the content, I'd likely end up with something like what Gmail has today.

P.S. Search actually already contracts (click on the search icon to collapse it). I let it be sticky for those that use it often. There are a number of cases where I auto-minimize it after usage (e.g. if you click the "X" on Search and you had it closed before). 

P.P.S. Thanks for the feedback and taking the time to mock up your feedback. Always appreciated.
