### ISSUE TITLE
Group by emails not working correctly

### ISSUE THREAD

**Issue by thomich** [leggett/simplify#770]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

If enabling "Group by email" it will work immediately, see screenshot.

![image](https://github.com/leggett/simplify/assets/4398840/8b258374-462c-4bda-a7c3-4a3e5044da81)

Group by email settings

![image](https://github.com/leggett/simplify/assets/4398840/0c96e4b3-bddf-4377-99db-e95023e1f424)

But if clicking eg. twice to "Inbox" or even leave inbox, got to sent messages and back to inbox.. grouping by date disapears.

Let me know, if you need more information.

:heart: it anyway ;)

Regards
thomi

---
Simplify v.3.0.56 - Configuration: aAX appNavOff bundle bundleInbox caA caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideExtWarnSome hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideTabIcons importantBadge inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthFull lowDensity matYou msgWidthFull nPane navOpen newNav newUI no-touch rightImportance rightStar sendLater showAvatars simplify simplifyCanary simplifyPrefsOpen - System: Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 - Window: 1891 x 1001 (100pct zoom) - Language: de

**Comment by leggett** [comment]
I can't replicate this issue. I switched my interface language and my preferences and it still didn't happen. 

Do you have any other extensions installed that modify Gmail? I noticed the "no-touch" class name which isn't put there by Gmail (as far as I know) or Simplify.

**Comment by thomich** [comment]
hey @leggett 

this are the installed extensions:
Web Storeversion 0_2
JSON Formatterversion 0_7_1
Web Developerversion 0_5_5
ColorZillaversion 4_0
Plasma Integrationversion 1_8_0_1
Xdebug helperversion 1_6_1
Google Docs Offlineversion 1_69_0
AdBlock — best ad blockerversion 5_12_0
Checker Plus for Google Calendar™version 33_1_1
Mate Translate – translator, dictionaryversion 10_1_17
DI.FM - addictive electronic music (Official)version 1_1_0
Simplify Gmail (Canary)version 3_0_56
Window Resizerversion 2_6_4_2101
Duplicate Tab Shortcutversion 1_6_0
Chrome PDF Viewerversion 1
Screencastify - Screen Video Recorderversion 3_18_0_4993
Google Network Speechversion 1_0
Google Hangoutsversion 1_3_21
Chrome Web Store Paymentsversion 1_0_0_6

I think the only one is Mate Translate, which adds maybe that no-touch class, as with Mate Translate i can anywhere select text and directly translate it.

About AdBlock, it's paused for mail.google.com.

thomi

**Comment by leggett** [comment]
Yeah, none of these jump out as a problem. I installed Mate Translate and it didn't break things for me. I guess you could try disabling everything and confirming the problem persists. 

I can't really do anything to fix a problem I can't reproduce. :(  

If you'd be up for it, we can do a short video call where I can see the problem first hand and try to diagnose what is happening. Email me at hi@simpl.fyi to set something up.

**Comment by thomich** [comment]
hey @leggett 

have tested around, disabled all extensions expect Simlify... still same problem.
will send you a video to hi@simpl.fyi... 

regards
thomi

**Comment by leggett** [comment]
Thanks for the video. I didn't know that it was bundles in your first email. I thought it was just emails. I don't take into consideration bundles right now when grouping (as their date changes as you archive messages inside the bundle). 

I hope to fix it soon! Thanks again for the video.

**Comment by thomich** [comment]
Hey @leggett 

You're right... bundle by label and group by date does not make sense ;)
I think, there are to possible solutions:
1. easiest: if "bundle emails by label" is activated, disable group emails by date
2. more complex: if "bundle emails by label" and group by date are activated, group by date inside bundled by label ;)

regards
thomi

**Comment by leggett** [comment]
I think it can work depending on your set up. Most people who use bundles don't have all their messages in bundles. I just need to take into consideration the date of the most recent message in the bundle.

For your setup, two things you might try:

1. Disable date grouping in just the inbox (a recently added option)
2. Switch bundles to not expand inline. This will go to the search for all the matching messages and will be grouped by date. I wouldn't do this if you're not applying labels by filters though as there are flaws in Gmail search when it comes to manually applied labels.

**Comment by thomich** [comment]
for me, currently this works... thanks

**Comment by leggett** [comment]
Update on this... I don't think it was your original problem but I think it is related. I improved this some in v3.0.88 (in review). Date groups now take into consideration bundles when deciding to nix date headers (so a header will show up if there is only a collapsed bundle in a time period).
