### ISSUE TITLE
First email is always slightly darker/lighter

### ISSUE THREAD

**Issue by megaroeny** [leggett/simplify#771]
For some reason, I recently noticed the first email in any tab is always slightly darker (light mode) or lighter (dark mode). In my screenshot, you can see that the first Primary email subtly shows this. This appears in any tab, too (Promotions, Updates, etc.)

Is there a way I can share what my settings are with you? Thanks!

<img width="233" alt="Light mode" src="https://github.com/leggett/simplify/assets/1559447/2e965907-c8da-4950-be0b-0c932e44590d">

<img width="235" alt="Dark mode" src="https://github.com/leggett/simplify/assets/1559447/3280debb-670a-40a7-bfb1-55576d8700e3">

**Comment by leggett** [comment]
That's where the keyboard focus is. Press up/down to move focus and enter to open. You can also enable auto select in Simplify prefs so you can press delete or any of the other shortcuts (E to archive, L to label, etc) without having to select the message first.

If you never use keyboard shortcuts (including up/down and enter) you can disable them in Gmail settings (press the ? key and scroll down a bit to where there is a toggle). This should get rid of the background color.

**Comment by megaroeny** [comment]
Ohhhh! Got it, thanks Michael!

**Comment by ben-foxmoore** [comment]
@leggett do you know if there's a hotkey to "drop" the focus, or at least reset it to the first email? Mine sometimes gets stuck way down my inbox, and then Simplify keeps on jumping down to focus on it whenever I go back to the Inbox view.

**Comment by leggett** [comment]
There isn't a shortcut to return focus to the top of the inbox. 

But can you email me at hi@simpl.fyi to discuss -- it sounds like something isn't working as intended.
