### ISSUE TITLE
Messages no longer appear in dark mode

### ISSUE THREAD

**Issue by hachre** [leggett/simplify#772]
I've been using Simplify on Edge for macOS for many weeks and it has worked fine. I have the option enabled that makes all messages dark. However since the latest update (I don't know which version I had before but I now have 2.5.45) the messages are no longer painted in dark mode, they instead appear in the normal white background mode. 

This applies to both HTML and Text messages. The setting simply seems to have no effect anymore and is stuck on white. The rest of the UI is in dark mode as before.

I am on macOS Sonoma 14.1.1 

---
Simplify v.2.5.45 - Configuration: aAX appMenuOpen appNavOff ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab darkTheme dateGroup fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity matYou minimizeChat msgWidthSm navOpen newNav newUI simplify simplifyMenuOpen supExtWarn vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0 - Window: 1920 x 1080 (125pct zoom) - Language: en

![Screenshot 2023-11-20 at 19 34 36](https://github.com/leggett/simplify/assets/885304/5e7d00e9-26e1-4cd7-a0ec-c9eff74b176c)

**Comment by leggett** [comment]
Gmail is rolling out a change that breaks a number of things in Simplify including this. 

I submitted an update that fixes it last night. It is already live in the [Chrome Web Store](https://chrome.simpl.fyi). Microsoft takes FOREVER to approve updates (usually 2-4 weeks). It is so bad that I'm considering removing Simplify from the Edge app store and forcing people to use the one in the Chrome Web Store.

**Comment by hachre** [comment]
Thank you, I switched to the Chrome Extension and it is working again 👍
