### ISSUE TITLE
Wish Reminders could be "pinned" to the top of the email list

### ISSUE THREAD

**Issue by luey33** [leggett/simplify#773]
-perhaps as an option.
Thanks,
Lw.

**Comment by leggett** [comment]
Not reliably as the reminder may be not on the current page. I don't have full API access (intentionally, better for your security) so I can only move around what I see on the current page.

For the current page, I do plan to add an option to only see certain types of emails when you pause the inbox (reminders, starred messages, important messages, etc). But that isn't what you asked for...

If you want them at the top of your inbox, your best bet is to use Priority Inbox with a filter on reminders so you can apply a label that is the top section of your inbox. If you're open to that, I can describe how to set that up in more detail.

**Comment by luey33** [comment]
understood.
will do. thanks for the reply.
Lw.
