### ISSUE TITLE
Feature request: hide the new "emoji" reactions icons

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#775]
I'd like to request a feature that adds the ability to hide the emoji reaction icons:

![Screenshot 2023-12-14 13 35 04](https://github.com/leggett/simplify/assets/5102461/794fb80c-b4f5-4fa4-808f-0aaa17d21821)

They clutter my workflow, and I don't want to be enticed to add this kind of reply to an email in the first place.

**Comment by leggett** [comment]
Very reasonable request... I want to make sure hiding those doesn't hide other people's reactions though as I don't want you to miss other people sending them.

**Comment by erikgeurts** [comment]
If only you could also make it go away on the Android app...

**Comment by leggett** [comment]
Ok, added for the next release (v3.0.72)

**Comment by erikgeurts** [comment]
When do you expect to release it out of beta?

**Comment by leggett** [comment]
I hit feature complete tonight (this change just barely made it in under the wire). Maybe in a week? 

Remaining steps:

- I'm pushing v3.0.72 tonight and making sure there aren't any issues
- I'm going to reevaluate the default preferences one more time and make sure I'm happy with the in-app launch experience (people did NOT like the full screen take over when I launched v2... planning to just use the new preferences menu)
- I want to add some new fonts and new inbox zero backgrounds (very little code)
- I need to work on some launch content (first new blog post in over a year) 
- and start testing on Firefox and Safari (I'm going to block launching v3 on them -- will launch on Chrome first).

**Comment by erikgeurts** [comment]
How's the progress towards a public release of v3?

**Comment by leggett** [comment]
SUPER close. I might launch for Chrome today even (although I just pushed an update to the canary/beta channel last night and I'd like to make sure I didn't introduce any new bugs). I've been testing on Safari and Firefox and working through issues with moving to manifest v3.

**Comment by leggett** [comment]
P.S. The version I pushed last night was v3.0.84 so there have been [12 updates](https://docs.google.com/document/d/1Py6B-ar1ogKqoFLdeY0z5JEKDWhm5F2AkPsWW6uEVX0/preview#heading=h.xv6y1ckimcsv) since my "it's feature complete" update 2 weeks ago.

**Comment by erikgeurts** [comment]
Exciting!

**Comment by erikgeurts** [comment]
I'm very happy that with v3.1.x, I can now hide those icons!
