### ISSUE TITLE
Left Labels heading missing after enabling "Saved Searches"

### ISSUE THREAD

**Issue by leejoramo-d51** [leggett/simplify#777]
If I enable Saved Searches with the Labels above searches, the Label Heading disappears. Leaving only the Labels "More"  toggle

![image](https://github.com/leggett/simplify/assets/36970352/011a564b-f869-4594-9d33-c463e1e0e786)

If the Saved Searches are above, it is not a problem

![image](https://github.com/leggett/simplify/assets/36970352/0e17a9fa-142b-42f0-823b-ef1a41b00d68)

---
Simplify v.3.0.52 - Configuration: aAX addOnsOpen appMenuOpen boldHighlight bundleInbox ca3 caI caL cfC cfO cfQ cfR cfU composeActions defaultTheme fontList fontMsg hPane hideLabelChips hideListCount hideMailTitle hideMsgCount hideSignatures hideTabIcons highDensity inInbox inList invertAddons invertCompose izBgOff lightTheme listWidthLg matYou minimizeChat msgLabelsRight msgWidthSm navOpen newNav newUI quickSettings rightStar sendLater showAppNav simplify simplifyCanary simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47 - Window: 1440 x 2560 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Are you saying the header for the list of labels in the left nav is missing with saved searches enabled?

**Comment by leejoramo-d51** [comment]
sorry somehow saved that initially with out the comment content

**Comment by leejoramo-d51** [comment]
Additionally, toggling saved searches off and on again, results in multiple Search sections

![image](https://github.com/leggett/simplify/assets/36970352/6b12b2fa-e9ec-442a-bcdb-c351cad1a089)

**Comment by leejoramo-d51** [comment]
I will also note that I had similar issues using a clean copy of Chrome with only Simplify and 1Password installed.

**Comment by leggett** [comment]
Ah, there was a bug in v3.0.75 that has since been fixed. Once you have v3.0.76 or 3.0.77, disabling Saved Searches actually works (and removes the section from the nav). Sorry!
