### ISSUE TITLE
How to remove the two small icons in a list view?

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#780]
In v3.1.x, there are two small buttons/icons in the conversation list, at the right side of the list, that say something like "Remove {label name} from X conversations" and "Archive X unstarred conversations".

![image](https://github.com/leggett/simplify/assets/5102461/2653c3a8-51b9-4d03-a56b-d3b012f56ad8)

While I understand what they're for, I'd prefer not to see them and/or accidentally click them.

I haven't been able to figure out which setting (and where in the settings panel) I need to disable, to remove/hide those 2 icons.

Can you please enlighten me?

Also, at the very end of the debug information below, I don't really understand what that "Couldn't find the label? X" and "undefined X" refers to, since that label really does exist. Perhaps the / in the label name causes confusion?

---
Simplify v.3.1.2 configuration: aAX appNavOff avatarsZoom caA caI caL cfC cfO cfQ cfR cfU cfZ composeActions composeFab composeFormat dateGroup debug defaultTheme fontMsg gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons highDensity importantBadge inLabel inList inUserLabel invertAddons izBgDefault lightTheme listWidthLg matYou msgWidthMd nPane newNav newUI reminders rightImportance rightLabels rightStar sendLater simplify simplifyPrefsOpen- System: Mozilla/5.0 (X11 CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 - gmail.pinto-server_20240101.06_p1 - Window: 1272 x 750 (100pct zoom) - Language: en-GBErrors:10858:81: Couldn't find the label? infrastructure-wordpress-woocommerce undefined Infrastructure/WordPress/WooCommerce

**Comment by leggett** [comment]
Disable the actions on date groups to hide those actions:
https://mail.google.com/mail/?simplify=groupemails&pref=gaArchive

The bit at the end of your system report is an error (now being added to the system reports). I'm not handling really long labels or labels that are in a deep hierarchy. It isn't a catastrophic error but something I'm looking into.

**Comment by erikgeurts** [comment]
Ah, got it, thanks.

I am aware that I tend to use lots of long, and nested, labels. That does indeed result in pretty long label names.
