### ISSUE TITLE
Feature request: add ability to sync (or import/export) settings across multiple profiles

### ISSUE THREAD

**Issue by chrisgo** [leggett/simplify#781]
This is just a nice-to-have ... I am using simplify gmail on a couple of different profiles (aka browsers) so did not want to manually try to find every setting and copy if across 5-6 profiles as there lots of settings you have made available!  

Not sure if this is already available but I could not find it but just a way to make my settings the same across all my profiles using simplify gmail

Thanks!

**Comment by erikgeurts** [comment]
See also #598

**Comment by leggett** [comment]
I'm going to close this as a dup of #598 (thanks Erik). I definitely plan to offer syncing preferences across devices (I think that would be way easier than a way to export/import them). It didn't make the cut for v3 but it is high on my list.

**Comment by chrisgo** [comment]
Thanks!
