### ISSUE TITLE
[Feature request] Reminders could work regardless of sender

### ISSUE THREAD

**Issue by wapiflapi** [leggett/simplify#783]
Hi,

I've always used the "send email to self" trick, ever since no longer using inbox by gmail.

I like that it is now supported as "reminders".

I noticed when sending from myemail+reminder@gmail.com to myemail@gmail.com it is presented as a reminder, but the other way around, sending from myemail@gmail.com to myemail+reminder@gmail.com is not recognized.

I would love an option to have reminders depend on "to" instead of "from", because it makes it easier to add reminders from the gmail app on my phone, just by sending an email to myemail+reminder@gmail.com (which is auto completed) instead of having to change both sender and dest. It would also allow me to forward reminders from other tools easily :)

Best,

**Comment by leggett** [comment]
Unfortunately, this isn't possible.

Since Simplify doesn't have full access to Gmail (I can only see what you see), I don't know who the message was sent to in list view.

The good news is it does work from mobile -- just change the from adresss: ![Screenshot_20240109-091723.png](https://github.com/leggett/simplify/assets/8763662/e267e716-eafb-42a6-9083-ec77a20b00a2)

This also means only you can send yourself reminders (no one else)

**Comment by perler** [comment]
ok, just to chip in, I am searching for a way to set a Simplify Gmail reminder from iOS. The obvious way is to use the Shortcuts app, they have a Gmail action but again, you cannot set the from address there. Any other ideas how to get this to work? From: is really hard to set from email clients..

**Comment by erikgeurts** [comment]
In the Android app, it is actually extremely simple to select a different sender (as in the screenshot above).

**Comment by perler** [comment]
a) not helpful because of android b) not helpful as it is not about sending an email from gmail.

**Comment by leggett** [comment]
Hi @perler -- are you using the Gmail app on iOS?

**Comment by perler** [comment]
yes, I do.

**Comment by leggett** [comment]
You should be able to send yourself an email from your reminders email then...

If you have set up Simplify reminders on desktop (just save one reminder), then you should have an additional From address that you can send email from in any of Gmail's apps (on Android or iOS). The iPad app has this ([video demo](https://youtu.be/mbVZDOfJZoA?t=1209)) and I assume so does the iPhone app once you have multiple from addresses on your account.
