### ISSUE TITLE
Dark mode is no longer black background color

### ISSUE THREAD

**Issue by benguaraldi** [leggett/simplify#784]
Sorry to complain, but the upgrade to Simplify v3 was very rocky for me, as it changed the background color of gmail: the dark mode is now a medium gray instead of black.  I couldn't stand looking at it, so I spent 45 minutes trying different configurations and javascript code to fix it, and then I gave up and installed Dark Mode Night Eye to deal with it (https://nighteye.app).

Might there be an option to change colors in the options?  It seems like there's something that sets all the backgrounds to rgb(39, 39, 39).  Even being able to set options in localStorage would be great.  Right now, it seems the only way to do that is to fork the Simplify javascript code on my computer.

Also, it would have been nice to have an option to revert to v2.

The good news is that issue #706 is overcome by these events, so that can be closed.

Thanks!

---
Simplify v.3.1.3 configuration: aAX appNavOff avatarsZoom boldHighlight bundleInbox caA caI caL cfA cfC cfF cfI cfO cfQ cfR cfS cfU composeActions composeFab composeFormat darkTheme debug fontMsg hideAds hideExtWarn hideFileIcons hideImportance hideInboxHideAllLink hideLabelChips hideListCount hideListEmoji hideMsgReplies hideSearchChips hideTabIcons highDensity importantBadge inInbox inList invertAddons invertCompose izBgDefault listWidthFull matYou msgWidthSm newNav newUI reminders rightImportance rightLabels rightStar simplify simplifyPrefsOpen- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 - gmail.pinto-server_20240101.06_p1 - Window: 1280 x 713 (100pct zoom) - Language: en - Errors: / 0:0: SGP.CH failed

**Comment by leggett** [comment]
I'll spare you the full defense of the change (short version: it is harder to read on a true black bg)

That said, enough people have complained about this that I am going to add an option for true black in Simplify preferences. Hope to do it soon.

**Comment by benguaraldi** [comment]
Thanks!  You are my hero!

Yeah, my vision is weird, with astigmatism, myopia, presbyopia, lens scratches, and mild color-blindness, so sometimes things that work for other people don't necessarily work for me.  :)

**Comment by leggett** [comment]
This was added a while back:
https://mail.google.com/mail/?simplify=darktheme&pref=darkerTheme

**Comment by benguaraldi** [comment]
Thank you!  It's great!

I am using it all the time, but completely forgot I'd opened an issue about it.
