### ISSUE TITLE
I lose dark mode in an empty Inbox

### ISSUE THREAD

**Issue by tomhusband** [leggett/simplify#785]
Hi there,

I'm on Linux Mint and the Chrome browser and am running dark mode. Dark mode works fine in everything except my empty inbox. When the last email is moved or deleted it goes to a very bright screen. If I go to any other category like Trash, Drafts or Sent it's back to dark mode. I'd like dark mode everywhere.

I guess Simpl.fyi only runs in Chrome right? Gmail looks great in Floorp and Brave which I also use.

Thanks,

Tom husband
![gmail](https://github.com/leggett/simplify/assets/19576799/8acd725b-1f0c-4340-a517-e492747deb06)
![draft](https://github.com/leggett/simplify/assets/19576799/05027a0b-a688-48f3-90c9-03ed8a669833)

---
Simplify v.3.1.3 configuration: aAX appNavOff avatarsInList avatarsZoom bundleInbox caA caI caL cfC cfF cfO cfR cfU composeActions composeFab darkTheme dateGroup debug fontList fontMsg fontNav gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons htmlEmail idc8_350 importantBadge inLabel inList invertAddons invertCompose izBg23 listWidthLg lowDensity matYou msgWidthSm navOpen newNav newUI reminders rightImportance rightLabels rightStar sendLater simplify simplifyPrefsOpen yzorn- System: Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 - gmail.pinto-server_20240104.06_p1 - Window: 1920 x 959 (100pct zoom) - Language: en

**Comment by leggett** [comment]
This is the inbox zero reward background. You can change the background or choose no background here:
https://mail.google.com/mail/?simplify=inboxzero

You're not the first to be surprised by this so clearly I need to do more to make it clearer what is going on.
