### ISSUE TITLE
Enhance avatar setting not persisting

### ISSUE THREAD

**Issue by jazanne** [leggett/simplify#787]
I have turned off "Enhance avatars", but each page reload or new window shows the avatars until i retoggle the setting. See attached gif.

![CleanShot 2024-01-10 at 09 52 37](https://github.com/leggett/simplify/assets/4053924/2e88fd70-84f0-4b77-88cc-18920268aa62)

---
Simplify v.3.1.3 configuration: aAX appNavOff avatarsInList bundleInbox caA caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons importantBadge inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matYou msgWidthSm navOpen newNav newUI rightImportance rightLabels rightStar simplify simplifyPrefsOpen- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 - gmail.pinto-server_20240104.06_p1 - Window: 1430 x 754 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Fix for this is rolling out in v3.1.4
