### ISSUE TITLE
Travel Categorisation from Navigation Settings has disapeared?

### ISSUE THREAD

**Issue by perks** [leggett/simplify#789]
Hi, before updating to v 3.x.x using the "Travel" categorisation features was very important to my use-case for Simplify, greatly helping me track down travel timelines etc.

Did this option get deprecated? It no longer appears as a toggle under navigation options.

**Comment by perks** [comment]
Nevermind, this has moved to a "saved search" feature. Closing!

**Comment by leggett** [comment]
Sorry for the confusion. Glad you found it.
