### ISSUE TITLE
Full on dark mode

### ISSUE THREAD

**Issue by theostrauss** [leggett/simplify#79]
When the dark mode theme is selected via the Themes panel, messages and drafts have a dark gray theme too!

**Comment by leggett** [comment]
As in, invert the content to be white text on a black background?

**Comment by leggett** [comment]
The inbox does that after the first refresh (I only detect theme changes on load right now)

**Comment by theostrauss** [comment]
Yeah after the refresh the messages panel shifts to dark mode as well, but message bodies remain white. Would be nice to have continuity. This extension is awesome, btw!

![image](https://user-images.githubusercontent.com/16072127/56663405-02292080-6674-11e9-8356-e7faf7c39f8a.png)

**Comment by leggett** [comment]
So, (1) that is how the theme is designed by Google -- inverting could hurt readability and (2) inverting it could be disastrous with html emails where I may not be able to change the font color rendering emails unreadable. 

I'll leave this issue open and look into it...

**Comment by theostrauss** [comment]
Totally feel you there. Lmk! You rock.

**Comment by leggett** [comment]
I'm adding this to Someday... I will close it (so I don't see it in my list of open issues) but will come back to it when I've cleared the other things and am ready to reconsider things like this.

**Comment by leggett** [comment]
Inverting things inverts inline images too. I don't see an easy way around that.

**Comment by yedlosh** [comment]
There is [a plugin for Stylus](https://github.com/jackbuehner/gmail-dark-modifications) which tries to achieve this - and overall looks very successful in doing so. But I do expect that there might be edge cases where the inversion might break stuff. 
However, the dark theme as implemented with the white background for emails themselves does look just plain stupid (and is not usable as a proper dark mode).
