### ISSUE TITLE
Version 3 for Firefox

### ISSUE THREAD

**Issue by ERisEPR** [leggett/simplify#791]
I do not know if I am missing something but is there no v3 for Firefox?

**Comment by leggett** [comment]
I'm about to push it... took extra testing/work because Firefox likes to be different and doesn't support all the same APIs.

**Comment by ERisEPR** [comment]
Great!  Thank you for the update.  I don't mean to bother, love everything you are doing, miss Inbox still :)

**Comment by leggett** [comment]
The update **just** got approved and went live: https://addons.mozilla.org/en-US/firefox/addon/simplifygmail/
