### ISSUE TITLE
Negative profile page in Calendar event

### ISSUE THREAD

**Issue by zampierilucas** [leggett/simplify#794]
HI, 

This issue is pretty much the same as https://github.com/leggett/simplify/issues/709, but It is still happening on the calendar events.
Dark mode:
![image](https://github.com/leggett/simplify/assets/25491728/8a2f1f42-c3ab-422f-a01d-98e507b5e1b2)
Light mode:
![image](https://github.com/leggett/simplify/assets/25491728/eb29cacd-3b1f-4eda-ad28-071489ac80fb)

**Comment by leggett** [comment]
This is different as I don't have access to any of the add-ons (Calendar, Contacts, etc). They are all iframes inside Gmail. 

So with the "Make add-ons dark" option enabled, I am inverting the entire pane but can not un-invert any images. You can turn that off here: https://mail.google.com/mail/?simplify=darktheme&pref=invertAddons

I may some day offer to accept access to those domains so I can uninvert images but it seemed like the annoyance didn't warrant asking for broader permissions.
