### ISSUE TITLE
The unread count does not get hidden in the browser tab

### ISSUE THREAD

**Issue by abaldwin06** [leggett/simplify#795]
Please describe the issue and the steps to reproduce it. Screenshots are useful.

I enabled "hide unread count in nav" and I read somewhere that this would affect the browser tab unread count and it didn't. It does affect the unread counts elsewhere on the page. Not sure if this is a bug or just not what the setting is meant to control, but this is the primary feature I'm looking for in an extension

---
System: Mozilla/5.0 (Macintosh

**Comment by leggett** [comment]
There is a different preference for hiding it on the browser tab:
https://mail.google.com/mail/?simplify=browsertab&pref=btabHideUnread
