### ISSUE TITLE
Keyboard shortcuts for "Remove conversation from current view and go newer/older" seem to be reversed

### ISSUE THREAD

**Issue by flavorjones** [leggett/simplify#796]
When in the "inbox" view, I click on an email conversation. I want to "remove from current view and go to older", so I type `[`. I expect this to take me to the next-oldest email in the inbox view, but instead it takes me to the next-newest. Similarly, typing `]` takes me to the next-oldest when I expect it to take me to the next-newest.

This all works correctly if I'm in the context of a search results list (e.g., searched "label:feed is:unread" and clicked on an email conversation from there).

This also works correctly if I use the "Archive conversation and go newer/older" shortcuts in any view (`{` and `}`).

Please let me know if it would be helpful to record a screencap gif of what's going on.

---
Simplify v.3.1.6 configuration: aAX bundleInbox caA cfF cfQ cfR cfS composeFab dateGroup defaultTheme gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReactions hideMsgReplies hideNavLabels hideNavUnreads hideSearchChips hideSelectRefresh hideSignatures hideTabIcons highDensity inInbox inList invertAddons invertCompose izBgOff lightTheme listWidthLg maArchive maDelete maDiv maDone maLabel maMark maMove maPin maSnooze maSpam maTask matYou msgWidthSm newNav newUI reminders rightImportance rightLabels simplify simplifyPrefsOpen- System: Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 - gmail.pinto-server_20240115.06_p1 - Window: 1221 x 1209 (85pct zoom) - Language: en - Errors: / 11549:16: Uncaught TypeError: Cannot read properties of null (reading 'classList')

**Comment by leggett** [comment]
Thanks for the report. I must have these flipped when you're in a bundled inbox. I'll take a look!

**Comment by leggett** [comment]
Ok, found the bug and will fix it in the next update (v3.1.8). Thanks for bringing this to my attention!

**Comment by flavorjones** [comment]
Thanks so much for the fast turnaround! :heart:

**Comment by leggett** [comment]
Hmm... I don't think it is fixed yet for a bundled inbox. If you turn off bundling, or are in a list that isn't bundled, it will work. It should be in the next few days.
