### ISSUE TITLE
Extra tabs in settings dont display nicely

### ISSUE THREAD

**Issue by JemarJones** [leggett/simplify#8]
In advanced settings i added a keyboard shortcuts tab, and it ends up overflowing awkwardly like this:
![image](https://user-images.githubusercontent.com/6874590/55595371-77f33980-5711-11e9-8d41-f53b3778acfb.png)

**Comment by leggett** [comment]
Oh advanced settings. How you do make things difficult. Thanks for the report. Will look into it.

**Comment by leggett** [comment]
Fixed in v1.1.0
