### ISSUE TITLE
simpl just isn't loading on my gmail

### ISSUE THREAD

**Issue by dsandler** [leggett/simplify#80]
I've got the extension installed, but nothing seems to happen to my mail.google.com windows (personal gmail account). 

It doesn't look like it's running at all:

```
> document.documentElement.classList
DOMTokenList ["aAX", value: "aAX"]
0: "aAX"
length: 1
value: "aAX"
__proto__: DOMTokenList
```

I'd like to debug this further for you but don't know how to go about it.

**Comment by leggett** [comment]
I've heard Google is blocking the extension on corp machines, even on personal accounts. Is this a corp machine? Are at Google when you tried it?

I've also seen at least once where Chrome for some reason didn't run any added extensions until I restarted the browser. I was so excited when I had it happen to me but couldn't figure out why no added extension (not just Simplify) would run. Eventually I tried a browser restart and it worked. If a restart doesn't fix it, let me know.

**Comment by dsandler** [comment]
Yeah I just came to the same conclusion. I am using a work computer, figured the personal profile would be immune, but it ain't.

**Comment by dsandler** [comment]
(fyi the only tip-off about the new extension policy came in a toast that I only received when I switched to loading the extension unpacked from a git checkout.)

**Comment by leggett** [comment]
There is an internal build being maintained by someone on the inside. Email me at hi.simplify@gmail.com and I'll tell you more.
