### ISSUE TITLE
Preferences popover keeps appearing in Arc

### ISSUE THREAD

**Issue by megaroeny** [leggett/simplify#800]
I started using Arc browser. When going to my Gmail tab, the Simplify preferences popover seems to appear almost every time. Not quite sure why, found the behavior odd. This didn't happen on Edge.

![image](https://github.com/leggett/simplify/assets/1559447/8b0f14c0-27bc-4fa7-9439-d1fd423a78c1)

---
Simplify v.3.1.9 configuration: aAX avatarsInList avatarsZoom bundleInbox caA caI caL cfC cfF cfO cfR cfU composeActions composeFab defaultTheme fontList fontMsg fontNav hideAds hideEmptySections hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons importantBadge inInbox inList invertCompose izBg23 lightTheme listWidthLg lowDensity maDone maPin matYou msgWidthSm nPane navOpen newNav newUI reminders rightImportance rightLabels rightStar sendLater simplify simplifyCanary simplifyPrefsOpen unreadDot- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 - gmail.pinto-server_20240115.06_p1 - Window: 1576 x 1130 (120pct zoom) - Language: en

**Comment by leggett** [comment]
**Are you going to Gmail from a bookmark?** 

There is some url params that I add when the menu is open to show the menu (this also lets me send a link to things in the nav so it opens at the right place for customers). BUT, as soon as you close the menu, those params are removed. 

Arc obscures the URL so you may not see that a bookmark you are using has that url param built in. Testing on my end, as soon as I close the menu, hitting refresh doesn't bring it back.

**Comment by megaroeny** [comment]
Hmm, well not sure about a bookmark. I have the tab pinned in Arc. I can double-check the URL when I'm back at my work computer next week.

Good to know though, I'll circle back when I test!

**Comment by leggett** [comment]
Cool cool... in case it is helpful, here is what I see on Arc:
https://github.com/leggett/simplify/assets/8763662/9530480d-545a-4d4d-8b99-f71844da0e97

**Comment by megaroeny** [comment]
> Cool cool... in case it is helpful, here is what I see on Arc: https://github.com/leggett/simplify/assets/8763662/9530480d-545a-4d4d-8b99-f71844da0e97

Ahhhhhh, okay got it. It could very well be that. I'll follow-up on Monday. 👍

**Comment by megaroeny** [comment]
Was on my MacBook today, and took a look at the pinned URL, and it indeed was the reason you mentioned! Updated the URL of the tab to not have the params, and all good! Thanks Michael!
