### ISSUE TITLE
New Reminder button opens a blank Compose

### ISSUE THREAD

**Issue by jncasey** [leggett/simplify#802]
Trying to create a new reminder via the floating button launches a blank compose window. 

I can still create a reminder manually by setting the from address to the `+reminder` version, sending the email to myself, and snoozing it, so the reminders system is working. Just not creating new ones.

Trying to create a reminder using the keyboard shortcut successfully launches reminder creation window alongside a new blank email:
![Screenshot 2024-02-05 at 10 38 19 AM](https://github.com/leggett/simplify/assets/31020859/28e56cc2-0eec-4c12-884b-e75d403fdc77)

---
Simplify v.3.1.11 configuration: aAX avatarsInList avatarsZoom bundleInbox bundleLists caA caD caI cfC cfF cfI cfO cfR cfU composeActions composeFab composeFormat dateGroup fontList fontMsg fontNav gaArchive gaRemove grayTheme groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarn hideFileIcons hideImportance hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideNavLabels hideSignatures hideStars hideTabIcons inInbox inList invertCompose izBg23 lightTheme listWidthLg lowDensity maDelete maDone maPin matYou msgWidthSm nPane newNav newUI reminders rightImportance rightLabels rightStar sendLater simplify simplifyCanary simplifyPrefsOpen- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 - gmail.pinto-server_20240128.06_p0 - Window: 1344 x 1136 (100pct zoom) - Language: en - Errors: / 9301:92: Couldn't find profile button to build App Menu. Was loading = true / 0:0: Trying to add avatar to css but can't find avatars.sheet. Does the style tag exist? true

**Comment by leggett** [comment]
Thanks for the report. If you refresh Gmail, does it start working correctly again?

**Comment by jncasey** [comment]
Refreshing doesn't solve the problem. Neither does a complete Chrome restart. 

I've also noticed something else strange (not sure if this is related or should be reported as a separate issue):

Opening the Simplify menu and dragging to move it leaves behind a second copy in the original location (this copy doesn't accept clicks)

![Screenshot 2024-02-05 at 11 14 39 AM](https://github.com/leggett/simplify/assets/31020859/b7faa900-0797-4f4b-b844-ca45fb04bffb)

If you drill down into a submenu, the ghost menu becomes a blank white rectangle that blocks clicks to anything placed under it.

![Screenshot 2024-02-05 at 11 15 59 AM](https://github.com/leggett/simplify/assets/31020859/50d28024-9cd0-4c69-8b6c-4255162fd142)

Refreshing Chrome doesn't solve this problem either

**Comment by leggett** [comment]
Whoa. Very strange. Do you happen to have two different versions of Simplify installed by chance? I thought I detected that and warned about it (it can cause weirdness) but someone else had two copies installed and hadn't seen the warning.

**Comment by jncasey** [comment]
That was it! To both problems.

I had been using the canary release to get some of the big new changes early. I guess at some point the stable release was also activated. I guess I'll stick to stable for now until there are more cutting-edge features to try.

**Comment by leggett** [comment]
Cool. I'll fix the warning on both versions being installed.
