### ISSUE TITLE
Conversation view: newly archived conversations still load when navigating with next/previous

### ISSUE THREAD

**Issue by sturob** [leggett/simplify#803]
This happens when I read an email, archive it, and stay in the conversation view. 

I have 'Auto-advance' set to: 'Go to the previous (older) conversation' in Gmail settings.

Steps:

1. Go to Inbox
1. Load a conversation you want to Archive
2. Hit y to archive it, the next conversation loads automatically
3. Hit j to load the next conversation and then kk (OR hit k then j)

The archived conversation is loaded again, even though it isn't in the Inbox. 

---
Simplify v.3.1.11 configuration: aAX appNavOff boldHighlight bundleInbox caA caI caL cfC cfO cfQ cfR cfU composeActions composeFab darkTheme dateGroup debug fontList fontMsg fontNav gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideNavLabels hideTabIcons htmlEmail imgTheme importantBadge inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity matYou msgWidthSm nPane navOpen newNav newUI reminders rightImportance rightLabels rightStar simplify simplifyPrefsOpen- System: Mozilla/5.0 (X11 CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 - gmail.pinto-server_20240131.07_p1 - Window: 1351 x 778 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Thanks @sturob -- This is part of #801

**Comment by sturob** [comment]
Ah, I skimmed other issues but missed that. Glad you're on it!

**Comment by leggett** [comment]
I just posted an update on #801. Subscribe there if you want to follow along.
