### ISSUE TITLE
Quick way to label emails?

### ISSUE THREAD

**Issue by lucharo** [leggett/simplify#804]
Is there any way to label emails quickly with simplify? I'd like to drag and drop emails to label them if possible. I use the bundle emails by label which is useful already hence why I was thinking you might have done something about this problem?
---
Simplify v.3.1.12 configuration: aAX appNavOff avatarsInList avatarsZoom bundleInbox caA caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons importantBadge inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matYou msgWidthXLg newNav newUI reminders rightImportance rightLabels rightStar simplify simplifyCanary simplifyPrefsOpen- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 - gmail.pinto-server_20240201.05_p0 - Window: 1440 x 746 (100pct zoom) - Language: en-GB - Errors: / 4734:61: Could not find Simplify pref toggle: autoAdvance

**Comment by leggett** [comment]
Hi Luis, Gmail has native support for:

- dragging emails to labels (this will move the email out of the current list into that label)
- dragging labels (from the left nav) onto emails (this is lesser known)

I have investigated building on this functionality (can you just drag an email into a bundle) and so far I haven't figured out a way to do that.

Gmail also has great keyboard shortcuts but they are disabled by default. If you enable them and enable [Simplify's option for auto-select](https://mail.google.com/mail/?simplify=keyboard&pref=kbsAutoSelect), you can simply hit the "L" key to label the focused message.

Lastly, for bundles, I will say that it works better to have labels applied via filters but the above should work as well.
