### ISSUE TITLE
Quick calendar reply looks ugly 

### ISSUE THREAD

**Issue by robinpokorny** [leggett/simplify#806]
When I have only few emails (two in my case) in the view and one of them is a calendar invite, the quick response window is cut on the bottom. Plus the original email moves out of the view on the top.

<img width="1177" alt="Screenshot 2024-02-20 at 17 52 54" src="https://github.com/leggett/simplify/assets/68341/add1e5a7-02af-4a81-a149-33710f854315">

---
Simplify v.3.1.13 configuration: aAX appNavOff avatarsInList avatarsZoom bundleInbox caA caI caL cfC cfF cfO cfR cfU composeActions composeFab dateGroup defaultTheme fontList fontMsg fontNav gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons inInbox inList invertCompose izBg23 lightTheme listWidthLg lowDensity matYou msgWidthSm newNav newUI reminders rightImportance rightLabels rightStar sendLater simplify simplifyPrefsOpen- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 - gmail.pinto-server_20240209.05_p0 - Window: 1530 x 1107 (116pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Sorry it took so long but I finally figured out what was causing this and fixed it (in v3.1.16). Thanks for filing the original issue.
