### ISSUE TITLE
Ctrl-T no longer opens a new tab/window when running Gmail in a Window

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#808]
I have my Gmail running in a Chrome window (Windows 10), starting it from an icon on my desktop.

I used to be able to press Ctrl-T to open a new Chrome tab, but that stopped working recently. I'm not sure if it due to Chrome 123 (which it was updated to earlier today) or to some change in Gmail itself.

If I open Gmail inside a regular Chrome tab, then pressing Ctrl-T does open a new tab.

Would this be something that Simplify can fix?

---
Simplify v.3.1.13 configuration: aAX appNavOff avatarsZoom caI caL cfO cfQ cfR cfU cfZ composeActions composeFab composeFormat composeHeightXL dateGroup defaultTheme fontList fontMsg fontNav groupHideFirst groupInbox groupOtherLists hideAds hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListEmoji hideMsgReactions hideMsgReplies hideSelectRefresh hideTabIcons highDensity importantBadge inInbox inList izBgR lightTheme listWidthLg matYou msgWidthLg newNav newUI reminders rightImportance rightLabels rightStar sendLater simplify simplifyPrefsOpen- System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 - gmail.pinto-server_20240311.06_p2 - Window: 1514 x 950 (101pct zoom) - Language: en-GB - Errors: / 9363:92: Couldn't find profile button to build App Menu. Was loading = false / 1925:71: get(div[selector="scheduledSend"]) called with undefined parent, null / 0:0: Trying to add avatar to css but can't find avatars.sheet. Does the style tag exist? false / 8332:47: Couldn't find right side bar / 8614:45: Couldn't find add-ons pane

**Comment by leggett** [comment]
This isn't broken for me running Chrome v123. So I think the better approach here is to find out what broke for you... maybe just restarting your browser will fix it? Or see if another extension is capturing the Ctrl+T shortcut under chrome://extensions/shortcuts?

Could Simplify fix this? Sort of. Simplify *could* capture this shortcut and open a new tab. BUT (1) It would have to be opened with a URL (e.g., not the new tab screen) which is not really the same thing and (2) I can't detect if you're in a PWA or in Chrome so I would do it in all instances which is bad. So not something I really want to consider. Hope you figure out what is going on.

**Comment by erikgeurts** [comment]
On my Chromebook, right now, I'm still on v122 while I write this, and pressing Ctrl-T does open a new browser window or a new tab if the browser is already open. While I write this, an update of ChromeOS is downloading. I'll report back if the Ctrl-T behavior has changed after the reboot (if it turns out to be ChromeOS 123).

**Comment by erikgeurts** [comment]
My Chromebook is still at v122, so I can't say anything about that.

After restarting my Windows 10 PC and thus Chrome, this issue still persists, Ctrl-T doesn't do anything when I'm inside the PWA flavor of Gmail. There's nothing listed in the shortcuts page about another extension capturing it. The only thing that changed was that Chrome was updated to v123, Ctrl-T worked before the update, not anymore after the update. It's probably something between the Chrome developers and Gmail developers that's out of whack now.

**Comment by erikgeurts** [comment]
Update: I've got many other systems and services that I open from an icon on my Windows desktop. I guess those would be called PWAs, although they're really just sites that open in a window instead of a tab.

Anyway, my observation today is that Ctrl-T stopped working in all of those windows, not just in Gmail. So this appears to be a Chrome related matter, not just Gmail. As such, it doesn't make sense to fix it in Gmail only.

I'll see if I can find out more about why Chrome is (not) doing this. Perhaps someone else reading this issue can comment on this?

**Comment by erikgeurts** [comment]
So to put this in context, from within a PWA window, Ctrl-N still opens a new browser window (which makes sense), but Ctrl-T no longer opens a new tab (which by definition would be in a new Chrome window that would have to be opened first).

To some extent, I understand why Ctrl-T within a PWA window doesn't work, since a PWA doesn't have tabs after all.

But being able to quickly open a new tab in a new Chrome window from within a(ny) PWA was extremely convenient, so I don't understand why the Chrome developers decided to change this.
