### ISSUE TITLE
Not working on LInux

### ISSUE THREAD

**Issue by wunderdojo** [leggett/simplify#81]
I'm using Chrome 72.0.3626.96 on Ubuntu 18.04. Just installed and nothing happens. Originally copied an error here but looking at the src realized it was unrelated (coming from another extension). Disabled that one but still no go. Seems to be loaded and active but not seeing any changes.

**Comment by leggett** [comment]
It should only require a reload of Gmail after it is installed. I've seen a full restart of Chrome be required to get it to work a few times. 

If the Gmail logo is hidden, it is working. Sometimes the difference is subtle (if you have the nav visible and/or are using advanced settings like Right-side chat), your Gmail will still look pretty cluttered. You can hide the nav and turn off those features if you don't use them to achieve full simplicity.

**Comment by wunderdojo** [comment]
Hi Michael,

That's exactly what happened. Didn't realize initially that it had taken
effect b/c it was so subtle and then realized there was no Gmail logo. I'll
try changing the settings.

Thanks for the quick reply and for the extension.

Cheers.

*Jamie Currie*
------------------
CEO, wunderdojo
949-734-0758
Located in sunny Southern California
GMT / UTC - 7 hours

**Comment by cflewis** [comment]
I was having a similar issue on Chrome OS. Turns out a full reboot of the laptop enabled the extension. Weird.
