### ISSUE TITLE
Menu background with inbox zero is hard to read

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#810]
When I've reached inbox zero and get to see the associated background image (in my case image of the day), the left hand menu doesn't have a background and is thus very hard to read.

I usually have the menu hidden, but sometimes it's necessary to briefly display it.

This is when I press Alt-M:
![image](https://github.com/leggett/simplify/assets/5102461/f9f96aea-086b-4582-b4b4-56d5d180282d)

When I hover my mouse over the hamburger icon, it looks better:
![image](https://github.com/leggett/simplify/assets/5102461/6500ce6a-3f6f-44d9-8855-9c62b066b581)

But when I then click to keep the menu visible, it's the same as the first image above.

**Comment by leggett** [comment]
This is tricky... basically, your Gmail theme (probably the default white theme?) has the menu set to black links on what it expects is a light background. But the inbox zero reward background is dark giving you dark text on a dark background. 

With the image-of-the-day, it can be a light background or a dark one and I don't really have a way of knowing. I think the only fix here is to use a different inbox zero background OR a different Gmail theme (neither are a perfect fix).

**Comment by erikgeurts** [comment]
The issue appears to be that the background of the menu is light and very transparent, if it was less transparent (or entirely white like when I hover the hamburger with the mouse), things would work a lot better. Is the color/transparency of the menu background something you control with Simplify?

**Comment by leggett** [comment]
I can and do, but it will look bad to always show a background as some backgrounds don't need it. Compare:

Bad (dark inbox zero background with default Gmail theme):
<img width="423" alt="image" src="https://github.com/leggett/simplify/assets/8763662/1b547c18-e3bc-4d49-abc6-3fcda8296bf7">

Good (and would be ugly with a background behind just the nav):
<img width="1053" alt="image" src="https://github.com/leggett/simplify/assets/8763662/81810587-4a8f-4b90-9b85-9c7fc78cdc2c">

**Comment by erikgeurts** [comment]
In the trade-off between aesthetics and usability, my personal preference would be for something that's readable first.

I've now resolved this for my own use case by choosing a fixed inbox-zero image with a light color palette, so that the menu and many other UI elements have sufficient levels of contrast to be visible. The image of the day, while a nice surprise when inbox-zero is reached, proves to be too much of a cause/source of confusion the way it is.

**Comment by leggett** [comment]
Someday I might integrate with Unsplash's API and maybe I could have a "Light image of the day" and a "Dark image of the day"
