### ISSUE TITLE
Hamburger panel menu does not show on hover when Chat is active

### ISSUE THREAD

**Issue by yshyonli2** [leggett/simplify#811]
When the Chat button is active on the sidebar, hovering over the hamburger icon (in email view) does not automatically show the side panel.

![image](https://github.com/leggett/simplify/assets/14921674/6bc0e134-8783-4ec9-89cb-4e7927252134)

Hovering over the Mail button, on the other hand, does bring up the side panel. But it seems to disappear much sooner than it should when mousing to the right.

---
Simplify v.3.1.13 configuration: aAX avatarsInList avatarsZoom caA caD caI caM caT composeActions composeFormat composeMenuOpen darkTheme dateGroup fontList fontMsg fontNav gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarn hideFileIcons hideInboxHideAllLink hideListCount hideMsgCount hideMsgReactions hideMsgReplies hideNavLabels hideSelectRefresh hideSignatures hideTabIcons inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity maDelete maDiv maDone maMove maPin maSpam maTask matYou msgWidthSm nPane newNav newUI reverseMsgs rightImportance rightStar showAppNav simplify simplifyCanary simplifyPrefsOpen unreadDot- System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 - gmail.pinto-server_20240415.06_p3 - Window: 985 x 1830 (110pct zoom) - Language: en - Errors: / 12662:27: Uncaught TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator)) / 2221:49: doWhenReady(.aiL .a7J) timed out / 2405:22: Something went wrong with the click series / 0:0: Something went wrong when trying to dynamically change the theme / 2210:54: clickOnWhenReady(.QW .OD, div[aria-label="Theme"]   button) timed out / 2381:22: Something went wrong with the click series

**Comment by leggett** [comment]
This is unfortunately working as expected. When Gmail's app bar (Mail, Chat, etc) is expanded, and the left nav is collapsed (via the hamburger button), you can only peek the left nav by hovering over the app (Mail, Chat, etc). The same is true if you are in Mail. 

I remember trying to get the hover-on-hamburger to work when the app bar is expanded it being hard to support.
