### ISSUE TITLE
Window scrolls down even with no content

### ISSUE THREAD

**Issue by ralvs** [leggett/simplify#812]
Please, watch the video below:

https://github.com/leggett/simplify/assets/5287233/4d8b2f68-7429-4a35-8a9e-8bc73f835616

---
Simplify v.3.1.13 configuration: aAX avatarsInList avatarsZoom bundleInbox bundleLists caA caI caL cfC cfF cfO cfR cfU composeActions composeFab darkTheme dateGroup draggingImage fontList fontMsg fontNav gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarn hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons htmlEmail inInbox inList invertCompose izBg23 listWidthLg lowDensity matYou msgWidthSm newNav newUI reminders rightImportance rightLabels rightStar sendLater simplifyPrefsOpen- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 - gmail.pinto-server_20240403.06_p0 - Window: 1665 x 1340 (89pct zoom) - Language: en - Errors: / 0:0: Trying to add avatar to css but can't find avatars.sheet. Does the style tag exist? false

**Comment by leggett** [comment]
I've never been able to reproduce this issue but I think I found the problem and will push a fix in the next update (v3.1.17)

**Comment by ralvs** [comment]
Hi @leggett, thank you for your attention on this.

Sorry but it isn’t working yet.
See if this print helps in some way, and feel free to ask any other questions.

<img width="686" alt="Screenshot 2024-07-29 at 9 50 09 AM" src="https://github.com/user-attachments/assets/3e85a2bd-89b6-4795-a3e6-e2f3dae13c21">

**Comment by leggett** [comment]
You might have to refresh Gmail once.

If it still doesn't work, can you tell me:
- What kind of Gmail inbox do you use?
- Is this only in the inbox or also in search or label lists?
- Are you still zooming the interface with the browser?

**Comment by ralvs** [comment]
Actually I rebooted the whole computer :)

- using Default Type with no categories enable
- happen in every list: inbox, spam, draft, starred, etc
- my default zoom on browser is 75%
