### ISSUE TITLE
New Gmail frame outline renders in front of pop-up chats in Simplify

### ISSUE THREAD

**Issue by alanhoyle** [leggett/simplify#813]
Gmail appears to have a new outline frame with schmancy curved corners.  

Pop-up chats render in front of the frame in standard Gmail, but when Simplify Gmail is enabled, the frame renders in front of the chat, blocking the bottom of the pop-up.  

Standard Gmail:
<img width="471" alt="Screenshot 2024-04-23 at 2 20 13 PM" src="https://github.com/leggett/simplify/assets/289779/e76ac07c-f492-4a95-831f-0a2eceb3dbd8">

Simplify:
<img width="431" alt="Screenshot 2024-04-23 at 2 18 21 PM" src="https://github.com/leggett/simplify/assets/289779/555f5d57-ae5c-47fc-a39b-01f182065290">

---
Simplify v.3.1.13 configuration: aAX avatarsInList avatarsZoom bundleInbox caA caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup fontMsg gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideNavUnreads hideTabIcons imgTheme importantBadge inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity maTask matYou mediumTheme msgWidthSm newNav newUI reminders rightImportance rightLabels rightStar showAppNav simplify simplifyPrefsOpen vPane- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 - gmail.pinto-server_20240418.06_p1 - Window: 1446 x 1360 (104pct zoom) - Language: en - Errors: / 0:0: Trying to add avatar to css but can't find avatars.sheet. Does the style tag exist? false / 9363:92: Couldn't find profile button to build App Menu. Was loading = true

**Comment by alanhoyle** [comment]
Simplify appears to not only put the pop-up behind the frame, but it also shifts it down and towards the right bottom corner.

**Comment by alanhoyle** [comment]
Okay, so now 25 minutes later, things are rendering differently, but I'm still on Simplify v3.1.13:

<img width="388" alt="Screenshot 2024-04-23 at 2 54 56 PM" src="https://github.com/leggett/simplify/assets/289779/e91f593e-8d1c-4b16-b5c5-64adce254e73">

I had reloaded multiple times before posting....

**Comment by alanhoyle** [comment]
So, less than half an hour later, things are rendering properly.  I had reloaded multiple times before posting...

<img width="388" alt="Screenshot 2024-04-23 at 2 54 56 PM" src="https://github.com/leggett/simplify/assets/289779/8ab427f5-8126-47eb-96fa-b4382f1196bc">

**Comment by leggett** [comment]
Thanks for the screenshots. I'll try to reproduce this on my test accounts and see if I can find the cause.

**Comment by alanhoyle** [comment]
... and it's come back again...

<img width="328" alt="Screenshot 2024-04-26 at 10 22 23 AM" src="https://github.com/leggett/simplify/assets/289779/3e704b81-4de1-4c66-9b49-8ea876584efa">

Restarting my browser (Wavebox: 10.124.17.2 stable w/Chromium: 124.0.6367.79) appears to have cleared it up.  
<img width="365" alt="Screenshot 2024-04-26 at 10 28 00 AM" src="https://github.com/leggett/simplify/assets/289779/677a45f5-2de2-4d2d-a225-ce3dd1ae3734">

**Comment by leggett** [comment]
I never was able to reproduce this issue... let me know if it is still happening for you.

<img width="419" alt="image" src="https://github.com/user-attachments/assets/67da1780-6778-4308-9ba8-b47e49801478">
