### ISSUE TITLE
Hitting return doesn't select message

### ISSUE THREAD

**Issue by mwean** [leggett/simplify#814]
When there are no messages in the inbox and a new message comes in, I can arrow down to highlight the message, but hitting return does not select it. I have to click on it with my mouse.

---
Simplify v.3.1.13 configuration: aAX appNavOff avatarsInList avatarsZoom caA caI caL cfC cfF cfO cfR cfU composeActions composeFab dateGroup defaultTheme fontList fontMsg fontNav gaArchive gaRemove groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarn hideFileIcons hideFiles hideImportance hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReactions hideMsgReplies hideNavLabels hideNavUnreads hideSignatures hideStars hideTabIcons importantBadge inMsg invertCompose izBgOff lightTheme listWidthLg lowDensity matYou msgWidthSm navOpen newNav newUI rightImportance rightLabels rightStar sendLater simplify simplifyPrefsOpen- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 - gmail.pinto-server_20240428.06_p0 - Window: 1551 x 1176 (110pct zoom) - Language: en - Errors: / 2221:49: doWhenReady(.aiL .a7J) timed out / 2405:22: Something went wrong with the click series / 0:0: Something went wrong when trying to dynamically change the theme / 2210:54: clickOnWhenReady(.vh div[role="button"]) timed out

**Comment by leggett** [comment]
Thanks for the report... I'll look into it!

**Comment by leggett** [comment]
Finally dug into this and figured out how to support it. Going out in v3.1.15.
