### ISSUE TITLE
The UI moves when the email creation form is expanded

### ISSUE THREAD

**Issue by jahirfiquitiva** [leggett/simplify#816]
![Shot 2024-05-29 at 18 22 25@2x](https://github.com/leggett/simplify/assets/10360816/87bc26fa-09d0-4384-887a-7e333a7652ba)
![Shot 2024-05-29 at 18 22 17@2x](https://github.com/leggett/simplify/assets/10360816/503800dd-ecc4-4579-99bf-e6e1e32db463)

---
System: macOS
Browser: Arc
Extension Version: 3.1.14

**Comment by leggett** [comment]
Interesting... I thought I fixed this in v3.1.14 which you have. I think I sort of did but it is having an unintended consequence in this scenario where your window is so large. 

Basically, when you open a compose, the message is supposed to move to the LEFT to make space for it. Ideally, it wouldn't move at all if there is already plenty of space. But my calculation isn't working correctly in this scenario.

Thanks for the report -- I'll try to make it right soon.

**Comment by jahirfiquitiva** [comment]
@leggett thank you! 🙌

**Comment by leggett** [comment]
I finally looked at this more... I decided to not move the conversation at all if your window is larger than 2400px wide with everything closed (nav, add-ons, quick settings, etc) and 2700px if you have anything open. It looks like your screen is larger than both of these so the conversation should stop moving when you open a new message with the v3.1.15 update.
