### ISSUE TITLE
Feature request: copy URL to email message

### ISSUE THREAD

**Issue by SamEdwardes** [leggett/simplify#818]
I really enjoy using Simplify! I have one feature request that I hope you could consider. I want to be able to generate a URL for a selected message.

I often get emails that I would like to bookmark for future reference. I take my notes in Notion, so I would like to be able to copy and paste a link to a specific email so I can easily find it later. 

There are (or were) tools that can help:

- There was a Chrome extension I used to use that I can no longer find. It got taken down. 
- I found this one today that looks similar: https://chromewebstore.google.com/detail/referenceemail/ohhblkgfjjbjcaddddgooclkoeiiklgk?hl=en-US&utm_source=ext_sidebar

I think this could fit no to the scope of simplify. Thank you for considering!

**Comment by leejoramo** [comment]
I had submitted a similar request https://github.com/leggett/simplify/issues/809 were I included an example javascript bookmarklet. 

Like you I use email URL's in my various note taking and task management tools.

**Comment by SamEdwardes** [comment]
Thanks @leejoramo! Sorry the duplicate :)

**Comment by leggett** [comment]
Thanks to you both -- this is on my radar. I'll close this as a duplicate and will update #809 when I get to it.

**Comment by leejoramo-d51** [comment]
Michael, Just wanted to thank you again for adding this feature. 

As a whole, Simplify changes Gmail from something I dislike, to a very good email system. I probably use the majority of the extensions features. I know copying a permanent link to a message is not a core part of Simplify, but it ends up being the single feature I miss the most when on my phone or a system with out Simplify. 

I thought about what an impact your tool makes on my workflow while I was updating payment information for the annual renewal. I have been paying for Simplify for 4 years. And used it for several years when it was a free product. Great work and thanks again.
