### ISSUE TITLE
Displayed list of emails centered on page - left justify and use whole page?

### ISSUE THREAD

**Issue by agglomerator** [leggett/simplify#82]
I may be not aware of a way to configure this - my display of the list of emails is centered on the page and uses only about 1/2 of the available space.  Is there a way to widen the display used by this window to fill the whole page?  See the attached screenshot.   It's just my preference.

![image](https://user-images.githubusercontent.com/3915357/56755903-649e2180-6745-11e9-8b4e-4eb2afbbe39d.png)

**Comment by leggett** [comment]
Not in this view. The longer line lengths make it really hard to read.

But, other views use more of the page. You can enable the split pane view under Gmail Settings > Advanced > Preview Pane. Vertical split pane is better in my opinion and it will use a lot more of the screen.

**Comment by bw86** [comment]
Even in split pane view, I have the same problem as OP. Apart from the top bar with the hamburger and the Search box, and the (+) in the lower right, Simplify is only using the middle 1/3 of my screen.

![image](https://user-images.githubusercontent.com/18662806/56769795-29ace580-6767-11e9-91d9-478ce8005262.png)

**Comment by leggett** [comment]
Hmmm... some thoughts.

1. What resolution is that? It looks crazy wide! Make your window less wide and Simplify will use more of the screen :P
2. Even with your crazy-big window, something doesn't look right. My window is a fair bit smaller and it looks like I have more space for my messages (see below). But maybe I'm just making the split between the left and right pane more like 25/75 than your 40/60 split. Maybe I can increase the max-width for vertical split pane. 
3. You're using text buttons (which is fine but may break at low resolutions FYI)
4. Your action bar is near the content when it should be up in the app bar (that's a new bug I can't reproduce... I'm thinking Gmail renamed some css classnames I'm using or something). You're not using any other extensions that change Gmail are you?

<img width="1440" alt="Screen Shot 2019-04-25 at 5 08 46 PM" src="https://user-images.githubusercontent.com/8763662/56775756-5cfa6f00-677d-11e9-9e02-66b31e59f64f.png">

**Comment by bw86** [comment]
Hi there,
Tried it on my G-Suite as well as personal accounts in different sessions on the same machine – same problem.
The laptop was connected to a wide-screen monitor, so I tried it on the machine’s native 4k built-in screen – same problem.
I tried it in 1920x1080 – same problem.
Same when all other extensions are disabled.

BUT, it works fine on a Chromebook.

I’ll do some more troubleshooting, and get back to you.

Thanks!

Mark

**Comment by leggett** [comment]
Thanks for all the effort to troubleshoot Mark. I'm troubleshooting the buttons being in the wrong place on issue #84 and I think the problem may be related.

**Comment by bw86** [comment]
Hi there Michael,
I looked at G-atb on both my Chromebook and my laptop.
I’m not a developer, but one difference caught my eye: this is from the laptop where it is not working as expected. On the Chromebook (which works), position: relative; is struck through in the inspect, like the padding line just before it. No idea if this is relevant or not.

[cid:image001.png@01D4FB93.65802C10]

**Comment by leggett** [comment]
I should have been clearer in my request... can you send me a screenshot of the inspector? You can email it to hi.simplify@gmail.com

**Comment by leggett** [comment]
Ok, fixed Preview Pane not stretching on large displays in v1.2.6. Just pushed to the Chrome store. And I bumped the max-width for preview pane to 1680px. Let me know if you still have issues after the update.
