### ISSUE TITLE
[Feature request] Default bundle theme

### ISSUE THREAD

**Issue by judehansen** [leggett/simplify#821]
not so much a request but a possible suggestion. Currently there is an option to display bundles with the chosen theme or to not display a theme. It would be cool to be able to set a  default theme so that a theme could be used but that they are all the same. Thanks. 

Also, have you considered making your own email client? This would grant you far more control over the presentation and you could go even beyond what Inbox used to provide. It would be a big lift though. I'd likely subscribe to it though. Thanks again!

**Comment by leggett** [comment]
Thanks for the suggestion -- are you referring to the option to apply the label color to the bundle? 
<img width="369" alt="image" src="https://github.com/leggett/simplify/assets/8763662/60bd32a9-3277-445f-9da7-e8c0f9605228">

And if so, are you saying you want to choose a color for the label and a different color for the bundle?

**Comment by judehansen** [comment]
Hi Michael. I was thinking there could be another option to set the color of the bundles. This would the color of all the bundles and would be separate from the color of the labels. So there would be 3 options for bundles:

1. do not apply color/theme to bundle names
2. apply this one color/theme to all bundle names (new)
3. apply label color/theme to bundle names

the motivation was that I like the clean subdued look in the inbox but I still wanted the bundles to be more visually identifiable than simply text. I've emulated this by setting my label themes to be one of the gray themes and this actually looks nice in the inboxes but I have to sacrifice the color coding of my labels.  Not a deal breaker but if it's low hanging fruit, it would be appreciated!

**Comment by leggett** [comment]
Ahhh, interesting. The easiest change here would be to still make the bundle names look like a label but make them all gray if you opt out of applying the label color. This might be a better option than what I fall back to now. 

Adding an option to set the default label color could indeed be another option but I think the above would satisfy your request, yes?

**Comment by judehansen** [comment]
yeah, that'd work 👍🏻

**Comment by leggett** [comment]
Ok, this is going out in v3.1.15. You can't customize the default color but it does change to dark with a dark theme. I think it is better to always see the bundle names in the form of a label pill (makes it clearer it is different). Fingers crossed people aren't upset that you can no longer get a plain text bundle name.
