### ISSUE TITLE
Cannot Enable "Customize browser tab"

### ISSUE THREAD

**Issue by JaceHensley** [leggett/simplify#823]
I cannot enable the "Customize browser tab" setting, when I toggle the switch in the settings panel I see the following error in the console.

```
ReferenceError: btabColor is not defined[simplifyGmail.js:4106:17](moz-extension://7ed86bbf-7479-4086-8100-063491d36fa6/js/simplifyGmail.js)
```

**Comment by leggett** [comment]
Thanks for the report -- I broke this on the last update. Have a fix already queued up for the next update (v3.1.18).
