### ISSUE TITLE
Order of emails changes on delete

### ISSUE THREAD

**Issue by rhulse** [leggett/simplify#824]
I am on Arc  Version 1.57.2 (53036) Chromium Engine Version 128.0.6613.85 and Simplify (3.1.18).

When I delete an item at the top of the list of emails, something from lower down jumps up to the top of the list.

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/3f52ba3d-092b-4f0d-a223-b9d1c23b51f8">

I turned off the extension, the order was restored, then I turned it back on and there were two items out of order:

<img width="197" alt="image" src="https://github.com/user-attachments/assets/c6ced2be-d841-4793-9946-11b117464283">

Doing a hard refresh of the browser did not fix it.

**Comment by leggett** [comment]
Whoa... also strange that there is no avatar for the conversation. I'm thinking Simplify just hasn't processed that message (not sure why not) or maybe it is an issue with the date format (I'd need to know what interface language you're using). 

Could you email me (or copy here) the system report? That will tell me if there were errors and what your interface language is. You can get it here: https://mail.google.com/mail/?simplify=debug&do=copySystemReport

**Comment by rhulse** [comment]
Simplify v.3.1.18 configuration: aAX appNavOff avatarsInList avatarsZoom bundleInbox caA caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg gaArchive gaRemove geminiMin genSumMin groupHideFirst groupInbox groupOtherLists hideAds hideEmptySections hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons importantBadge inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matYou msgWidthSm newNav newUI reminders rightImportance rightStar sendLater simplify simplifyCanary simplifyPrefsOpen- 

System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 - gmail.pinto-server_20240826.04_p1 - Window: 1512 x 1000 (119pct zoom) - Language: en-GB - Errors: / 2421:76: doWhenReady([role='main'] .bHJ) timed out after 120 attempts

**Comment by rhulse** [comment]
Errors v3.0.86:

Errors v3.0.87:

Errors v3.1.1:

Errors v3.1.2:

Errors v3.1.3:

Errors v3.1.4:

Errors v3.1.5:
13358:67: Couldn't test theme - app switcher not loaded yet.

Errors v3.1.6:

Errors v3.1.7:

Errors v3.1.9:

Errors v3.1.10:

Errors v3.1.11:

Errors v3.1.13:
8580:79: Couldn't find loading screen, initializing Simplify in 5 sec
9742:92: Couldn't find profile button to build App Menu. Was loading = true
0:0: Trying to add avatar to css but can't find avatars.sheet. Does the style tag exist? false

Errors v3.1.14:
0:0: Trying to add avatar to css but can't find avatars.sheet. Does the style tag exist? false
8724:79: Couldn't find loading screen, initializing Simplify in 5 sec
9995:73: Simplify > nav.init() > Couldn't find menu button or nav
13206:52: Couldn't find search form or input.
13902:67: Couldn't test theme - app switcher not loaded yet.
9892:92: Couldn't find profile button to build App Menu. Was loading = false
8855:47: Couldn't find right side bar
9139:45: Couldn't find add-ons pane

Errors v3.1.15:

Errors v3.1.16:

Errors v3.1.17:
10201:92: Couldn't find profile button to build App Menu. Was loading = true

Errors v3.1.18:
2421:76: doWhenReady([role='main'] .bHJ) timed out after 120 attempts

**Comment by leggett** [comment]
Hmm... nothing jumps out here as problematic. :(

Safe to assume you don't use any other extensions that modify Gmail?

**Comment by rhulse** [comment]
Nope, none.

**Comment by leggett** [comment]
I've done more digging and am convinced this is a change in how Gmail works that they are testing on some users (including you). I have a guess as to what they are doing and how to correct for it. I'll make a change in my next update and will check back in to see if it fixed the problem for you.

**Comment by lennartcl** [comment]
I've had the same problem for a long time now. Though I use 'archive' and note 'delete.' And I'm usin Chrome.

This happens for me in some sessions, not always, and the workaround is to open a new tab with gmail (Refresh doesn't help).

**Comment by lennartkats-db** [comment]
Any update on this?

@leggett 
> I've done more digging and am convinced this is a change in how Gmail works that they are testing on some users

This problem has been there for many months though and I see it both with my personal and Google Apps email.

Note that opening gmail in a new tab consistently fixes the issue. So it might be something that is just triggered by longer-running sessions? Maybe after laptop hibernation?

**Comment by leggett** [comment]
Thanks for checking in. 

I pushed an update (v3.1.19) last week to my canary channel that included an attempt to fix this. I got feedback on other changes and pushed it with some adjustments to all users yesterday (v3.1.20). It is out to 10% is users in the Chrome store and should be to all users within 24 hours. 

I'm eager to hear if it resolves the problem. 

Full change log: https://changelog.simpl.fyi

**Comment by leggett** [comment]
Has anyone gotten v3.1.20 yet? And has this resolved the problem?

**Comment by CarlosRebolledo** [comment]
Hola Michael

Lo descargué las dos últimas hace un par de minutos (3.1.21 Canary). Te
comento dentro de la mañana (en Chile)

Abrazos
Carlos

**Comment by lennartkats-db** [comment]
@leggett
> Has anyone gotten v3.1.20 yet? And has this resolved the problem?

I haven't seen this issue anymore for some time. I used to run into it quite often. I'm on 3.1.22 now.
