### ISSUE TITLE
Hotkey to unsnooze selected message(s) or open message?

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#825]
I make frequent use of the B keypress to snooze one or more messages. Sometimes, however, I want to get something out of Snoozed and back into my inbox before the set time.

I was wondering if there's a way to quickly unsnooze using a hotkey, for example by pressing shift-B? Is this something you could incorporate in Simplify?

**Comment by erikgeurts** [comment]
> I make frequent use of the B keypress to snooze one or more messages. Sometimes, however, I want to get something out of Snoozed and back into my inbox before the set time.
> 
> I was wondering if there's a way to quickly unsnooze using a hotkey, for example by pressing shift-B? Is this something you could incorporate in Simplify?

Is this feasible?

**Comment by leggett** [comment]
Hi Erik, sorry I missed this one. Especially because it is already supported! 

The opposite of snooze is Move to Inbox, which I support with the Shift+E (also unarchive).

I just tested it and it worked for me.

**Comment by erikgeurts** [comment]
Funny thing is, I was the one to suggest Shift-E as Unarchive, but I never realized that it also Unsnoozes a message.
