### ISSUE TITLE
option to always show Snooze

### ISSUE THREAD

**Issue by mrooney** [leggett/simplify#827]
It seems that recently the "Snooze" button is now always hidden away, but I use this all the time. I poked around in Simplify and assume this is on Gmail's side. Would it be possible to have the option to pin Snooze (or other hidden ones) so it's easier to access?

Also, would you be open to a request / issue for being able to choose a snooze time? The default snooze time seems hard locked at 8am, but I *always* want 12pm, and I have to adjust this every time which is a pain. It would be incredible QoL if I could specify my own default.

![image](https://github.com/user-attachments/assets/dfbc5478-0228-40d0-9923-e392ab6840a0)

**Comment by erikgeurts** [comment]
Strange as it may sound, the only way to change the default times of day for Snooze is by using Google Keep:
![image](https://github.com/user-attachments/assets/4c8f12e3-5b4b-4af9-aab8-754976b9d496)
You can change it there, the new times will be the defaults the next time you start Gmail.

Meanwhile, for me the Snooze button is still present in its usual spot. You may have unknowingly changed to the new simple toolbar by Gmail, you can easily change back here to the Advanced toolbar and the snooze button will be back in its old spot:
![image](https://github.com/user-attachments/assets/c1280c31-0fda-485b-aa27-3b798de06b08)

**Comment by leggett** [comment]
@erikgeurts is right about both things (thanks Erik!) -- you want to switch to the advanced toolbar to see the Snooze action and can manage snooze times in Google Keep (which is very weird but is how it is).

I hope to eventually support adding other custom times and dates in the menu but there are a number of things ahead of doing that on my to-do list.

**Comment by mrooney** [comment]
Wow, thanks @erikgeurts, you rock! That was able to resolve both those issues, sorry for the trouble but thanks for the huge QoL fixes you have provided :D

**Comment by erikgeurts** [comment]
> Wow, thanks @erikgeurts, you rock! That was able to resolve both those issues, sorry for the trouble but thanks for the huge QoL fixes you have provided :D

You're welcome, I have often wondered why Gmail has those snooze times hidden in such a non-intuitive place.

> I hope to eventually support adding other custom times and dates in the menu but there are a number of things ahead of doing that on my to-do list.

@leggett Something like "snooze for 4 hours" and so on would be amazing!
