### ISSUE TITLE
Snooze button has wrong color

### ISSUE THREAD

**Issue by ginkel** [leggett/simplify#831]
Hi there,

I am using Gmail w/ a custom background image. This seems to cause the snooze action to use the wrong color (light vs. dark theme):

![image](https://github.com/user-attachments/assets/b6438ac9-5df2-4b2d-b879-4924f9ad24cd)

**Comment by leggett** [comment]
Got a fix out for this yesterday. Thanks for the report!

**Comment by ginkel** [comment]
Thanks, the update has just been rolled out. I can confirm that the issue is fixed.
