### ISSUE TITLE
Hide new upgrade to workspace button

### ISSUE THREAD

**Issue by joeclarkx** [leggett/simplify#833]
A new upgrade to workspace button appears bottom left for me. Is it possible to hide it?

![Screenshot 2024-11-23 at 23 46 58](https://github.com/user-attachments/assets/f74d2829-0bc5-497e-87d8-7f2f33025849)

**Comment by leggett** [comment]
I'd be happy to. I don't have this any of my test accounts. Is this a grandfathered free Workspace account? Or are they just trying to get you to upgrade to a more expensive tier?

If I can't find it in one of my accounts, I might need some help. I could do a short video call or if you comfortable with the developer console, you could inspect the button and copy the DOM for the parent of the button down?

**Comment by joeclarkx** [comment]
Thanks, Michael.

This is just a vanilla personal account

here's the element:

<span class="I6agWe"><div class="Od0X9"><div jscontroller="YbzfXd"
jsaction="rcuQ6b:npT2md;JIbuQc:etmvrb;" data-onramp-input="357"
data-button-classes="M1LkOe" data-icon-classes="kaUFz" class="pt0Pr"><div
jsname="z1ikhe" class="CRPU9d"><div jscontroller="GcrEAe"
jsaction="JIbuQc:hN7Bec"
***@***.***,null,null,&quot;Upgrade&quot;,null,null,null,null,[[202,141,357,18,1],[2]],[[358,&quot;1&quot;]]]"><div
class="wKxlIc"><div class="bzc-Uw-LV-Zr"
data-is-touch-wrapper="true"><button class="FOBRw-I FOBRw-I-ql-JX-O
FOBRw-I-ql-Uw FOBRw-I-ql-zcdHbf M1LkOe EqiD4b" jscontroller="O626Fe"
jsaction="click:h5M12e;
clickmod:h5M12e;pointerdown:FEiYhc;pointerup:mF5Elf;pointerenter:EX0mI;pointerleave:vpvbp;pointercancel:xyn4sd;contextmenu:xexox;
focus:h06R8; blur:zjh6rb;mlnRJb:fLiPzd;" data-idom-class="M1LkOe
EqiD4b"><span class="OiePBf-zPjgPe"></span><span class="bHA-anp"><span
class="bHA-bHq"></span></span><span class="bHC-Q" jscontroller="LBaJxb"
jsname="m9ZlFb" soy-skip="" ssk="6:RWVI5c"></span><span
class="FOBRw-ano"></span><span class="FOBRw-ank-Rtc0Jf
FOBRw-ank-Rtc0Jf-ql-O" jsname="Xr1QTb"><img src="
https://fonts.gstatic.com/s/i/short-term/release/googlesymbols/workspace_premium/default/24px.svg"
class="kaUFz" aria-hidden="true"></span><span jsname="V67aGc"
class="FOBRw-anl">Upgrade</span><span class="FOBRw-ank-Rtc0Jf
FOBRw-ank-Rtc0Jf-ql-Sh" jsname="UkTUqb"></span></button></div><img src="
https://fonts.gstatic.com/s/i/short-term/release/googlesymbols/arrow_forward/default/24px.svg"
class="kaUFz cMggmd" aria-hidden="true"></div><div class="xiGlq"><button
class="wX4xVc-JX-I hMCF6c" jscontroller="PIVayb" jsaction="click:h5M12e;
clickmod:h5M12e;pointerdown:FEiYhc;pointerup:mF5Elf;pointerenter:EX0mI;pointerleave:vpvbp;pointercancel:xyn4sd;contextmenu:xexox;focus:h06R8;
blur:zjh6rb;mlnRJb:fLiPzd;" data-idom-class="hMCF6c"
data-use-native-focus-logic="true" aria-label="Upgrade"><span
class="OiePBf-zPjgPe wX4xVc-JX-UHGRz"></span><span class="bHC-Q"
jscontroller="LBaJxb" jsname="m9ZlFb" soy-skip=""
ssk="6:RWVI5c"></span><span class="wX4xVc-JX-ank-Rtc0Jf" jsname="S5tZuc"
aria-hidden="true"><img src="
https://fonts.gstatic.com/s/i/short-term/release/googlesymbols/workspace_premium/default/24px.svg"
class="kaUFz" aria-hidden="true"></span><div
class="wX4xVc-JX-ano"></div></button></div></div></div><div jsname="pVTSyb"
class="kbqhe"><iframe jsname="jkaScf"
class="Bkturc"></iframe></div></div></div></span>
-- 
Joe Clark
+49 176 992 12912

**Comment by leggett** [comment]
Wild that they would show that on a personal account! And you're sure this isn't from another extension? The Upgrade button goes to Workspace?

Assuming yes, I'll add something to the next update with some safety checks (since I don't have this on any of my accounts).

**Comment by joeclarkx** [comment]
Yes, it's definitely  Workspace. I disabled all plugins and it's still
there.

Clicking leads to this:
[image: Screenshot 2024-11-25 at 18.09.33.jpg]

I don't see this on my other personal accounts. On this account I am using
sendgrid to 'send-as' from my own domain. I'm guessing this is the reason
for the up-sell...


-- 
Joe Clark
+49 176 992 12912
