### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by schmidtl4** [leggett/simplify#86]
Hello,
I'm using simpl.fyi with Google gSuite gmail in Chrome 73, Windows 10.  Whenever simpli.fyi is active I can't search email.  This is  a non-starter.  Is this a known issue? (I couldn't find any)

**Comment by leggett** [comment]
Search is minimized by default. Look for the search icon in the top right. Once you open it, if you don't close it, it will stay open even after a refresh. Please re-open this issue if you see it but it isn't working somehow.

**Comment by ghazlewood** [comment]
I'm testing this in Firefox Developer Edition so this may be different in Chrome, but Search doesn't work (clicking the icon does nothing).

**Comment by ghazlewood** [comment]
> I'm testing this in Firefox Developer Edition so this may be different in Chrome, but Search doesn't work (clicking the icon does nothing).

I also tested in Chrome, it is a Firefox specific problem which would be relevant to #1

**Comment by jeffnm** [comment]
In Firefox 66.0.3 using the keyboard shortcut for search / opens the search bar, but clicking the magnifying glass icon does nothing.

**Comment by leggett** [comment]
An official build of Firefox is now live:  
https://addons.mozilla.org/firefox/addon/simplifygmail/ 

Search works for me. Let me know if it still doesn't work for you. Maybe you have another extension that is causing issues?

**Comment by jeffnm** [comment]
It may be that I failed to reload Gmail after loading the extension. Having done so, the new official one works great! Thanks!

**Comment by ghazlewood** [comment]
In FF 67.0b14 clicking the search icon does nothing but the keyboard shortcut does work, thanks @jeffnm.  Thanks for the official build @leggett ! ❤️

**Comment by schmidtl4** [comment]
> Search is minimized by default. Look for the search icon in the top right. Once you open it, if you don't close it, it will stay open even after a refresh. Please re-open this issue if you see it but it isn't working somehow.

@leggett  - I see the search icon.  I know that it is minimized.  As others have reported, clicking the icon does not expand the search bar and, accordingly, it is impossible to search.  Not sure why this is closed.

**Comment by leggett** [comment]
@schmidtl4 can you send a screenshot of the top right of your screen? I suspect another chrome extension is messing things up.
