### ISSUE TITLE
Tooltip is cut off on side pannel 3-dot menu

### ISSUE THREAD

**Issue by lijmoo** [leggett/simplify#89]
The Calendar tooltip when hovering over the 3-dot side panel app icons is cut off causing Calendar to appear "Calend..." https://pasteboard.co/IbVjwoS.png

**Comment by leggett** [comment]
This is intentional... some extensions have long names and I didn't want the label to be too far from the icon as I can't right-align them. I'll adjust the max-width so Calendar doesn't cut off in v1.2.7.

**Comment by lijmoo** [comment]
Makes sense! Keep up the smashing effort on this plugin!
