### ISSUE TITLE
Pagination overlaps search bar

### ISSUE THREAD

**Issue by IanMooreIsMe** [leggett/simplify#9]
When viewing an email or in the overview, the pagination buttons overlap the search. 
![image](https://user-images.githubusercontent.com/5406616/55599949-18ecef00-5728-11e9-84af-efe82bdbba6d.png)
Otherwise, everything else along the top looks normal.
![image](https://user-images.githubusercontent.com/5406616/55600110-b0524200-5728-11e9-96f9-54707c03da56.png)
If it is relevant, my screen resolution is 1440x900.

**Comment by leggett** [comment]
Already checked in a fix for this. If you force your extension to update, it should be fixed.

**Comment by IanMooreIsMe** [comment]
Looking at the manifest.json here in the repository, it looks like the latest version is 1.0.6, and that is the version I am using when getting this issue.

**Comment by leggett** [comment]
Thanks for the follow up. I'll have another look.

**Comment by leggett** [comment]
Re-worked this to leave settings to the left of search which should reduce the issues here. Re-open if you're still seeing it after updating to 1.0.7.
