### ISSUE TITLE
Wide Screen doesn't use all space

### ISSUE THREAD

**Issue by chuckdee68** [leggett/simplify#91]
On a wide screen monitor, when you expand the browser, the message view doesn't expand to fill the space, so there's a lot of negative space left.

**Comment by peekpeekpeekpeek** [comment]
Same here, limits compose and view to maybe 1/4 of screen width

**Comment by leggett** [comment]
I recommend using Preview pane (Gmail Settings > Advanced > Preview Pane) on wide monitors. I let the interface stretch to 1680px and might make that higher. 

Having the default view stretch across a wide screen makes reading horrible (one of the things I really disliked about Gmail). You're also welcome to create a mini-extension of your own that overrides it.

**Comment by chuckdee68** [comment]
That's better but would still like it if it would resize to the window size.  Thanks!
