### ISSUE TITLE
Category tabs disappeared when in message view

### ISSUE THREAD

**Issue by nipunj** [leggett/simplify#92]
(first,... thank you Michael.)
This may be an "old habits die hard" thing... but I find myself wanting the category tabs to be still be present atop the page when you dive into a message, not just in the Inbox view. 

I have 4 cat tabs. I scan each of the tab's lists and then jump into a message as needed. But once in the message I can't back out into that tab's list again. So, I resort to using "J/K" to slide up and down the list quickly. 

Are others using the left nav to meet this need? 

I'm not a fan of the disappeared category tabs in the message detail view, but I can see why that design choice was made.

Thanks again Michael.

**Comment by nipunj** [comment]
Surprisingly, just discovered "m" hotkey to jump back to message list. Still vote for tabs not disappearing so there's a clickable option.

**Comment by leggett** [comment]
There is a back button in the top left corner of the screen to return to whatever list you were in. You can also use the [ u ] key to go "up".
