### ISSUE TITLE
Don't hide search box when X is clicked

### ISSUE THREAD

**Issue by dmalan** [leggett/simplify#93]
Having the search box present at all times is quite helpful, particularly given Gmail's text-based shortcuts (e.g., `to:`, `from:`, etc.):

<img width="717" alt="Screen Shot 2019-04-26 at 12 00 38 PM" src="https://user-images.githubusercontent.com/788678/56820928-25420480-681b-11e9-9d07-e96ad4ff0888.png">

It looks like you can achieve such by clicking the magnifying glass once and then not actually searching anything, as by clicking outside the search box. The search box then stays open even after page reloads.

However, if you click the search box's X after having searched for something, as in

<img width="715" alt="Screen Shot 2019-04-26 at 12 00 22 PM" src="https://user-images.githubusercontent.com/788678/56821034-5c181a80-681b-11e9-91db-a6d0219d7147.png">

in order to get back to your inbox, the search box hides itself, becoming a magnifying glass instead:

<img width="267" alt="Screen Shot 2019-04-26 at 12 00 31 PM" src="https://user-images.githubusercontent.com/788678/56821015-53bfdf80-681b-11e9-8ac9-1758397f2619.png">

Would be great if the search box were instead stickier somehow. Or if there were some other way to return to one's inbox after having just searched (as is possible without the extension when the Gmail logo is present and clickable).

Many thanks for the great extension (and Gmail itself!).

**Comment by leggett** [comment]
Yeah, this isn't ideal. I'm not sure how to fix it without adding settings (which I really don't want to do). Will have to think about it some. Thanks for the detailed report.

**Comment by jaminroe** [comment]
For me, the X clear button doesn't even work! 🤔

**Comment by leggett** [comment]
@jaminroe  Gmail updated some of their classNames this weekend and it broke a few things including this. You're probably not running Simplify v1.3.0. Can you check?

**Comment by jaminroe** [comment]
@leggett yes you're correct! I'm using the browser, Brave, which doesn't auto update extensions quite the same way Chrome does. At least I don't see it update them unless I update Brave.

**Comment by leggett** [comment]
Got it. Bummer about no auto updates. Hopefully the pace of updates will show down soon ish. Hopefully.

**Comment by leggett** [comment]
I fixed this a while back. And in the next version (v1.6.4) I'm adding settings for the first time including a setting for opting in to always minimizing the search box when it isn't in use (for those that want that).
