### ISSUE TITLE
GMass Extension breaks layout

### ISSUE THREAD

**Issue by itjustwerks** [leggett/simplify#95]
The following Extension adds some buttons to the Gmail interface to the right of the search bar: https://chrome.google.com/webstore/detail/gmass-powerful-mail-merge/ehomdgjhgmbidokdgicgmdiedadncbgf. These buttons are breaking the Simplify layout and causing the search bar to be unusable. I'll see if I can come up with a fix, but thought I'd throw it on here first. Thanks.

**Comment by leggett** [comment]
Thanks. Unlikely to happen any time soon but tracking extensions to try and better integrate here in issue #83
