### ISSUE TITLE
Allow show/hide for UI elements

### ISSUE THREAD

**Issue by adamglazier** [leggett/simplify#99]
I wish it was possible to show/hide UI elements from the extensions menu.

Examples of elements that could be hidden: refresh button, checkbox options, language controls, offline indicator, pagination

See UI mockup showing more hidden elements
![centered search mock](https://user-images.githubusercontent.com/17174020/56837680-e1fa8c80-6840-11e9-8bf5-a3132095e9ca.png)

**Comment by leggett** [comment]
I don't want to introduce settings. Few will use them. It makes support and maintaining the extension harder. And it is a crutch for making hard decisions. 

Some of those things can be hidden via Gmail Settings (language input).

Some things are sticky (search showing and hiding). 

Some things already intelligently hide (pagination if your inbox is under a page).
